      SUBROUTINE PCGSOL(DISIT,IFFIX,REFOR,LNODS,
     .                  NDOFN,NELEM,NEVAB,NNODE,NPOIN,NTOTV,
     .                  INRHS,IPASS,KRESL,
     .                  GSTDI,CSTIF,DISIM,FOREL,ALOAD,DELTA,
     .                  NPREL,NGRUP,NPROP,NMATS,
     .                  NDATA,NPREV,NSTAT,NMATX,NDIME,
     .                  NDISR,NDISO,
     .                  MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .                  ELVAR,ELMAT,WORK1,TEMPN,DISPR,DTEMP,
     .                  VNORM,DISTO,COORD,INFRI,COFRI,
     .                  NACTI,LACTI)
C***********************************************************************
C
C**** THIS ROUTINE SOLVES THE SET OF LINEAR EQUATIONS USING THE
C     PRECONDITIONED CONJUGATE GRADIENT ITERATIVE SOLVER 
C
C     PCGSOL
C            - PCGASS 
C            - PCGTRI
C            - PCGITE  - PCGPRE - PCGMUL
C                      - SKYRHS
C            - SKYRHS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/SOLVERA/KRENU,KSOLV,KSYMM,NWIDT,MITCG,NBUFA,NPRIR,
     .               MITGM,MKRYL,IPGMR,KPARAM, NTHMCM, NTHSOM
      COMMON/SOLVERB/TOLCG,TOLC1,TOLGM
C
      DIMENSION DISIT(NTOTV),   IFFIX(NTOTV),  REFOR(NTOTV),
     .          LNODS(NNODE,NELEM)
      DIMENSION GSTDI(*),       CSTIF(NEVAB,*), DISIM(*),
     .          FOREL(*),       ALOAD(*),       DELTA(*)
C
      DIMENSION MATNO(NELEM),
     .          PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS),
     .          ELDAT(NDATA),       ELPRE(NPREV),
     .          ELVAR(NSTAT),       ELMAT(NMATX),
     .          WORK1(*)
      DIMENSION TEMPN(NPOIN,2),     DISPR(NTOTV,NDISR),
     .          DTEMP(NPOIN),       VNORM(NTOTV)
      DIMENSION DISTO(NTOTV,NDISO), COORD(NDIME,NPOIN)
      DIMENSION INFRI(*),           COFRI(*),
     .          LACTI(NELEM)
C
C**** ASSEMBLE & FACTORISE MATRIX IF NECESSARY
C
      IF(KRESL.EQ.1) THEN
       CALL PCGASS(CSTIF,GSTDI,LNODS,
     .             NDOFN,NELEM,NEVAB,NNODE,NPOIN,NWIDT,
     .             NPREL,NGRUP,NPROP,NMATS,
     .             NDATA,NPREV,NSTAT,NMATX,NTOTV,NDIME,
     .             NDISR,NDISO,
     .             MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .             ELVAR,ELMAT,WORK1,TEMPN,DISPR,DTEMP,
     .             VNORM,DISTO,COORD,INFRI,COFRI,LACTI)
C
       CALL PCGTRI(GSTDI,IFFIX,NDOFN,NPOIN,NWIDT,TOLC1)
      ENDIF
C
C**** IF NECESSARY MODIFY RHS FOR NON-ZERO BOUNDARY CONDITIONS
C
      IF(INRHS.EQ.1)
     . CALL SKYRHS(CSTIF,DISIT,REFOR,LNODS,NDOFN,NELEM,NEVAB,
     .             NNODE,NPOIN,DISIM,FOREL,    1,
     .             NPREL,NGRUP,NPROP,NMATS,
     .             NDATA,NPREV,NSTAT,NMATX,NTOTV,NDIME,
     .             NDISR,NDISO,
     .             MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .             ELVAR,ELMAT,WORK1,TEMPN,DISPR,DTEMP,
     .             VNORM,DISTO,COORD,INFRI,COFRI,LACTI)
C
C**** SOLVE THE EQUATIONS 
C
      CALL PCGITE(DISIT,IFFIX,LNODS,REFOR,
     .            NDOFN,NELEM,NEVAB,NNODE,NPOIN,NTOTV,
     .            ALOAD,CSTIF,DELTA,GSTDI,DISIM,FOREL,
     .            NPREL,NGRUP,NPROP,NMATS,
     .            NDATA,NPREV,NSTAT,NMATX,NDIME,
     .            NDISR,NDISO,
     .            MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .            ELVAR,ELMAT,WORK1,TEMPN,DISPR,DTEMP,
     .            VNORM,DISTO,COORD,INFRI,COFRI,LACTI)
C
C**** COMPUTE REACTIONS
C
      IF(IPASS.EQ.2) THEN
       CALL SKYRHS(CSTIF,DISIT,REFOR,LNODS,NDOFN,NELEM,NEVAB,
     .             NNODE,NPOIN,DISIM,FOREL,    0,
     .             NPREL,NGRUP,NPROP,NMATS,
     .             NDATA,NPREV,NSTAT,NMATX,NTOTV,NDIME,
     .             NDISR,NDISO,
     .             MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .             ELVAR,ELMAT,WORK1,TEMPN,DISPR,DTEMP,
     .             VNORM,DISTO,COORD,INFRI,COFRI,LACTI)
      ENDIF
C
      RETURN
      END
