      SUBROUTINE PROPMIC2(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 2
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** COMPOSITION
C
      NPRINT=0
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'COMPO') THEN
       WRITE(LURESS,810)
       WRITE(LURESS,809)
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'CARBO') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC2: NO CARBON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG CARBON COMPOSITION')
       WRITE(LURESS,811) PROPSS(NPOI2T)
       WRITE(LURESS,809)
       CA=PROPSS(NPOI2T)
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SILIC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC2: NO SILICON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG SILICON COMPOSITION')
       WRITE(LURESS,812) PROPSS(NPOI2T)
       WRITE(LURESS,809)
       SI=PROPSS(NPOI2T)
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'PHOSP') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC2: NO PHOSPHORUS CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG PHOSPORUS COMPOSITION')
       WRITE(LURESS,813) PROPSS(NPOI2T)
       WRITE(LURESS,809)
       PH=PROPSS(NPOI2T)
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'COPPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC2: NO COPPER CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG COPPER COMPOSITION')
       WRITE(LURESS,814) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MANGA') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC2: NO MANGANESE CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG MANGANESE COMPOSITION')
       WRITE(LURESS,815) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MAGNE') THEN      ! spheroidizer in SG cast iron
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC2: NO MAGNESIUM CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG MAGNESIUM COMPOSITION')
       WRITE(LURESS,816) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)    ! optional
       IF(WORDSS(1).EQ.'CHROM') THEN   
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.1.0D0)
     .  CALL RUNENDS('PROPMIC2: WRONG CHROMIUM COMPOSITION')
        WRITE(LURESS,817) PROPSS(NPOI2T)
        WRITE(LURESS,809)
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        GO TO 1
       ENDIF
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)    ! optional
    1  IF(WORDSS(1).EQ.'NICKE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.1.0D0)
     .   CALL RUNENDS('PROPMIC2: WRONG NICKEL COMPOSITION')
        WRITE(LURESS,818) PROPSS(NPOI2T)
        WRITE(LURESS,809)
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        GO TO 2
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC2: NO COMPOSITION CARD')
      ENDIF
C
C**** THERMAL PROPERTIES
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
    2 IF(WORDSS(1).EQ.'DENSI') THEN          ! optional
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0
       GO TO 3
      ENDIF
      WRITE(LURESS,821) PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
    3 IF(WORDSS(1).EQ.'SPECI') THEN          ! optional
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0
       GO TO 4
      ENDIF
      WRITE(LURESS,822) PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
    4 IF(WORDSS(1).EQ.'CONDU') THEN          ! optional
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0
       GO TO 5
      ENDIF
      WRITE(LURESS,823) PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
    5 IF(WORDSS(1).EQ.'LATEN') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
      ELSE
       CALL RUNENDS('PROPMIC2: NO LATENT HEAT CARD')
      ENDIF
      WRITE(LURESS,824) PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
C**** PRIMARY AUSTENITE SOLIDIFICATION
C
      CEQ=CA+0.33D0*(SI+PH)                  ! equivalent carbon content
C
      IF(CEQ.LT.4.26D0) THEN
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'AUSTE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1.0D0                 ! model 1
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(3)
        WRITE(LURESS,825) PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                    PROPSS(NPOI2T)
        WRITE(LURESS,809)
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0                 ! model 0
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        GO TO 10
       ENDIF
C
C**** PRIMARY GRAPHITE SOLIDIFICATION
C
      ELSE
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'GRAPH') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1.0D0                 ! model 1
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)             ! pg latent heat
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2)             ! maximum pg fraction
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
       ELSE
        CALL RUNENDS('PROPMIC2: NO GRAPHITE CARD')
       ENDIF
       WRITE(LURESS,826) PROPSS(NPOI2T-2),PROPSS(NPOI2T-1)
       WRITE(LURESS,809)
      ENDIF
C
C**** NUCLEATION PROPERTIES
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
   10 IF(WORDSS(1).EQ.'NUCLE') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(2)
      ELSE
       CALL RUNENDS('PROPMIC2: NO NUCLEATION CARD')
      ENDIF
      WRITE(LURESS,831) PROPSS(NPOI2T-1),PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
C**** GROWTH PROPERTIES
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'GROWT') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(2)
      ELSE
       CALL RUNENDS('PROPMIC2: NO GROWTH CARD')
      ENDIF
      WRITE(LURESS,832) PROPSS(NPOI2T-1),PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
C**** LAMELLAR SPACING PROPERTIES
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'LAMEL') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(2)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(3)
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0
       GO TO 11
      ENDIF
      WRITE(LURESS,833) PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),PROPSS(NPOI2T)
      WRITE(LURESS,809)
C
C**** NUMERICAL STRATEGY PARAMETERS
C
      CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
   11 IF(WORDSS(1).EQ.'NUMER') THEN
       WRITE(LURESS,860)
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TEMPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IFPCDT=INT(PARAMS(1))
        IF(IFPCDT.LT.1.OR.IFPCDT.GT.5)
     .   CALL RUNENDS('PROPMIC2: WRONG IFPCDT VALUE')
        WRITE(LURESS,861) IFPCDT
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC2: NO TEMPERATURE DERIVATIVE FORM OF FL')
       ENDIF
C
       CALL LISTENS('PROPMIC2',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'FRACT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IAFLOJ=INT(PARAMS(1))
        WRITE(LURESS,862) IAFLOJ
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC2: NO FRACTION CORRECTION CARD')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC2: NO NUMERICAL STRATEGY CARD')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA2S=1
      IPLLLS(INUPM)=2
C
      RETURN
  809 FORMAT(/)
  810 FORMAT(3X,'COMPOSITION:')
  811 FORMAT(3X,'   CARBON CONTENT     =',E15.6)
  812 FORMAT(3X,'   SILICON CONTENT    =',E15.6)
  813 FORMAT(3X,'   PHOSPHORUS CONTENT =',E15.6)
  814 FORMAT(3X,'   COPPER CONTENT     =',E15.6)
  815 FORMAT(3X,'   MANGANESE CONTENT  =',E15.6)
  816 FORMAT(3X,'   MAGNESIUM CONTENT  =',E15.6)
  817 FORMAT(3X,'   CHORMIUM CONTENT   =',E15.6)
  818 FORMAT(3X,'   NICKEL CONTENT     =',E15.6)
C
  821 FORMAT(3X,'DENSITY       =',E15.6)
  822 FORMAT(3X,'SPECIFIC HEAT =',E15.6)
  823 FORMAT(3X,'CONDUCTIVITY  =',E15.6)
  824 FORMAT(3X,'LATENT HEAT   =',E15.6)
C
  825 FORMAT(3X,'AUSTENITE: Ts=',E15.6,' Tl=',E15.6,' L=',E15.6)
  826 FORMAT(3X,'GRAPHITE: LATENT HEAT=',E15.6,' MAX. FRACTION=',E15.6)
C
  831 FORMAT(3X,'NUCLEATION PARAMETERS =',E15.6,3X,E15.6)
  832 FORMAT(3X,'GROWTH PARAMETERS     =',E15.6,3X,E15.6)
C
  833 FORMAT(3X,'LAMELLAR SPACING PARAMETERS=',E15.6,3X,E15.6,3X,E15.6)
C
  860 FORMAT(3X,'NUMERICAL STRATEGY PARAMETERS')
  861 FORMAT(3X,'TEMPERATURE DERIVATIVE FORM OF FL=',I5)
  862 FORMAT(3X,'FRACTION CORRECTION FORM         =',I5)
      END
