      SUBROUTINE OUTDISS(DISTOS,HEADSS,DISPLS)
C***********************************************************************
C
C**** THIS ROUTINE WRITES TEMPERATURES TO OUTPUT AND POSTPROCESSOR
C     FILES
C
C       KPRI1=0  DO NOT WRITE TEMPERATURES TO OUTPUT FILE
C             1  WRITE TEMPERATURES TO OUTPUT FILES
C       KFEMV=0  DO NOT WRITE TEMPERATURES TO POSTPROCESSOR FILE
C             1  WRITE TEMPERATURES TO POSTPROCESSOR FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION DISTOS(*), HEADSS(NPOINS,*), DISPLS(NTOTVMS)
C
C**** OUTPUT DISPLACEMENTS
C
      IF(IPRCOS.GT.0) THEN
       IF(KPRI1S.EQ.1) THEN
        WRITE(LURESS,915)
        IF(KPROBS.EQ.1) THEN
         IF(NDIMES.EQ.2.AND.KPORES.EQ.0) WRITE(LURESS,920)
         IF(NDIMES.EQ.2.AND.KPORES.NE.0) WRITE(LURESS,925)
         IF(NDIMES.EQ.3.AND.KPORES.EQ.0) WRITE(LURESS,930)
         IF(NDIMES.EQ.3.AND.KPORES.NE.0) WRITE(LURESS,935)
        ENDIF
        IF(KPROBS.EQ.4) WRITE(LURESS,950)
C
        GAMAWS=9999999.*GRAVYS         !???????????????????
        IF(GAMAWS.EQ.0.0) GAMAWS=1.0
        DO IPOINS=1,NPOINS
C
         ITOT0S=(IPOINS-1)*NDOFCS+1
         ITOT1S=(IPOINS-1)*NDOFCS+NDOFNS
         ITOTFS=IPOINS*NDOFCS
C
         IF(KPORES.EQ.0) TOPWPS=0.
         IF(KPORES.EQ.1) TOPWPS=HEADSS(IPOINS,1)
         IF(KPORES.EQ.2) TOPWPS=DISTOS(ITOTFS)
C
         IF(KPORES.NE.0) THEN
          EXPWPS=TOPWPS-HEADSS(IPOINS,1)
          THEADS=HEADSS(IPOINS,2)+EXPWPS/GAMAWS
         ENDIF
C
         IF(KPORES.EQ.0)
     .    WRITE(LURESS,905) IPOINS,(DISTOS(ITOTVS),
     .                      ITOTVS=ITOT0S,ITOT1S)
         IF(KPORES.NE.0)
     .    WRITE(LURESS,905) IPOINS,(DISTOS(ITOTVS),
     .                      ITOTVS=ITOT0S,ITOT1S),
     .                      EXPWPS,TOPWPS,THEADS
        ENDDO
       ENDIF
      ENDIF
C
      IF(KFEMVS.NE.0)
     . WRITE(LUPOSS) TITLES,SUBTIS,ITIMES,ISTEPS,IITERS,SNGL(TTIMES),
     .              (SNGL(DISTOS(ITOTVS)),ITOTVS=1,NTOTVS)
C
      IF(LARGES.GT.0) THEN
       IF(KFEMVS.NE.0)
     .  WRITE(LUPOSS) (SNGL(DISPLS(ITOTVM)),ITOTVM=1,NTOTVMS)
      ENDIF
C
      RETURN
  905 FORMAT(5X,I5,8E15.6)
  915 FORMAT(/,5X,19H NODAL TEMPERATURES)
  920 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.)
  925 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H EXP.PWP,
     .                      7X,8H TOT.PWP,6X,9H TOT.HEAD)
  930 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H Z-DISP.)
  935 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H Z-DISP.,
     .                      7X,8H EXP.PWP,7X,8H TOT.PWP,6X,9H TOT.HEAD)
  950 FORMAT(5X,5H NODE,3X,12H TEMPERATURE)
      END
