      SUBROUTINE BRIBA0(NCRIT,NTYPE,PROPS,SGTOT)
C***********************************************************************
C
C****THIS ROUTINE BRINGS BACK THE STRESS POINT ON THE SURFACE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION DEVIA(6), PROPS(*), SGTOT(*)
C
C***CALCULATE THE VARIATION OF THE EQUIVALENT MEAN PRESSURE
C
      CINTE=PROPS(33)
      FINCL=PROPS(34)
C
      CALL INVARS(SGTOT,DEVIA,NTYPE,PMEAN,QINVA,THETA,VARJ2,
     .            VARJ3)
C
C***DETERMINE THE INCLINATION OF THE FAILURE SURFACE
C
      IF(NCRIT.EQ.1)
     . CALL VARTHE(CAPTH,CINTE,FINCL,IFLAG,PROPS,THETA)
C
C***BRING BACK THE STRESS POINT ON THE SURFACE
C
      QULIN=-FINCL*PMEAN+CINTE
      REDUC=QULIN/QINVA
      SGTOT(1)=REDUC*DEVIA(1)+PMEAN   
      SGTOT(2)=REDUC*DEVIA(2)+PMEAN   
      SGTOT(3)=REDUC*DEVIA(3)
      SGTOT(4)=REDUC*DEVIA(4)+PMEAN   
C
      IF(NTYPE.NE.4)RETURN
C
      SGTOT(5)=REDUC*DEVIA(5)
      SGTOT(6)=REDUC*DEVIA(6)
C
      RETURN
      END
