      SUBROUTINE PLTOHA(NCRIT,PROPS,NTYPE,STRES,ANGFI,CAPAP,PREYS,DAMAG,
     .                  CCERO,A2COE,A3COE,ISOTT)
C***********************************************************************
C
C**** THIS SUBROUTINE EVALUATES THE TOTAL HARDENING FUNCTION
C
C     THE TOTAL HARDENING FUNCTION (COHESION OR EFFECTIVE UNIAXIAL
C     STRESS) IF IS NECESSARY (NORMALLY PREYS IS COMPUTED IN pltoha.f):
C
C               PREYS:
C               (C=C^th+(1-f_pc)*C^p in solidification problems)
C               (actually, C=C^th+C^p)
C
C     ( Old form: DATA ROOT3,PIVAL/1.732050807568877,3.141592654/ )
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION STRES(*), PROPS(*), DEVIA(6)
C
      ROOT3=1.732050807568877D0
      PIVAL=3.141592654D0
C
C**** YIELD CRITERION CHOICE
C
      GO TO (31,32,33,34,35,36,37,38,39,40,41,42) (NCRIT-30)
C 
C**** TRESCA
C
   31 CONTINUE
      CALL RUNEND('ERROR IN PLTOHA       ')
      RETURN
C 
C**** VON MISES
C
   32 PREYS=A3COE*(1.0D0-DAMAG)*CCERO
      IF(ISOTT.GT.0) PREYS=PREYS+A2COE*CAPAP
      RETURN
C
C**** MOHR-COULOMB & VERSION  WITH "TENSION CUT-OFF"
C
   33 CONTINUE
      CALL RUNEND('ERROR IN PLTOHA       ')
      RETURN
C
C**** DRUCKER-PRAGER
C
   34 CONTINUE
      CALL RUNEND('ERROR IN PLTOHA       ')
      RETURN
C 
C**** J. LUBLINER'S THEORY
C
   35 CONTINUE
      CALL RUNEND('ERROR IN PLTOHA       ')
      RETURN
C
C**** ABOUAF'S MODEL
C
   36 CONTINUE
      CALL RUNEND('ERROR IN PLTOHA       ')
      RETURN
C
C**** WEBER BROWN'S MODEL
C
   37 CONTINUE
      CALL RUNEND('ERROR IN PLTOHA       ')
      RETURN
C 
C**** SG CAST IRON
C
   38 PREYS=CCERO+A2COE*CAPAP
      RETURN
C 
C**** GREEN SAND
C
   39 PREYS=CCERO+A2COE*CAPAP
      RETURN
C 
C**** GREEN SAND
C
   40 PREYS=CCERO+A2COE*CAPAP
      RETURN
C 
C**** GURSON
C
   41 PREYS=A3COE*CCERO+A2COE*CAPAP
C
      IFVER=INT(PROPS(35))
      IF(IFVER.EQ.4) THEN
       IF(CAPAP.EQ.0.0D0) PREYS=CCERO
      ENDIF
      RETURN
C
C**** HILL 48
C
   42 PREYS=A3COE*CCERO+A2COE*CAPAP
C
      IFVER=INT(PROPS(35))
      IF(IFVER.EQ.4) THEN
       IF(CAPAP.EQ.0.0D0) PREYS=CCERO
      ENDIF
      RETURN
C
      END
