      SUBROUTINE BFGSUP(DISIT,REFOR,VVECT,WVECT)
C***********************************************************************
C
C**** THIS ROUTINE MODIFIES THE ITERATIVE DISPLACEMENTS 
C     IF A QUASI-NEWTON METHOD IS USED ( BFGS )
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
C
      COMMON/ANTESOA/NBFGS,NVECT
C
      DIMENSION DISIT(*), REFOR(NTOTV), VVECT(NTOTV), WVECT(NTOTV)
C
      IF(NVECT.EQ.0) GO TO 100
C
      DO 10 IVECT=1,NVECT
      READ(NBFGS) VVECT,WVECT
        CONST=0.0D+00
        DO 20 ITOTV=1,NTOTV
   20   CONST=CONST+VVECT(ITOTV)*DISIT(ITOTV)
        DO 30 ITOTV=1,NTOTV
   30   DISIT(ITOTV)=DISIT(ITOTV)+CONST*WVECT(ITOTV)     
   10 CONTINUE     
C
C**** RECOVER 'REAL' RESIDUAL FORCES ARRAY
C
  100 CONTINUE
      READ(NBFGS) REFOR
      BACKSPACE NBFGS
C
      RETURN
      END
