      SUBROUTINE RSCHEK
C***********************************************************************
C
C     FIND THE STARTING RECORD (NREC0) FOR RESTARTING CONVERGED STEP
C
C***********************************************************************
C
C      POS  1 : KINTX    LAST STORED INTERVAL NUMBER
C      POS  2 : KSTEX    LAST STORED STEP NUMBER
C      POS  3 : TIMMX    LAST STORED TIME
C      POS  4 : NRECX    RECORD NUMBER OF THE START OF RESULTS
C      POS  5 : KTSTE    TOTAL NUMBER OF STORED STEPS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      DATA TOLLE/1.0E-07/
C
      CALL CPUTIM(TIME1)
C
C**** READ FIRST RECORD TO FIND LAST CONVERGED RESULT
C
      READ(LURST,REC=1) KINTX,KSTEX,TIMMX,NRECX,KTSTE
C
C**** FIND APPROPRIATE NREC0
C
      IF(ISKIP.EQ.0)  THEN
C
C**** IF THIS IS A CONTINUATION THEN THE STARTING TIME IS THE LAST
C     STORED
C 
         NRECC=NRECX
         READ(LURST,REC=NRECC) KINTX,KSTEX,TIMMX,NRECX,KTSTX
         GO TO 101
C
      ELSE
C
C**** FIND APPROPIATE RECORD
C
         NRECC=NRECG+IDATP(1,2)*NELEM     !  START OF CONVERGED DATA
C
         KTSTO=KTSTE
         DO 100 INDEX=1,KTSTO
           READ(LURST,REC=NRECC) KINTX,KSTEX,TIMMX,NRECX,KTSTX
           IF(KSTEP.NE.0) THEN
             IF((KINTX.EQ.KTIME).AND.(KSTEX.EQ.KSTEP)) GOTO 101
           ELSE
             IF(ABS(TIMST-TIMMX).LT.TOLER) GOTO 101
           ENDIF
           NRECC=NRECC+NLENC
  100    CONTINUE
C
      ENDIF
C
C**** ERROR CONDITION
C
       CLOSE(LURST)
       WRITE(LURES,905) TIMST
       CALL RUNEND('  ERROR IN RESTART CARD            ')
C
C**** SUCCESFUL SEARCH
C
  101 CONTINUE   
      ITIME=KINTX
      TTIME=TIMMX
      KTSTE=KTSTX
      WRITE(LURES,900) TTIME,ITIME,KSTEX
C
      CALL CPUTIM(TIME2)
      CPURS=CPURS+(TIME2-TIME1)
C
      RETURN
C
  900 FORMAT('1',///,80('='),//,
     .'         * * * RESTARTS OF COMPUTATION * * *',//,
     .'             STARTING TIME         :',E12.6,/,
     .'             BELONGING TO INTERVAL :',7X,I5,/,
     .'             AT STEP               :',7X,I5,//,80('='))
  905 FORMAT(
     .'   THE DESIRED RESTARTING TIME ',E12.6,'HAS NOT BEEN FOUND',
     .'   INSIDE THE TIME HYSTORY OF THE PREVIOUS RUN')
      END
