      SUBROUTINE STRCEK
C***********************************************************************
C
C**** THIS ROUTINE CHECKS THE CONTROLLING PARAMETERS FOR THE
C     CURRENT TIME INTERVAL
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
C
      DIMENSION NEROR(13)
C
      DO 10 IEROR=1,13
   10 NEROR(IEROR)=0
C
C***CHECK ON PARAMETERS FOR STATIC-UNCOUPLED PROBLEM
C
      IF(KDYNA.EQ.0.AND.KPORE.NE.2) THEN
        IF(KINTE.NE.0)                                   NEROR(2)=1
        IF(KOPTI.NE.0.AND.LAUTO.NE.0)                    NEROR(3)=1
        IF(KARCL.EQ.4.AND.NCDIS.EQ.0)                    NEROR(9)=1
        IF(KSMUS.GT.0)                                   NEROR(10)=1
        IF(KARCL.NE.0.AND.LAUTO.EQ.0)                    NEROR(12)=1
      ENDIF
C
C***CHECK ON PARAMETERS FOR STATIC-COUPLED PROBLEM
C
      IF(KDYNA.EQ.0.AND.KPORE.EQ.2) THEN
        IF(KINTE.EQ.0)                                   NEROR(4)=1
        IF(LAUTO.NE.0)                                   NEROR(5)=1
        IF(KSMUS.GT.0.AND.LINES.NE.0)                    NEROR(6)=1 !???
        IF(LINES.NE.0)WRITE(LURES,800)
        IF(KARCL.NE.0)                                   NEROR(7)=1
        IF(LACCE.NE.0)                                   NEROR(8)=1
      ENDIF
C
C***CHECK ON PARAMETERS FOR DYNAMIC-UNCOUPLED PROBLEM
C
      IF(KDYNA.EQ.1.AND.KPORE.NE.2) THEN
        IF(LAUTO.NE.0)                                   NEROR(5)=1
        IF(KARCL.NE.0)                                   NEROR(7)=1
        IF(LACCE.NE.0)                                   NEROR(8)=1
        IF(KSMUS.GT.0)                                   NEROR(10)=1
c       IF(KINTE.NE.2.AND.KPROB.NE.4)                    NEROR(11)=1
        IF(KOPTI.NE.0)                                   NEROR(13)=1
      ENDIF
C
C***CHECK ON PARAMETERS FOR DYNAMIC-COUPLED PROBLEM
C
      IF(KDYNA.EQ.1.AND.KPORE.EQ.2) THEN
        IF(LAUTO.NE.0)                                   NEROR(5)=1
        IF(KSMUS.GT.0.AND.LINES.NE.0)                    NEROR(6)=1
        IF(LINES.NE.0)WRITE(LURES,800)
        IF(KARCL.GT.0)                                   NEROR(7)=1
        IF(LACCE.NE.0)                                   NEROR(8)=1
        IF(KINTE.NE.2)                                   NEROR(11)=1
        IF(KOPTI.NE.0)                                   NEROR(13)=1
      ENDIF
C
C***CHECK IF ERRORS HAD OCCURED
C
      KOUNT=0
      DO 20 IEROR=1,13
      IF(NEROR(IEROR).NE.1)GOTO 20
      KOUNT=KOUNT+1
   20 CONTINUE
C
      IF(KOUNT.EQ.0)RETURN
C
C***ERRORS DIAGNOSED BY ROUTINE STRCEK
C
      WRITE(LURES,600)KOUNT
  600 FORMAT(//,20X,I5,' INPUT ERRORS DETECTED BY STRATE.'/,
     .          25X,   ' DIAGNOSTIC FOLLOWS :',//)
C
      IF(NEROR(2).EQ.1)  WRITE(LURES,705) 
      IF(NEROR(3).EQ.1)  WRITE(LURES,710) 
      IF(NEROR(4).EQ.1)  WRITE(LURES,715) 
      IF(NEROR(5).EQ.1)  WRITE(LURES,720)
      IF(NEROR(6).EQ.1)  WRITE(LURES,725) 
      IF(NEROR(7).EQ.1)  WRITE(LURES,730) 
      IF(NEROR(8).EQ.1)  WRITE(LURES,735)
      IF(NEROR(9).EQ.1)  WRITE(LURES,740)
      IF(NEROR(10).EQ.1) WRITE(LURES,745)
      IF(NEROR(11).EQ.1) WRITE(LURES,750)
      IF(NEROR(12).EQ.1) WRITE(LURES,755)
      IF(NEROR(13).EQ.1) WRITE(LURES,760)
C
      CALL RUNEND('     ERROR DETECTED IN STRATE      ')
C
      RETURN
C
  705 FORMAT(
     .' THE PROBLEM IS STATIC-UNCOUPLED AND YOU ARE ASKING FOR',
     .' A TIME STEPPING ALGORITHM',/)
C
  710 FORMAT(
     .' YOU ARE ASKING SIMULTANEOUSLY FOR AUTOMATIC LOAD AND TIME',
     .' INCREMENTATION',/,' >>>> INCOMPATIBLE',/)
C
  715 FORMAT(
     .' THE PROBLEM ADVANCES IN TIME BUT YOU ARE NOT ASKING FOR',
     .' ANY TIME STEPPING ALGORITHM',/)
C
  720 FORMAT(
     .' AUTOMATIC LOAD INCREMENTATION IS INCOMPATIBLE WITH TIME',/,
     .' STEPPING ALGORITHMS',/)
C
  725 FORMAT(
     .' SMOOTING AND LINE SEARCH ARE NOT AVAILABLE SIMULTANEOUSLY'/)
C
  730 FORMAT(
     .' ARC-LENGTH IS NOT COMPATIBLE WITH TIME STEPPING PROBLEMS',/)
C
  735 FORMAT(
     .' CONVERGENCE ACCELERATOR IS NOT COMPATIBLE WITH TIME STEPPING',
     .' PROBLEMS',/)
C
  740 FORMAT(
     .' YOU HAVE SELECTED DISPLACEMENT CONTROL BUT HAVE NOT SPECIFIED',
     .' A CONTROLLING D.O.F.',/)
C
  745 FORMAT(
     .' THIS IS NOT A COUPLED PROBLEM AND YOU ARE ACTIVATING THE',
     .' SMOOTHING ALGORITHM',/)
C
  750 FORMAT(
     .' THE PROBLEM IS SECOND ORDER IN TIME AND YOU ARE NOT SELECTING'/,
     .' AN APPROPRIATE TIME STEPPING ALGORITHM',/)
C
  755 FORMAT(
     .' THE ARC-LENGTH ALGORITHM REQUIRES AUTOMATIC LOAD '/,
     .' PLEASE, SPECIFY ONE OF THE AVAILABLE OPTIONS',/)
C
  760 FORMAT(
     .' FOR THE DYNAMIC PROBLEM IT IS SUPPOSED TO HAVE CONSTANT TIME'/,
     .' WITHIN EACH INTERVAL. THUS IT SHOULD SET THE TIME PARAMETERS'/,
     .' IN CARD "TIME_INCREMENTION,<PARA1>,<PARA2>" EQUAL TO ZERO'/)
C
  800 FORMAT(
     .' WARNING: THE OPTION OF LINE-SEARCH FOR COUPLED PROBLEM HAS '/,
     .' NOT BEEN YET TESTED PROPERLY. PAY ATTENTIONS ON THE RESULTS.'/)
C
      END
