      SUBROUTINE CONCEK
C***********************************************************************
C
C**** THIS ROUTINE CHECKS THE MAIN CONTROL DATA ESTABLISHED IN "CONTRO"
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
C
      DIMENSION NEROR(12)
C
      DO IEROR=1,12
       NEROR(IEROR)=0
      ENDDO
C
C**** CHECK ON MAXIMUM DIMENSIONS
C
      IF(NPOIN.LE.0)                                     NEROR(1)=1
      IF(NELEM.LE.0)                                     NEROR(2)=1
      IF(NNODE.LT.2.OR.NNODE.GT.27)                      NEROR(3)=1
      IF(NMATS.LT.1.OR.NMATS.GT.NELEM)                   NEROR(4)=1
      IF(NFUNC.LT.1)                                     NEROR(5)=1
C
C**** PROBLEM INCOMPATIBILITY
C
      IF(KPROB.EQ.0)                                     NEROR(8)=1
      IF(KPORE.EQ.2.AND.LARGE.NE.0)                      NEROR(9)=1
      IF(KPORE.NE.2.AND.KSMUS.NE.0)                      NEROR(10)=1
C
C**** CHECK ON MISCELLANEOUS
C
C     Old version:
C
C     IF(KSYMM.EQ.0)                                     NEROR(11)=1
C
      IF(IABS(KSMUS).EQ.1.AND.NDIME.NE.2)                NEROR(12)=1
C
C**** WARNINGS
C
      IF(KSYMM.EQ.0.AND.NOCOI.EQ.0) THEN
       WRITE(LURES,905)
       WRITE(LUPRI,905)
  905  FORMAT(//,'WARNING: A NON-SYMMETRIC SOLVER IS USED FOR A',/,
     .           '      PROBLEM WITH NO NON COINCIDENT CONTACT MESH',//)
      ENDIF
      IF(KSYMM.EQ.1.AND.NOCOI.GT.0) THEN
       WRITE(LURES,906)
       WRITE(LUPRI,906)
  906  FORMAT(//,'WARNING: A SYMMETRIC SOLVER IS USED FOR A NON',/,
     .           '         COINCIDENT CONTACT MESH PROBLEM',//)
      ENDIF
C
      IF(NDIME.EQ.1.AND.NOCOI.GT.0) THEN
       WRITE(LURES,907)
       WRITE(LUPRI,907)
  907  FORMAT(//,'WARNING: A 1D PROBLEM HAS ALWAYS A COINCIDENT CON-',/,
     .           '         TACT MESH - THEREFORE, NOCOI=0 IS SET',//)
       NOCOI=0
      ENDIF
C
C**** CHECK IF ERRORS HAD OCCURED
C
      KOUNT=0
      DO 20 IEROR=1,12
      IF (NEROR(IEROR).NE.1) GOTO 20
      KOUNT=KOUNT+1
   20 CONTINUE
C
      IF (KOUNT.EQ.0) RETURN
C
C**** ERRORS DIAGNOSED BY ROUTINE CONCEK
C
      WRITE(LURES,600)KOUNT
  600 FORMAT(//,20X,I5,'  INPUT ERRORS DETECTED BY CONTRO',/,
     .          25X,   '  DIAGNOSTIC FOLLOWS: ',//)
C
      IF(NEROR(1).EQ.1)  WRITE(LURES,700) 
      IF(NEROR(2).EQ.1)  WRITE(LURES,705) 
      IF(NEROR(3).EQ.1)  WRITE(LURES,710) NNODE
      IF(NEROR(4).EQ.1)  WRITE(LURES,715) NMATS,NELEM
      IF(NEROR(5).EQ.1)  WRITE(LURES,720)
      IF(NEROR(8).EQ.1)  WRITE(LURES,735)
      IF(NEROR(9).EQ.1)  WRITE(LURES,740)
      IF(NEROR(10).EQ.1) WRITE(LURES,745)
      IF(NEROR(11).EQ.1) WRITE(LURES,750)
      IF(NEROR(12).EQ.1) WRITE(LURES,755)
C
      CALL RUNEND('CONCEK: ERROR DETECTED             ')
C
  700 FORMAT(' THE SPECIFIED NUMBER OF NODES IS LESS THAN ZERO'//)
C
  705 FORMAT(' THE SPECIFIED NUMBER OF ELEMENTS IS LESS THAN ZERO'//)
C
  710 FORMAT(
     .' THE NUMBER OF NODES PER ELEMENT IS LESS THAN 2 OR GREATER THAN',
     .' 20',/,10X,'NNODE=',I5//)
C
  715 FORMAT(
     .59H THE SPECIFIED TOTAL NUMBER OF DIFFERENT MATERIALS (NMATS) ,/,
     .59H IS LESS THAN OR EQUAL TO ZERO, OR GREATER THAN THE TOTAL  ,/,
     .59H NUMBER OF ELEMENTS (NELEM) IN THE STRUCTURE               ,/,
     .10X,'NMATS=',I5,5X,'NELEM=',I5//)
C
  720 FORMAT(
     .' THE SPECIFIED NUMBER OF FUNCTIONS IS LESS THAN OR EQUAL TO',
     .' ZERO'//)
C
  735 FORMAT(
     .' SEEPAGE PROBLEM IS NOT IMPLEMENTED YET',/ )
C
  740 FORMAT(
     .' COUPLED PROBLEM WITH LARGE DISPLACEMENTS IS NOT IMPLEMENTED',
     .' YET',/ )
C
  745 FORMAT(
     .' UNCOUPLED PROBLEM DOES NOT REQUIRE ANY SMOOTHING',/ )
C
  750 FORMAT(
     .' ALL IMPLEMENTED PROBLEMS YIELD A SYMMETRIX MATRIX AND YOU,',/,
     .' IDIOT, ARE ASKING FOR A NON-SYMMETRIC SOLVER',/)
C
  755 FORMAT(
     .' SPECIFIED TYPE OF SMOOTHING IS INCORRECT OR NOT YET',
     .' IMPLEMENTED',/)
C
      END
