      SUBROUTINE ZABART(AZABA,AZABB,AZABC,TEMPG,PROPS,
     .                  AZABAF,AZABAA,AZABBF,AZABBA,AZABCF,AZABCA)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE A, B & C COEFFICIENTS (TEMPERATURE
C     DEPENDENT) OF THE ZABARAS' LAW
C
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
C
C**** MECHANICAL VARIABLES
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      DIMENSION PROPS(*)
C
      IPEP4=INT(PROPS(4))
C
      IPEP3=INT(PROPS(3))
      IF(IPEP3.EQ.1) THEN
       AZABA=VZABA(1,1)
       AZABB=VZABB(1,1)
       AZABC=VZABC(1,1)
       IF(IVIFL.EQ.4) AZABC=VZABC(1,1)/(TEMPG+CENKEL)
       RETURN
      ENDIF
#ifndef restricted
C
      IF(IPEP4.EQ.0.OR.IPEP4.EQ.2) THEN
C
C**** COEFFICIENT A
C
       IF(TEMPG.LE.VZABA(1,2)) AZABA=VZABA(1,1)
       DO IZABA=2,NZABA
        I1=IZABA-1
        I2=IZABA
        IF(TEMPG.GE.VZABA(I1,2).AND.TEMPG.LE.VZABA(I2,2)) 
     .   AZABA=(VZABA(I2,1)-VZABA(I1,1))/(VZABA(I2,2)-VZABA(I1,2))*
     .         (TEMPG-VZABA(I1,2))+VZABA(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABA(NZABA,2)) AZABA=VZABA(NZABA,1)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT A
C
       DZABA=0.0
C
C**** COEFFICIENT B
C
       IF(TEMPG.LE.VZABB(1,2)) AZABB=VZABB(1,1)
       DO IZABB=2,NZABB
        I1=IZABB-1
        I2=IZABB
        IF(TEMPG.GE.VZABB(I1,2).AND.TEMPG.LE.VZABB(I2,2))
     .   AZABB=(VZABB(I2,1)-VZABB(I1,1))/(VZABB(I2,2)-VZABB(I1,2))*
     .         (TEMPG-VZABB(I1,2))+VZABB(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABB(NZABB,2)) AZABB=VZABB(NZABB,1)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT B
C
       DZABB=0.0
C
C**** COEFFICIENT C
C
       IF(TEMPG.LE.VZABC(1,2)) AZABC=VZABC(1,1)
       DO IZABC=2,NZABC
        I1=IZABC-1
        I2=IZABC
        IF(TEMPG.GE.VZABC(I1,2).AND.TEMPG.LE.VZABC(I2,2))
     .   AZABC=(VZABC(I2,1)-VZABC(I1,1))/(VZABC(I2,2)-VZABC(I1,2))*
     .         (TEMPG-VZABC(I1,2))+VZABC(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABC(NZABC,2)) AZABC=VZABC(NZABC,1)
       IF(IVIFL.EQ.4) AZABC=AZABC/(TEMPG+CENKEL)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT C
C
       DZABC=0.0        ! to be revised
C
      ENDIF             ! ipep4.eq.0
C
      IF(IPEP4.EQ.1) THEN
C
C**** COEFFICIENT A (FERRITE)
C
       IF(TEMPG.LE.VZABAF(1,2)) AZABAF=VZABAF(1,1)
       DO IZABA=2,NZABAF
        I1=IZABA-1
        I2=IZABA
        IF(TEMPG.GE.VZABAF(I1,2).AND.TEMPG.LE.VZABAF(I2,2))
     .   AZABAF=(VZABAF(I2,1)-VZABAF(I1,1))/(VZABAF(I2,2)-VZABAF(I1,2))*
     .          (TEMPG-VZABAF(I1,2))+VZABAF(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABAF(NZABAF,2)) AZABAF=VZABAF(NZABAF,1)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT A (FERRITE)
C
       DZABAF=0.0
C
C**** COEFFICIENT A (AUSTENITE)
C
       IF(TEMPG.LE.VZABAA(1,2)) AZABAA=VZABAA(1,1)
       DO IZABA=2,NZABAA
        I1=IZABA-1
        I2=IZABA
        IF(TEMPG.GE.VZABAA(I1,2).AND.TEMPG.LE.VZABAA(I2,2))
     .   AZABAA=(VZABAA(I2,1)-VZABAA(I1,1))/(VZABAA(I2,2)-VZABAA(I1,2))*
     .          (TEMPG-VZABAA(I1,2))+VZABAA(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABAA(NZABAA,2)) AZABAA=VZABAA(NZABAA,1)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT A (AUSTENITE)
C
       DZABAA=0.0
C
C**** COEFFICIENT B (FERRITE)
C
       IF(TEMPG.LE.VZABBF(1,2)) AZABBF=VZABBF(1,1)
       DO IZABB=2,NZABBF
        I1=IZABB-1
        I2=IZABB
        IF(TEMPG.GE.VZABBF(I1,2).AND.TEMPG.LE.VZABBF(I2,2))
     .   AZABBF=(VZABBF(I2,1)-VZABBF(I1,1))/(VZABBF(I2,2)-VZABBF(I1,2))*
     .          (TEMPG-VZABBF(I1,2))+VZABBF(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABBF(NZABBF,2)) AZABBF=VZABBF(NZABBF,1)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT B (FERRITE)
C
       DZABBF=0.0
C
C**** COEFFICIENT B (AUSTENITE)
C
       IF(TEMPG.LE.VZABBA(1,2)) AZABBA=VZABBA(1,1)
       DO IZABB=2,NZABBA
        I1=IZABB-1
        I2=IZABB
        IF(TEMPG.GE.VZABBA(I1,2).AND.TEMPG.LE.VZABBA(I2,2))
     .   AZABBA=(VZABBA(I2,1)-VZABBA(I1,1))/(VZABBA(I2,2)-VZABBA(I1,2))*
     .          (TEMPG-VZABBA(I1,2))+VZABBA(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABBA(NZABBA,2)) AZABBA=VZABBA(NZABBA,1)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT B (AUSTENITE)
C
       DZABBA=0.0
C
C**** COEFFICIENT C (FERRITE)
C
       IF(TEMPG.LE.VZABCF(1,2)) AZABCF=VZABCF(1,1)
       DO IZABC=2,NZABCF
        I1=IZABC-1
        I2=IZABC
        IF(TEMPG.GE.VZABCF(I1,2).AND.TEMPG.LE.VZABCF(I2,2))
     .   AZABCF=(VZABCF(I2,1)-VZABCF(I1,1))/(VZABCF(I2,2)-VZABCF(I1,2))*
     .          (TEMPG-VZABCF(I1,2))+VZABCF(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABCF(NZABCF,2)) AZABCF=VZABCF(NZABCF,1)
       IF(IVIFL.EQ.4) AZABCF=AZABCF/(TEMPG+CENKEL)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT C (FERRITE)
C
       DZABCF=0.0       ! to be revised
C
C**** COEFFICIENT C (AUSTENITE)
C
       IF(TEMPG.LE.VZABCA(1,2)) AZABCA=VZABCA(1,1)
       DO IZABC=2,NZABCA
        I1=IZABC-1
        I2=IZABC
        IF(TEMPG.GE.VZABCA(I1,2).AND.TEMPG.LE.VZABCA(I2,2))
     .   AZABCA=(VZABCA(I2,1)-VZABCA(I1,1))/(VZABCA(I2,2)-VZABCA(I1,2))*
     .          (TEMPG-VZABCA(I1,2))+VZABCA(I1,1)
       ENDDO
       IF(TEMPG.GE.VZABCA(NZABCA,2)) AZABCA=VZABCA(NZABCA,1)
       IF(IVIFL.EQ.4) AZABCA=AZABCA/(TEMPG+CENKEL)
C
C**** TEMPERATURE DERIVATIVE OF COEFFICIENT C (AUSTENITE)
C
       DZABCA=0.0       ! to be revised
C
      ENDIF             ! ipep4.eq.1
C
#endif
      RETURN
      END
