      SUBROUTINE BOUC05T(TEINIT,ELDIST,BOUCHL)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES BOUNDARY CHANGES DUE TO DENSITY VARIATIONS
C
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'prob_omt.f'
C
      DIMENSION TEINIT(NDOFCT,*), ELDIST(NDOFCT,*)
      DIMENSION BOUCHL(NDOFCT,*)
C
      IF(NMEMO10.EQ.0) RETURN
C
      DO INODLT=1,NNODLT
       TGAUST=ELDIST(1,INODLT)
       TGAUIT=TEINIT(1,INODLT)
C
C**** COMPUTES DENSITY
C
       IF(TGAUST.LE.VDENS(1,2)) BASMM=VDENS(1,1)
       DO IDENS=2,NDENS
        I1=IDENS-1
        I2=IDENS
        IF(TGAUST.GT.VDENS(I1,2).AND.TGAUST.LE.VDENS(I2,2)) 
     .   BASMM=(VDENS(I2,1)-VDENS(I1,1))/(VDENS(I2,2)-VDENS(I1,2))*
     .         (TGAUST-VDENS(I1,2))+VDENS(I1,1)
       ENDDO
       IF(TGAUST.GT.VDENS(NDENS,2)) BASMM=VDENS(NDENS,1)
C
C**** COMPUTES INITIAL DENSITY
C
       IF(TGAUIT.LE.VDENS(1,2)) BASMI=VDENS(1,1)
       DO IDENS=2,NDENS
        I1=IDENS-1
        I2=IDENS
        IF(TGAUIT.GT.VDENS(I1,2).AND.TGAUIT.LE.VDENS(I2,2)) 
     .   BASMI=(VDENS(I2,1)-VDENS(I1,1))/(VDENS(I2,2)-VDENS(I1,2))*
     .         (TGAUIT-VDENS(I1,2))+VDENS(I1,1)
       ENDDO
       IF(TGAUIT.GT.VDENS(NDENS,2)) BASMI=VDENS(NDENS,1)
C
C**** COMPUTES BOUCHL
C
       BOUCHL(1,INODLT)=1.0D0
       IF(BASMM.GT.0.0D0) BOUCHL(1,INODLT)=BASMI/BASMM
      ENDDO
C
      RETURN
      END
