
      SUBROUTINE VARTHE(CAPTH,CINTE,FINCL,IFLAG,PROPS,THETA)
C**********************************************************************
C
C****THIS ROUTINE CALCULATE RATIO AND CAPTH
C
C**********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION PROPS(*)
      DATA ROOT3/1.732050807568877/
C
      COHES=PROPS(13)
      SINPH=PROPS(29)
      COSPH=PROPS(30)
C
C***CALCULATE THE INCLINATION OF THE CRITICAL STATE
C
      ABTHE=DABS(THETA*57.29577951308232)
      IF(ABTHE.GT.29.)GOTO 10
C
      SINTE=DSIN(THETA)
      COSTE=DCOS(THETA)
      DENOM=ROOT3*COSTE-SINPH*SINTE
      FINCL=3.0*SINPH/DENOM
      CINTE=3.0*COHES*COSPH/DENOM
      CAPTH=(ROOT3*SINTE+COSTE*SINPH)/DENOM
      IFLAG=1
C
      RETURN
C
   10 CONTINUE
      PLUMI=1.
      IF(THETA.LT.0.)PLUMI=-1.
      FINCL=6.*SINPH/(3.-PLUMI*SINPH)
      CINTE=6.*COHES*COSPH/(3.-PLUMI*SINPH)
C
      RETURN
      END
