      SUBROUTINE MODULT(WORKST,WORK1T,IPRINT,LPRINT)
C====================================================================
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8, ALLOCATABLE, INTENT(INOUT) :: WORK1T(:)
C
C**** THERMAL VARIABLES
C
      DIMENSION WORKST(LPRINT), IPRINT(50)
      INCLUDE 'modult0.inc'
C
      CALL MODULT0(
     .     WORKST(IPRINT( 1)),WORKST(IPRINT( 2)),WORKST(IPRINT( 3)),
     .     WORKST(IPRINT( 4)),WORKST(IPRINT( 5)),WORKST(IPRINT( 6)),
     .     WORKST(IPRINT( 7)),WORKST(IPRINT( 8)),WORKST(IPRINT( 9)),
     .     WORKST(IPRINT(10)),WORKST(IPRINT(11)),WORKST(IPRINT(12)),
     .     WORKST(IPRINT(13)),WORKST(IPRINT(14)),WORKST(IPRINT(15)),
     .     WORKST(IPRINT(16)),WORKST(IPRINT(17)),WORKST(IPRINT(18)),
     .     WORKST(IPRINT(19)),WORKST(IPRINT(20)),WORKST(IPRINT(21)),
     .     WORKST(IPRINT(22)),WORKST(IPRINT(23)),WORKST(IPRINT(24)),
     .     WORKST(IPRINT(25)),WORKST(IPRINT(26)),WORKST(IPRINT(27)),
     .     WORKST(IPRINT(28)),WORKST(IPRINT(29)),WORKST(IPRINT(30)),
     .     WORKST(IPRINT(31)),
     .     WORK1T)
C
      RETURN
      END
