      SUBROUTINE LOADPSS(ELDATS,ELPRES,ELVARS,ELMATS,
     .                   LNODSS,MATNOS,PROELS,PROPSS,RLOADS,RLOAHS,
     .                   TEMPIS,
     .                   WORK1S,
     .                   PRESCS,ADVELS,COORDS,FPCHAS,DISPLS)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE CONSISTENT NODAL FORCES FOR EACH
C     ELEMENT
C
C     Notes: DINT is used to avoid problems in challenge machines
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      COMMON/LDFILES/ITAPES
C
      DIMENSION MATNOS(NELEMS),        LNODSS(NNODES,NELEMS),
     .          PROELS(NPRELS,NGRUPS), PROPSS(NPROPS,NMATSS),
     .          ELDATS(NDATAS),        ELPRES(NPREVS),
     .          ELVARS(NSTATS),        ELMATS(NMATXS),
     .          PRESCS(*),             WORK1S(*)
      DIMENSION RLOADS(*),             RLOAHS(NTOTVS,NFUNCS),
     .          TEMPIS(NPOINS,2),      ADVELS(NTOTVS*NDIMES),
     .          COORDS(NDIMES,NPOINS), FPCHAS(NFPCH,NPOINS),
     .          DISPLS(NTOTVMS)
C
      PARAMETER (MCOMMS=5)
C
      CHARACTER*5 COMMDS(MCOMMS)
C
      DATA COMMDS/'TITLE','POINT','VOLUM','SURFA','PRINT'/
C
      WRITE(LURESS,900)
C
c     IERR1T=1
c     IF(ITAPET.NE.LUDATT.AND.ITAPET.NE.LULOAT) GOTO 1000
c     IF(ITAPET.EQ.LULOAT) THEN       ! external .loa file
c      OPEN(UNIT=LULOAT,FILE=CE1T,STATUS='OLD',ERR=1000)
c      IERR1T=0
C
c1000  IF(IERR1T.NE.0) THEN
c       IF(IERR1T.EQ.1) WRITE(LUREST,901)
c       CALL RUNENDT('ERROR IN OPENING FILE ')
c      ENDIF
c     ENDIF      ! itapet.eq.luloat
C
C**** INITIALISE REFERENCE LOAD ARRAY
C
      DO ITOTVS=1,NTOTVS
       RLOADS(ITOTVS)=0.0
       DO IFUNCS=1,NFUNCS
        RLOAHS(ITOTVS,IFUNCS)=0.0
       ENDDO
      END DO
C
C**** READ NEW COMMAND
C
  200 NPRINS=0
      CALL LISTENS('LOADPSS',NPRINS,ITAPES)
C
C**** IDENTIFY COMMAND
C
      DO ICOMMS=1,MCOMMS
       IF(WORDSS(1).EQ.COMMDS(ICOMMS)) GO TO 300
      END DO
      GO TO 2000
C
C**** EXECUTE APROPRIATE COMMAND
C
  300 CONTINUE
      GO TO (1,2,3,4,5), ICOMMS
C
C**** 'TITLE' READ LOAD TITLE
C
    1 READ(ITAPES,902) SUBTIS
      WRITE(LURESS,905) SUBTIS
      GO TO 200
C
C**** 'POINT' NODAL POINT SECTION
C
    2 CONTINUE
      IF(PARAMS(1).EQ.0.0)
     . CALL RUNENDS('ERROR: WRONG NUMBER OF POINT HEATS')
      NLOPOS=DINT(PARAMS(1))
      call runends('loapois not implemented')
c     CALL LOAPOIS(NDIMET,NDOFCT,NDOFNT,NPOINT,KPROBT,NTOTVT,NFUNCT,
c    .             RLOADT,RLOAHT,NLOPOT,LUREST)
      GO TO 200
C
C**** 'VOLUM' SOURCE HEAT SECTION
C
    3 CONTINUE
      IF(PARAMS(1).EQ.0.0)
     . CALL RUNENDS('ERROR: WRONG NUMBER OF VOLUME HEATS')
      NLOEL1=DINT(PARAMS(1))
      call runends('loagras not implemented')
c     CALL LOAGRAS(ELDATT,ELPRET,ELVART,ELMATT,LNODST,MATNOT,PROELT,
c    .             PROPST,RLOADT,RLOAHT,TEMPIT(1,1),3,WORK1T,NLOEL1,
c    .             ADVELT,COORDT,TEMPIT(1,2),FPCHAT,DISPLT)
      GO TO 200
C
C**** 'SURFA' DISTRIBUTED EDGE HEAT SECTION
C
    4 CONTINUE
      IF(PARAMS(1).EQ.0.0)
     . CALL RUNENDS('ERROR: WRONG NUMBER OF SURFACE HEATS')
      NLOEL2=DINT(PARAMS(1))
      call runends('loagras not implemented')
c     CALL LOAGRAT(ELDATT,ELPRET,ELVART,ELMATT,LNODST,MATNOT,PROELT,
c    .             PROPST,RLOADT,RLOAHT,TEMPIT(1,1),4,WORK1T,NLOEL2,
c    .             ADVELT,COORDT,TEMPIT(1,2),FPCHAT,DISPLT)
      GO TO 200
C
C**** 'PRINT' PRINTOUT TOTAL NODAL FORCES
C
    5 WRITE(LURESS,920)
C
      WRITE(LURESS,925)
      DO IPOINS=1,NPOINS
       ITOT0S=(IPOINS-1)*NDOFCS+1
       ITOTFS=IPOINS*NDOFCS
       WRITE(LURESS,940) IPOINS,(RLOADS(ITOTVS),ITOTVS=ITOT0S,ITOTFS)
      END DO
      GO TO 200
C
 2000 CONTINUE
      RETURN
C
  900 FORMAT(1H1,///,10X,'ECHO OF HEAT & FIXITY DATA FOLLOWS :',/
     .               10X,'=================================='/)
  901 FORMAT('ERROR IN OPENING HEAT INPUT FILE')
  902 FORMAT(8A8)  
  905 FORMAT(//5X,8A8)
c 906 FORMAT(//,4X,'HEAT INCREMENTATION DATA',
c    .          '  ( NO. OF FUNCTIONS :',I3,')'//,
c    .          4X,'NUMBER',6X,'TYPE',35X,'PARAMETERS')
c 907 FORMAT(I5,8E15.6)
c 908 FORMAT(5X,I5,5X,I5,12(5X,E15.6))
  920 FORMAT(5X,' REFERENCE ARRAY ( HEATS & PRESCRIBED TEMP. )',/)
  925 FORMAT(5H NODE,6X,5H HEAT)
  940 FORMAT(1X,I5,5X,10E12.4)
      END
