      SUBROUTINE SKYGRAT(DISIT,REFOR,LNODS,
     .                   NDOFN,NELEM,NEVAB,NNODE,NPOIN,NTOTV,
     .                   IDSK2,INRHS,IPASS,KPASS,KPORE,KRESL,NEQNS,
     .                   NLAST,
     .                   IFFIX,
     .                   GSTDI,GSTLO,GSTUP,CSTIF,ELOAD,LNUEQ,LPONT,
     .                   DISIM,FOREL,ALOAD,DELTA,DISIC,LOCAL,
     .                   iiter,miter,
     .                   NPREL,NGRUP,NPROP,NMATS,
     .                   NDATA,NPREV,NSTAT,NMATX,NDIME,NTOTVM,NFPCH,
     .                   MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .                   ELVAR,ELMAT,WORK1,DISTO,COORD,
     .                   ADVEL,TEMPI,PREAS,TGAPS,DISPL,FPCHA,
     .                   NACTI,LACTI)
C***********************************************************************
C
C**** THIS ROUTINE SOLVES THE SET OF LINEAR EQUATIONS USING THE
C         SEmi Direct And iteraTIVE SOLVER ( "SEDATIVE" ) 
C
C     SKYDES
C     SKYGRA
C            - SKYASS 
C            - SKYTRI
C                      - SKYCEK
C                      - SKYDIA
C            - SKYTAP
C            - SKYRHS 
C         !  - SKYBAK              ! Direct Skyline Solver
C         !  - SKYITE  - SKYBAK    ! Iterative PCG Solver
C                      - SKYPRO
C            - SKYRHS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/SOLVERTA/KRENUT,KSOLVT,KSYMMT,NWIDTT,MITCGT,NBUFAT,NPRIRT,
     .                MITGMT,MKRYLT,IPGMRT
      COMMON/SOLVERTB/TOLCGT,TOLC1T,TOLGMT
C
      COMMON/LOGUNT/LUDTST,LUSOLT,LUFROT,LUFRHT,LUDATT,LUPRIT,LUREST,
     .              LUSO2T,LUFR2T,LUPOST,LURSTT,LUBFGT,LUPIPT,LUPANT,
     .              LUGEOT,LUSETT,LUMATT,LUINIT,LULOAT,LUFIXT,LUADVT,
     .              LUACTT,LUFANT,LUSTRT,
     .              LUCU1T,LUCU2T,LUCU3T,LUCU4T,LUCU5T,LUCU6T,LUCU7T,
     .              LUCU8T,LUCU9T,LUC10T
C
      DIMENSION DISIT(NTOTV),   REFOR(NTOTV),  LNODS(NNODE,NELEM)
      DIMENSION LNUEQ(NTOTV),   LPONT(NTOTV)      
      DIMENSION GSTDI(*),       GSTLO(*),      GSTUP(*), 
     .          CSTIF(NEVAB,*), ELOAD(*),      DISIM(*),
     .          FOREL(*),       ALOAD(*),      DELTA(*),
     .          DISIC(*),       LOCAL(*)
      DIMENSION IFFIX(*)
C
      DIMENSION MATNO(NELEM),
     .          PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS),
     .          ELDAT(NDATA),       ELPRE(NPREV),
     .          ELVAR(NSTAT),       ELMAT(NMATX)
      DIMENSION DISTO(NTOTV,3),     COORD(NDIME,NPOIN)
      DIMENSION ADVEL(NTOTV*NDIME), TEMPI(NPOIN,2)
      DIMENSION PREAS(NPOIN),       TGAPS(NPOIN)
      DIMENSION DISPL(NTOTVM),      FPCHA(NFPCH,NPOIN),
     .          LACTI(NELEM)
C
C**** IDENTIFY THE DESTINATION OF THE EQUATIONS INTO PROFILE
C     NEQNS,NLAST,LNUEQ,LPONT
C
      IF((KPASS.EQ.0).OR.((KPORE.EQ.2).AND.(NEQNS.GT.0))) THEN
       REWIND IDSK2
       READ(IDSK2) NEQNS,NLAST,LNUEQ,LPONT
       KPASS=1
      ENDIF
C
C**** ASSEMBLE & FACTORISE MATRIX IF NECESSARY
C
      IF(KRESL.EQ.1) THEN
       CALL SKYASST(CSTIF,GSTDI,GSTLO,GSTUP,LNUEQ,LPONT,KSYMMT,
     .              LNODS,NDOFN,NELEM,NEQNS,NEVAB,NLAST,NNODE,
     .              NWIDTT,NTOTV,NPOIN,
     .              NPREL,NGRUP,NPROP,NMATS,
     .              NDATA,NPREV,NSTAT,NMATX,NDIME,NTOTVM,NFPCH,
     .              MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .              ELVAR,ELMAT,WORK1,DISTO,COORD,DISIT,
     .              ADVEL,TEMPI,PREAS,TGAPS,DISPL,FPCHA,LACTI)
C
       CALL SKYTRI(GSTDI,GSTLO,GSTUP,KSYMMT,LPONT,KPORE,NEQNS,LUREST,
     .                 0,    0)
      ENDIF
C
C**** STORE OR READ BACK THE FACTORISED GLOBAL STIFFNESS MATRICES
C
      IF(KPORE.EQ.2) THEN
       IF(NEQNS.GT.0)
     .  CALL SKYTAP(KRESL,KSYMMT,GSTDI,GSTLO,GSTUP,IDSK2,NLAST,
     .              NEQNS)
      ENDIF
C
C**** IF NECESSARY MODIFY RHS FOR NON-ZERO BOUNDARY CONDITIONS
C
      IF(INRHS.EQ.1)
     . CALL SKYRHST(CSTIF,DISIT,REFOR,LNODS,NDOFN,NELEM,NEVAB,
     .              NNODE,NPOIN,DISIM,FOREL,    1,
     .              NPREL,NGRUP,NPROP,NMATS,
     .              NDATA,NPREV,NSTAT,NMATX,NTOTV,NDIME,NTOTVM,NFPCH,
     .              MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .              ELVAR,ELMAT,WORK1,DISTO,COORD,
     .              ADVEL,TEMPI,PREAS,TGAPS,DISPL,FPCHA,LACTI)
C
C**** COMPRESS RHS
C
      DO ITOTV=1,NTOTV
       IEQNS=LNUEQ(ITOTV)
       IF(IEQNS.GT.0) ELOAD(IEQNS)=REFOR(ITOTV)
      ENDDO
C
C**** SOLVE THE EQUATIONS 
C
      IF(MITCGT.EQ.0) THEN                                ! Skyline
       CALL SKYBAK(GSTDI,GSTLO,GSTUP,LPONT,NEQNS,ELOAD,LUREST)
      ELSE                                               ! PCG
       CALL SKYITET(ELOAD,LNODS,NDOFN,NELEM,NEQNS,NEVAB,NNODE,
     .              NPOIN,NTOTV,CSTIF,LNUEQ,LPONT,DISIM,FOREL,
     .              ALOAD,DELTA,DISIC,GSTDI,GSTLO,GSTUP,LOCAL,
     .              NPREL,NGRUP,NPROP,NMATS,
     .              NDATA,NPREV,NSTAT,NMATX,NDIME,NTOTVM,NFPCH,
     .              MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .              ELVAR,ELMAT,WORK1,DISTO,COORD,DISIT,
     .              ADVEL,TEMPI,PREAS,TGAPS,DISPL,FPCHA,LACTI)
      ENDIF
C
C**** REALLOCATE SOLUTION ARRAY INTO TOTAL NTOTV
C
      DO ITOTV=1,NTOTV
       IEQNS=LNUEQ(ITOTV)
       IF(IEQNS.GT.0) DISIT(ITOTV)=ELOAD(IEQNS)
      ENDDO
C
C**** COMPUTE REACTIONS
C
      IF(IPASS.EQ.2) THEN
       CALL SKYRHST(CSTIF,DISIT,REFOR,LNODS,NDOFN,NELEM,NEVAB,
     .              NNODE,NPOIN,DISIM,FOREL,    0,
     .              NPREL,NGRUP,NPROP,NMATS,
     .              NDATA,NPREV,NSTAT,NMATX,NTOTV,NDIME,NTOTVM,NFPCH,
     .              MATNO,PROEL,PROPS,ELDAT,ELPRE,
     .              ELVAR,ELMAT,WORK1,DISTO,COORD,
     .              ADVEL,TEMPI,PREAS,TGAPS,DISPL,FPCHA,LACTI)
      ENDIF
C
      RETURN
      END
