      SUBROUTINE ADVECTS(ADVELS)
C***********************************************************************
C
C**** THIS ROUTINE READS AND SETS DATA FOR ADVECTIVE VELOCITY
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'inpo_oms.f'
      INCLUDE 'prob_oms.f'
C
      COMMON/LDFILES/ITAPES
C
      DIMENSION ADVELS(NDIMES,NTOTVS)
C
c     IERR1T=1
c     IF(ITAPET.NE.LUDATT.AND.ITAPET.NE.LUADVT) GOTO 1000
c     IF(ITAPET.EQ.LUADVT) THEN       ! external .adv file
c      OPEN(UNIT=LUADVT,FILE=CG1T,STATUS='OLD',ERR=1000)
c      IERR1T=0
C
c1000  IF(IERR1T.NE.0) THEN
c       IF(IERR1T.EQ.1) WRITE(LUREST,901)
c       CALL RUNENDT('ERROR IN OPENING FILE ')
c      ENDIF
c     ENDIF      ! itapet.eq.luadvt
C
      WRITE(LURESS,900)
C
C**** READ THE ADVECTIVE VELOCITY
C
      NPRINS=1
      CALL LISTENS('ADVECTS',NPRINS,ITAPES)
      NPOI1S=INT(PARAMS(1))
      WRITE(LURESS,905) NPOI1S
      IF(NPOINS.LT.NPOI1S) THEN
       WRITE(LURESS,910)
       CALL RUNENDS('ADVECTS: ERROR WHEN READING THE NUMBER OF POINTS
     .                        WITH ADVECTIVE VELOCITY')
      ENDIF
C
C**** READ NODAL VARIABLES
C
      DO IPOINS=1,NPOI1S
       CALL LISTENS('ADVECTS',NPRINS,ITAPES)
       JPOINS=INT(PARAMS(1))
       DO IDIMES=1,NDIMES
        ADVELS(IDIMES,JPOINS)=PARAMS(1+IDIMES)
       ENDDO
      ENDDO
C
C**** ECHO NODAL VALUES FOR THE WHOLE MESH
C
      WRITE(LURESS,921)
      DO IPOINS=1,NPOINS
       WRITE(LURESS,930) IPOINS,(ADVELS(IDIMES,IPOINS),IDIMES=1,NDIMES)
      ENDDO
C
      WRITE(LURESS,940)
C
      RETURN
C
  900 FORMAT('ADVECTIVE VELOCITY DATA',//)
  901 FORMAT(' ERROR IN OPENING ADVECTIVE VELOCITY INPUT FILE 246',
     . '(56 LINUX)')
  905 FORMAT(/,5X,'NUMBER OF NODES WITH ADVECTIVE VELOCITY DATA',I5,/)
  910 FORMAT(//,'ERROR: NUMBER OF INPUT POINTS GT TOTAL NO. POINTS')
  921 FORMAT(1X,'NODE',4X,'ADVECTIVE VELOCITY',/)
  930 FORMAT(I5,10X,3(E15.6,5X))
  940 FORMAT(/)
      END
