      SUBROUTINE PROPMIC5(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 5
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** COMPOSITION (INITIAL)
C
      NPRINT=0
      CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'COMPO') THEN
       WRITE(LURESS,810)
       WRITE(LURESS,809)
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'CARBO') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO CARBON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG CARBON COMPOSITION')
       WRITE(LURESS,811) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SILIC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO SILICON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG SILICON COMPOSITION')
       WRITE(LURESS,812) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'PHOSP') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO PHOSPHORUS CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG PHOSPORUS COMPOSITION')
       WRITE(LURESS,813) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'COPPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO COPPER CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG COPPER COMPOSITION')
       WRITE(LURESS,814) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MANGA') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO MANGANESE CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG MANGANESE COMPOSITION')
       WRITE(LURESS,815) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MAGNE') THEN      ! spheroidizer in SG cast iron
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO MAGNESIUM CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG MAGNESIUM COMPOSITION')
       WRITE(LURESS,816) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC5: NO COMPOSITION CARD')
      ENDIF
C
C**** EQUILIBRIUM DIAGRAM PARAMETERS
C
      CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'EQUIL') THEN
       WRITE(LURESS,820)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SILIC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC5: NO SILICON PARTITION COEFFICIENT CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0)
     .  CALL RUNENDS('PROPMIC5: WRONG SILICON PARTITION COEFFICIENT')
       WRITE(LURESS,821) PARAMS(1)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'CORRE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1.0D0                              ! Heine
        IF(WORDSS(2).EQ.'LACAZ') PROPSS(NPOI2T)=2.0D0     ! Lacaze
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1.0D0      ! default: Heine
        GO TO 11
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC5: NO EQUIL. DIAGRAM PARAM. CARD')
      ENDIF
C
C**** PRIMARY AUSTENITE SOLIDIFICATION (not implemented yet!)
C

C
C**** EUTECTIC SOLIDIFICATION
C
      CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
   11 IF(WORDSS(1).EQ.'EUTEC') THEN
       WRITE(LURESS,840)
       WRITE(LURESS,809)
C
C**** NUCLEATION PROPERTIES
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'NUCLE'.AND.WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)     ! nucleation model index
        INUCMX=INT(PARAMS(1))
        IF(INUCMX.EQ.1.OR.           ! Su, Boeri & Lacaze nuc. models
     .     INUCMX.EQ.2.OR.INUCMX.EQ.3) THEN
         CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! coefficient b
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)    ! coefficient c
         WRITE(LURESS,841) PROPSS(NPOI2T-1),PROPSS(NPOI2T)
        ELSE
         CALL RUNENDS('PROPMIC5: INCORRECT NUCLEATION MODEL NUMBER')
        ENDIF
C
        CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'ARRES') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! nucleation arrest criterion index
         INUCAX=INT(PARAMS(1))
         IF(INUCAX.NE.1.AND.INUCAX.NE.2)         ! Trecal & Tmin
     .    CALL RUNENDS('PROPMIC5: INCORRECT ARREST CRITERION NUMBER')
        ELSE
         CALL RUNENDS('PROPMIC5: NO ARREST CRITERION CARD')
        ENDIF
C
        CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'CONTR') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=1.0D0        ! control minimum N index
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! minimum N
        ELSE
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=0.0D0
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=0.0D0
         GO TO 1
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC5: NO NUCLEATION OR MODEL CARD')
       ENDIF
       WRITE(LURESS,809)
C
C**** GROWTH PROPERTIES
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
    1  IF(WORDSS(1).EQ.'GROWT'.AND.WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)     ! growth model index
        IGROMX=INT(PARAMS(1))
        IF(IGROMX.EQ.1.OR.           ! Su (2) & Lacaze growth models
     .     IGROMX.EQ.2.OR.IGROMX.EQ.3) THEN
         CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! diffusion coef. of C in austenite
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)    ! initial r of aust. shell
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)    ! initial r of graphite nodule
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(4)    ! auste. shell r/graphite r ratio
         WRITE(LURESS,842) PROPSS(NPOI2T-3),PROPSS(NPOI2T-2),
     .                     PROPSS(NPOI2T-1),PROPSS(NPOI2T)
        ELSE
         CALL RUNENDS('PROPMIC5: INCORRECT GROWTH MODEL NUMBER')
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC5: NO GROWTH OR MODEL CARD')
       ENDIF
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC5: NO EUTECTIC SOLIDIFICATION CARD')
      ENDIF
C
C**** MICROSTRUCTURE-DEPENDENT THERMAL PROPERTIES
C
      CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONDU'.AND.WORDSS(2).EQ.'MODEL') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1) ! micro-dependent conductivity index
       IKMICX=INT(PARAMS(1))
       IF(IKMICX.EQ.1.OR.IKMICX.EQ.2.OR.IKMICX.EQ.3) THEN
        CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1) ! solid conductivity
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2) ! mushy conductivity
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(3) ! liquid conductivity
        WRITE(LURESS,851) PROPSS(NPOI2T-3),PROPSS(NPOI2T-2),
     .                    PROPSS(NPOI2T-1),PROPSS(NPOI2T)
       ELSE
        CALL RUNENDS('PROPMIC5: INCORRECT CONDUCTIVITY MODEL NUMBER')
       ENDIF
       WRITE(LURESS,809)
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0     ! conductivity does not depend on micro.
       GO TO 2
      ENDIF
C
C**** NUMERICAL STRATEGY PARAMETERS
C
      CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
    2 IF(WORDSS(1).EQ.'NUMER') THEN
       WRITE(LURESS,860)
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TEMPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IFPCDT=INT(PARAMS(1))
        IF(IFPCDT.LT.1.OR.IFPCDT.GT.5)
     .   CALL RUNENDS('PROPMIC5: WRONG IFPCDT VALUE')
        WRITE(LURESS,861) IFPCDT
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC5: NO TEMPERATURE DERIVATIVE FORM OF FL')
       ENDIF
C
       CALL LISTENS('PROPMIC5',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'FRACT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IAFLOJ=INT(PARAMS(1))
        WRITE(LURESS,862) IAFLOJ
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC5: NO FRACTION CORRECTION CARD')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC5: NO NUMERICAL STRATEGY CARD')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA5S=1
      IPLLLS(INUPM)=5
C
      RETURN
  809 FORMAT(/)
  810 FORMAT(3X,'COMPOSITION (INITIAL):')
  811 FORMAT(3X,' CARBON CONTENT     =',E15.6)
  812 FORMAT(3X,' SILICON CONTENT    =',E15.6)
  813 FORMAT(3X,' PHOSPHORUS CONTENT =',E15.6)
  814 FORMAT(3X,' COPPER CONTENT     =',E15.6)
  815 FORMAT(3X,' MANGANESE CONTENT  =',E15.6)
  816 FORMAT(3X,' MAGNESIUM CONTENT  =',E15.6)
C
  820 FORMAT(3X,'EQUILIBRIUM DIAGRAM PARAMETERS:')
  821 FORMAT(3X,' SILICON PARTITION COEFFICIENT=',E15.6)
C

C
  840 FORMAT(3X,'EUTECTIC SOLIDIFICATION PARAMETERS:')
  841 FORMAT(3X,' NUCLEATION PARAMETERS:',/,
     .       3X,'  COEFFICIENT b            =',E15.6,/,
     .       3X,'  COEFFICIENT c            =',E15.6)
  842 FORMAT(3X,' GROWTH PARAMETERS:',/,
     .       3X,'  DIFFUSION COEF. OF C IN AUSTENITE=',E15.6,/,
     .       3X,'  INITIAL RADIUS OF AUSTENITE SHELL=',E15.6,/,
     .       3X,'  INITIAL RADIUS OF NODULES=',E15.6,/,
     .       3X,'  AUSTENITE SHELL RADIUS/GRAPHITE RADIUS=',E15.6)
C
  851 FORMAT(3X,'MICROSTRUCTURE-DEPENDENT CONDUCTIVITY:',/,
     .       3X,' MODEL              =',E15.6,/,
     .       3X,' SOLID CONDUCTIVITY =',E15.6,/,
     .       3X,' MUSHY CONDUCTIVITY =',E15.6,/,
     .       3X,' LIQUID CONDUCTIVITY=',E15.6)
C
  860 FORMAT(3X,'NUMERICAL STRATEGY PARAMETERS')
  861 FORMAT(3X,'TEMPERATURE DERIVATIVE FORM OF FL=',I5)
  862 FORMAT(3X,'FRACTION CORRECTION FORM         =',I5)
      END
