      SUBROUTINE WACOBST(CARTD,DERIV,NDIME,NNODE,XJACM)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE JACOBIAN MATRIX AND THE CARTESIAN
C     PERTURBATION FUNCTION DERIVATIVES
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION CARTD(NDIME,*), DERIV(NDIME,*), XJACM(NDIME,*)
      DIMENSION XJACI(3,3)
C
C**** CALCULATE THE DETERMINANT AND INVERS OF JACOBIAN MATRIX
C
      CALL INVMTX(XJACM,XJACI,DETJM,NDIME)
C
C**** CALCULATE CARTESIAN DERIVATIVES
C
      CALL PROMA1(CARTD,XJACI,DERIV,NDIME,NNODE,NDIME)
C
      RETURN
      END
