      SUBROUTINE PLAMTX(DMATX,EHIST,NCRIT,NSTR1,NSTRS,NTYPE,PROPS,
     .                  SGTOT)
C**********************************************************************
C
C****THIS ROUTINE CALCULATES THE PLASTIC PART OF THE CONSTITUTIVE 
C    MATRIX
C
C**********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION DMATX(NSTRS,*), EHIST(*), PROPS(*), SGTOT(*)
      DIMENSION AVECT(6), DVECT(6)
C
      IF(EHIST(1).LE.0.0) RETURN
C
      VSTOT=EHIST(2)
      CALL YIELDS(AVECT,DEFPI,EHIST,HARDS,NCRIT,NSTR1,NTYPE,
     .            PROPS,SGTOT,VSTOT)
      CALL FLOWPL(AVECT,ABETA,DMATX,DVECT,HARDS,NSTRS,NTYPE,
     .            PROPS)
C
      KOUNT=0
      DO 10 ISTRS=    1,NSTRS
      DO 10 JSTRS=ISTRS,NSTRS
      DMATX(ISTRS,JSTRS)=DMATX(ISTRS,JSTRS)
     .                  -ABETA*DVECT(ISTRS)*DVECT(JSTRS)
   10 DMATX(JSTRS,ISTRS)=DMATX(ISTRS,JSTRS)
C
      RETURN
      END
