      SUBROUTINE PLPDXV(VECTO,DMATX,DXVEC,NSTRS,NTYPE,ISOTR,NSTR1)
C***********************************************************************
C
C**** THIS SUBROUTINE EVALUATES DxV PRODUCT
C
C     Note: the full product (i.e., considering DMATX(1,3), etc.) must
C           be performed for LARGE > 0
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION VECTO(6), DMATX(6,6), DXVEC(6)
C
      
      IF(ISOTR.NE.0.) GO TO 10          ! isotr=1 for anisotropic models
C
C**** 1D CASE
C
      IF(NTYPE.EQ.5) THEN
       DXVEC(1)=DMATX(1,1)*VECTO(1)
      ENDIF
C
      IF(NTYPE.EQ.1) GO TO 20
C
C**** PLANE STRAIN AND AXISYMMETRIC CASES
C
      DXVEC(1)=DMATX(1,1)*VECTO(1)+DMATX(1,2)*VECTO(2)+
     .         DMATX(1,3)*VECTO(3)+DMATX(1,4)*VECTO(4)
      DXVEC(2)=DMATX(2,1)*VECTO(1)+DMATX(2,2)*VECTO(2)+
     .         DMATX(2,3)*VECTO(3)+DMATX(2,4)*VECTO(4)
      DXVEC(3)=DMATX(3,1)*VECTO(1)+DMATX(3,2)*VECTO(2)+
     .         DMATX(3,3)*VECTO(3)+DMATX(3,4)*VECTO(4)
      DXVEC(4)=DMATX(4,1)*VECTO(1)+DMATX(4,2)*VECTO(2)+
     .         DMATX(4,3)*VECTO(3)+DMATX(4,4)*VECTO(4)
C
      IF(NTYPE.NE.4) GO TO 30
C
C**** ADD THE PROPER TERMS FOR 3-D CASE
C
      DXVEC(1)=DXVEC(1)+DMATX(1,5)*VECTO(5)+DMATX(1,6)*VECTO(6)
      DXVEC(2)=DXVEC(2)+DMATX(2,5)*VECTO(5)+DMATX(2,6)*VECTO(6)
      DXVEC(3)=DXVEC(3)+DMATX(3,5)*VECTO(5)+DMATX(3,6)*VECTO(6)
      DXVEC(4)=DXVEC(4)+DMATX(4,5)*VECTO(5)+DMATX(4,6)*VECTO(6)
      DXVEC(5)=DMATX(5,1)*VECTO(1)+DMATX(5,2)*VECTO(2)+
     .         DMATX(5,3)*VECTO(3)+DMATX(5,4)*VECTO(4)+
     .         DMATX(5,5)*VECTO(5)+DMATX(5,6)*VECTO(6)
      DXVEC(6)=DMATX(6,1)*VECTO(1)+DMATX(6,2)*VECTO(2)+
     .         DMATX(6,3)*VECTO(3)+DMATX(6,4)*VECTO(4)+
     .         DMATX(6,5)*VECTO(5)+DMATX(6,6)*VECTO(6)
C
      GOTO 30
C
C**** PLANE STRESS CASE
C
   20 DXVEC(1)=DMATX(1,1)*VECTO(1)+DMATX(1,2)*VECTO(2)+
     .         DMATX(1,3)*VECTO(3)
      DXVEC(2)=DMATX(2,1)*VECTO(1)+DMATX(2,2)*VECTO(2)+
     .         DMATX(2,3)*VECTO(3)
      DXVEC(3)=DMATX(3,1)*VECTO(1)+DMATX(3,2)*VECTO(2)+
     .         DMATX(3,3)*VECTO(3)
C
      GOTO 30
C
C**** FOR THE CASE WHEN THE PRINCIPAL DIRECTION OF THE ELASTIC TENSOR
C     DOES NOT COINCIDE WITH THE CARTESIAN REFERENCE SISTEM
C     (ANISOTROPIC MODELS)
C
   10 DO 40 ISTRS=1,NSTRS
      DXVEC(ISTRS)=0.0D0
      DO 40 JSTRS=1,NSTRS
   40 DXVEC(ISTRS)=DXVEC(ISTRS)+DMATX(ISTRS,JSTRS)*VECTO(JSTRS)
C
   30 RETURN
      END
