      SUBROUTINE OUTCEKT(IITERT,ISTEPT,KPRINT,NCHEKT,NOUTPT,NSTEPT,
     .                   TLIMTT,NCKGLO)
C***********************************************************************
C
C**** THIS ROUTINE CHECKS IF THE RESULTS SHOULD BE PRINTOUT
C
C       KPRI0=0  DO NOT WRITE TO OUTPUT FILE
C             1  WRITE TO OUTPUT FILES
C       KPRI1=0  DO NOT WRITE TEMPERATURES TO OUTPUT FILE
C             1  WRITE TEMPERATURES TO OUTPUT FILES
C       KPRI2=0  DO NOT WRITE GAUSSIAN HEAT FLUXES TO OUTPUT FILE
C             1  WRITE GAUSSIAN HEAT FLUXES TO OUTPUT FILES
C       KPRI3=0  ---
C             1  ---
C       KPRI4=0  DO NOT WRITE GAUSSIAN INTERNAL VARIABLES TO OUTPUT FILE
C             1  WRITE GAUSSIAN INTERNAL VARIABLES TO OUTPUT FILES
C       KPRI5=0  DO NOT WRITE NODAL HEAT FLUXES
C             1  WRITE NODAL HEAT FLUXES
C       KPRI6=0  DO NOT WRITE NODAL MACROSCOPIC PHASE-CHANGE FUNCTION
C             1  WRITE NODAL MACROSCOPIC PHASE-CHANGE FUNCTION
C       KPRI7=0  DO NOT WRITE NODAL INTERNAL VARIABLES TO OUTPUT FILE
C             1  WRITE NODAL INTERNAL VARIABLES TO OUTPUT FILES
C       KPRI8=0  DO NOT NODAL WRITE POROSITY CRITERIA
C            =1  WRITE NODAL POROSITY CRITERIA
C
C       KPRIN=1  WRITE TO OUTPUT FILES TEMPERATURES AND HEAT FLUXES
C
C       KFEMV=0  DO NOT WRITE FOR POSTPROCESOR
C             1  WRITE FOR POSTPROCESOR
C
C       NOUTP( 1) RESTART INDICATOR
C       NOUTP( 2) POSTPROCESOR         INDICATOR FOR CONVERGED
C                                      ITERATIONS
C
C       NOUTP( 4) TEMPERATURES     OUTPUT  "      "      "         "
C       NOUTP( 5) GAUSS HEAT FLUXES   "    "      "      "         "
C       NOUTP( 6) 
C       NOUTP( 7) GAUSSIAN INT. VAR.  "    "      "      "         "
C       NOUTP( 8) NODAL HEAT FLUXES   "    "      "      "         "
C       NOUTP( 9) NODAL MACROSCOPIC PHASE-CHANGE FUNCTION
C       NOUTP(10) TOTAL               "    "      "      "         "
C       NOUTP(11) POSTPROCESOR
C       NOUTP(20) NODAL INT. VAR.     "    "      "      "         "
C       NOUTP(22) NODAL POROSITY CRITERIA
C
C                                      INDICATOR FOR NON CONVERGED
C                                      ITERATIONS
C
C       NOUTP(13) TEMPERATURES     OUTPUT  "      "   "      "        "
C       NOUTP(14) GAUSS HEAT FLUXES   "    "      "   "      "        "
C       NOUTP(15) 
C       NOUTP(16) GAUSSIAN INT. VAR.  "    "      "   "      "        "
C       NOUTP(17) NODAL HEAT FLUXES   "    "      "   "      "        "
C       NOUTP(18) NODAL MACROSCOPIC PHASE-CHANGE FUNCTION
C       NOUTP(19) TOTAL               "    "      "   "      "        "
C       NOUTP(21) NODAL INT. VAR.     "    "      "   "      "        "
C       NOUTP(23) NODAL POROSITY CRITERIA
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'inpo_omt.f'
C
      DIMENSION NOUTPT(50)
C
      KFEMVT=0
      KPRINT=0
      KPRI0T=0
      KPRI1T=0
      KPRI2T=0
      KPRI3T=0
      KPRI4T=0
      KPRI5T=0
      KPRI6T=0
      KPRI7T=0
      KPRI8T=0
      KPRI9T=0
      KPRI10T=0
C
      IF(NCHEKT.EQ.0.AND.NCKGLO.EQ.0) THEN        ! CONVERGED RESULTS
       IF(NOUTPT( 2).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT( 2)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KFEMVT=1
       ENDIF
       IF(NOUTPT( 4).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT( 4)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI1T=1
       END IF
       IF(NOUTPT( 5).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT( 5)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI2T=1
       END IF
       IF(NOUTPT( 7).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT( 7)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI4T=1
       END IF
       IF(NOUTPT( 8).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT( 8)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI5T=1
       END IF
       IF(NOUTPT( 9).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT( 9)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI6T=1
       END IF
       IF(NOUTPT(20).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT(20)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI7T=1
       END IF
       IF(NOUTPT(22).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT(22)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRI8T=1
       END IF
       IF(NOUTPT(10).NE.0) THEN
        IF(MOD(ISTEPT,NOUTPT(10)).EQ.0.OR.ISTEPT.EQ.NSTEPT) KPRINT=1
       END IF
      ELSE                                ! NON CONVERGED RESULTS
       IF(NOUTPT(11).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(11)).EQ.0) KFEMVT=1
       ENDIF
       IF(NOUTPT(13).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(13)).EQ.0) KPRI1T=1
       END IF
       IF(NOUTPT(14).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(14)).EQ.0) KPRI2T=1
       END IF
       IF(NOUTPT(16).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(16)).EQ.0) KPRI4T=1
       END IF
       IF(NOUTPT(17).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(17)).EQ.0) KPRI5T=1
       END IF
       IF(NOUTPT(18).NE.0) THEN
        IF(MOD(IITERT,NOUTPT( 9)).EQ.0) KPRI6T=1
       END IF
       IF(NOUTPT(21).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(21)).EQ.0) KPRI7T=1
       END IF
       IF(NOUTPT(23).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(23)).EQ.0) KPRI8T=1
       END IF
       IF(NOUTPT(19).NE.0) THEN
        IF(MOD(IITERT,NOUTPT(19)).EQ.0) KPRINT=1
       END IF
      ENDIF
C
      IF(KPRINT.EQ.1) THEN
       KPRI0T=1
       KPRI1T=1
       KPRI2T=1
       KPRI4T=1
       KPRI5T=1
       KPRI6T=1
       KPRI7T=1
       KPRI8T=1
      ENDIF
      IF((KPRI1T+KPRI2T+KPRI4T+KPRI5T+KPRI6T+KPRI7T+KPRI8T).GT.0)
     .                                                          KPRI0T=1
C
      CALL CPUTIMT(CUCPUT)
      IF((CUCPUT.GE.TLIMTT).AND.(NCHEKT.EQ.0).AND.(NCKGLO.EQ.0)) THEN
       IF((NOUTPT(2)+NOUTPT(11)).GT.0) KFEMVT=1
      ENDIF
C
C**** SIMILAR TREATMENT FOR THE POSTPROCESS OPTIONS (not implem. yet)
C
cpost
cpost       only nodal values for postprocessing
cpost       see: strinpt, outpost, outdist, outgaut & outnodt
C
      RETURN
      END
