      SUBROUTINE BFGSUPT(DISITT,REFORT,VVECTT,WVECTT)
C***********************************************************************
C
C**** THIS ROUTINE MODIFIES THE ITERATIVE DISPLACEMENTS 
C     IF A QUASI-NEWTON METHOD IS USED ( BFGS )
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
C
      COMMON/ANTESOTA/NBFGST,NVECTT
C 
      DIMENSION DISITT(*),      REFORT(NTOTVT), VVECTT(NTOTVT), 
     .          WVECTT(NTOTVT)
C
      IF(NVECTT.EQ.0) GO TO 100
C
      DO 10 IVECTT=1,NVECTT
      READ(NBFGST) VVECTT,WVECTT
        CONSTT=0.0D+00
        DO 20 ITOTVT=1,NTOTVT
   20   CONSTT=CONSTT+VVECTT(ITOTVT)*DISITT(ITOTVT)
        DO 30 ITOTVT=1,NTOTVT
   30   DISITT(ITOTVT)=DISITT(ITOTVT)+CONSTT*WVECTT(ITOTVT)     
   10 CONTINUE     
C
C**** RECOVER 'REAL' RESIDUAL FORCES ARRAY
C
  100 CONTINUE
      READ(NBFGST) REFORT
      BACKSPACE NBFGST
C
      RETURN
      END
