C=============================================================== ADDITIO
C**** ADDITI
C
      INTEGER*4      NDISKDS,NFURESS,NMACHIS,NMEMOS,ICHALS
      COMMON/ADDITIS/NDISKDS,NFURESS,NMACHIS,NMEMOS,ICHALS
C
      INTEGER*4       NMEMO1S,NMEMO2S,NMEMO3S,NMEMO4S,NMEMO5S
      COMMON/ADDITI1S/NMEMO1S,NMEMO2S,NMEMO3S,NMEMO4S,NMEMO5S
C
      INTEGER*4       NMEMO6S,NMEMO7S,NMEMO8S,NMEMO9S,NMEMO10S
      COMMON/ADDITI2S/NMEMO6S,NMEMO7S,NMEMO8S,NMEMO9S,NMEMO10S
C
      INTEGER*4       NMEMO11S,NMEMO12S,NMEMO13S,NMEMO14S,NMEMO15S
      COMMON/ADDITI3S/NMEMO11S,NMEMO12S,NMEMO13S,NMEMO14S,NMEMO15S
C
      INTEGER*4       NMEMO16S,NMEMO17S,NMEMO18S,NMEMO19S,NMEMO20S
      COMMON/ADDITI4S/NMEMO16S,NMEMO17S,NMEMO18S,NMEMO19S,NMEMO20S
C
C=============================================================== ADDITIO
