#!/usr/bin/python

import os, pwd

users = os.listdir("/home")

for user in users:
  try:
    a = pwd.getpwnam(user)
    os.mkdir(os.path.join('home', user, 'datos'))
    os.mkdir(os.path.join('home', user, 'scratch'))
    os.chown(os.path.join('home', user, 'datos'), a[2], a[3])
    os.chown(os.path.join('home', user, 'scratch'), a[2], a[3])
  except (OSError, KeyError):
    pass  
