      SUBROUTINE FIXITYT(IFFIXT,LNODST,PRESCT,PRESHT,ELDATT,MATNOT,
     .                   PROELT,WORK1T)
C***********************************************************************
C
C**** THIS ROUTINE READS AND SETS DATA FOR FIXITY CONDITIONS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inpo_omt.f'
      INCLUDE 'prob_omt.f'
C
      COMMON/LDFILET/ITAPET
C
      DIMENSION IFFIXT(NTOTVT,*), LNODST(NNODET,*), PRESCT(NTOTVT,2)
      DIMENSION PRESHT(*)
      DIMENSION ELDATT(*),        MATNOT(*),        PROELT(*),
     .          WORK1T(*)
C
      IERR1T=1
      IF(ITAPET.NE.LUDATT.AND.ITAPET.NE.LUFIXT) GOTO 1000
      IF(ITAPET.EQ.LUFIXT) THEN       ! external .fix file
       IF(IOFIXT.EQ.0) OPEN(UNIT=LUFIXT,FILE=CF1T,STATUS='OLD',ERR=1000)
       IOFIXT=1
       IERR1T=0
C
 1000  IF(IERR1T.NE.0) THEN
        IF(IERR1T.EQ.1) WRITE(LUREST,901)
        CALL RUNENDT('ERROR IN OPENING FILE ')
       ENDIF
      ENDIF      ! itapet.eq.lufixt
C
C**** INITIALISE FIXITY ARRAY
C
      WRITE(LUREST,900)
C
      DO 10 ITOTVT=1,NTOTVT
   10 IFFIXT(ITOTVT,1)=0
C
      IF(KSMUST.NE.0) THEN
       DO 12 ITOTVT=1,NTOTVT
   12  IFFIXT(ITOTVT,2)=0
       DO 15 IPOINT=1,NPOINT
       ITOTVT=IPOINT*NDOFCT
   15  IFFIXT(ITOTVT,2)=1
      ENDIF
C
C**** READ THE FIXITY CONDITIONS AND PRESCRIBED VALUES
C
   20 NPRINT=1
      CALL LISTENT('FIXITYT',NPRINT,ITAPET)
      NOFIXT=DINT(PARAMT(1))
      IFPRET=DINT(PARAMT(2))
      IFUNCT=DINT(PARAMT(3))
      IF(NOFIXT.LE.0.OR.NOFIXT.GT.NPOINT)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PRESCRIBED NODE')
      DO IDOFNT=1,NDOFNT
       PRESHT(IDOFNT)=PARAMT(IDOFNT+3)
      ENDDO
      WRITE(LUREST,920) NOFIXT,IFPRET,IFUNCT,
     .                 (PRESHT(IDOFNT),IDOFNT=1,NDOFCT)
C
      NLOCAT=(NOFIXT-1)*NDOFCT
      IFDOCT=10**(NDOFCT-1)
C
      DO 30 IDOFCT=1,NDOFCT
      ITOTVT=NLOCAT+IDOFCT
      IF(IFPRET.LT.IFDOCT) GOTO 30
      IFFIXT(ITOTVT,1)=1
      IF(KSMUST.NE.0) IFFIXT(ITOTVT,2)=1
      PRESCT(ITOTVT,1)=PRESHT(IDOFCT)
      PRESCT(ITOTVT,2)=IFUNCT
      IFPRET=IFPRET-IFDOCT
   30 IFDOCT=IFDOCT/10
C
      IF(NOFIXT.LT.NPOINT) GOTO 20
C
      WRITE(LUREST,925)
C
C**** STORES DEFINED BOUNDARY CONDITIONS WHEN ACTIVE ELEMENTS ARE USED
C
      IF(NACTIT.EQ.1) THEN
       DO ITOTVT=1,NTOTVT
        IF(KSMUST.EQ.0) THEN
         IFFIXT(ITOTVT,2)=IFFIXT(ITOTVT,1)
        ELSE
         IFFIXT(ITOTVT,3)=IFFIXT(ITOTVT,1)
         IFFIXT(ITOTVT,4)=IFFIXT(ITOTVT,2)
        ENDIF
       ENDDO
      ENDIF
C
      RETURN
  900 FORMAT(//10X,5H NODE,10X,5H CODE,10X,6H FUNC.,6X,
     .       12HFIXED VALUES)
  901 FORMAT(' ERROR IN OPENING BOUNDARY CONDITIONS INPUT FILE 245',
     . '(55 LINUX)')
c 910 FORMAT(2I5,10F10.6)
c 915 FORMAT(I5,I10,10F10.6)
  920 FORMAT(3(5X,I10),5X,1F10.6)
  925 FORMAT(/)
      END
