      SUBROUTINE RSSETPT
C***********************************************************************
C
C**** THIS ROUTINE CALCULATES  THE RECORD ADDRES FOR DIFFERENT ARRAYS
C     STORED IN THE PROCESSING AREA
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
C
C**** SET IDATP POINTERS
C
      DO INDEXT=1,12
       IDATPT(INDEXT,1)=0
       IDATPT(INDEXT,2)=0
      ENDDO
C
C**** EVALUATE LENGTH OF EACH ARRAY IN DOUBLE PRECISION WORDS
C
      NMEMA6=1-NMEMO6
      NMEMA7=1-NMEMO7
C
      IDATPT( 1,1)=NDATAT                                   ! ELDAT
      IDATPT( 2,1)=NPREVT                                   ! ELPRE
      IDATPT( 3,1)=NSTATT                                   ! ELVAR
      IDATPT( 4,1)=NPREVT                                   ! ELPRE
      IDATPT( 5,1)=NSTATT                                   ! ELVAR
      IDATPT( 6,1)=NEVACT*NEVACT*NMEMA7                     ! CSTIF
      IDATPT( 7,1)=NKOVAT*NMEMA6                            ! ESTIF
      IF(KDYNAT.NE.0) IDATPT( 8,1)=NKOVAT*NMEMA6            ! WSTIF
      IF(KPORET.EQ.2) THEN
       IDATPT( 9,1)=NKONDT                                  ! PSTIF
       IDATPT(10,1)=NKONDT                                  ! QSTIF
       IDATPT(11,1)=NEVABT*NNODET                           ! HSTIF
      ENDIF
      IDATPT(12,1)=NTOTVT                                   ! DISTO
C
      GO TO (101,102,102,101,101,101,101,101), NMACHI
C
  101 CONTINUE
      LENWDT=LENRCT/4
      GO TO 1000
C
  102 CONTINUE
      LENWDT=LENRCT
      GO TO 1000
C
 1000 CONTINUE
C
C**** EVALUATE LENGTH OF EACH ARRAY IN RECORDS
C
      DO INDEXT=1,12
       IF(IDATPT(INDEXT,1).NE.0)
     .  IDATPT(INDEXT,2)=(2*IDATPT(INDEXT,1)-1)/LENWDT+1
      ENDDO
C
C**** INITIALIZE POINTERS FOR POSITION IN DOUBLE PRECISION WORDS
C
      IDATPT( 1,3)=0
      DO INDEXT=2,7
       IDATPT(INDEXT,3)=IDATPT(INDEXT-1,3)+IDATPT(INDEXT-1,1)
      ENDDO
C
      IF((KPROBT.EQ.1).AND.(KPORET.NE.2.AND.KDYNAT.NE.1)) THEN
       IDATPT(8,3)=IDATPT(7,3)
       IDATPT(7,3)=IDATPT(6,3)
      ELSE
       IDATPT(8,3)=IDATPT(7,3)+IDATPT(7,1)
      ENDIF
C
      IDATPT(9,3)=IDATPT(8,3)+IDATPT(8,1)
C
      IDATPT(10,3)=IDATPT( 9,3)+IDATPT( 9,1)
      IDATPT(11,3)=IDATPT(10,3)+IDATPT(10,1)
      IDATPT(12,3)=IDATPT(11,3)+IDATPT(11,1)
C
C**** INITIALIZE POINTERS FOR POSITION IN RECORDS
C
      IDATPT( 1,4)=0
      DO INDEXT=2,7
       IDATPT(INDEXT,4)=IDATPT(INDEXT-1,4)+IDATPT(INDEXT-1,2)
      ENDDO
C
      IF((KPROBT.EQ.1).AND.(KPORET.NE.2.AND.KDYNAT.NE.1)) THEN
       IDATPT(8,4)=IDATPT(7,4)
       IDATPT(7,4)=IDATPT(6,4)
      ELSE
       IDATPT(8,4)=IDATPT(7,4)+IDATPT(7,2)
      ENDIF
C
      IDATPT(9,4)=IDATPT(8,4)+IDATPT(8,2)
C
      IDATPT(10,4)=IDATPT( 9,4)+IDATPT( 9,2)
      IDATPT(11,4)=IDATPT(10,4)+IDATPT(10,2)
      IDATPT(12,4)=IDATPT(11,4)+IDATPT(11,2)
C
C**** LAST RECORD OF THE BLOCK
C
      NLENPT=IDATPT(12,4)
C
C**** LAST RECORD OF THE FILE
C
      NRECPT=NLENPT*NELEMT
C
C**** INITIALIZE FLAGS FOR ARRAYS ALLOCATION
C
      DO INDEXT=1,11
       IDATPT(INDEXT,5)=-1
      ENDDO
      IDATPT(12,5)=0
C
      RETURN
      END
