      SUBROUTINE PROP05FO(ITAPET,PROPST)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MATERIAL PROPERTIES FOR SOLID MODEL
C     (ELEMENT NO. 5) - FILLING MATERIAL
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
      INCLUDE 'nuef_om.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION PROPST(*)
C
C**** CHECKS DIMENSIONS OF THERMAL INTERNAL VARIABLES
C
      IF(NMEMO3.EQ.1) THEN
       NHISTY=7+NDIMET          ! see index of variables in micr05t.f
       NHISTX=NHISTT
       IF(IMICR.EQ.1) NHISTX=NHISTT-NHISTM
       IF(NHISTY.GT.NHISTX)        ! increase NHIST1 in consett.f
     .  CALL RUNENDT('ERROR: (NHISTY GT NHISTX - prop05t.f')
      ENDIF
C
C**** ESTABLISH SOME PARAMETERS
C
      PROPST(1)=1.0D0           ! isotrt=1 => orthotropic material
      NSOTRT=1                  ! at least one orthotropic material
      PROPST(2)=1.0D0           ! ifill=1 => filling material
      NFILL=1                   ! at least one filling material
C
C**** READ & WRITE MATERIAL PROPERTIES
C
      NPRINT=0
C
C**** LOOK FOR 'METAL DENSITY-TEMPERATURE CURVE' CARD
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'DENSI') THEN
       IF(KDYNAT.EQ.1.OR.ICONVT.EQ.1) THEN
        CALL RUNENDT('PROP05T: DENSITY-TEMP. CARD NOT FOUND   ')
       ELSE
        NPOI1T=3                ! ISOTRT=PROPST(1),IFILL=PROPST(2)
        NPOI2T=7
        PROPST(3)=2.0D0
        DO IPROPT=NPOI1T+1,NPOI2T
         PROPST(IPROPT)=0.0D0
        ENDDO
        CALL RUNMENT('WARNING: ZERO DENSITY VALUE IS ASSUMED')
        IF(NMEMO10.EQ.1)
     .   CALL RUNMENT('WARNING: ZERO DENSITY WITH NMEMO10=1')
        GOTO 3
       ENDIF
      ELSE
       IF(WORDST(2).EQ.'METAL') THEN
        IF(PARAMT(1).EQ.0.0D0)
     .   CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN DENSITY')
C
C**** READ 'DENSITY-TEMPERATURE CURVE' BY LISTEN
C
        NPOI1T=3                ! ISOTRT=PROPST(1),IFILL=PROPST(2)
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)
        NLINET=INT(PARAMT(1))
        IF(NLINET.GT.20)
     .   CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN DENSITY')
        NPRINT=1
        DO LINEAT=1,NLINET
         CALL LISTENT('PROP05T',NPRINT,ITAPET)
         DO I=1,2
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=PARAMT(I)
         ENDDO
        ENDDO
        WRITE(LUREST,803)
        DO IPROPT=NPOI1T+1,NPOI2T,2
         WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
        ENDDO
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: METAL DENSITY CARD IS LACKING')
       ENDIF
      ENDIF
C
      DO IPROPT=NPOI1T+1,NPOI2T-2,2
       IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .  CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, DENSITY')
       IF(NMEMO10.EQ.0) THEN
        IF(PROPST(IPROPT).NE.PROPST(IPROPT+2))
     .   CALL RUNMENT('WARNING: INITIAL DENSITY WILL BE CONSIDERED')
       ENDIF
      ENDDO
C
C**** LOOK FOR 'AIR DENSITY-TEMPERATURE CURVE' CARD
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'DENSI') THEN
       IF(KDYNAT.EQ.1.OR.ICONVT.EQ.1) THEN
        CALL RUNENDT('PROP05T: DENSITY-TEMP. CARD NOT FOUND   ')
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI2T+5
        PROPST(NPOI1T)=2.0D0
        DO IPROPT=NPOI1T+1,NPOI2T
         PROPST(IPROPT)=0.0D0
        ENDDO
        CALL RUNMENT('WARNING: ZERO DENSITY VALUE IS ASSUMED')
        IF(NMEMO10.EQ.1)
     .   CALL RUNMENT('WARNING: ZERO DENSITY WITH NMEMO10=1')
        GOTO 3
       ENDIF
      ELSE
       IF(WORDST(2).EQ.'AIR') THEN
        IF(PARAMT(1).EQ.0.0D0)
     .   CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN DENSITY')
C
C**** READ 'DENSITY-TEMPERATURE CURVE' BY LISTEN
C
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI2T+1
        PROPST(NPOI1T)=PARAMT(1)
        NLINET=INT(PARAMT(1))
        IF(NLINET.GT.20)
     .   CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN DENSITY')
        NPRINT=1
        DO LINEAT=1,NLINET
         CALL LISTENT('PROP05T',NPRINT,ITAPET)
         DO I=1,2
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=PARAMT(I)
         ENDDO
        ENDDO
        WRITE(LUREST,903)
        DO IPROPT=NPOI1T+1,NPOI2T,2
         WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
        ENDDO
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: AIR DENSITY CARD IS LACKING')
       ENDIF
      ENDIF
C
      DO IPROPT=NPOI1T+1,NPOI2T-2,2
       IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .  CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, DENSITY')
       IF(NMEMO10.EQ.0) THEN
        IF(PROPST(IPROPT).NE.PROPST(IPROPT+2))
     .   CALL RUNMENT('WARNING: INITIAL DENSITY WILL BE CONSIDERED')
       ENDIF
      ENDDO
C
C**** LOOK FOR 'METAL SPECIFIC_HEAT-TEMPERATURE CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    3 IF(WORDST(1).NE.'SPECI') THEN
       IF(KDYNAT.EQ.1.OR.ICONVT.EQ.1) THEN
        CALL RUNENDT('ERROR: SPECIFIC_HEAT-TEMP. CARD NOT FOUND')
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=4+NPOI1T
        PROPST(NPOI1T)=2.0D0
        DO IPROPT=NPOI1T+1,NPOI2T
         PROPST(IPROPT)=0.0D0
        ENDDO
        GOTO 4
       ENDIF
      ELSE
       IF(WORDST(2).EQ.'METAL') THEN
        IF(KDYNAT.EQ.1.OR.ICONVT.EQ.1) THEN
         IF(PARAMT(1).EQ.0.0D0)
     .    CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN SPEC. HEAT')
        ELSE
         CALL RUNMENT('WARNING: SPEC. HEAT-TEMP. CURVE NOT USED')
        ENDIF
C
C**** READ FOR 'SPECIFIC_HEAT-TEMPERATURE CURVE' BY LISTEN
C
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)
        NLINET=INT(PARAMT(1))
        IF(NLINET.GT.500)
     .   CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN SPEC. HEAT')
        NPRINT=1
        DO LINEAT=1,NLINET
         CALL LISTENT('PROP05T',NPRINT,ITAPET)
         DO I=1,2
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=PARAMT(I)
         ENDDO
        ENDDO
        WRITE(LUREST,805)
        DO IPROPT=NPOI1T+1,NPOI2T,2
         WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
        ENDDO
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: METAL SPEC. HEAT CARD IS LACKING')
       ENDIF
      ENDIF
C
      DO IPROPT=NPOI1T+1,NPOI2T-2,2
       IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .  CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, SPEC. HEAT')
      ENDDO
C
C**** LOOK FOR 'AIR SPECIFIC_HEAT-TEMPERATURE CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'SPECI') THEN
       IF(KDYNAT.EQ.1.OR.ICONVT.EQ.1) THEN
        CALL RUNENDT('ERROR: SPECIFIC_HEAT-TEMP. CARD NOT FOUND')
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=4+NPOI1T
        PROPST(NPOI1T)=2.0D0
        DO IPROPT=NPOI1T+1,NPOI2T
         PROPST(IPROPT)=0.0D0
        ENDDO
        GOTO 4
       ENDIF
      ELSE
       IF(WORDST(2).EQ.'AIR') THEN
        IF(KDYNAT.EQ.1.OR.ICONVT.EQ.1) THEN
         IF(PARAMT(1).EQ.0.0D0)
     .    CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN SPEC. HEAT')
        ELSE
         CALL RUNMENT('WARNING: SPEC. HEAT-TEMP. CURVE NOT USED')
        ENDIF
C
C**** READ FOR 'SPECIFIC_HEAT-TEMPERATURE CURVE' BY LISTEN
C
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)
        NLINET=INT(PARAMT(1))
        IF(NLINET.GT.500)
     .   CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN SPEC. HEAT')
        NPRINT=1
        DO LINEAT=1,NLINET
         CALL LISTENT('PROP05T',NPRINT,ITAPET)
         DO I=1,2
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=PARAMT(I)
         ENDDO
        ENDDO
        WRITE(LUREST,905)
        DO IPROPT=NPOI1T+1,NPOI2T,2
         WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
        ENDDO
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: AIR SPEC. HEAT CARD IS LACKING')
       ENDIF
      ENDIF
C
      DO IPROPT=NPOI1T+1,NPOI2T-2,2
       IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .  CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, SPEC. HEAT')
      ENDDO
C
C**** LOOK FOR 'METAL CONDUCTIVITY-TEMPERATURE CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    4 IF(WORDST(1).NE.'CONDU')
     . CALL RUNENDT('ERROR: CONDUCTIVITY-TEMPERATURE CARD NOT FOUND')
C
      IF(WORDST(2).NE.'METAL')
     . CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
C

      DO IDIMET=1,NDIMET
       CALL LISTENT('PROP05FO',NPRINT,ITAPET)
       IF(WORDST(1).NE.'DIREC')
     .  CALL RUNENDT('ERROR: DIRECTION CARD NOT FOUND               ')
C
       IF(PARAMT(1).EQ.0.0D0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUCTIVITY')
C
C**** READ 'CONDUCTIVITY-TEMPERATURE CURVE' BY LISTEN
C
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.500)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUCTIVITY')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,806) IDIMET
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,809)
C
       DO IPROPT=NPOI1T+1,NPOI2T-2,2
        IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .   CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, CONDUC.')
       ENDDO
      ENDDO           ! idimet=1,ndimet
C
C**** LOOK FOR 'AIR CONDUCTIVITY-TEMPERATURE CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'CONDU')
     . CALL RUNENDT('ERROR: CONDUCTIVITY-TEMPERATURE CARD NOT FOUND')
C
      IF(WORDST(2).NE.'AIR')
     . CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
C
      DO IDIMET=1,NDIMET
       CALL LISTENT('PROP05TO',NPRINT,ITAPET)
       IF(WORDST(1).NE.'DIREC')
     .  CALL RUNENDT('ERROR: DIRECTION CARD NOT FOUND               ')
C
       IF(PARAMT(1).EQ.0.0D0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUCTIVITY')
C
C**** READ 'CONDUCTIVITY-TEMPERATURE CURVE' BY LISTEN
C
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.500)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUCTIVITY')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,906) IDIMET
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,809)
C
       DO IPROPT=NPOI1T+1,NPOI2T-2,2
        IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .   CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, CONDUC.')
       ENDDO
      ENDDO           ! idimet=1,ndimet
C
C**** LOOK FOR 'METAL PHASE_CHANGE_HEAT CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      NPOI2T=NPOI2T+1
      PROPST(NPOI2T)=0.0D0
      IF(WORDST(1).NE.'PHASE') GOTO 6      ! PHASE_CHANGE CARD NOT FOUND
      IF(KDYNAT.NE.1.AND.ICONVT.NE.1)
     . CALL RUNENDT('ERROR: PHASE-CHANGE ONLY IN TRANS. OR ADVEC. PROB')
C
      IF(WORDST(2).NE.'METAL')
     . CALL RUNENDT('ERROR: METAL CARD IS LACKING')
C
      IF(PARAMT(1).EQ.0.0D0)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
C
C**** READ 'PHASE_CHANGE_HEAT CURVE' BY LISTEN
C
      NPOI1T=NPOI2T
      PROPST(NPOI1T)=PARAMT(1)
      NLINET=INT(PARAMT(1))
      NSUBDT=INT(PARAMT(2))
      IF(NLINET.GT.MPLAT)          ! see auxl_om*.f & nued_om.f
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
      NLINEA=NFPCH/2
      IF(NLINET.GT.NLINEA)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
      IF(ITERME.GE.0) THEN
       CALL RUNMENT('WARNING: CHECK THE CORRESPONDANCE BETWEEN THERMAL &
     . MECHANICAL PHASE-CHANGES    ')
      ENDIF
C
      IF(IMICR.EQ.0) THEN          ! checks number of macroscopic ph-chs
       IF(NLINET.GT.NNUPC) NNUPC=NLINET
       IF(NNUPC.GT.NLINEA)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
       NNUPT=NNUPC
      ENDIF
C
      NPOI2T=NPOI2T+1              ! LINPC: linearized phase-change
      NPOI1T=NPOI2T
      PROPST(NPOI2T)=0.0D0
      IF(WORDST(3).EQ.'LINEA') PROPST(NPOI2T)=1.0D0
      LINPC=INT(PROPST(NPOI2T))
C
      IF(IMICR.EQ.1) THEN
       IF(IMICO.EQ.0) THEN
        IF(LINPC.EQ.1)
     .   CALL RUNENDT('ERROR: IMICO=0 & LINPC=1 ARE INCOMPATIBLE')
       ENDIF
      ENDIF
C
      NPRINT=1
      NPOI1T=NPOI1T+1
      DO LINEAT=1,NLINET
       WRITE(LUREST,810) LINEAT
       CALL LISTENT('PROP05T',NPRINT,ITAPET)
C
       IF(WORDST(1).EQ.'     ') THEN    ! linear
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(PARAMT(1).EQ.PARAMT(2)) THEN
         IF(LINPC.EQ.1)
     .    CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
         IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
          IF(ITERMEF.EQ.0) THEN
c          CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
           CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
          ELSE
c          CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
           CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
          ENDIF
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,811)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'LINEA') THEN    ! linear
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(PARAMT(1).EQ.PARAMT(2)) THEN
         IF(LINPC.EQ.1)
     .    CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
         IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
          IF(ITERMEF.EQ.0) THEN
c          CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
           CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
          ELSE
c          CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
           CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
          ENDIF
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,811)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'NO_RE') THEN    ! no real phase-change
        NNUPC=NNUPC-1
        NNUPT=NNUPT-1
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=-1.0D0           ! IPCMO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=10.0E+20
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=10.1E+20
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0
        WRITE(LUREST,870)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'ISOTH') THEN    ! linear (isoth-pc for residual)
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=-2.0D0           ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(LINPC.EQ.1)
     .   CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
        IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
         IF(ITERMEF.EQ.0) THEN
c         CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
          CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
         ELSE
c         CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
          CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,811)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'PIECE'.OR.WORDST(1).EQ.'FS_PI') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        IF(WORDST(1).EQ.'PIECE') THEN   ! piece wise linear
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=1.0D0           ! IPCMO
         IPCMO=1
        ENDIF
        IF(WORDST(1).EQ.'FS_PI') THEN   ! solid fract. piece wise linear
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=2.0D0           ! IPCMO
         IPCMO=2
        ENDIF
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=PARAMT(1)
        NPCFU=INT(PARAMT(1))
        IF(NPCFU.LE.1.OR.NPCFU.GT.500)
     .   CALL RUNENDT('PROP05T: ERROR WITH PIECE WISE LINEAR FUNCTION')
C
        IF(WORDST(2).EQ.'     '.OR.WORDST(2).EQ.'CONST') THEN
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=0.0D0       ! nlate
         DO IPCFU=1,NPCFU
          CALL LISTENT('PROP05T',NPRINT,ITAPET)
          DO I=1,2
           NPOI2T=NPOI2T+1
           PROPST(NPOI2T)=PARAMT(I)
          ENDDO
         ENDDO
         DO IPROPT=NPOI1T+4,NPOI2T-2,2  ! 4=IPCFO,IPCMO,NPCFU,NLATE
          IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .     CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, LINEAR')
         ENDDO
         IF(IPCMO.EQ.1) THEN            ! piece wise linear
          WRITE(LUREST,821)
          WRITE(LUREST,822)
         ENDIF
         IF(IPCMO.EQ.2) THEN            ! solid fract. piece wise linear
          WRITE(LUREST,824)
          WRITE(LUREST,825)
         ENDIF
         DO IPROPT=NPOI1T+4,NPOI2T,2
          WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
         ENDDO
C
         CALL LISTENT('PROP05T',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(1)            ! constant latent heat
         IF(PARAMT(1).LT.0.0D0)
     .    CALL RUNENDT('LATENT HEAT < 0.0         ')
         WRITE(LUREST,823) PROPST(NPOI2T)
         WRITE(LUREST,809)
        ELSE
         IF(WORDST(2).EQ.'VARIA') THEN       ! temp-dep latent heat
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=1.0D0        ! nlate
          IF(WORDST(3).EQ.'     '.OR.WORDST(3).EQ.'SECAN') THEN
           NPOI2T=NPOI2T+1
           PROPST(NPOI2T)=0.0D0       ! ntypc (0=secant L)
          ENDIF
          IF(WORDST(3).EQ.'TANGE') THEN
           NPOI2T=NPOI2T+1
           PROPST(NPOI2T)=1.0D0       ! ntypc (1=tangent L)
          ENDIF
          DO IPCFU=1,NPCFU
           CALL LISTENT('PROP05T',NPRINT,ITAPET)
           DO I=1,3
            NPOI2T=NPOI2T+1
            PROPST(NPOI2T)=PARAMT(I)
           ENDDO
          ENDDO
          DO IPROPT=NPOI1T+5,NPOI2T-3,3   ! 5=idem former,NTYPC
           IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+4))
     .      CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, LINEAR')
          ENDDO
          WRITE(LUREST,824)
          WRITE(LUREST,826)
          DO IPROPT=NPOI1T+5,NPOI2T,3
           WRITE(LUREST,807) PROPST(IPROPT),PROPST(IPROPT+1),
     .                       PROPST(IPROPT+2)
          ENDDO
          WRITE(LUREST,809)
         ELSE
          CALL RUNENDT('ERROR IN PHASE-CHANGE DATA')
         ENDIF
        ENDIF
       ENDIF
C
       IF(WORDST(1).EQ.'PARAB') THEN  ! parabolic
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=3.0D0            ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(PARAMT(1).EQ.PARAMT(2)) THEN
         IF(LINPC.EQ.1)
     .    CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
         IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
          IF(ITERMEF.EQ.0) THEN
c          CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
           CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
          ELSE
c          CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
           CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
          ENDIF
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,831)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'CUBIC') THEN  ! cubic
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=4.0D0            ! IPCMO
        call runendt('prop05t: cubic not implemented yet')
       ENDIF
C
       IF(WORDST(1).EQ.'SCHEI') THEN  ! Scheil's equation
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=5.0D0            ! IPCMO
        DO I=1,5
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS > T_EUTECTIC    ')
        IF(PARAMT(2).GT.PARAMT(3))
     .   CALL RUNENDT('T_EUTECTIC > T_LIQUIDUS   ')
        IF(PARAMT(3).GT.PARAMT(4))
     .   CALL RUNENDT('T_LIQUIDUS > T_MELTING    ')
        IF(PARAMT(5).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,861)
        WRITE(LUREST,863)
        WRITE(LUREST,813) PROPST(NPOI2T-4),PROPST(NPOI2T-3),
     .                    PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'LEVER') THEN  ! lever rule
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=6.0D0            ! IPCMO
        DO I=1,4
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS > T_LIQUIDUS    ')
        IF(PARAMT(2).GT.PARAMT(3))
     .   CALL RUNENDT('T_LIQUIDUS > T_MELTING    ')
        IF(PARAMT(4).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,861)
        WRITE(LUREST,862)
        WRITE(LUREST,813) PROPST(NPOI2T-3),PROPST(NPOI2T-2),
     .                    PROPST(NPOI2T-1),PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
      ENDDO                 ! do lineat=1,nlinet
C
C**** LOAD "NSUBDT"
C
      NPOI1T=NPOI2T
      IF(NSUBDT.EQ.0) NSUBDT=4
      DO IDIMET=1,NDIMET
       DO IAUXX=1,2
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=FLOAT(NSUBDT)
       ENDDO
      ENDDO
C
C**** POROSITY CRITERIA
C
C     Note: see assprot.f, inppros.f, propmic.f, idepros.f & ideprom.f
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      NPOI1T=NPOI2T
      IF(WORDST(1).EQ.'POROS') THEN
       IF(WORDST(2).EQ.'PHASE') THEN
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=PARAMT(1)                  ! KPOROT
        IF(IMICR.EQ.1) PROPST(NPROPM+1)=PARAMT(1) ! KPOROT
       ELSE
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0                      ! KPOROT
        IF(IMICR.EQ.1) PROPST(NPROPM+1)=0.0D0     ! KPOROT
        CALL RUNMENT('WARNING: POROSITY CRITERIA NOT CONSIDERED')
       ENDIF
      ELSE
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0D0                       ! KPOROT
       IF(IMICR.EQ.1) PROPST(NPROPM+1)=0.0D0      ! KPOROT
       GOTO 6
      ENDIF
C
C**** LOOK FOR 'AIR PHASE_CHANGE_HEAT CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    6 NPOI2T=NPOI2T+1
      PROPST(NPOI2T)=0.0D0
      IF(WORDST(1).NE.'PHASE') GOTO 5      ! PHASE_CHANGE CARD NOT FOUND
      IF(KDYNAT.NE.1.AND.ICONVT.NE.1)
     . CALL RUNENDT('ERROR: PHASE-CHANGE ONLY IN TRANS. OR ADVEC. PROB')
C
      IF(WORDST(2).NE.'AIR')
     . CALL RUNENDT('ERROR: METAL CARD IS LACKING')
C
      IF(PARAMT(1).EQ.0.0D0)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
C
C**** READ 'PHASE_CHANGE_HEAT CURVE' BY LISTEN
C
      NPOI1T=NPOI2T
      PROPST(NPOI1T)=PARAMT(1)
      NLINET=INT(PARAMT(1))
      NSUBDT=INT(PARAMT(2))
      IF(NLINET.GT.MPLAT)          ! see auxl_om*.f & nued_om.f
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
      NLINEA=NFPCH/2
      IF(NLINET.GT.NLINEA)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
      IF(ITERME.GE.0) THEN
       CALL RUNMENT('WARNING: CHECK THE CORRESPONDANCE BETWEEN THERMAL &
     . MECHANICAL PHASE-CHANGES    ')
      ENDIF
C
      IF(NLINET.GT.0.AND.IMICR.EQ.1)
     . CALL RUNMENT('WARNING: NPLATFI > 0 & IMICR=1 COULD NOT BE
     . COMPATIBLE')
      IF(NLINET.GT.0.AND.ITERME.GE.0)
     . CALL RUNMENT('WARNING: NPLATFI > 0 & ITERME GE 0 COULD NOT BE
     . COMPATIBLE')
C
      IF(IMICR.EQ.0) THEN          ! checks number of macroscopic ph-chs
       IF(NLINET.GT.NNUPC) NNUPC=NLINET
       IF(NNUPC.GT.NLINEA)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF PHASE_CHANGES')
       NNUPT=NNUPC
      ENDIF
C
      NPOI2T=NPOI2T+1              ! LINPCFI: linearized phase-change
      NPOI1T=NPOI2T
      PROPST(NPOI2T)=0.0D0
      IF(WORDST(3).EQ.'LINEA') PROPST(NPOI2T)=1.0D0
      LINPCFI=INT(PROPST(NPOI2T))
C
      IF(IMICR.EQ.1) THEN
       IF(IMICO.EQ.0) THEN
        IF(LINPCFI.EQ.1)
     .   CALL RUNENDT('ERROR: IMICO=0 & LINPCFI=1 ARE INCOMPATIBLE')
       ENDIF
      ENDIF
C
      NPRINT=1
      NPOI1T=NPOI1T+1
      DO LINEAT=1,NLINET
       WRITE(LUREST,910) LINEAT
       CALL LISTENT('PROP05T',NPRINT,ITAPET)
C
       IF(WORDST(1).EQ.'     ') THEN    ! linear
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(PARAMT(1).EQ.PARAMT(2)) THEN
         IF(LINPCFI.EQ.1)
     .    CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
         IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
          IF(ITERMEF.EQ.0) THEN
c          CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
           CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
          ELSE
c          CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
           CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
          ENDIF
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,811)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'LINEA') THEN    ! linear
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(PARAMT(1).EQ.PARAMT(2)) THEN
         IF(LINPCFI.EQ.1)
     .    CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
         IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
          IF(ITERMEF.EQ.0) THEN
c          CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
           CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
          ELSE
c          CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
           CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
          ENDIF
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,811)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'NO_RE') THEN    ! no real phase-change
        NNUPC=NNUPC-1
        NNUPT=NNUPT-1
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=-1.0D0           ! IPCMO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=10.0E+20
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=10.1E+20
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0
        WRITE(LUREST,870)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'ISOTH') THEN    ! linear (isoth-pc for residual)
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=-2.0D0           ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(LINPCFI.EQ.1)
     .   CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
        IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
         IF(ITERMEF.EQ.0) THEN
c         CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
          CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
         ELSE
c         CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
          CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,811)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'PIECE'.OR.WORDST(1).EQ.'FS_PI') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        IF(WORDST(1).EQ.'PIECE') THEN   ! piece wise linear
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=1.0D0           ! IPCMO
         IPCMO=1
        ENDIF
        IF(WORDST(1).EQ.'FS_PI') THEN   ! solid fract. piece wise linear
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=2.0D0           ! IPCMO
         IPCMO=2
        ENDIF
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=PARAMT(1)
        NPCFU=INT(PARAMT(1))
        IF(NPCFU.LE.1.OR.NPCFU.GT.500)
     .   CALL RUNENDT('PROP05T: ERROR WITH PIECE WISE LINEAR FUNCTION')
C
        IF(WORDST(2).EQ.'     '.OR.WORDST(2).EQ.'CONST') THEN
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=0.0D0       ! nlate
         DO IPCFU=1,NPCFU
          CALL LISTENT('PROP05T',NPRINT,ITAPET)
          DO I=1,2
           NPOI2T=NPOI2T+1
           PROPST(NPOI2T)=PARAMT(I)
          ENDDO
         ENDDO
         DO IPROPT=NPOI1T+4,NPOI2T-2,2  ! 4=IPCFO,IPCMO,NPCFU,NLATE
          IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+3))
     .     CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, LINEAR')
         ENDDO
         IF(IPCMO.EQ.1) THEN            ! piece wise linear
          WRITE(LUREST,821)
          WRITE(LUREST,822)
         ENDIF
         IF(IPCMO.EQ.2) THEN            ! solid fract. piece wise linear
          WRITE(LUREST,824)
          WRITE(LUREST,825)
         ENDIF
         DO IPROPT=NPOI1T+4,NPOI2T,2
          WRITE(LUREST,804) PROPST(IPROPT),PROPST(IPROPT+1)
         ENDDO
C
         CALL LISTENT('PROP05T',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(1)            ! constant latent heat
         IF(PARAMT(1).LT.0.0D0)
     .    CALL RUNENDT('LATENT HEAT < 0.0         ')
         WRITE(LUREST,823) PROPST(NPOI2T)
         WRITE(LUREST,809)
        ELSE
         IF(WORDST(2).EQ.'VARIA') THEN       ! temp-dep latent heat
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=1.0D0        ! nlate
          IF(WORDST(3).EQ.'     '.OR.WORDST(3).EQ.'SECAN') THEN
           NPOI2T=NPOI2T+1
           PROPST(NPOI2T)=0.0D0       ! ntypc (0=secant L)
          ENDIF
          IF(WORDST(3).EQ.'TANGE') THEN
           NPOI2T=NPOI2T+1
           PROPST(NPOI2T)=1.0D0       ! ntypc (1=tangent L)
          ENDIF
          DO IPCFU=1,NPCFU
           CALL LISTENT('PROP05T',NPRINT,ITAPET)
           DO I=1,3
            NPOI2T=NPOI2T+1
            PROPST(NPOI2T)=PARAMT(I)
           ENDDO
          ENDDO
          DO IPROPT=NPOI1T+5,NPOI2T-3,3   ! 5=idem former,NTYPC
           IF(PROPST(IPROPT+1).GT.PROPST(IPROPT+4))
     .      CALL RUNENDT('PROP05T: TAKE CARE TEMPERATURE ORDER, LINEAR')
          ENDDO
          WRITE(LUREST,824)
          WRITE(LUREST,826)
          DO IPROPT=NPOI1T+5,NPOI2T,3
           WRITE(LUREST,807) PROPST(IPROPT),PROPST(IPROPT+1),
     .                       PROPST(IPROPT+2)
          ENDDO
          WRITE(LUREST,809)
         ELSE
          CALL RUNENDT('ERROR IN PHASE-CHANGE DATA')
         ENDIF
        ENDIF
       ENDIF
C
       IF(WORDST(1).EQ.'PARAB') THEN  ! parabolic
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=3.0D0            ! IPCMO
        DO I=1,3
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS < T_LIQUIDUS    ')
        IF(PARAMT(1).EQ.PARAMT(2)) THEN
         IF(LINPCFI.EQ.1)
     .    CALL RUNENDT('ERROR: LINEARIZED ISOT-PC NOT IMPLEMENTED')
         IF(ICONVT.EQ.1) THEN                            ! see elm005t.f
          IF(ITERMEF.EQ.0) THEN
c          CALL RUNMENT('ERROR: AD-PC TERM TREATED AS NON-ISOTHERMAL')
           CALL RUNENDT('ERROR: AD-ISOT-PC NOT IMPLEMENTED')
          ELSE
c          CALL RUNMENT('WARNING: AD-PC/ISOLIF=1 TERM TREATED AS NI-PC')
           CALL RUNMENT('WARNING: AD-ISOT-PC IS ONLY AVA. FOR ISOLIF=0')
          ENDIF
         ENDIF
        ENDIF
        IF(PARAMT(3).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,831)
        WRITE(LUREST,812)
        WRITE(LUREST,813) PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'CUBIC') THEN  ! cubic
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=4.0D0            ! IPCMO
        call runendt('prop05t: cubic not implemented yet')
       ENDIF
C
       IF(WORDST(1).EQ.'SCHEI') THEN  ! Scheil's equation
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=5.0D0            ! IPCMO
        DO I=1,5
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS > T_EUTECTIC    ')
        IF(PARAMT(2).GT.PARAMT(3))
     .   CALL RUNENDT('T_EUTECTIC > T_LIQUIDUS   ')
        IF(PARAMT(3).GT.PARAMT(4))
     .   CALL RUNENDT('T_LIQUIDUS > T_MELTING    ')
        IF(PARAMT(5).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,861)
        WRITE(LUREST,863)
        WRITE(LUREST,813) PROPST(NPOI2T-4),PROPST(NPOI2T-3),
     .                    PROPST(NPOI2T-2),PROPST(NPOI2T-1),
     .                    PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
       IF(WORDST(1).EQ.'LEVER') THEN  ! lever rule
        CALL LISTENT('PROP05T',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0            ! IPCFO
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=6.0D0            ! IPCMO
        DO I=1,4
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
        IF(PARAMT(1).GT.PARAMT(2))
     .   CALL RUNENDT('T_SOLIDUS > T_LIQUIDUS    ')
        IF(PARAMT(2).GT.PARAMT(3))
     .   CALL RUNENDT('T_LIQUIDUS > T_MELTING    ')
        IF(PARAMT(4).LT.0.0D0)
     .   CALL RUNENDT('LATENT HEAT < 0.0         ')
        WRITE(LUREST,861)
        WRITE(LUREST,862)
        WRITE(LUREST,813) PROPST(NPOI2T-3),PROPST(NPOI2T-2),
     .                    PROPST(NPOI2T-1),PROPST(NPOI2T)
        WRITE(LUREST,809)
       ENDIF
C
      ENDDO                 ! do lineat=1,nlinet
C
C**** LOAD "NSUBDT"
C
      NPOI1T=NPOI2T
      IF(NSUBDT.EQ.0) NSUBDT=4
      DO IDIMET=1,NDIMET
       DO IAUXX=1,2
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=FLOAT(NSUBDT)
       ENDDO
      ENDDO
C
C**** POROSITY CRITERIA
C
C     Note: see assprot.f, inppros.f, propmic.f, idepros.f & ideprom.f
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
      NPOI1T=NPOI2T
      IF(WORDST(1).EQ.'POROS') THEN
       IF(WORDST(2).EQ.'PHASE') THEN
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=PARAMT(1)                  ! KPOROT
        IF(IMICR.EQ.1) PROPST(NPROPM+1)=PARAMT(1) ! KPOROT
       ELSE
        NPOI2T=NPOI2T+1
        PROPST(NPOI2T)=0.0D0                      ! KPOROT
        IF(IMICR.EQ.1) PROPST(NPROPM+1)=0.0D0     ! KPOROT
        CALL RUNMENT('WARNING: POROSITY CRITERIA NOT CONSIDERED')
       ENDIF
      ELSE
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0D0                       ! KPOROT
       IF(IMICR.EQ.1) PROPST(NPROPM+1)=0.0D0      ! KPOROT
       GOTO 5
      ENDIF
C
C**** LOOK FOR METAL FREE ENERGY MODEL
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    5 IF(WORDST(1).EQ.'FREE_') THEN
       IF(WORDST(2).EQ.'METAL') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)       ! ifrent
        IFRENT=INT(PROPST(NPOI1T))
        IF(LARGET.EQ.0) THEN
         IF(IFRENT.LE.0.OR.IFRENT.GT.3)
     .    CALL RUNENDT('ERROR: WRONG FREE ENERGY MODEL')
        ELSE
         IF(IFRENT.LE.0.OR.IFRENT.GT.8)
     .    CALL RUNENDT('ERROR: WRONG FREE ENERGY MODEL')
        ENDIF
        WRITE(LUREST,875) IFRENT
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: WORD METAL IS LACKING')
       ENDIF
      ELSE                            ! defaults
       IF(LARGET.EQ.0) THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrent
        IFRENT=1
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrent
        IFRENT=1
       ENDIF
       WRITE(LUREST,875) IFRENT
       WRITE(LUREST,809)
       GO TO 7
      ENDIF
C
C**** LOOK FOR AIR FREE ENERGY MODEL
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    7 IF(WORDST(1).EQ.'FREE_') THEN
       IF(WORDST(2).EQ.'AIR') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)       ! ifrenfi
        IFRENFI=INT(PROPST(NPOI1T))
        IF(LARGET.EQ.0) THEN
         IF(IFRENFI.LE.0.OR.IFRENFI.GT.3)
     .    CALL RUNENDT('ERROR: WRONG FREE ENERGY MODEL')
        ELSE
         IF(IFRENFI.LE.0.OR.IFRENFI.GT.8)
     .    CALL RUNENDT('ERROR: WRONG FREE ENERGY MODEL')
        ENDIF
        WRITE(LUREST,876) IFRENFI
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: WORD AIR IS LACKING')
       ENDIF
      ELSE                            ! defaults
       IF(LARGET.EQ.0) THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrenfi
        IFRENFI=1
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrenfi
        IFRENFI=1
       ENDIF
       WRITE(LUREST,876) IFRENFI
       WRITE(LUREST,809)
       GO TO 8
      ENDIF
C
C**** LOOK FOR METAL HEAT FLUX MODEL
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    8 IF(WORDST(1).EQ.'HEAT_') THEN
       IF(WORDST(2).EQ.'METAL') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)       ! ifrekt
        IFREKT=INT(PROPST(NPOI1T))
        IF(LARGET.EQ.0) THEN
         IF(IFREKT.LE.0.OR.IFREKT.GT.1)
     .    CALL RUNENDT('ERROR: WRONG HEAT FLUX MODEL')
        ELSE
         IF(IFREKT.LE.0.OR.IFREKT.GT.2)
     .    CALL RUNENDT('ERROR: WRONG HEAT FLUX MODEL')
        ENDIF
        WRITE(LUREST,877) IFREKT
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: WORD METAL IS LACKING')
       ENDIF
      ELSE                            ! defaults
       IF(LARGET.EQ.0) THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrekt
        IFREKT=1
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrekt
        IFREKT=1
       ENDIF
       WRITE(LUREST,877) IFREKT
       WRITE(LUREST,809)
       GO TO 9
      ENDIF
C
C**** LOOK FOR AIR HEAT FLUX MODEL
C
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
    9 IF(WORDST(1).EQ.'HEAT_') THEN
       IF(WORDST(2).EQ.'AIR') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)       ! ifrekfi
        IFREKFI=INT(PROPST(NPOI1T))
        IF(LARGET.EQ.0) THEN
         IF(IFREKFI.LE.0.OR.IFREKFI.GT.1)
     .    CALL RUNENDT('ERROR: WRONG HEAT FLUX MODEL')
        ELSE
         IF(IFREKFI.LE.0.OR.IFREKFI.GT.2)
     .    CALL RUNENDT('ERROR: WRONG HEAT FLUX MODEL')
        ENDIF
        WRITE(LUREST,878) IFREKFI
        WRITE(LUREST,809)
       ELSE
        CALL RUNENDT('ERROR: WORD AIR IS LACKING')
       ENDIF
      ELSE                            ! defaults
       IF(LARGET.EQ.0) THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrekfi
        IFREKFI=1
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0          ! ifrekfi
        IFREKFI=1
       ENDIF
       WRITE(LUREST,878) IFREKFI
       WRITE(LUREST,809)
       GO TO 10
      ENDIF
C
C**** LOOK FOR 'END_MATERIAL' CARD
C
      NPRINT=0
      CALL LISTENT('PROP05T',NPRINT,ITAPET)
   10 IF(WORDST(1).NE.'END_M')
     . CALL RUNENDT('PROP05T: END_MATERIAL CARD NOT FOUND   ')
      WRITE(LUREST,809)
C
C**** GLOBAL CONTROL OF NFPCH (NNUPT: the greatest of air & metal)
C
      NLINEA=NFPCH
      NLINET=2*NNUPT+IFILL+IGALFA           ! micro checked in pointes.f
      IF(NLINET.GT.NLINEA)
     . CALL RUNENDT('PROP05F: WRONG NUMBER OF PHASE_CHANGES')
C
C**** CONTROLS DIMENSION OF PROPST
C
      IF(NPOI2T.GT.NPROPT) THEN
       WRITE(LUREST,900) NPROPT,NPOI2T
       CALL RUNENDT('PROP05T: TOO MANY PROPERTIES TO READ')
      ENDIF
C
      RETURN
  803 FORMAT(/,'   METAL DENSITY    Vs.     TEMPERATURE',/)
  903 FORMAT(/,'   AIR DENSITY      Vs.     TEMPERATURE',/)
  804 FORMAT(E15.6,10X,E15.6)
  805 FORMAT(/,'METAL SPECIFIC HEAT Vs.     TEMPERATURE',/)
  905 FORMAT(/,'AIR SPECIFIC HEAT   Vs.     TEMPERATURE',/)
  806 FORMAT(/,'METAL CONDUCTIVITY  Vs.     TEMPERATURE',
     .         '   DIRECTION=',I5,/)
  906 FORMAT(/,'AIR CONDUCTIVITY    Vs.     TEMPERATURE',
     .         '   DIRECTION=',I5,/)
  807 FORMAT(E15.6,10X,E15.6,10X,E15.6)
  809 FORMAT(/)
  810 FORMAT(/,3X,'METAL PHASE-CHANGE NUMBER  =',I5,/)
  910 FORMAT(/,3X,'AIR PHASE-CHANGE NUMBER  =',I5,/)
  811 FORMAT(/,3X,'LINEAR PHASE-CHANGE',/)
  812 FORMAT(/,3X,'SOLIDUS TEMP.',11X,'LIQUIDUS TEMP.',12X,
     .            'LATENT HEAT',/)
  813 FORMAT(E15.6,10X,E15.6,10X,E15.6,10X,E15.6,10X,E15.6)
  821 FORMAT(/,3X,'PIECE WISE LINEAR PHASE-CHANGE',/)
  822 FORMAT(/,'PHASE-CHANGE FUNC.  Vs.     TEMPERATURE',/)
  823 FORMAT(/,3X,'CONSTANT LATENT HEAT =',E15.6)
  824 FORMAT(/,3X,'PIECE WISE LINEAR SOLID FRACTION',/)
  825 FORMAT(/,'SOLID FRACTION      Vs.     TEMPERATURE',/)
  826 FORMAT(/,'SOLID FRACTION      Vs.     TEMPERATURE',
     .         '               LATENT HEAT',/)
  831 FORMAT(/,3X,'PARABOLIC PHASE-CHANGE',/)
  861 FORMAT(/,3X,'LEVER RULE',/)
  862 FORMAT(/,3X,'SOLIDUS TEMP.',11X,'LIQUIDUS TEMP.',11X,
     .            'MELTING TEMP.',12X,'LATENT HEAT',/)
  863 FORMAT(/,3X,'SOLIDUS TEMP. ',11X,'EUTECTIC TEMP.',11X,
     .            'LIQUIDUS TEMP.',11X,'MELTING TEMP. ',12X,
     .            'LATENT HEAT   ',/)
  870 FORMAT(/,3X,'NO REAL PHASE-CHANGE',/)
  875 FORMAT(/,3X,'METAL FREE ENERGY MODEL=',I5,/)
  876 FORMAT(/,3X,'AIR FREE ENERGY MODEL=',I5,/)
  877 FORMAT(/,3X,'METAL HEAT FLUX MODEL=',I5,/)
  878 FORMAT(/,3X,'AIR HEAT FLUX MODEL=',I5,/)
  900 FORMAT(//,'TOO MANY MATERIAL PROPERTIES TO READ:',/,
     .      20X,'NPROP =',I5,5X,'NUMBE =',I5,/)
      END
