      SUBROUTINE CALTHE(BARMN,BARQU,BARTH,DESMN,DESJ2,DESJ3,PREMN,
     .                  PREJ2,PREJ3,REDUC,WCOJ3,YCOJ3,ZCOJ2)
C***********************************************************************
C
C****THIS ROUTINE CALCULATES THE STRESS INVARIANT RELATED TO THE
C    REDUCED STRESS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DATA ROOT3/1.732050807568877/
C
      REDU2=REDUC*REDUC
      BARMN=PREMN+REDUC*DESMN
      BARJ2=(PREJ2+2.0*REDUC*ZCOJ2+REDU2*DESJ2)
      BARSF=DSQRT(BARJ2)
      BARQU=ROOT3*BARSF
      BARJ3=PREJ3+REDUC*YCOJ3+REDU2*WCOJ3+REDU2*REDUC*DESJ3
C
C***CALCULATES THETA AND RATIO
C
      SINT3=1.0
      DENOM=BARJ2*BARSF
      IF(DENOM.NE.0.0)SINT3=-3.0*ROOT3*BARJ3/(2.0*DENOM)
      IF(SINT3.LT.-0.9986295348) SINT3=-1.0
      IF(SINT3.GT. 0.9986295348) SINT3= 1.0
      BARTH=DASIN(SINT3)/3.0
C
      RETURN
      END
