      SUBROUTINE PREVOS(DISTO,ELDAT,ELPRE,ELVAR,ELMAT,HEADS,LNODS,
     .                  MATNO,PROEL,PROPS,SINI2,SINI3,WORK1)
C***********************************************************************
C
C**** THIS ROUTINE READS THE INITIAL STATE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_om.f'
C
C**** MECHANICAL VARIABLES
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
      INCLUDE 'inpo_om.f'
C
      COMMON/PRFILE/JTAPE,IFLAG
C
      DIMENSION MATNO(NELEM),       LNODS(NNODE,NELEM),
     .          PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS),
     .          ELDAT(NDATA),       ELPRE(NPREV),
     .          ELVAR(NSTAT),       ELMAT(NMATX)
      DIMENSION DISTO(NTOTV,*),     HEADS(NPOIN,*)
      DIMENSION SINI2(*),           SINI3(*)
      DIMENSION WORK1(*)
C
      PARAMETER   (MCOMM=9)
      CHARACTER*5 COMMD(MCOMM)
C
      SAVE IFLA1,IFLA2,ISTOP
      DATA IFLA1,IFLA2,ISTOP/0,0,0/
C
      DATA COMMD/'GAUSS','WATER','TEMPE','DISPL','VELOC','ACCEL',
     .           'STRES','INTER','END_I'/
C
      CALL CPUTIM(TIME1)
      WRITE(LURES,900)
C
C**** READ INITIAL_DATA CARD
C
      NPRIN=0
      ITAPE=LUDAT
      CALL LISTEN('PREVOS',NPRIN,ITAPE)
      IF(WORDS(1).NE.'INITI') GO TO 1000
C
C**** READ NEW COMMAND
C
  100 CALL LISTEN('PREVOS',NPRIN,ITAPE)
C
C**** IDENTIFY COMMAND
C
      DO ICOMM=1,MCOMM
       IF(WORDS(1).EQ.COMMD(ICOMM)) GO TO 20
      END DO
      GO TO 1000 
C
C**** EXECUTE APPROPRIATE COMMAND
C
   20 JTAPE=LUDAT
      IF(PARAM(1).NE.0.0) JTAPE=INT(PARAM(1))
      GO TO (1,2,3,4,4,4,4,4,5), ICOMM
C
C**** READ THE INITIAL STATE VARIABLES AT THE GAUSSIAN POINTS
C
    1 IFLAG=0
      IF(NMEMOM.EQ.0)
     . CALL RUNEND('ERROR (PREVOS): MEMORY IS NOT DIMENSIONED FOR 
     .              INITIAL GAUSSIAN VARIABLES')
      IF(WORDS(2).EQ.'STRAI') IFLAG=1
      IF(WORDS(2).EQ.'STRES') IFLAG=2
      IF(WORDS(2).EQ.'PLAST') IFLAG=3
      IF(IFLAG.NE.0)
     .  CALL PREGAU(ELDAT,ELPRE,ELVAR,ELMAT,LNODS,MATNO,PROEL,
     .              PROPS)
      GO TO 100
C
C**** READ THE INITIAL PORE PRESSURE AT NODES
C
    2 CONTINUE
      IF(NMEMOM.EQ.0)
     . CALL RUNEND('ERROR (PREVOS): MEMORY IS NOT DIMENSIONED FOR 
     .              WATER VARIABLES')
      CALL PREPWP(DISTO,HEADS)
      IF(KPORE.NE.2) KPORE=1
      GO TO 100
C
C**** READ THE TEMPERATURE DATA AT NODES
C
    3 CONTINUE
      IF(NMEMOM.EQ.0)
     . CALL RUNEND('ERROR (PREVOS): MEMORY IS NOT DIMENSIONED FOR 
     .              INITIAL TEMPERATURES')
      CALL PRETEM(ELPRE,LNODS,MATNO,PROEL,WORK1)
      KTEMP=1
      GO TO 100
C
C**** READ THE INITIAL DISPLACEMENT, VELOCITY OR ACCELERATION AT NODES
C
    4 NCOMP=0
      IF(WORDS(1).EQ.'DISPL') NCOMP=1
      IF(WORDS(1).EQ.'VELOC') NCOMP=2
      IF(WORDS(1).EQ.'ACCEL') NCOMP=3
      NSINI=0
      IF(WORDS(1).EQ.'STRES') NSINI=1
      IF(WORDS(1).EQ.'INTER') NSINI=2
      CALL PREDIS(DISTO(1,NCOMP),NCOMP,
     .            SINI2,SINI3,NSINI)
      GO TO 100
C
C**** RETURN
C
    5 CALL CPUTIM(TIME2)
      CPUDA=CPUDA+(TIME2-TIME1)
      RETURN
C
 1000 CALL RUNEND('PREVOS: ERROR IN INITIAL DATA BLOCK')
  900 FORMAT(1H1,///,10X,'ECHO OF INITIAL STATE DATA FOLLOWS :',/
     .               10X,'=================================='/)
      END
