      SUBROUTINE LDGR01(DVOLU,PROPS,SHAPE,WORK1)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE EQUIVALENT NODAL FORCES DUE TO 
C     THE WEIGHT ( ELEMENT NO. 1 )
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      DIMENSION DVOLU(*), PROPS(*), SHAPE(NNODL,*), WORK1(*)
      DIMENSION PVECT(3)
C
      DENSE=PROPS(12)
C
      IF(DENSE.EQ.0.) RETURN
C
      DO 110 IDIME=1,NDIME
  110 PVECT(IDIME)=DENSE*GRAVY*GVECT(IDIME)
C
C***ENTER LOOPS FOR AREA NUMERICAL INTEGRATION
C
      DO 100 IGAUS=1,NGAUL
C
C***CALCULATE LOADS AND ASSOCIATE WITH ELEMENT NODAL POINTS
C
      IEVAB=0
      DO 130 INODE=1,NNODL
      SHAVO=SHAPE(INODE,IGAUS)*DVOLU(IGAUS)
C
      DO 130 IDIME=1,NDIME
      IEVAB=IEVAB+1
      WORK1(IEVAB)=WORK1(IEVAB)+PVECT(IDIME)*SHAVO
  130 CONTINUE
C
  100 CONTINUE
C
      RETURN
      END
