      SUBROUTINE PREGAUT(ELDATT,ELPRET,ELVART,ELMATT,LNODST,MATNOT,
     .                   PROELT,PROPST)
C***********************************************************************
C
C**** THIS ROUTINE READS THE INITIAL STATE VARIABLES 
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
      COMMON/PRFILET/JTAPET,IFLAGT
C
      DIMENSION MATNOT(NELEMT),        LNODST(NNODET,NELEMT),
     .          PROELT(NPRELT,NGRUPT), PROPST(NPROPT,NMATST),
     .          ELDATT(NDATAT),        ELPRET(NPREVT),
     .          ELVART(NSTATT),        ELMATT(NMATXT)
      DIMENSION SUBTAT(12)
C
      READ(JTAPET,905) SUBTAT
      WRITE(LUREST,906)   SUBTAT
C
      WRITE(LUREST,915)
C
C**** LOOP ON ELEMENTS
C
      DO 1000 IELEMT=1,NELEMT
        LGRUPT=MATNOT(IELEMT)
        LMATST=INT(PROELT(1,LGRUPT))
C
C**** READ ELPRE, ELVAR FROM RESTART-FILE
C 
        IF(IFLAGT.EQ.1) THEN
         IF(NMEMO.EQ.1) 
     .    CALL DATBAST(ELPRET,    2,    2)
        ELSE IF(IFLAGT.EQ.2) THEN
         IF(NMEMO.EQ.1)
     .    CALL DATBAST(ELPRET,    2,    2)
         IF(NMEMO3.EQ.1.OR.NMEMO4.EQ.1)
     .    CALL DATBAST(ELVART,    3,    2)
        ELSE IF(IFLAGT.EQ.3) THEN
         IF(NMEMO3.EQ.1.OR.NMEMO4.EQ.1)
     .    CALL DATBAST(ELVART,    3,    2)
        ENDIF
C
C**** CALL ELEMENT PROCESSOR TO PERFORM REQUIRED OPERATIONS
C
        CALL ELMLIBT(LNODST(1,IELEMT),PROELT(1,LGRUPT),PROPST(1,LMATST),
     .               ELDATT,ELPRET,ELVART,ELMATT,DUMMYT,WORK1T,    11)
C
C**** WRITE ELPRE,ELVAR TO RESTART-FILE
C 
        IF(IFLAGT.EQ.1) THEN
         IF(NMEMO.EQ.1)
     .    CALL DATBAST(ELPRET,    2,    1)
        ELSE IF(IFLAGT.EQ.2) THEN
         IF(NMEMO.EQ.1)
     .    CALL DATBAST(ELPRET,    2,    1)
         IF(NMEMO3.EQ.1.OR.NMEMO4.EQ.1)
     .    CALL DATBAST(ELVART,    3,    1)
        ELSE IF(IFLAGT.EQ.3) THEN
         IF(NMEMO3.EQ.1.OR.NMEMO4.EQ.1)
     .    CALL DATBAST(ELVART,    3,    1)
        ENDIF
C
 1000 CONTINUE
C
      RETURN
  905 FORMAT(12A6)
  906 FORMAT(5X,12A6)
  915 FORMAT(//,10X,'INITIAL STATE VARIABLES AT GAUSS POINTS',/)
      END
