      SUBROUTINE KMATRIC(BMATX,CARTD,DMATX,DVOLU,ESTIF,GPCOD,LARGE,
     .                   KSYMM,NDIME,NDOFN,NEVAB,NKOVA,NNODE,NSTRE,
     .                   NSTRS,NTYPE,SHAPE)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE MATERIAL CONVECTIVE MATRIX
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION BMATX(NSTRE,*), CARTD(NDIME,*), DMATX(NSTRS,*),
     .          ESTIF(*),       SHAPE(*)
      DIMENSION EMATX(20,20)
C
C                    T
C**** PERFORMS THE N  D  B PRODUCT (N=SHAPE, B=CARTD)
C
      IF(LARGE.EQ.0.OR.LARGE.EQ.3) THEN
       CALL BDBSEMC(CARTD,DMATX,EMATX,GPCOD,KSYMM,NDIME,NDOFN,
     .              NEVAB,NNODE,NSTRS,NTYPE,SHAPE)
      ELSE
c      CALL RUNENDT('ERROR IN KMATRIC: LARGE=1,2 NOT IMPLEMENTED')
c      CALL BDBCO1T(BMATX,DMATX,EMATX,KSYMM,NEVAB,NSTRE,NSTRS)
      ENDIF
C
C**** ADD THE CONTRIBUTION TO THE CONDUCTIVITY MATRIX
C
      CALL SQTOTA(ESTIF,EMATX,DVOLU,NEVAB,KSYMM)
C
      RETURN
      END
