      SUBROUTINE PRO104T(ITAPET,PROPST)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MATERIAL PROPERTIES FOR THE GAP INTERFACE
C     MODEL (ELEMENT=104)
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLE
C
      INCLUDE 'nuec_om.f'      ! thermal-mechanical
C
C**** THERMAL VARIABLE
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION PROPST(*)
C
C**** ESTABLISH SOME PARAMETERS
C
      PROPST(1)=0.0             ! ifill=0 => standard material
C
C**** READ & WRITE MATERIAL PROPERTIES
C
      NPRINT=0
C
C**** LOOK FOR 'CONDUCTANCE COEFFICIENT CURVE' CARD
C
      ICONT=0
      CALL LISTENT('PRO104T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'CONDU')
     . CALL RUNENDT('ERROR: CONDUCTANCE COEFF.-TEMP. CARD NOT FOUND')
C
C**** LOOK FOR 'CONDUCTANCE-TEMP1 CURVE' CARD
C
      CALL LISTENT('PRO104T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'TEMP1')THEN
       NPOI1T=2                 ! IFILL=PROPST(1)
       NPOI2T=6
       PROPST(2)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 1
      ELSE
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'CONDUCTANCE-TEMPERATURE 1 CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=2                 ! IFILL=PROPST(1)
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,802)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,803) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,804)
      ENDIF
C
C**** LOOK FOR 'CONDUCTANCE-TEMP2 CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104T',NPRINT,ITAPET)
    1 IF(WORDST(1).NE.'TEMP2')THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 2
      ELSE
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'CONDUCTANCE-TEMPERATURE 2 CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,802)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,803) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,804)
      ENDIF
C
C**** LOOK FOR 'CONDUCTANCE-GAP_N CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104T',NPRINT,ITAPET)
    2 IF(ITERME.LE.0.AND.ICONT.EQ.0)     ! thermal or unidirect. coupled
     . CALL RUNENDT('ERROR: NO VALUES OF CONDUCTANCE ARE FOUND')
      IF(WORDST(1).NE.'GAP_N')THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 3
      ELSE
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'CONDUCTANCE-GAP_N (NORMAL GAP) CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,902)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,803) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,804)
      ENDIF
C
C**** LOOK FOR 'CONDUCTANCE-PRESS (NORMAL PRESSURE) CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104T',NPRINT,ITAPET)
    3 IF(WORDST(1).NE.'PRESS')THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0
       IAUXX=0
      ELSE
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'CONDUCTANCE-PRESSURE (NORMAL) CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,912)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,803) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,804)
C
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0  ! normal stiffness to be assigned in checkp.f
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0  ! index IR432 to be assigned in checkp.f
       IAUXX=1
      ENDIF
C
      IF(NOCOIT.EQ.1) THEN ! deals with non-coincident contact mesh
       IF(IAUXX.EQ.0) GOTO 4
C
C**** LOOK FOR 'FRICTIONAL_HEATING' & 'PARTITION_COEFFICIENT' CARDS
C     (both indexes are transferred to mechanical problem in checkp.f)
C
       NPRINT=0
       CALL LISTENT('PRO104T',NPRINT,ITAPET)
    4  IF(WORDST(1).NE.'FRICT') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=0.0D0
        GOTO 5
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0       ! index IGAFRT for frictional heating
C
        IF(WORDST(2).NE.'PARTI') THEN
         NPOI1T=NPOI2T+1
         NPOI2T=NPOI1T
         PROPST(NPOI1T)=0.5D0      ! default value for partition coeff.
         CALL RUNMENT('WARNING: PARTITION COEFFICIENT=0.5')
        ELSE
         NPOI1T=NPOI2T+1
         NPOI2T=NPOI1T
         PROPST(NPOI1T)=PARAMT(1)  ! partition coefficient (AGAFPT)
         CALL RUNMENT('WARNING: A DIFFERENT MATERIAL FOR EACH DIFFERENT
     . CONTACT SET COULD BE NECESSARY IN THIS CASE')
        ENDIF
       ENDIF
C
C**** LOOK FOR 'BOUNDARY' CARD
C
       NPRINT=0
       CALL LISTENT('PRO104T',NPRINT,ITAPET)
    5  IF(WORDST(1).NE.'BOUND') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=0.0D0
        GOTO 6
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0    ! index IGABO3 for existence of boundary
       ENDIF
C
C**** LOOK FOR 'ENVIRONMENTAL TEMPERATURE' CARD
C
       CALL LISTENT('PRO104T',NPRINT,ITAPET)
       IF(WORDST(1).NE.'ENVIR')
     .  CALL RUNENDT('ERROR: ENVIR. TEMP. CARD NOT FOUND')
C
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)    ! TENVI3
C
C**** LOOK FOR 'CONVECTION COEFFICIENT CURVE' CARD
C
       CALL LISTENT('PRO104T',NPRINT,ITAPET)
       IF(WORDST(1).NE.'CONVE')
     .  CALL RUNENDT('ERROR: CONVECTION COEFF.-TEMP. CARD NOT FOUND ')
C
       IF(PARAMT(1).EQ.0.0D0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF CONV. COEFF. POINTS  ')
C
C**** READ 'CONVECTION COEFFICIENT CURVE' BY LISTEN
C
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONV. COEFF.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104T',NPRINT,ITAPET)
         DO I=1,2
          NPOI2T=NPOI2T+1
          PROPST(NPOI2T)=PARAMT(I)
         ENDDO
        ENDDO
       WRITE(LUREST,1804)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,1805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,804)
C
C**** LOOK FOR 'CRITICAL_GAP' CARD
C     (if g_n > g_crit, AIRGAP becomes BOUNDARY)
C
       CALL LISTENT('PRO104T',NPRINT,ITAPET)
       IF(WORDST(1).NE.'CRITI') THEN
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=0.0D0
        GOTO 6
       ELSE
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=1.0D0             ! index IGABO4 for critical gap
        NPOI1T=NPOI2T+1
        NPOI2T=NPOI1T
        PROPST(NPOI1T)=PARAMT(1)         ! critical gap AGABO4
       ENDIF
      ELSE
       IF(IAUXX.EQ.0) GOTO 6
      ENDIF                   ! nocoit.eq.1
C
C**** LOOK FOR 'END_MATERIAL' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104T',NPRINT,ITAPET)
    6 IF(WORDST(1).NE.'END_M')
     . CALL RUNENDT('ERROR: END_MATERIAL CARD NOT FOUND   ')
      IF(ICONT.EQ.0)
     . CALL RUNENDT('ERROR: NO VALUES OF CONDUCTANCE ARE FOUND')
      WRITE(LUREST,804)
C
C**** CONTROLS DIMENSION OF PROPST
C
      IF(NPOI2T.GT.NPROPT) THEN
       WRITE(LUREST,900) NPROPT,NPOI2T
       CALL RUNENDT('PROP05T: TOO MANY PROPERTIES TO READ')
      ENDIF
C
      RETURN
  802 FORMAT(/,'CONDUCTANCE COEF.    Vs.     TEMPERATURE',/)
  902 FORMAT(/,'CONDUCTANCE COEF.    Vs.     NORMAL GAP ',/)
  912 FORMAT(/,'CONDUCTANCE COEF.    Vs.     PRESSURE   ',/)
  803 FORMAT(E15.6,10X,E15.6)
  804 FORMAT(/)
  900 FORMAT(//,'TOO MANY MATERIAL PROPERTIES TO READ:',/,
     .      20X,'NPROP =',I5,5X,'NUMBE =',I5,/)
 1804 FORMAT(/,'CONVECTION COEF.     Vs.     TEMPERATURE',/)
 1805 FORMAT(E15.6,10X,E15.6)
      END
