      SUBROUTINE ADDWORS
C***********************************************************************
C
C**** THIS ROUTINE CALCULATES THE POINTERS FOR TEMPORARY ARRAYS
C
C***********************************************************************
C
C**** GENERAL DIMENSIONS
C
      INCLUDE 'para_oms.f'
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_oms.f'
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'     ! thermal-mechanical
      INCLUDE 'nued_om.f'     ! thermal-microstructural
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
      NNODGS=NNODES
      IF(NGAUSS.GT.NNODES) NNODGS=NGAUSS
C
      ITERME1=1                              ! unidirectional coupled
      ITERME2=1                              ! bidirectional coupled
      ITERME3=1                              ! deformed shape
      IF(ITERME.LT.0) THEN                   ! uncoupled problems
       ITERME1=0                             ! not used
       ITERME2=0
       ITERME3=0
      ENDIF
      IF(ITERME.EQ.0) THEN                   ! unidirectional coupled
       ITERME1=1                             ! not used
       ITERME2=0
       ITERME3=0
      ENDIF
      IF(ITERME.GT.0) THEN
       IF(ITERMD.EQ.0) ITERME3=0
      ENDIF
      NMEMA11S=1-NMEMO11S
      MMTER113S=0
      IF(ITERME2.GT.0.AND.(NMEMO11S.GT.0.OR.ITERME3.GT.0)) MMTER113S=1
C
      LWOR1S=0
C
C**** ROUTINE STARTSS
C
      IF(NMEMO1S.EQ.0) THEN          ! coordinates in an elemental array
       ISTARS(1)=1                               ! COORD(NDIME,NPOIN)
       ISTARS(2)=ISTARS(1)+NDIMES*NPOINS         ! GPCOD(NDIME,NGAUS)
       LINDAS   =ISTARS(2)+NDIMES*NGAUSS
      ELSE                           ! coordinates in a global array
       ISTARS(1)=1                               ! GPCOD(NDIME,NGAUS)
       LINDAS   =ISTARS(1)+NDIMES*NGAUSS
      ENDIF
      IF(NMEMO2S.NE.0) THEN
       ISTARS(3) =LINDAS                      ! CARTD(NDIME,NNODE,NGAUS)
       ISTARS(4) =ISTARS( 3)+NDIMES*NNODES*NGAUSS   ! DVOLU(NGAUS)
       ISTARS(5) =ISTARS( 4)+NGAUSS                 ! GPCOD(NDIME,NGAUS)
       ISTARS(6) =ISTARS( 5)+NDIMES*NGAUSS          ! SHAPE(NNODE,NGAUS)
       ISTARS(7) =ISTARS( 6)+NNODES*NGAUSS    ! DERIV(NDIME,NNODE,NGAUS)
       ISTARS(8) =ISTARS( 7)+NDIMES*NNODES*NGAUSS   ! POSGP(NDIME,NGAUS)
       ISTARS(9) =ISTARS( 8)+NDIMES*NGAUSS          ! WEIGP(NGAUS)
       ISTARS(10)=ISTARS( 9)+NGAUSS                 ! XJACM(NDIME,NDIME)
       ISTARS(11)=ISTARS(10)+NDIMES*NDIMES          ! ELCO1(NDIME,NNODE)
       ISTARS(12)=ISTARS(11)+NDIMES*NNODES          ! EMASS(NNODE,NNODE)
       ISTARS(13)=ISTARS(12)+NNODES*NNODES          ! ELDI1(NDOFN,NNODE)
       ISTARS(14)=ISTARS(13)+NDOFCS*NNODES          ! VNORL(NDIME,NGAUS)
       ISTARS(15)=ISTARS(14)+NDIMES*NGAUSS*ITERME2*NMEMO11S
C                                                   ! DVOLI(NGAUS)
       ISTARS(16)=ISTARS(15)+NGAUSS*ITERME3         ! ELCOI(NDIME,NNODE)
       ISTARS(17)=ISTARS(16)+NDIMES*NNODES*ITERME3  ! DISPT(NDOFC,NNODE)
       LINDAS    =ISTARS(17)+NDOFCMS*NNODES*ITERME3
      ENDIF
C
      IF(LINDAS.GT.LWOR1S) LWOR1S=LINDAS
C
      IF(KRENUS.NE.0) THEN                      ! renumbering
       LRENUS=NPOINS*(10*NNODES+3)/2
       IF(LRENUS.GT.LWOR1S) LWOR1S=LRENUS
      ENDIF
C
C**** ROUTINES ANTESO & POSTSO
C
      IQUASS(1)=1                               ! VVECT(NTOTV)
      IQUASS(2)=IQUASS(1)+NTOTVS                ! WVECT(NTOTV)
      LQUASS   =IQUASS(5)+NTOTVS
C
      IF(LQUASS.GT.LWOR1S) LWOR1S=LQUASS
C
C**** ROUTINE AQUAMX
C
      IF(KPORES.NE.2) GOTO 10
C
      IAQUAS(1)=1                               ! PMATX
      IAQUAS(2)=IAQUAS(1)+NDIMES*(NDIMES+1)/2   ! PMAT1
      IAQUAS(3)=IAQUAS(2)+NDIMES*(NDIMES+1)/2   ! BPBMX
      IAQUAS(4)=IAQUAS(3)+NNODES*(NNODES+1)/2   ! BMATX
      LNAQUS   =IAQUAS(4)+NEVABS*NSTR1S
C
      IF(LNAQUS.GT.LWOR1S) LWOR1S=LNAQUS
C
   10 CONTINUE
C
C**** ROUTINE SOLADDS
C
      IFIXYS(1)=1                               !  LEQNS(NEVAC)
      IFIXYS(2)=IFIXYS(1)+(NEVACS*ICHALS+4)/8   !  LNUEQ(NTOTV)
      IFIXYS(3)=IFIXYS(2)+(NTOTVS*ICHALS+4)/8   !  LOCEL(NEVAC)
      IFIXYS(4)=IFIXYS(3)+(NEVACS*ICHALS+4)/8   !  LPONT(NTOTV)
      IFIXYS(5)=IFIXYS(4)+(NTOTVS*ICHALS+4)/8   !  NACVA(NTOTV)
      IFIXYS(6)=IFIXYS(5)+(NTOTVS*ICHALS+4)/8   !  NDEST(NEVAC)
      IFIXYS(7)=IFIXYS(6)+(NEVACS*ICHALS+4)/8   !  NDFRO(NELEM)
      IFIXYS(8)=IFIXYS(7)+(NELEMS*ICHALS+4)/8   !  PRESC(NDOFC)
      LFIXYS   =IFIXYS(8)+NDOFCS
C
      IF(LFIXYS.GT.LWOR1S) LWOR1S=LFIXYS
C
C**** ROUTINE FORCIN
C
      IFORCS( 1)=1                              ! BMSIG(NEVAB)
      IFORCS( 2)=IFORCS( 1)+NEVABS              ! BMATX(NSTR1,NEVAB)
      IFORCS( 3)=IFORCS( 2)+NSTR1S*NEVABS       ! DESIG(NSTR1) 
      IFORCS( 4)=IFORCS( 3)+NSTR1S              ! DMATX(NSTR1,NSTR1)
      IFORCS( 5)=IFORCS( 4)+NSTR1S*NSTR1S       ! DSTRA(NSTR1)
      IFORCS( 6)=IFORCS( 5)+NSTR1S              ! PRESG(NSTR1)
      IFORCS( 7)=IFORCS( 6)+NSTR1S              ! SGTOT(NSTR1)
      IFORCS( 8)=IFORCS( 7)+NSTR1S              ! SIGMA(NSTR1)
      IFORCS( 9)=IFORCS( 8)+NSTR1S              ! TSTRA(NSTR1)
      IFORCS(10)=IFORCS( 9)+NSTR1S              ! XJACM(NDIME,NDIME)
      IFORCS(11)=IFORCS(10)+NDIMES*NDIMES       ! ELELT(NEVAB)
      IFORCS(12)=IFORCS(11)+NEVABS              ! VELCM(NEVAB)
      IFORCS(13)=IFORCS(12)+NEVABS              ! DISPT(NDOFC,NNODET)
      IFORCS(14)=IFORCS(13)+NDOFCMS*NNODES*MMTER113S ! PREASL(NNODET)
      IFORCS(15)=IFORCS(14)+NNODES*ITERME2*NMEMA11S ! TGAPSL(NNODET)
      IFORCS(16)=IFORCS(15)+NNODES*ITERME2*NMEMA11S ! ELCO1(NDIME,NNODE)
C
      IAUXX=0
      IF(ICONVS.EQ.1.OR.IGALES.EQ.1) IAUXX=1
      IFORCS(17)=IFORCS(16)+NDIMES*NNODES           ! SHAPD(NNODE,NGAUS)
      IFORCS(18)=IFORCS(17)+NNODES*NGAUSS*IAUXX     ! DVOLD(NGAUS)
      IFORCS(19)=IFORCS(18)+NGAUSS*ICONVS           ! POSGP(NDIME,NGAUS)
      IFORCS(20)=IFORCS(19)+NDIMES*NGAUSS*IAUXX     ! WEIGP(NGAUS)
      IFORCS(21)=IFORCS(20)+NGAUSS*IAUXX      ! DERID(NDIME,NNODE,NGAUS)
      IFORCS(22)=IFORCS(21)+NDIMES*NNODES*NGAUSS*IAUXX
C                                                   ! XJACM(NDIME,NDIME)
      IFORCS(23)=IFORCS(22)+NDIMES*NDIMES*IAUXX
C                                             ! CARDD(NDIME,NNODE,NGAUS)
      IFORCS(24)=IFORCS(23)+NDIMES*NNODES*NGAUSS*IAUXX
C                                                   ! GPCDD(NDIME,NGAUS)
      IFORCS(25)=IFORCS(24)+NDIMES*NGAUSS*IAUXX     ! ELEL1(NEVAB)
      IFORCS(26)=IFORCS(25)+NEVABS*ICONVS           ! ELEL2(NEVAB)
C
      IFORCS(27)=IFORCS(26)+NEVABS*ICONVS           ! WHAPE(NNODE,NGAUS)
      IFORCS(28)=IFORCS(27)+NNODES*NGAUSS           ! HACHE(NNODE)
      IFORCS(29)=IFORCS(28)+NNODES*IGALES     ! WARTD(NDIME,NNODE,NGAUS)
      IFORCS(30)=IFORCS(29)+NDIMES*NNODES*NGAUSS
C                                             ! WERIV(NDIME,NNODE,NGAUS)
      IFORCS(31)=IFORCS(30)+NDIMES*NNODES*NGAUSS*IGALES
C                                                   ! WHADE(NNODE,NGAUS)
      IFORCS(32)=IFORCS(31)+NNODES*NGAUSS*ICONVS    ! CENTR(NDIME,NNODE)
C
      IAUX1=0
      IF(IMICR.EQ.1) THEN
       IF(IMICO.EQ.0) IAUX1=1
      ENDIF
      IFORCS(33)=IFORCS(32)+NDIMES*NNODES*IGALES    ! VEL1M(NEVAB)
      IFORCS(34)=IFORCS(33)+NEVABS*IAUX1            ! ADVEM(NDIME*NNODE)
C
      IFORCS(35)=IFORCS(34)+NDIMES*NNODES*ICONVS
C                                             ! CARTD(NDIME,NNODE,NGAUS)
      IFORCS(36)=IFORCS(35)+NDIMES*NNODES*NGAUSS    ! DVOLU(NGAUS)
      IFORCS(37)=IFORCS(36)+NGAUSS                  ! GPCOD(NDIME,NGAUS)
      IFORCS(38)=IFORCS(37)+NDIMES*NGAUSS           ! SHAPE(NNODE,NGAUS)
      IFORCS(39)=IFORCS(38)+NNODES*NGAUSS     ! DERIV(NDIME,NNODE,NGAUS)
      IFORCS(40)=IFORCS(39)+NDIMES*NNODES*NGAUSS    ! POSGP(NDIME,NGAUS)
      IFORCS(41)=IFORCS(40)+NDIMES*NGAUSS           ! WEIGP(NGAUS)
      IFORCS(42)=IFORCS(41)+NGAUSS                  ! XJACM(NDIME,NDIME)
      IFORCS(43)=IFORCS(42)+NDIMES*NDIMES           ! EMASS(NNODE,NNODE)
      IFORCS(44)=IFORCS(43)+NNODES*NNODES           ! ELDI1(NDOFN,NNODE)
      IFORCS(45)=IFORCS(44)+NDOFCS*NNODES           ! TEINI(NDOFN,NNODE)
      IFORCS(46)=IFORCS(45)+NDOFCS*NNODES           ! BOUCH(NDOFN,NNODE)
      IFORCS(47)=IFORCS(46)+NDOFCS*NNODES*NMEMO10S  ! VNORL(NDIME,NGAUS)
      IFORCS(48)=IFORCS(47)+NDIMES*NGAUSS*ITERME2*NMEMO11S
C                                                   ! FPCHL(NFPCH,NNODE)
      IFORCS(49)=IFORCS(48)+NFPCH*NNODES            ! DVOLI(NGAUS)
      IFORCS(50)=IFORCS(49)+NGAUSS*ITERME3          ! ELCOI(NDIME,NNODE)
      LFORCS    =IFORCS(50)+NDIMES*NNODES*ITERME3
C
      IF(LFORCS.GT.LWOR1S) LWOR1S=LFORCS
C
C**** ROUTINE THERDYS
C
      IF(KDYNAS.EQ.1)THEN
       IFORDS(1)=1                              ! ELELM(NEVAB)
       IFORDS(2)=IFORDS(1)+NEVABS               ! VELCM(NEVAB)
       IFORDS(3)=IFORDS(2)+NEVABS               ! DISIM(NEVAB)
       IFORDS(4)=IFORDS(3)+NEVABS               ! ESTIF(NKOVA)
       IFORDS(5)=IFORDS(4)+NKOVAS               ! DSTIF(NKOVA)
       IFORDS(6)=IFORDS(5)+NKOVAS               ! ELELT(NEVAB)
       IFORDS(7)=IFORDS(6)+NEVABS               ! SHAPD(NNODE,NGAUS)
       IFORDS(8)=IFORDS(7)+NNODES*NGAUSS        ! DVOLD(NGAUS)
       IFORDS(9)=IFORDS(8)+NGAUSS               ! POSGP(NDIME,NGAUS)
       IFORDS(10)=IFORDS(9)+NDIMES*NGAUSS       ! WEIGP(NGAUS)
       IFORDS(11)=IFORDS(10)+NGAUSS           ! DERID(NDIME,NNODE,NGAUS)
       IFORDS(12)=IFORDS(11)+NDIMES*NNODES*NGAUSS ! XJACM(NDIME,NDIME)
       IFORDS(13)=IFORDS(12)+NDIMES*NDIMES    ! CARDD(NDIME,NNODE,NGAUS)
       IFORDS(14)=IFORDS(13)+NDIMES*NNODES*NGAUSS ! GPCDD(NDIME,NGAUS)
       IFORDS(15)=IFORDS(14)+NDIMES*NGAUSS      ! ELEL1(NEVAB)
       IFORDS(16)=IFORDS(15)+NEVABS             ! ELEL2(NEVAB)
       IFORDS(17)=IFORDS(16)+NEVABS             ! ELCO1(NDIME,NNODE)
       IFORDS(18)=IFORDS(17)+NDIMES*NNODES          ! WHAPE(NNODE,NGAUS)
       IFORDS(19)=IFORDS(18)+NNODES*NGAUSS          ! HACHE(NNODE)
       IFORDS(20)=IFORDS(19)+NNODES*IGALES          ! WHADE(NNODE,NGAUS)
       IFORDS(21)=IFORDS(20)+NNODES*NGAUSS          ! CENTR(NDIME,NNODE)
       IFORDS(22)=IFORDS(21)+NDIMES*NNODES*IGALES   ! ADVEM(NDIME,NNODE)
       IFORDS(23)=IFORDS(22)+NDIMES*NNODES*ICONVS
C                                             ! CARTD(NDIME,NNODE,NGAUS)
       IFORDS(24)=IFORDS(23)+NDIMES*NNODES*NGAUSS   ! DVOLU(NGAUS)
       IFORDS(25)=IFORDS(24)+NGAUSS                 ! GPCOD(NDIME,NGAUS)
       IFORDS(26)=IFORDS(25)+NDIMES*NGAUSS          ! SHAPE(NNODE,NGAUS)
       IFORDS(27)=IFORDS(26)+NNODES*NGAUSS    ! DERIV(NDIME,NNODE,NGAUS)
       IFORDS(28)=IFORDS(27)+NDIMES*NNODES*NGAUSS   ! POSGP(NDIME,NGAUS)
       IFORDS(29)=IFORDS(28)+NDIMES*NGAUSS          ! WEIGP(NGAUS)
       IFORDS(30)=IFORDS(29)+NGAUSS                 ! XJACM(NDIME,NDIME)
       IFORDS(31)=IFORDS(30)+NDIMES*NDIMES          ! EMASS(NNODE,NNODE)
       IFORDS(32)=IFORDS(31)+NNODES*NNODES          ! ELDI1(NDOFN,NNODE)
       IFORDS(33)=IFORDS(32)+NDOFCS*NNODES          ! TEINI(NDOFN,NNODE)
       IFORDS(34)=IFORDS(33)+NDOFCS*NNODES          ! FPCHL(NFPCH,NNODE)
       IFORDS(35)=IFORDS(34)+NFPCH*NNODES           ! DVOLI(NGAUS)
       IFORDS(36)=IFORDS(35)+NGAUSS*ITERME3         ! ELCOI(NDIME,NNODE)
       IFORDS(37)=IFORDS(36)+NDIMES*NNODES*ITERME3  ! DISPT(NDOFC,NNODE)
       LFORDS    =IFORDS(37)+NDOFCMS*NNODES*ITERME3
C
       IF(LFORDS.GT.LWOR1S) LWOR1S=LFORDS
      ENDIF                                  ! kdynat.eq.1
C
C**** ROUTINE FORCWP
C
      IF(KPORES.EQ.2) THEN
       IFORWS( 1)=1                            ! HSTIF(NEVAB,NNODE)
       IFORWS( 2)=IFORWS( 1)+NEVABS*NNODES     ! PSTIF(NKOND)
       IFORWS( 3)=IFORWS( 2)+NKONDS            ! QSTIF(NKOND)
       LFORWS    =IFORWS( 3)+NKONDS
C
       IF(LFORWS.GT.LWOR1S) LWOR1S=LFORWS
      ENDIF
C
C**** ROUTINE LOADPSS & FIXITYS
C
      NGAULS=4          
      ILOSUS( 1)=1                              ! ALOAD(NEVAB)
      ILOSUS( 2)=ILOSUS( 1)+NEVABS              ! DERIV(NDIME,NNODE)
      ILOSUS( 3)=ILOSUS( 2)+NDIMES*NNODES       ! ELEDG(NDIME,NNODE)
      ILOSUS( 4)=ILOSUS( 3)+NDIMES*NNODES       ! GPCOD(NDIME)
      ILOSUS( 5)=ILOSUS( 4)+NDIMES              ! GVECT(NDIME)
      ILOSUS( 6)=ILOSUS( 5)+NDIMES              ! NOPRS(NNODE)
      ILOSUS( 7)=ILOSUS( 6)+NNODES              ! POSGP(NDIME,NGAUS)
      ILOSUS( 8)=ILOSUS( 7)+NDIMES*NGAUSS       ! PRESS(NNODE,NDIME)
      ILOSUS( 9)=ILOSUS( 8)+NNODES*NDIMES       ! PVECT(NDIME)
      ILOSUS(10)=ILOSUS( 9)+NDIMES              ! SHAPE(NNODE)
      ILOSUS(11)=ILOSUS(10)+NNODES              ! VAREA(NDIME)
      ILOSUS(12)=ILOSUS(11)+NDIMES              ! WEIGP(NGAUS)
      ILOSUS(13)=ILOSUS(12)+NGAUSS              ! XJACM(NDIME*NDIME)
      ILOSUS(14)=ILOSUS(13)+NDIMES*NDIMES       ! CARTD(NDIME,NNODE)
      ILOSUS(15)=ILOSUS(14)+NDIMES*NDIMES       ! PRESC(NTOTV)
      ILOSUS(16)=ILOSUS(15)+NTOTVS              ! VELCM(NEVAB)
      ILOSUS(17)=ILOSUS(16)+NEVABS              ! ELCO1(NDIME,NNODE)
      ILOSUS(18)=ILOSUS(17)+NDIMES*NNODES       ! WHAPE(NNODE,NGAUS)
      ILOSUS(19)=ILOSUS(18)+NNODES*NGAUSS       ! HACHE(NNODE)
      ILOSUS(20)=ILOSUS(19)+NNODES*IGALES       ! CENTR(NDIME,NNODE)
      ILOSUS(21)=ILOSUS(20)+NDIMES*NNODES*IGALES
C                                             ! CARTD(NDIME,NNODE,NGAUS)
      ILOSUS(22)=ILOSUS(21)+NDIMES*NNODES*NGAUSS    ! DVOLU(NGAUS)
      ILOSUS(23)=ILOSUS(22)+NGAUSS                  ! GPCOD(NDIME,NGAUS)
      ILOSUS(24)=ILOSUS(23)+NDIMES*NGAUSS           ! SHAPE(NNODE,NGAUS)
      ILOSUS(25)=ILOSUS(24)+NNODES*NGAUSS     ! DERIV(NDIME,NNODE,NGAUS)
      ILOSUS(26)=ILOSUS(25)+NDIMES*NNODES*NGAUSS    ! POSGP(NDIME,NGAUS)
      ILOSUS(27)=ILOSUS(26)+NDIMES*NGAUSS           ! WEIGP(NGAUS)
      ILOSUS(28)=ILOSUS(27)+NGAUSS                  ! XJACM(NDIME,NDIME)
      ILOSUS(29)=ILOSUS(28)+NDIMES*NDIMES           ! EMASS(NNODE,NNODE)
      ILOSUS(30)=ILOSUS(29)+NNODES*NNODES           ! ELDI1(NDOFN,NNODE)
      ILOSUS(31)=ILOSUS(30)+NDOFCS*NNODES           ! TEINI(NDOFN,NNODE)
      ILOSUS(32)=ILOSUS(31)+NDOFCS*NNODES           ! ADVEM(NDIME,NNODE)
      ILOSUS(33)=ILOSUS(32)+NDIMES*NNODES*ICONVS    ! BOUCH(NDOFN,NNODE)
      ILOSUS(34)=ILOSUS(33)+NDOFCS*NNODES*NMEMO10S  ! FPCHL(NFPCH,NNODE)
      ILOSUS(35)=ILOSUS(34)+NFPCH*NNODES            ! DVOLI(NGAUS)
      ILOSUS(36)=ILOSUS(35)+NGAUSS*ITERME3          ! ELCOI(NDIME,NNODE)
      ILOSUS(37)=ILOSUS(36)+NDIMES*NNODES*ITERME3   ! DISPT(NDOFC,NNODE)
      LLOSUS    =ILOSUS(37)+NDOFCMS*NNODES*ITERME3
C
      IF(LLOSUS.GT.LWOR1S) LWOR1S=LLOSUS
C
C**** ROUTINE OUTSMOS & OUTGAUS
C
      ISMOMS=0
      IF(KSGAUS.NE.0) ISMOMS=1
C
      IGSMOS(1)=1                                   ! SMSTS(NSTR1,NPOIN)
      IGSMOS(2)=IGSMOS(1)+NSTR1S*NPOINS*ISMOMS*NMEMO4S
C                                                   ! SMSTN(NSTR1,NPOIN)
      IGSMOS(3)=IGSMOS(2)+NSTR1S*NPOINS*ISMOMS*NMEMO4S
C                                                   ! ACCPN(NPOIN)
C
C**** NODAL FLUXES:      STREB(NSTR1,NNODE) & STREA(NNODE,NSTR1)
C     NODAL TEMP. GRAD.: SFISB(NSTR1,NNODE) & SFISA(NNODE,NSTR1)
C
      IGSMOS(4)=IGSMOS(3)+NPOINS*ISMOMS             ! STREB(NSTR1,NNODE)
      IGSMOS(5)=IGSMOS(4)+NSTR1S*NNODES*ISMOMS*NMEMO4S
C                                                   ! STREA(NNODE,NSTR1)
      IGSMOS(6)=IGSMOS(5)+NNODES*NSTR1S*ISMOMS*NMEMO4S
C                                                   ! SFISB(NSTR1,NNODE)
      IGSMOS(7)=IGSMOS(6)+NSTR1S*NNODES*ISMOMS*NMEMO4S
C                                                   ! SFISA(NNODE,NSTR1)
C
C**** NODAL INT. VARIABLES: SFIPB(NNUIN,NNODE) & SFIPA(NNODE,NNUIN)
C
      IGSMOS( 8)=IGSMOS( 7)+NNODES*NSTR1S*ISMOMS*NMEMO4S
C                                                   ! SMSTP(NNUIN,NPOIN)
      IGSMOS( 9)=IGSMOS( 8)+NPOINS*NNUINS*ISMOMS    ! SFIPA(NNODE,NNUIN)
      IGSMOS(10)=IGSMOS( 9)+NNODES*NNUINS*ISMOMS    ! SFIPB(NNUIN,NNODE)
C
      IGSMOS(11)=IGSMOS(10)+NNUINS*NNODES*ISMOMS
C                                             ! CARTD(NDIME,NNODE,NGAUS)
      IGSMOS(12)=IGSMOS(11)+NDIMES*NNODES*NGAUSS    ! DVOLU(NGAUS)
      IGSMOS(13)=IGSMOS(12)+NGAUSS                  ! GPCOD(NDIME,NGAUS)
      IGSMOS(14)=IGSMOS(13)+NDIMES*NGAUSS           ! SHAPE(NNODE,NGAUS)
      IGSMOS(15)=IGSMOS(14)+NNODES*NGAUSS     ! DERIV(NDIME,NNODE,NGAUS)
      IGSMOS(16)=IGSMOS(15)+NDIMES*NNODES*NGAUSS    ! POSGP(NDIME,NGAUS)
      IGSMOS(17)=IGSMOS(16)+NDIMES*NGAUSS           ! WEIGP(NGAUS)
      IGSMOS(18)=IGSMOS(17)+NGAUSS                  ! XJACM(NDIME,NDIME)
      IGSMOS(19)=IGSMOS(18)+NDIMES*NDIMES           ! ELCO1(NDIME,NNODE)
      IGSMOS(20)=IGSMOS(19)+NDIMES*NNODES           ! EMASS(NNODE,NNODE)
      IGSMOS(21)=IGSMOS(20)+NNODES*NNODES           ! ELDI1(NDOFN,NNODE)
      IGSMOS(22)=IGSMOS(21)+NDOFCS*NNODES           ! SMSPP(NPORO,NPOIN)
      IGSMOS(23)=IGSMOS(22)+NPOROS*NPOINS           ! SPIPA(NNODE,NPORO)
      IGSMOS(24)=IGSMOS(23)+NNODES*NPOROS           ! SPIPB(NPORO,NNODE)
      IGSMOS(25)=IGSMOS(24)+NPOROS*NNODES           ! SPIBC(NPORO,NNODG)
      IGSMOS(26)=IGSMOS(25)+NPOROS*NNODGS           ! FPCHL(NFPCH,NNODE)
      IGSMOS(27)=IGSMOS(26)+NFPCH*NNODES            ! VELCM(NDOFN,NNODE)
      IGSMOS(28)=IGSMOS(27)+NDOFCS*NNODES           ! DVOLI(NGAUS)
      IGSMOS(29)=IGSMOS(28)+NGAUSS*ITERME3          ! ELCOI(NDIME,NNODE)
      IGSMOS(30)=IGSMOS(29)+NDIMES*NNODES*ITERME3   ! DISPT(NDOFC,NNODE)
      LGSMOS    =IGSMOS(30)+NDOFCMS*NNODES*ITERME3
C
      IF(LGSMOS.GT.LWOR1S) LWOR1S=LGSMOS
C
C**** ROUTINE SETMTXS
C
      ISETMS( 1)=1                            ! DERIV(NDIME,NNODE,NGAUS)
      ISETMS( 2)=ISETMS( 1)+NDIMES*NNODES*NGAUSS    ! POSGP(NDIME,NGAUS)
      ISETMS( 3)=ISETMS( 2)+NGAUSS*NDIMES           ! WEIGP(NGAUS)
      ISETMS( 4)=ISETMS( 3)+NGAUSS                  ! XJACM(NDIME,NDIME)
      ISETMS( 5)=ISETMS( 4)+NDIMES*NDIMES           ! RMAT2(NSTR1,NSTR1)
      ISETMS( 6)=ISETMS( 5)+NSTR1S*NSTR1S           ! ELCO1(NDIME,NNODE)
      ISETMS( 7)=ISETMS( 6)+NDIMES*NNODES     ! CARTD(NDIME,NNODE,NGAUS)
      ISETMS( 8)=ISETMS( 7)+NDIMES*NNODES*NGAUSS    ! DVOLU(NGAUS)
      ISETMS( 9)=ISETMS( 8)+NGAUSS                  ! GPCOD(NDIME,NGAUS)
      ISETMS(10)=ISETMS( 9)+NDIMES*NGAUSS           ! SHAPE(NNODE,NGAUS)
      ISETMS(11)=ISETMS(10)+NNODES*NGAUSS           ! EMASS(NNODE,NNODE)
      ISETMS(12)=ISETMS(11)+NNODES*NNODES           ! ELDI1(NDOFN,NNODE)
      ISETMS(13)=ISETMS(12)+NDOFCS*NNODES           ! TEINI(NDOFN,NNODE)
      ISETMS(14)=ISETMS(13)+NDOFCS*NNODES           ! FPCHL(NFPCH,NNODE)
      ISETMS(15)=ISETMS(14)+NFPCH*NNODES            ! VNORL(NDIME,NGAUS)
      ISETMS(16)=ISETMS(15)+NDIMES*NGAUSS*ITERME2*NMEMO11S !DVOLI(NGAUS)
      ISETMS(17)=ISETMS(16)+NGAUSS*ITERME3          ! ELCOI(NDIME,NNODE)
      ISETMS(18)=ISETMS(17)+NDIMES*NNODES*ITERME3   ! DISPT(NDOFC,NNODE)
      LSETMS    =ISETMS(18)+NDOFCMS*NNODES*ITERME3
C
      IF(LSETMS.GT.LWOR1S) LWOR1S=LSETMS
C
C**** ROUTINE STIFMXSS
C
      ISTIFS(1)=1                               ! BMATX(NSTR1,NEVAB)
      ISTIFS(2)=ISTIFS(1)+NSTR1S*NEVABS         ! DMATX(NSTR1,NSTR1)
      ISTIFS(3)=ISTIFS(2)+NSTR1S*NSTR1S         ! SIGMA(NSTR1)
      ISTIFS(4)=ISTIFS(3)+NSTR1S                ! XJACM(NDIME,NDIME)
      ISTIFS(5)=ISTIFS(4)+NDIMES*NDIMES         ! SHAPD(NNODE,NGAUS)
      ISTIFS(6)=ISTIFS(5)+NNODES*NGAUSS         ! DVOLD(NGAUS)
      ISTIFS(7)=ISTIFS(6)+NGAUSS                ! POSGP(NDIME,NGAUS)
      ISTIFS(8)=ISTIFS(7)+NDIMES*NGAUSS         ! WEIGP(NGAUS)
      ISTIFS(9)=ISTIFS(8)+NGAUSS              ! DERID(NDIME,NNODE,NGAUS)
      ISTIFS(10)=ISTIFS(9)+NDIMES*NNODES*NGAUSS ! XJACM(NDIME,NDIME)
      ISTIFS(11)=ISTIFS(10)+NDIMES*NDIMES     ! CARDD(NDIME,NNODE,NGAUS)
      ISTIFS(12)=ISTIFS(11)+NDIMES*NNODES*NGAUSS ! GPCDD(NDIME,NGAUS)
      ISTIFS(13)=ISTIFS(12)+NDIMES*NGAUSS       ! VELCM(NEVAB)
      ISTIFS(14)=ISTIFS(13)+NEVABS              ! WSTI1(NKOVA)
      ISTIFS(15)=ISTIFS(14)+NKOVAS              ! WSTI2(NKOVA)
      ISTIFS(16)=ISTIFS(15)+NKOVAS              ! VELAN(NEVAB)
      ISTIFS(17)=ISTIFS(16)+NEVABS              ! DISIT(NEVAB)
      ISTIFS(18)=ISTIFS(17)+NEVABS              ! ELCO1(NDIME,NNODE)
      ISTIFS(19)=ISTIFS(18)+NDIMES*NNODES       ! WHAPE(NNODE,NGAUS)
      ISTIFS(20)=ISTIFS(19)+NNODES*NGAUSS       ! HACHE(NNODE)
      ISTIFS(21)=ISTIFS(20)+NNODES*IGALES     ! WARTD(NDIME,NNODE,NGAUS)
      ISTIFS(22)=ISTIFS(21)+NDIMES*NNODES*NGAUSS
C                                             ! WERIV(NDIME,NNODE,NGAUS)
      ISTIFS(23)=ISTIFS(22)+NDIMES*NNODES*NGAUSS*IGALES
C                                                   ! WHADE(NNODE,NGAUS)
      ISTIFS(24)=ISTIFS(23)+NNODES*NGAUSS           ! CENTR(NDIME,NNODE)
      ISTIFS(25)=ISTIFS(24)+NDIMES*NNODES*IGALES    ! ADVEM(NDIME*NNODE)
      ISTIFS(26)=ISTIFS(25)+NDIMES*NNODES*ICONVS
C                                             ! CARTD(NDIME,NNODE,NGAUS)
      ISTIFS(27)=ISTIFS(26)+NDIMES*NNODES*NGAUSS    ! DVOLU(NGAUS)
      ISTIFS(28)=ISTIFS(27)+NGAUSS                  ! GPCOD(NDIME,NGAUS)
      ISTIFS(29)=ISTIFS(28)+NDIMES*NGAUSS           ! SHAPE(NNODE,NGAUS)
      ISTIFS(30)=ISTIFS(29)+NNODES*NGAUSS     ! DERIV(NDIME,NNODE,NGAUS)
      ISTIFS(31)=ISTIFS(30)+NDIMES*NNODES*NGAUSS    ! POSGP(NDIME,NGAUS)
      ISTIFS(32)=ISTIFS(31)+NDIMES*NGAUSS           ! WEIGP(NGAUS)
      ISTIFS(33)=ISTIFS(32)+NGAUSS                  ! XJACM(NDIME,NDIME)
      ISTIFS(34)=ISTIFS(33)+NDIMES*NDIMES           ! EMASS(NNODE,NNODE)
      ISTIFS(35)=ISTIFS(34)+NNODES*NNODES           ! PREASL(NNODE)
      ISTIFS(36)=ISTIFS(35)+NNODES*ITERME2*NMEMA11S ! TGAPSL(NNODE)
      ISTIFS(37)=ISTIFS(36)+NNODES*ITERME2*NMEMA11S ! ESTII(NKOVA)
      ISTIFS(38)=ISTIFS(37)+NKOVAS                  ! WSTII(NKOVA)
      ISTIFS(39)=ISTIFS(38)+NKOVAS*KDYNAS           ! ELDI1(NDOFN,NNODE)
      ISTIFS(40)=ISTIFS(39)+NDOFCS*NNODES           ! TEINI(NDOFN,NNODE)
      ISTIFS(41)=ISTIFS(40)+NDOFCS*NNODES           ! CSTI1(NEVAB,NEVAB)
      ISTIFS(42)=ISTIFS(41)+NEVABS*NEVABS*NMEMO7S   ! BOUCH(NDOFN,NNODE)
      ISTIFS(43)=ISTIFS(42)+NDOFCS*NNODES*NMEMO10S  ! VNORL(NDIME,NGAUS)
      ISTIFS(44)=ISTIFS(43)+NDIMES*NGAUSS*ITERME2*NMEMO11S
C                                                   ! DISPT(NDOFC,NNODE)
      ISTIFS(45)=ISTIFS(44)+NDOFCMS*NNODES*MMTER113S !FPCHL(NFPCH,NNODE)
      ISTIFS(46)=ISTIFS(45)+NFPCH*NNODES            ! DVOLI(NGAUS)
      ISTIFS(47)=ISTIFS(46)+NGAUSS*ITERME3          ! ELCOI(NDIME,NNODE)
      ISTIFS(48)=ISTIFS(47)+NDIMES*NNODES*ITERME3   ! EMATX(NEVAB,NEVAB)
      ISTIFS(49)=ISTIFS(48)+NEVABS*NEVABS           ! FMATX(NEVAB,NEVAB)
      LSTIFS    =ISTIFS(49)+NEVABS*NEVABS
C
      IF(LSTIFS.GT.LWOR1S) LWOR1S=LSTIFS
C
C**** MEMORY CONTROL
C
      IF(LWOR1S.GT.MWORK1S)
     . CALL RUNENDS('ERROR IN ADDWORS: LWOR1S          ')
C
C**** OTHER CONTROLS
C
      IF(KDYNAS.GT.MDYNAS)
     . CALL RUNENDS('ERROR IN ADDWORS: KDYNAS          ')
      IF(ISMOMS.GT.MSMOMS)
     . CALL RUNENDS('ERROR IN ADDWORS: ISMOMS          ')
      IF(KRENUS.GT.MRENUS)
     . CALL RUNENDS('ERROR IN ADDWORS: KRENUS          ')
      IF(KPORES.GT.MPORES)
     . CALL RUNENDS('ERROR IN ADDWORS: KPORES          ')
      IF(NHOURS.GT.MHOURS)
     . CALL RUNENDS('ERROR IN ADDWORS: NHOURS          ')
C
      ITERMA=1
      IF(ITERME.LE.0) ITERMA=0                   ! uncoupled prob.
C
      IF(ITERMA.GT.MTERME)
     . CALL RUNENDS('ERROR IN ADDWORS: ITERME          ')
c     IF(IMICR.GT.MMICR)
c    . CALL RUNENDS('ERROR IN ADDWORS: IMICR           ')
c     IF(IMICR.EQ.1) THEN
c      IF(IMICO.LT.MMICO)
c    .  CALL RUNENDS('ERROR IN ADDWORS: IMICO          ')
c     ENDIF
      IF(ICONVS.GT.MCONVS)
     . CALL RUNENDS('ERROR IN ADDWORS: ICONVS          ')
      IF(IGALES.GT.MGALES)
     . CALL RUNENDS('ERROR IN ADDWORS: IGALES          ')
C
c     IF(NMEMO3S.EQ.0.AND.IMICR.NE.0)
c    . CALL RUNENDS('ERROR: NMEMO3S=0 WITH IMICR=1')
      IF(NMEMO3S.EQ.0.AND.NITERCS.EQ.1)
     . CALL RUNENDS('ERROR: NMEMO3S=0 WITH NITERCS=1')
C
      IF(NPOROS.GT.MPOROS)
     . CALL RUNENDS('ERROR: NPOROS GT MPOROS      ')
C
      IF(NNUM4S.GT.MNUM4S)
     . CALL RUNENDS('ERROR: NNUM4S GT MNUM4S      ')
      IF(NNUM4S.GT.MNU4SX)
     . CALL RUNENDS('ERROR: NNUM4S GT MNU4SX      ')
      IF(NNUM4SM.GT.MNUM4SM)
     . CALL RUNENDS('ERROR: NNUM4SM GT MNUM4SM    ')
      IF(NNUM4SM.GT.MNU4SMX)
     . CALL RUNENDS('ERROR: NNUM4SM GT MNU4SMX    ')
C
C**** DEFINE STARTING POSITION OF MEMORY
C
      LBYW1S=LWOR1S*8
C
      RETURN
      END
