      SUBROUTINE RSTAR2S(LPNTNS,LNODSS,MATNOS,PROELS,PROPSS,IFLAGS)
C***********************************************************************
C
C**** THIS ROUTINE READS OR WRITES SOME GENERAL DATA ARRAYS
C
C   - IFLAG = 1 - NEW RUN    : WRITE INTO RESTART FILE 
C   - IFLAG = 2 - RESTART RUN: READ  FROM RESTART FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'auxl_oms.f'
C
      DIMENSION LPNTNS(*), LNODSS(NNODES,NELEMS), MATNOS(NELEMS),
     .                     PROELS(NPRELS,NGRUPS), PROPSS(NPROPS,NMATSS)


      call runends('stop in rstar2s')

C
      CALL CPUTIMS(TIME1S)
C
c     NRCURT=4
c     NUNITT=LURSTT
C
C**** WRITE OR READ ALL MATRICES
C
c     LENGHT=NPOINT
c     CALL RESTDKT(NUNITT,IFLAGT,LPNTNT,LENGHT,LENRCT,NRCURT)
C
c     LENGHT=NNODET*NELEMT
c     CALL RESTDKT(NUNITT,IFLAGT,LNODST,LENGHT,LENRCT,NRCURT)
C
c     LENGHT=NELEMT
c     CALL RESTDKT(NUNITT,IFLAGT,MATNOT,LENGHT,LENRCT,NRCURT)
C
c     LENGHT=NPRELT*NGRUPT*2
c     CALL RESTDKT(NUNITT,IFLAGT,PROELT,LENGHT,LENRCT,NRCURT)
C
c     LENGHT=NPROPT*NMATST*2
c     CALL RESTDKT(NUNITT,IFLAGT,PROPST,LENGHT,LENRCT,NRCURT)
C
      CALL CPUTIMS(TIME2S)
      CPURSS=CPURSS+(TIME2S-TIME1S)
C
      RETURN
      END
