      SUBROUTINE TRASMEC(DISTO, PWORK, PREAS, TGAPS,
     .                   DISPLT,PWORKT,PREAST,TGAPST)
C***********************************************************************
C
C**** THIS ROUTINE TRANSFER NODAL MECHANICAL VARIABLES TO THERMAL
C     PROBLEM
C
C     CURRENT VALUES DURING ITERATION OR LAST CONVERGED ONES
C     (PREDICTION FOR A NEW TIME STEP)
C
C
C     DISPLT    :  DISPLACEMENTS
C
C     PWORKT(1) :  CURRENT MECHANICAL COUPLING TERM
C     PWORKT(2) :  LAST CONVERGED MECHANICAL COUPLING TERM
C     PWORKT(3) :  COUPLING TERM OF THE IMPROVED STAGGERED SCHEME
C
C     PREAST    :  NORMAL FORCE
C
C     TGAPST    :  NORMAL GAP
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
C
C**** MECHANICAL VARIABLES
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
C
      DIMENSION   DISTO(NTOTV,NDISO), PWORK(NPOIN,2),
     .            PREAS(NPOIN),       TGAPS(NPOIN),
     .            DISPLT(NTOTVM),     PWORKT(NPOINT,3),
     .            PREAST(NPOINT),     TGAPST(NPOINT)
C
      IF(ITERMP.GT.0.OR.ITERMF.GT.0) THEN
       DO IPOINC=1,NPOINC
        PWORKT(IPOINC,1)=PWORK(IPOINC,1)
        IF(NITERC.EQ.2) PWORKT(IPOINC,3)=PWORK(IPOINC,2)
       END DO
      ENDIF
C
      IF(ITERMG.GT.0) THEN
       IF(NMEMO11.EQ.0) THEN
        DO IPOINC=1,NPOINC
         PREAST(IPOINC)=PREAS(IPOINC)
         TGAPST(IPOINC)=TGAPS(IPOINC)
        END DO
       ENDIF
      ENDIF
C
      IF(ITERMG.GT.0.OR.ITERMD.GT.0) THEN
       DO IPOINC=1,NPOINC
        DO IDOFN=1,NDOFN
         ITOTV=(IPOINC-1)*NDOFN+IDOFN
         DISPLT(ITOTV)=DISTO(ITOTV,1)
        END DO
       END DO
      ENDIF
C
      RETURN
      END
