      SUBROUTINE PROPMIC3(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 3: ALUMINIUM ALLOYS MODEL
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** ALLOY COMPOSITION
C
      NPRINT=1
      CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'COMPO') THEN
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SILIC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC3: NO SILICON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0.OR.PARAMS(1).GT.100.0)
     .  CALL RUNENDS('PROPMIC3: WRONG SILICON COMPOSITION')
       WRITE(LURESS,810) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'ANTIM') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC3: NO ANTIMONIUM CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0.OR.PARAMS(1).GT.100.0)
     .  CALL RUNENDS('PROPMIC3: WRONG ANTIMONIUM COMPOSITION')
       WRITE(LURESS,811) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC3: NO COMPOSITION CARD')
      ENDIF
C
C**** EQUILIBRIUM DIAGRAM PARAMETERS
C
      CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'EQUIL') THEN
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'EUTEC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC3: NO EUTECTIC SILICON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0.OR.PARAMS(1).GT.100.0)
     .  CALL RUNENDS('PROPMIC3: WRONG EUTECTIC SILICON COMPOSITION')
       WRITE(LURESS,812) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'LIQUI') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        NLICO=INT(PARAMS(1))
       ELSE
        CALL RUNENDS('PROPMIC3: NO LIQUIDUS COMPOS.-TEMPERATURE CARD')
       ENDIF
       IF(NLICO.LT.2.OR.NLICO.GT.50)
     .  CALL RUNENDS('PROPMIC3: WRONG LIQUIDUS COMPOS.-TEMP. POINTS')
C
       WRITE(LURESS,813)
       WRITE(LURESS,809)
       NPOI1T=NPOI2T+1
       DO ILICO=1,NLICO
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2)
       ENDDO
       DO IPROPT=NPOI1T,NPOI2T-2,2
        IF(PROPSS(IPROPT+1).GT.PROPSS(IPROPT+3))
     .   CALL RUNENDS('PROPMIC3: TAKE CARE OF TEMPERATURE ORDER')
       ENDDO
       DO IPROPT=NPOI1T,NPOI2T,2
        WRITE(LURESS,814) PROPSS(IPROPT),PROPSS(IPROPT+1)
       ENDDO
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'PARTI') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        PARCO=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC3: NO PARTITION COEFFICIENT CARD')
       ENDIF
       IF(PARCO.LT.0.0)
     .  CALL RUNENDS('PROPMIC3: WRONG PARTITION COEFFICIENT')
       WRITE(LURESS,815) PARCO
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC3: NO EQUIL. DIAGRAM PARAM. CARD')
      ENDIF
C
C**** DENDRITIC SOLIDIFICATION
C
      CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'DENDR') THEN
C
C**** NUCLEATION PROPERTIES
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'NUCLE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IMNUC=INT(PARAMS(1))
       ELSE
        CALL RUNENDS('PROPMIC3: NO NUCLEATION CARD')
       ENDIF
       IF(IMNUC.LT.0.OR.IMNUC.GT.2)
     .  CALL RUNENDS('PROPMIC3: WRONG NUCLEATION MODEL')
C
       WRITE(LURESS,820) IMNUC
       WRITE(LURESS,809)
C
       IF(IMNUC.EQ.1.OR.IMNUC.EQ.2) THEN
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'AVERA') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         TEMAV=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO AVERAGE UNDERCOOLING CARD')
        ENDIF
        IF(TEMAV.LT.0.0.OR.TEMAV.GT.100.0)
     .   CALL RUNENDS('PROPMIC3: WRONG AVERAGE UNDERCOOLING')
        WRITE(LURESS,821) TEMAV
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'STAND') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         TEMDE=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3:NO STANDARD DEVIATION UNDERCOOL. CARD')
        ENDIF
        IF(TEMDE.LE.0.0.OR.TEMDE.GT.100.0)
     .   CALL RUNENDS('PROPMIC3: WRONG STANDARD DEVIATION UNDERCOOLING')
        WRITE(LURESS,822) TEMDE
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'MAXIM') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         GRDEM=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO MAXIMUM GRAIN DENSITY CARD')
        ENDIF
        IF(GRDEM.LT.0.0)
     .   CALL RUNENDS('PROPMIC3: WRONG MAXIMUM GRAIN DENSITY')
        WRITE(LURESS,823) GRDEM
        WRITE(LURESS,809)
       ENDIF                 ! imnuc.eq.1
C
C**** GROWTH PROPERTIES
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'GROWT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IMGRO=INT(PARAMS(1))
       ELSE
        CALL RUNENDS('PROPMIC3: NO GROWTH CARD')
       ENDIF
       IF(IMGRO.LT.1.OR.IMGRO.GT.5)
     .  CALL RUNENDS('PROPMIC3: WRONG GROWTH MODEL')
C
       WRITE(LURESS,824) IMGRO
       WRITE(LURESS,809)
C
       IF(IMGRO.EQ.1.OR.IMGRO.EQ.2.OR.IMGRO.EQ.3.OR.IMGRO.EQ.4.OR.
     .    IMGRO.EQ.5) THEN
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'RADIU') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         NRAUN=INT(PARAMS(1))
        ELSE
         CALL RUNENDS('PROPMIC3: NO RADIUS-UNDERCOOLING CARD')
        ENDIF
        IF(NRAUN.LT.2.OR.NRAUN.GT.50)
     .   CALL RUNENDS('PROPMIC3: WRONG RADIUS-UNDERCOOLING POINTS')
C
        WRITE(LURESS,825)
        WRITE(LURESS,809)
        NPOI1T=NPOI2T+1
        DO IRAUN=1,NRAUN
         CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)
        ENDDO
        DO IPROPT=NPOI1T,NPOI2T-2,2
         IF(PROPSS(IPROPT+1).GT.PROPSS(IPROPT+3))
     .    CALL RUNENDS('PROPMIC3: TAKE CARE OF UNDERCOOLING ORDER')
        ENDDO
        DO IPROPT=NPOI1T,NPOI2T,2
         WRITE(LURESS,814) PROPSS(IPROPT),PROPSS(IPROPT+1)
        ENDDO
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'LIQUI'.OR.WORDSS(1).EQ.'NON_E') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         DIFLI=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO LIQUIDUS DIFFUSIVITY CARD')
        ENDIF
        IF(DIFLI.LT.0.0)
     .   CALL RUNENDS('PROPMIC3: WRONG LIQUIDUS DIFFUSIVITY')
        WRITE(LURESS,826) DIFLI
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'LATEN') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         HENER=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO DENDRITIC LATENT HEAT CARD')
        ENDIF
        IF(HENER.LT.0.0)
     .   CALL RUNENDS('PROPMIC3: WRONG DENDRITIC LATENT HEAT VALUE')
        WRITE(LURESS,827) HENER
        WRITE(LURESS,809)
       ENDIF                 ! imgro.eq.1.or....
      ELSE
       CALL RUNENDS('PROPMIC3: NO DENDRITIC SOLIDIFICATION CARD')
      ENDIF
C
C**** EUTECTIC SOLIDIFICATION
C
      CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'EUTEC') THEN
C
C**** NUCLEATION PROPERTIES
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'NUCLE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IMNUCE=INT(PARAMS(1))
       ELSE
        CALL RUNENDS('PROPMIC3: NO NUCLEATION CARD')
       ENDIF
       IF(IMNUCE.LT.0.OR.IMNUCE.GT.2)
     .  CALL RUNENDS('PROPMIC3: WRONG NUCLEATION MODEL')
C
       WRITE(LURESS,830) IMNUCE
       WRITE(LURESS,809)
C
       IF(IMNUCE.EQ.1.OR.IMNUCE.EQ.2) THEN
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'AVERA') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         TEMAVE=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO AVERAGE UNDERCOOLING CARD')
        ENDIF
        IF(TEMAVE.LT.0.0.OR.TEMAVE.GT.100.0)
     .   CALL RUNENDS('PROPMIC3: WRONG AVERAGE UNDERCOOLING')
        WRITE(LURESS,831) TEMAVE
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'STAND') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         TEMDEE=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3:NO STANDARD DEVIATION UNDERCOOL. CARD')
        ENDIF
        IF(TEMDEE.LE.0.0.OR.TEMDEE.GT.100.0)
     .   CALL RUNENDS('PROPMIC3: WRONG STANDARD DEVIATION UNDERCOOLING')
        WRITE(LURESS,832) TEMDEE
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'MAXIM') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         GRDEME=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO MAXIMUM GRAIN DENSITY CARD')
        ENDIF
        IF(GRDEME.LT.0.0)
     .   CALL RUNENDS('PROPMIC3: WRONG MAXIMUM GRAIN DENSITY')
        WRITE(LURESS,833) GRDEME
        WRITE(LURESS,809)
       ENDIF                 ! imnuc.eq.1
C
C**** GROWTH PROPERTIES
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'GROWT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IMGROE=INT(PARAMS(1))
       ELSE
        CALL RUNENDS('PROPMIC3: NO GROWTH CARD')
       ENDIF
       IF(IMGROE.LT.1.OR.IMGROE.GT.6)
     .  CALL RUNENDS('PROPMIC3: WRONG GROWTH MODEL')
C
       WRITE(LURESS,834) IMGROE
       WRITE(LURESS,809)
C
       IF(IMGROE.EQ.1.OR.IMGROE.EQ.2.OR.IMGROE.EQ.3.OR.
     .    IMGROE.EQ.4.OR.IMGROE.EQ.5.OR.IMGROE.EQ.6) THEN
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'RADIU') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         NRAUNE=INT(PARAMS(1))
        ELSE
         CALL RUNENDS('PROPMIC3: NO RADIUS-UNDERCOOLING CARD')
        ENDIF
        IF(NRAUNE.LT.2.OR.NRAUNE.GT.50)
     .   CALL RUNENDS('PROPMIC3: WRONG RADIUS-UNDERCOOLING POINTS')
C
        WRITE(LURESS,835)
        WRITE(LURESS,809)
        NPOI1T=NPOI2T+1
        DO IRAUN=1,NRAUNE
         CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)
        ENDDO
        DO IPROPT=NPOI1T,NPOI2T-2,2
         IF(PROPSS(IPROPT+1).GT.PROPSS(IPROPT+3))
     .    CALL RUNENDS('PROPMIC3: TAKE CARE OF UNDERCOOLING ORDER')
        ENDDO
        DO IPROPT=NPOI1T,NPOI2T,2
         WRITE(LURESS,814) PROPSS(IPROPT),PROPSS(IPROPT+1)
        ENDDO
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'LATEN') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         HENERE=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC3: NO EUTECTIC LATENT HEAT CARD')
        ENDIF
        IF(HENER.LT.0.0)
     .   CALL RUNENDS('PROPMIC3: WRONG EUTECTIC LATENT HEAT VALUE')
        WRITE(LURESS,836) HENERE
        WRITE(LURESS,809)
       ENDIF                 ! imgro.eq.1.or....
      ELSE
       CALL RUNENDS('PROPMIC3: NO EUTECTIC SOLIDIFICATION CARD')
      ENDIF
C
C**** NUMERICAL STRATEGY PARAMETERS
C
      CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'NUMER') THEN
       WRITE(LURESS,860)
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TEMPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IFPCDT=INT(PARAMS(1))
        IF(IFPCDT.LT.1.OR.IFPCDT.GT.5)
     .   CALL RUNENDS('PROPMIC3: WRONG IFPCDT VALUE')
        WRITE(LURESS,861) IFPCDT
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC3: NO TEMPERATURE DERIVATIVE FORM OF FL')
       ENDIF
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'FRACT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IAFLOJ=INT(PARAMS(1))
        WRITE(LURESS,862) IAFLOJ
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC3: NO FRACTION CORRECTION CARD')
       ENDIF
C
       CALL LISTENS('PROPMIC3',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SUBIN') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        NSUGUEM=INT(PARAMS(1))
        WRITE(LURESS,863) NSUGUEM
        WRITE(LURESS,809)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2)
        EXTGUE=PARAMS(2)
        WRITE(LURESS,864) EXTGUE
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC3: NO SUBINCREMENTATION CARD')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC3: NO NUMERICAL STRATEGY CARD')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA3S=1
      IPLLLS(INUPM)=3
C
      RETURN
  809 FORMAT(/)
C
  810 FORMAT(3X,'SILICON CONTENT         =',E15.6)
  811 FORMAT(3X,'ANTIMONIUM CONTENT      =',E15.6)
C
  812 FORMAT(3X,'EUTECTIC SILICON CONTENT=',E15.6)
  813 FORMAT(3X,'LIQUIDUS COMPOSITION VS TEMPERATURE CURVE')
  814 FORMAT(E15.6,10X,E15.6)
  815 FORMAT(3X,'PARTITION COEFFICIENT   =',E15.6)
C
  820 FORMAT(3X,'DENDRITIC NUCLEATION MODEL    =',I5)
  821 FORMAT(3X,'AVERAGE UNDERCOOLING    =',E15.6)
  822 FORMAT(3X,'STANDARD DEVIATION UND. =',E15.6)
  823 FORMAT(3X,'MAXIMUM GRAIN DENSITY   =',E15.6)
  824 FORMAT(3X,'DENDRITIC GROWTH MODEL        =',I5)
  825 FORMAT(3X,'RADIUS RATE VS UNDERCOOLING CURVE')
  826 FORMAT(3X,'LIQUIDUS DIFFUSIVITY    =',E15.6)
  827 FORMAT(3X,'LATENT HEAT             =',E15.6)
C
  830 FORMAT(3X,'EUTECTIC NUCLEATION MODEL     =',I5)
  831 FORMAT(3X,'AVERAGE UNDERCOOLING    =',E15.6)
  832 FORMAT(3X,'STANDARD DEVIATION UND. =',E15.6)
  833 FORMAT(3X,'MAXIMUM GRAIN DENSITY   =',E15.6)
  834 FORMAT(3X,'EUTECTIC GROWTH MODEL         =',I5)
  835 FORMAT(3X,'RADIUS RATE VS UNDERCOOLING CURVE')
  836 FORMAT(3X,'LATENT HEAT             =',E15.6)
C
  860 FORMAT(3X,'NUMERICAL STRATEGY PARAMETERS')
  861 FORMAT(3X,'TEMPERATURE DERIVATIVE FORM OF FL=',I5)
  862 FORMAT(3X,'FRACTION CORRECTION FORM         =',I5)
  863 FORMAT(3X,'MAXIMUM NUMBER OF SUBINCREMENTS  =',I5)
  864 FORMAT(3X,'SUBINCREMENTATION FACTOR         =',E15.6)
      END
