      SUBROUTINE POSTSO(DISIT,DSOLD,REFOR,RFOLD,VVECT,WVECT)
C***********************************************************************
C
C**** THIS ROUTINE MODIFIES THE ITERATIVE DISPLACEMENTS IF A 
C     SECANT-NEWTON OR QUASI-NEWTON METHOD IS USED
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      DIMENSION DISIT(*), DSOLD(*), REFOR(*), RFOLD(*)
      DIMENSION VVECT(*), WVECT(*)
C
C**** MODIFY ITERATIVE DISPLACEMENTS FOR SECANT-NEWTON METHOD
C
      CALL SECANT(DISIT,DSOLD,REFOR,RFOLD)
C
C**** MODIFY ITERATIVE DISPLACEMENTS FOR QUASI-NEWTON METHOD ( BFGS )
C
      IF((LACCE.EQ.3).AND.IITER.GT.1.AND.KARCL.EQ.0)
     .  CALL BFGSUP(DISIT,REFOR,VVECT,WVECT)
C
      IF(LACCE.LE.1) RETURN
C
C**** STORE DISIT & REFOR IN ALLOCATED SPACE
C
      DO ITOTV=1,NTOTV
        DSOLD(ITOTV)=DISIT(ITOTV)
        RFOLD(ITOTV)=REFOR(ITOTV)
      ENDDO
C
      RETURN
      END
