      SUBROUTINE SHAFUR(EXISP,ETASP,EZETA,NDIME,NNODE,NGAUR,
     .                  NQUTR,SHAPE)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE "REDUCED" SHAPE FUNCTIONS FOR
C     LINEAR AND QUADRATIC ISOPARAMETRIC ELEMENTS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION SHAPE(*)
C
      GOTO(1,2,3), NDIME
    1 CALL RUNEND('ERROR IN SHAFUR WITH NDIME=1')
c     CALL SHAPR1(EXISP,NDIME,NNODE,NGAUR,NQUTR,SHAPE)
      RETURN
    2 CALL SHAPR2(EXISP,ETASP,NDIME,NNODE,NGAUR,NQUTR,SHAPE)
      RETURN
    3 CALL SHAPR3(EXISP,ETASP,EZETA,NDIME,NNODE,NGAUR,NQUTR,SHAPE)
      RETURN
      END
