      SUBROUTINE ROTATE(IELEM,NDIME,NSTRS,PROPS,RMAT1,RMAT2)
C***********************************************************************
C
C**** THIS ROUTINE CALCULATES THE CARTESIAN AND STRESS TENSOR
C     ROTATION MATRIX
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION PROPS(*), RMAT1(NDIME,*), RMAT2(NSTRS,*)
      DIMENSION TABPO(3)
C
      SAVE KOUNT
C
      DATA TWOPI/6.283185307179586/
      DATA KOUNT/0/
C
C     IF(KOUNT.EQ.0) WRITE(7,900)
C     KOUNT=1
C
C     WRITE(7,905) IELEM
C
C**CALCULATE THE CARTESIAN ROTATION MATRIX 
C
      FACTOR=TWOPI/360.D00
      TABPO(1)=PROPS(38)*FACTOR
      TABPO(2)=PROPS(39)*FACTOR
      TABPO(3)=PROPS(40)*FACTOR
C
      CALL RMATR1(NDIME,TABPO,RMAT1)
C
C     WRITE(7,935) 
C     WRITE(7,940)(JDIME,JDIME=1,NDIME)
C     DO 20 IDIME=1,NDIME
C  20 WRITE(7,945) IDIME,(RMAT1(IDIME,JDIME),JDIME=1,NDIME)
C
C**CALCULATE THE TENSOR ROTATION MATRIX 
C
      CALL RMATR2(NDIME,NSTRS,RMAT1,RMAT2)
C
C     WRITE(7,950)
C     WRITE(7,955)(JSTRS,JSTRS=1,NSTRS)
C     DO 30 ISTRS=1,NSTRS
C   30 WRITE(7,960) ISTRS,(RMAT2(ISTRS,JSTRS),JSTRS=1,NSTRS)
C
      RETURN 
C  900 FORMAT(//10X,'ROTATION MATRICES FOR ORTHOTROPIC ELEMENTS',//)
C  905 FORMAT(2X,' ELEMENT NO. ',I5)
C  935 FORMAT(/,15X,' CARTESIAN ROTATION MATRIX ')
C  940 FORMAT(6X,3('      L(',I1,')'))
C  945 FORMAT(2X,'L(',I1,')',3F10.6)
C  950 FORMAT(/,15X,' STRESS TENSOR ROTATION MATRIX')
C  955 FORMAT(16X,9(' SIGMA(',I1,')'))
C  960 FORMAT(2X,'SIGMA(',I1,')',9F10.6)
      END
