      SUBROUTINE PLCURV(NINDI,PREY,PEND,CAPAP,GEN,SIKMA,SIKPI,
     .                  CAPPI,HARD0,NICUR)
C**************************************************************
C
C**   ESTA RUTINA CONTIENE LAS FUNCIONES DE ENDURECIMIENTO
C     EN TENSIONES EQUIVALENTE, Y CALCULA ADEMAS LA PENDIENTE 
C                        DE DICHAS CURVAS
C**************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C 
      GO TO (10,20,30,40,50,60) NINDI
 
C***  FUNCION DE  C- CAPA --> LINEAL
C***              C- EPSI --> EXPONENCIAL

   10 CALL PLEQF1(CAPAP,PEND,PREY,SIKMA,NICUR,HARD0,GEN)

      GOTO 1000

C***  FUNCION DE  C- CAPA --> EXPONENCIAL
C***              C- EPSI --> POLINOMICA

   20 CALL PLEQF2(CAPAP,PEND,PREY,SIKMA,SIKPI,CAPPI)
 
      GOTO 1000
 
C***  FUNCION DE  C- CAPA --> POLINOMICA CUADRATICA Y CUBICA
C***              C- EPSI --> POLINOMICA DE MAYOR ORDEN

   30 CALL PLEQF3(CAPAP,PEND,PREY,SIKMA,SIKPI,CAPPI)

      GOTO 1000

C***  FUNCION DE  C- CAPA --> POLINOMICA
C***              C- EPSI --> LINEAL

   40 CALL PLEQF4(CAPAP,PEND,PREY,SIKMA,HARD0,NICUR,GEN)

      GOTO 1000

C***  FUNCION DE  C- CAPA --> POLINOMICA
C***              C- EPSI --> LINEAL

   50 CALL PLEQF5(CAPAP,PREY,PEND,SIKPI,SIKMA,2)

      GOTO 1000

C***  FUNCION DE  C- CAPA --> PARA LA PARTE DE COMPRESION DE LOS
C***                ELEMENTOS DE FRICCION

   60 CALL PLEQF6(CAPAP,PREY,PEND,SIKMA)

      GOTO 1000

 1000 RETURN
      END
