      SUBROUTINE LIHEATX(DSTRAT,TSTRAT,DMATXT,CONVET,NDIMET,NSTR1T,
     .                   NNODET,NDOFCT,CARTDT,FPCHLT,NFPCH,IFPCH,KDYNAT)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE CONVECTIVE TERM
C     (PHASE-CHANGE FUNCTION GRADIENT * DENSITY*LATENT HEAT * VELOCITY)
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
C
      DIMENSION DSTRAT(*),        TSTRAT(*),
     .          DMATXT(NSTR1T,*)
      DIMENSION CARTDT(NDIMET,*), FPCHLT(NFPCH,*)
C
C**** CALCULATE THE TOTAL TEMPERATURE GRADIENT IN TSTRAT
C
      DO IDIMET=1,NDIMET
       TSTRAT(IDIMET)=0.0D0
       DO IEVABT=1,NNODET
        TSTRAT(IDIMET)=TSTRAT(IDIMET)+CARTDT(IDIMET,IEVABT)*
     .                 FPCHLT(IFPCH,IEVABT)
       END DO
      END DO
C
C**** CALCULATE THE INCREMENTAL TEMPERATURE GRADIENT IN DSTRAT
C
      DO IDIMET=1,NDIMET
       DSTRAT(IDIMET)=0.0D0
       IF(KDYNAT.EQ.1) THEN
        DO IEVABT=1,NNODET
         DSTRAT(IDIMET)=DSTRAT(IDIMET)+CARTDT(IDIMET,IEVABT)*
     .                  FPCHLT(IFPCH+1,IEVABT)*DTIMET
        END DO
       ENDIF
      END DO
C
C**** CALCULATE THE CONVECTIVE TERM
C
      CONVET=0.0D0
      DO IDIMET=1,NDIMET
       CONVET=CONVET+DMATXT(IDIMET,1)*TSTRAT(IDIMET)
      ENDDO
C
      IF(KDYNAT.EQ.1) THEN     ! transient
       IF(KINTET.EQ.1) THEN    ! Euler method
        CONVET=0.0D0
        DO IDIMET=1,NDIMET
         CONVET=CONVET+DMATXT(IDIMET,1)*
     .         (TALFAT*TSTRAT(IDIMET)+
     .         (1.0D+00-TALFAT)*(TSTRAT(IDIMET)-DSTRAT(IDIMET)))
        ENDDO
       ENDIF
      ENDIF
C
      RETURN
      END
