
      SUBROUTINE BRIBAC(DVPLA,EHIST,KGAUS,NBACK,NCRIT,NTYPE,PROPS,
     .                  SGTOT,VSTOT)
C***********************************************************************
C
C****THIS ROUTINE BRINGS BACK THE STRESS POINT ON THE SURFACE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EHIST(*), PROPS(*), SGTOT(*)
C
      IF(NCRIT.EQ.3.OR.NCRIT.EQ.4)GOTO 5
C
C***PERFECTLY PLASTIC MATERIALS
C
      CALL BRIBA0(NCRIT,NTYPE,PROPS,SGTOT)
C
      RETURN
C
C***CAM-CLAY CHOOSE THE CRITERIA
C
    5 GOTO(10,20),NBACK
C
C***CALCULATE THE ELLIPSE PASSING THROUGH THE CURRENT STRESS POINT
C
   10 CALL BRIBA1(EHIST,KGAUS,NCRIT,NTYPE,PROPS,SGTOT)
C
      RETURN
C
C***CALCULATE THE ELLIPSE ON THE BASIS OF THE VOLUMTRIC PLASTIC STRAIN
C   BRING BACK THE STRESS POINT ON IT
C
   20 CALL BRIBA2(DVPLA,EHIST,NCRIT,NTYPE,PROPS,SGTOT,VSTOT)
C
      RETURN
      END
