      SUBROUTINE MODULM0(LNODS,MATNO,PROEL,PROPS,COORD,HTLOD,
     .                   IFFIX,PRESC,RLOAD,RLOAH,FICTO,TFICT,
     .                   DISIT,DISPR,DISTO,HEADS,REFOR,TLOAD,
     .                   LPNTN,ELDAT,ELPRE,ELVAR,ELMAT,TEMPN,
     .                   DTEMP,INFRI,COFRI,PWORK,PREAS,TGAPS,
     .                   VNORM,FPCHA,LACTI,NOPRF,PRESF,PREHF,
     .                   VANIS,WORK1)
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
C
C**** MECHANICAL VARIABLES
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
      INCLUDE 'inpo_om.f'
C
C**** MECHANICAL VARIABLES
C
      DIMENSION LNODS(NNODE,NELEM), MATNO(NELEM),
     .          PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS),
     .          COORD(NDIME,NPOIN), HTLOD(NHLOD,NSUBF,NFUNC)
      DIMENSION IFFIX(NTOTV,2),     PRESC(NTOTV,2),
     .          RLOAD(NTOTV),       RLOAH(NTOTV,NFUNC),
     .          FICTO(NFUNC),       TFICT(NFUNC)
      DIMENSION DISIT(NTOTV,2),     DISPR(NTOTV,NDISR),
     .          DISTO(NTOTV,NDISO), HEADS(NPOIN,4),
     .          REFOR(NTOTV,2),     TLOAD(NTOTV,2)
      DIMENSION LPNTN(NPOIN),       ELDAT(NDATA),
     .          ELPRE(NPREV),       ELVAR(NSTAT),
     .          ELMAT(NMATX),       TEMPN(NPOIN,2),
     .          DTEMP(NPOIN)
      DIMENSION INFRI(NPOIN),       COFRI(NSKEW,NDIME,*),
     .          PWORK(NPOIN,2),     PREAS(NPREA,NPOIN),
     .          TGAPS(NPOIN),       VNORM(NTOTV),
     .          FPCHA(NFPCH,NPOIN), LACTI(NELEM)
      DIMENSION NOPRF(NNODE,NELEM), PRESF(NNODE,NDIME,NELEM),
     .          PREHF(NNODE,NDIME,NELEM,NFUNC),
     .          VANIS(NANIV,NANIC,NELEM)
C      DIMENSION WORK1(*)
      REAL*8, ALLOCATABLE, INTENT(INOUT) :: WORK1(:)
      INTERFACE
        INCLUDE 'interv.inc'
        INCLUDE 'iterat.inc'
        INCLUDE 'tmstep.inc'
      END INTERFACE
C
C**** GLOBAL CONVERGENCE FOR OUTPUT
C
      NCKGLO=0
C
C***********************************************************************
C
C**** START
C
C***********************************************************************
C
C**** START THE COMPUTATIONS FOR THE MECHANICAL PROBLEM
C
      CALL STARTS(DISTO,DISPR,ELDAT,ELPRE,ELVAR,ELMAT,
     .            HEADS,HTLOD,IFFIX,LNODS,LPNTN,MATNO,
     .            PROEL,PROPS,REFOR,RLOAD,TLOAD,COORD,
     .            TEMPN,DTEMP,PWORK,PREAS,TGAPS,VNORM,
     .            FPCHA,LACTI,PRESF,VANIS,WORK1,    1)
C
C**** CONTINUES THE COMPUTATIONS FOR THE MECHANICAL PROBLEM
C
      CALL STARTS(DISTO,DISPR,ELDAT,ELPRE,ELVAR,ELMAT,
     .            HEADS,HTLOD,IFFIX,LNODS,LPNTN,MATNO,
     .            PROEL,PROPS,REFOR,RLOAD,TLOAD,COORD,
     .            TEMPN,DTEMP,PWORK,PREAS,TGAPS,VNORM,
     .            FPCHA,LACTI,PRESF,VANIS,WORK1,    2)
C
C**** LOOP ON TIME INTERVALS (FOR MECHANICAL PROBLEM)
C
      DO WHILE (.TRUE.)                                
C
C**** START TIME INTERVAL FOR THE MECHANICAL PROBLEM
C
       CALL INTERV(DISTO,ELDAT,ELPRE,ELVAR,ELMAT,HTLOD,IFFIX,
     .             PRESC,LNODS,LPNTN,MATNO,PROEL,PROPS,RLOAD,
     .             RLOAH,FICTO,TFICT,INFRI,COFRI,COORD,HEADS,
     .             TLOAD,REFOR,PWORK,TGAPS,PREAS,LACTI,NOPRF,
     .             PREHF,VANIS,WORK1,
     .             NEQNS)
C
C**** INDEX TO PRINT INITIAL CONDITIONS
C
       IPRCO=IPRCO+1
C
C**** LOOP OVER TIME STEPS (FOR MECHANICAL PROBLEM)
C
       DO ISTEP = KSTEP,NSTEP
C
C**** ADVANCE ON TIME AND PREDICT RESPONSE FOR THE MECHANICAL PROBLEM
C
        DO ISSTEP=1,NSSTEP             !  SUBINCREMENTS
C
         CALL TMSTEP(DISIT,DISPR,DISTO,ELDAT,ELPRE,ELVAR,ELMAT,
     .               HEADS,HTLOD,IFFIX,PRESC,LNODS,MATNO,PROEL,
     .               PROPS,REFOR,RLOAD,RLOAH,FICTO,TFICT,TLOAD,
     .               TEMPN,DTEMP,INFRI,COFRI,PWORK,PREAS,TGAPS,
     .               VNORM,COORD,FPCHA,LACTI,LPNTN,NOPRF,PRESF,
     .               PREHF,VANIS,WORK1,
     .               NEQNS)
C
C**** LOOP ON ITERATIONS FOR THE MECHANICAL PROBLEM
C
         DO WHILE
     .    ((NCHEK.NE.0).AND.(IITER.LE.MITER))
C
C**** ITERATIVE CORRECTION FOR THE MECHANICAL PROBLEM
C
          CALL ITERAT(DISIT,DISPR,DISTO,ELDAT,ELPRE,ELVAR,ELMAT,
     .                HEADS,IFFIX,PRESC,LNODS,MATNO,PROEL,PROPS,
     .                REFOR,RLOAD,FICTO,TLOAD,TEMPN,DTEMP,INFRI,
     .                COFRI,PWORK,PREAS,TGAPS,VNORM,LPNTN,COORD,
     .                FPCHA,LACTI,NOPRF,PRESF,VANIS,WORK1,
     .                NEQNS)
C
         ENDDO
C
         IF(NCHEK.NE.0)
     .    CALL RUNEND(' NOT CONVERGED                    ') 
C
C**** CHECK FOR ANALYSIS TERMINATION FOR THE MECHANICAL PROBLEM
C
         IF(NSSTEP.GT.1)
     .    CALL FINISH(DISPR,DISTO,ELPRE,ELVAR,HEADS,HTLOD,IFFIX,
     .                REFOR,RLOAD,TLOAD,INFRI,COFRI,LACTI)
C
        ENDDO             ! LOOP OF SUBINCREMENTS
C
C***********************************************************************
C
C**** FINISH
C
C***********************************************************************
C
C**** CHECK FOR ANALYSIS TERMINATION FOR THE MECHANICAL PROBLEM
C
        IF(NSSTEP.EQ.1)
     .   CALL FINISH(DISPR,DISTO,ELPRE,ELVAR,HEADS,HTLOD,IFFIX,
     .               REFOR,RLOAD,TLOAD,INFRI,COFRI,LACTI)
C
       ENDDO                                 ! END OF TIME STEPS LOOP
C
      ENDDO                                  ! END OF TIME INTERVAL 
C
      END
