      SUBROUTINE FUNLOD(FACTO,HTLOD,NSUBF,NFUNC,NHLOD,TFACT,TTIME)
C***********************************************************************
C
C****THIS ROUTINE COMPUTES THE TOTAL AND INCREMENTAL LOAD FACTOR
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION HTLOD(NHLOD,NSUBF,*), FACTO(NFUNC), TFACT(NFUNC)
C
      DO IFUNC=1,NFUNC
       ITYPE=INT(HTLOD(1,1,IFUNC))    
       TFOLD=TFACT(IFUNC)
       TFNEW=0.0D0
       ISUBF=1
       DO WHILE (ITYPE.NE.0.AND.ISUBF.LE.NSUBF)
C
        FACTI=0.0D0
        IF(ITYPE.EQ.1) THEN
         CALL FUNLO1(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.2) THEN
         CALL FUNLO2(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.3) THEN
         CALL FUNLO3(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.4) THEN
         CALL FUNLO4(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.5) THEN
         CALL FUNLO5(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.6) THEN
         CALL FUNLO6(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.7) THEN
         CALL FUNLO7(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.8) THEN
         CALL FUNLO8(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
        ELSE IF(ITYPE.EQ.9) THEN
         CALL FUNLO9(FACTI,HTLOD(1,ISUBF,IFUNC),TTIME)
C
        ELSE IF(ITYPE.EQ.101) THEN
        ELSE IF(ITYPE.EQ.102) THEN
        ELSE IF(ITYPE.EQ.103) THEN
        ENDIF
C
        TFNEW=TFNEW+FACTI
        ISUBF=ISUBF+1
        ITYPE=INT(HTLOD(1,ISUBF,IFUNC))
       ENDDO
       FACTO(IFUNC)=TFNEW-TFOLD
      ENDDO
C
      RETURN
      END
