      SUBROUTINE DEGRAD(SIGMA,DESIG,PRESG,EBASE,DMATX,
     .                  PROPS,SGTOT,DMTEP,ALENG,KUNL1,
     .                  DMATE,STRAN,VADEG,DSTRA,YIEPR,
     .                  SIGM0,ENELI,DELMU,DM,ANGFI,ANGSI,
     .                  DMATP,ALFAT,BETAT,GAMAT,RETEN,
     .                  RETEP,CCERO,RODEN,A1COE,A2COE)  
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES TOTAL STRESSES FOR ELASTO/DAMAGE MATERIALS
C                            NCRIT= 31 -35
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'auxl_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'prob_om.f'

      DIMENSION DESIG(*),DMATX(NSTRS,*), EBASE(11),SIGM0(6),
     .          PRESG(*),PROPS(*),   SGTOT(*), 
     .          SIGMA(*), DMTEP(*),DSTRA(*),
     .          STRAN(*),DMATE(6,6),AUX(6),DM(6,6),
     .          DMATP(6,6)
C
      DIMENSION VECTF(6),DEVIA(6),DS(6),VCONV(120)
      DIMENSION BACKS(6)
C
C*** INICIALIZACION
C
      DO 180 ISTRS=1,NSTRS
  180 SGTOT(ISTRS)=SIGMA(ISTRS)
C
      DELMU=0.0
C
C***  CALCULO DE INVARIANTES Y DE LA TENSION EFECTIVA 
C 
      CALL PLINVA(NCRIT,PROPS,NTYPE,SIGM0,ANGFI,EBASE(7),
     .            PMEAN,VARJ2,VARJ3,DEVIA,STEFF,SMAXS,THETA,
     .            DFTEQ,DFAFI,YIELD,NSTR1,ALFAT,BETAT,   ! llamaba roden
     .            GAMAT,RETEN,A1COE,A2COE,BACKS)
C
C***  VERIFICACION DE ESTADO ELASTICO O DE DEGRADACION
C
        ESCUR=(YIELD)-DABS(EBASE(8))
        IF(ESCUR.LE.0.0) GOTO 60 ! caso elastico
C 
C***  CASO DE DANO (tension previa e incremento de tension efectiva)
C 
      KUNL1=0
      TENPR=EBASE(8)
      YIELP=YIELD-YIEPR
      YIEPR=YIELD
C
C*** CALCULO DEL VECTOR DE FLUJO
C
c      CALL PLYIEL(VECTF,ANGFI,NCRIT,RETEN,ALFAT,
c     .            GAMAT,PROPS(48),PMEAN,VARJ2,VARJ3,DEVIA,
c     .            STEFF,SMAXS,THETA,PROPS,A1COE,A2COE)  ! NORMAL A F
C
C*** CALCULO DE PREDICCION
C
       VANEW=1.0-(EBASE(8)/YIELD)
       DELMU=VANEW-VADEG
C
C***  VARIABLES INTERNAS - PREDICCION
C       
            CAPAD=EBASE(7)
            CALL DEVARI(PROPS,ALENG,SIGM0,DELMU,CAPAD,
     .                  EBASE(8),NSTRS,ANGFI,ANGSI,YIELD,
     .                  ENELI,EBASE(1),NSTR1,RETEN,RODEN,
     .                  CCERO)
C 
C***  CALCULO DEL INCREMENTO DE LA VARIABLE DE DANO
C 
       DELMU=0.0
       DFDTE=0.0
       VANEW=1.0-(EBASE(8)/YIELD)
       DEL=VANEW-VADEG
       IF((DEL.GT.0.0).and.(VANEW.LE.1.0))THEN
        DELMU=DEL
        VADEG=VANEW
       ENDIF
C
C***  VARIABLES INTERNAS
C       
            CALL DEVARI(PROPS,ALENG,SIGM0,DELMU,EBASE(7),
     .                  EBASE(8),NSTRS,ANGFI,ANGSI,YIELD,
     .                  ENELI,EBASE(1),NSTR1,RETEN,RODEN,
     .                  CCERO)
C
C*** CALCULO DE LA TENSION DEGRADADA Y LA TENSION ACTUALIZADA
C
      DO 220 ISTR1=1,NSTR1
      SGTOT(ISTR1)=(1-VADEG)*SIGM0(ISTR1)
  220 CONTINUE
C
C***  CALCULO DE LOS INVARIANTES, con SGTOT
C
      CALL PLINVA(NCRIT,PROPS,NTYPE,SGTOT,ANGFI,EBASE(7),
     .            PMEAN,VARJ2,VARJ3,DEVIA,STEFF,SMAXS,THETA,
     .            DFTEQ,DFAFI,YIELD,NSTR1,ALFAT,BETAT, ! llamaba a roden
     .            GAMAT,RETEN,A1COE,A2COE,BACKS)
C
C***  CALCULO DE LA DERIVADA DE LA FUNCION DE DEGRADACION RESPECTO
C                       DE LA TENSION EFECTIVA
C
C      DFDTE=(EBASE(8)-TENPR)/(YIELP)
       IF(YIELP.NE.0.0)DFDTE=DELMU/YIELP
C
C***  CALCULO DEL TENSOR TANGENTE
C 
       DO 205 ISTRS=1,NSTRS
       AUX(ISTRS)=0.0
       DO 205 JSTRS=1,NSTRS
       DMATE(ISTRS,JSTRS)=(1.0-VADEG)*DMATX(ISTRS,JSTRS)
       DMATP(ISTRS,JSTRS)=DMATE(ISTRS,JSTRS)
       AUX(ISTRS)=AUX(ISTRS)+VECTF(JSTRS)*DMATX(JSTRS,ISTRS)
  205  CONTINUE
C
       DO 207 ISTRS=1,NSTRS
       DO 207 JSTRS=1,NSTRS
       DMATX(ISTRS,JSTRS)=DMATE(ISTRS,JSTRS)
       DM(ISTRS,JSTRS)=(DFDTE/(1.0-VADEG))*(AUX(ISTRS)*SGTOT(JSTRS))
  207  DMATE(ISTRS,JSTRS)=DMATE(ISTRS,JSTRS)-DM(ISTRS,JSTRS)
C
       IF(NALGO.GT.1)THEN
        IKONT=0
        DO 62 ISTRS=1,    NSTRS
        DO 62 JSTRS=ISTRS,NSTRS
        IKONT=IKONT+1
   62   DMTEP(IKONT)=DMATE(ISTRS,JSTRS)
       ENDIF
C
C*** DEFINE COMO TENSION DE PREDICCION LA TENSION OBTENIDA
C
       DO 211 ISTRS=1,NSTRS
  211  SIGMA(ISTRS)=SGTOT(ISTRS)
       RETURN

C***  CASO ELASTICO
 
   60 KUNL1=1
      RETURN
      END
