      SUBROUTINE CRKMTX(DMATX,EHIST,PROPS)
C***********************************************************************
C
C**** THIS ROUTINE COMPUTES THE D-MATRIX FOR CRACKING MATERIALS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'auxl_om.f'
C
      DIMENSION DMATX(NSTRS,*), EHIST(*), PROPS(*)
      DIMENSION DUMMY(6), TRANS(6,6)
      DATA MCRAK/3/
C
C***FIND THE NUMBER OF PREVIOUSLY EXISTING CRACKS
C
      NCRAK=0
      DO 10 ICRAK=1,MCRAK
   10 IF(EHIST(15+ICRAK).GT.0.0) NCRAK=NCRAK+1
C
      IF(NCRAK.EQ.0) RETURN
C
C***INITIALISE D-MATRIX
C
      DO 15 ISTRE=1,NSTRS
      DUMMY(ISTRE)=0.0
      DO 15 JSTRE=1,NSTRS
   15 DMATX(ISTRE,JSTRE)=0.0
C
C***BUILD D-MATRIX IN LOCAL SYSTEM
C
      CALL CRKLCL(DUMMY,NCRAK,NSTRS,PROPS,EHIST(10),EHIST(13))
C
C***TRANSFORM D-MATRIX TO GLOBAL SYSTEM
C
      CALL CRKGBL(DMATX,DUMMY,EHIST(1),TRANS,NDIME,NSTRS)
C
      RETURN
      END
