      SUBROUTINE PRO101F(ITAPET,PROPST)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MATERIAL PROPERTIES FOR THE BOUNDARY
C     INTERFACE MODEL (ELEMENT=101) FOR FILLING MATERIAL
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION PROPST(*)
C
C**** ESTABLISH SOME PARAMETERS
C
      PROPST(1)=1.0             ! ifill=1 => filling material
      NFILL=1                   ! at least one filling material
C
C**** READ & WRITE MATERIAL PROPERTIES
C
      NPRINT=0
C
C**** LOOK FOR 'ENVIRONMENTAL TEMPERATURE' CARD
C
      CALL LISTENT('PRO101T',NPRINT,ITAPET)
      PROPST(2)=0.0
      IF(WORDST(1).NE.'ENVIR')
     . CALL RUNENDT('ERROR: ENVIR. TEMP. CARD NOT FOUND')
C
      PROPST(2)=PARAMT(1)       ! IFILL=PROPST(1)
C
C**** LOOK FOR 'METAL CONVECTION COEFFICIENT CURVE' CARD
C
      CALL LISTENT('PRO101T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'CONVE')
     . CALL RUNENDT('ERROR: CONVECTION COEFF.-TEMP. CARD NOT FOUND ')
C
      IF(WORDST(2).NE.'METAL')
     . CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
C
      IF(PARAMT(1).EQ.0.0)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF CONV. COEFF. POINTS  ')
C
C**** READ 'METAL CONVECTION COEFFICIENT CURVE' BY LISTEN
C
      NPOI1T=3                  ! IFILL=PROPST(1),TENVI
      NPOI2T=NPOI1T
      PROPST(NPOI1T)=PARAMT(1)
      NLINET=INT(PARAMT(1))
      IF(NLINET.GT.20)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONV. COEFF.')
      NPRINT=1
      DO LINEAT=1,NLINET
       CALL LISTENT('PRO101T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
      WRITE(LUREST,803)
      DO IPROPT=NPOI1T+1,NPOI2T,2
       WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
      ENDDO
      WRITE(LUREST,806)
C
C**** LOOK FOR 'AIR CONVECTION COEFFICIENT CURVE' CARD
C
      CALL LISTENT('PRO101T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'CONVE')
     . CALL RUNENDT('ERROR: AIR CONVECTION COEFF.-TEMP. CARD NOT FOUND')
C
      IF(WORDST(2).NE.'AIR')
     . CALL RUNENDT('ERROR: AIR CARD NOT FOUND')
C
      IF(PARAMT(1).EQ.0.0)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF AIR CONV. COEFF. POINTS  ')
C
C**** READ 'AIR CONVECTION COEFFICIENT CURVE' BY LISTEN
C
      NPOI1T=NPOI2T+1
      NPOI2T=NPOI1T
      PROPST(NPOI1T)=PARAMT(1)
      NLINET=INT(PARAMT(1))
      IF(NLINET.GT.20)
     . CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN AIR CONV. COEFF.')
      NPRINT=1
      DO LINEAT=1,NLINET
       CALL LISTENT('PRO101T',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
      WRITE(LUREST,804)
      DO IPROPT=NPOI1T+1,NPOI2T,2
       WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
      ENDDO
      WRITE(LUREST,806)
C
C**** LOOK FOR 'END_MATERIAL' CARD
C
      NPRINT=0
      CALL LISTENT('PRO101T',NPRINT,ITAPET)
      IF(WORDST(1).NE.'END_M')
     . CALL RUNENDT('ERROR: END_MATERIAL CARD NOT FOUND   ')
      WRITE(LUREST,806)
C
C**** CONTROLS DIMENSION OF PROPST
C
      IF(NPOI2T.GT.NPROPT) THEN
       WRITE(LUREST,900) NPROPT,NPOI2T
       CALL RUNENDT('PROP05T: TOO MANY PROPERTIES TO READ')
      ENDIF
C
      RETURN
  803 FORMAT(/,'METAL CONVECTION COEF.     Vs.     TEMPERATURE',/)
  804 FORMAT(/,'AIR CONVECTION COEF.       Vs.     TEMPERATURE',/)
  805 FORMAT(E15.6,10X,E15.6)
  806 FORMAT(/)
  900 FORMAT(//,'TOO MANY MATERIAL PROPERTIES TO READ:',/,
     .      20X,'NPROP =',I5,5X,'NUMBE =',I5,/)
      END
