      SUBROUTINE LIQCOMT(COMPL,PROPST,TGAUST,NLICO,INDEX3)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES:
C
C     INDEX3=1 >> 1) LIQUIDUS TEMPERATURE FOR A GIVEN SILICON CONTENT
C                 2) EUTECTIC TEMPERATURE FOR A GIVEN EUTECTIC SILICON
C                 CONTENT
C                 3) MELTING TEMPERATURE OF A PURE METAL
C     INDEX3=2 >> LIQUID COMPOSITION (SILICON CONTENT) FOR A GIVEN
C                 TEMPERATURE
C     INDEX3=3 >> SLOPE OF THE LIQUIDUS TEMPERATURE-SILICON CONTENT
C                 CURVE FOR A GIVEN SILICON CONTENT
C
C     INDEX3=4 >> GRAIN VELOCITY AS A FUNCTION OF THE UNDERCOOLING
C                 (DENDRITIC SOLIDIFICATION)
C     INDEX3=5 >> TEMPERATURE DERIVATIVE OF GRAIN VELOCITY
C                 (DENDRITIC SOLIDIFICATION)
C
C     INDEX3=6 >> GRAIN VELOCITY AS A FUNCTION OF THE UNDERCOOLING
C                 (EUTECTIC SOLIDIFICATION)
C     INDEX3=7 >> TEMPERATURE DERIVATIVE OF GRAIN VELOCITY
C                 (EUTECTIC SOLIDIFICATION)
C
C     INDEX3=8 >> SOLIDUS TEMPERATURE FOR A GIVEN SILICON CONTENT
C
C     In these cases, bijectivity is assumed
C
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
      DIMENSION PROPST(*)
C
C**** COMPUTES THE LIQUIDUS TEMPERATURE
C
      IF(INDEX3.EQ.1) THEN
       IF(COMPL.LE.VGRO2(NLICO+1,1)) TGAUST=VGRO2(NLICO+1,2)
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(COMPL.GT.VGRO2(NLICO+I1,1).AND.COMPL.LE.VGRO2(NLICO+I2,1))
     .   TGAUST=(VGRO2(NLICO+I2,2)-VGRO2(NLICO+I1,2))/
     .          (VGRO2(NLICO+I2,1)-VGRO2(NLICO+I1,1))*
     .          (COMPL-VGRO2(NLICO+I1,1))+VGRO2(NLICO+I1,2)
       ENDDO
       IF(COMPL.GT.VGRO2(NLICO+NLICO,1)) TGAUST=VGRO2(NLICO+NLICO,2)
      ENDIF
C
C**** COMPUTES THE LIQUID COMPOSITION (SILICON CONTENT)
C
      IF(INDEX3.EQ.2) THEN
       IF(TGAUST.LE.VGRO2(1,2)) COMPL=VGRO2(1,1)
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(TGAUST.GT.VGRO2(I1,2).AND.TGAUST.LE.VGRO2(I2,2))
     .   COMPL=(VGRO2(I2,1)-VGRO2(I1,1))/
     .         (VGRO2(I2,2)-VGRO2(I1,2))*
     .         (TGAUST-VGRO2(I1,2))+VGRO2(I1,1)
       ENDDO
       IF(TGAUST.GT.VGRO2(NLICO,2)) COMPL=VGRO2(NLICO,1)
      ENDIF
C
C**** COMPUTES THE SLOPE OF THE LIQUIDUS LINE
C
      IF(INDEX3.EQ.3) THEN
       IF(COMPL.LE.VGRO2(NLICO+1,1)) TGAUST=0.0
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(COMPL.GT.VGRO2(NLICO+I1,1).AND.COMPL.LE.VGRO2(NLICO+I2,1))
     .   TGAUST=(VGRO2(NLICO+I2,2)-VGRO2(NLICO+I1,2))/
     .          (VGRO2(NLICO+I2,1)-VGRO2(NLICO+I1,1))
       ENDDO
       IF(COMPL.GT.VGRO2(NLICO+NLICO,1)) TGAUST=0.0
      ENDIF
C
C**** COMPUTES GRAIN VELOCITY (DENDRITIC)
C
      IF(INDEX3.EQ.4) THEN
       IF(TGAUST.LE.VGRO1(1,2)) COMPL=VGRO1(1,1)
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(TGAUST.GT.VGRO1(I1,2).AND.TGAUST.LE.VGRO1(I2,2))
     .   COMPL=(VGRO1(I2,1)-VGRO1(I1,1))/
     .         (VGRO1(I2,2)-VGRO1(I1,2))*
     .         (TGAUST-VGRO1(I1,2))+VGRO1(I1,1)
       ENDDO
       IF(TGAUST.GT.VGRO1(NLICO,2)) COMPL=VGRO1(NLICO,1)
      ENDIF
C
C**** COMPUTES TEMPERATURE DERIVATIVE OF GRAIN VELOCITY (DENDRITIC)
C
      IF(INDEX3.EQ.5) THEN
       IF(TGAUST.LE.VGRO1(1,2)) COMPL=0.0
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(TGAUST.GT.VGRO1(I1,2).AND.TGAUST.LE.VGRO1(I2,2))
     .   COMPL=(VGRO1(I2,1)-VGRO1(I1,1))/
     .         (VGRO1(I2,2)-VGRO1(I1,2))
       ENDDO
       IF(TGAUST.GT.VGRO1(NLICO,2)) COMPL=0.0
      ENDIF
C
C**** COMPUTES GRAIN VELOCITY (EUTECTIC)
C
      IF(INDEX3.EQ.6) THEN
       IF(TGAUST.LE.VGRO1E(1,2)) COMPL=VGRO1E(1,1)
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(TGAUST.GT.VGRO1E(I1,2).AND.TGAUST.LE.VGRO1E(I2,2))
     .   COMPL=(VGRO1E(I2,1)-VGRO1E(I1,1))/
     .         (VGRO1E(I2,2)-VGRO1E(I1,2))*
     .         (TGAUST-VGRO1E(I1,2))+VGRO1E(I1,1)
       ENDDO
       IF(TGAUST.GT.VGRO1E(NLICO,2)) COMPL=VGRO1E(NLICO,1)
      ENDIF
C
C**** COMPUTES TEMPERATURE DERIVATIVE OF GRAIN VELOCITY (EUTECTIC)
C
      IF(INDEX3.EQ.7) THEN
       IF(TGAUST.LE.VGRO1E(1,2)) COMPL=0.0
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(TGAUST.GT.VGRO1E(I1,2).AND.TGAUST.LE.VGRO1E(I2,2))
     .   COMPL=(VGRO1E(I2,1)-VGRO1E(I1,1))/
     .         (VGRO1E(I2,2)-VGRO1E(I1,2))
       ENDDO
       IF(TGAUST.GT.VGRO1E(NLICO,2)) COMPL=0.0
      ENDIF
C
C**** COMPUTES THE SOLIDUS TEMPERATURE
C
      IF(INDEX3.EQ.8) THEN
       IF(COMPL.LE.VGRO3(NLICO+1,1)) TGAUST=VGRO3(NLICO+1,2)
       DO ILICO=2,NLICO
        I1=ILICO-1
        I2=ILICO
        IF(COMPL.GT.VGRO3(NLICO+I1,1).AND.COMPL.LE.VGRO3(NLICO+I2,1))
     .   TGAUST=(VGRO3(NLICO+I2,2)-VGRO3(NLICO+I1,2))/
     .          (VGRO3(NLICO+I2,1)-VGRO3(NLICO+I1,1))*
     .          (COMPL-VGRO3(NLICO+I1,1))+VGRO3(NLICO+I1,2)
       ENDDO
       IF(COMPL.GT.VGRO3(NLICO+NLICO,1)) TGAUST=VGRO3(NLICO+NLICO,2)
      ENDIF
C
      RETURN
      END
