C=============================================================== AUXLIAR
C**** INDWORSA
      INTEGER*4       IAQUAS,IASEMS,IFIXYS,IFORCS,
     .                IFORDS,IFORWS,IGSMOS,IIPCWS,
     .                ILOSUS,IQUASS,ISETMS,ISOLVS,
     .                ISTARS,ISTIFS
C
      COMMON/INDWORSA/IAQUAS(10),IASEMS(10),IFIXYS(20),IFORCS(60),
     .                IFORDS(50),IFORWS(10),IGSMOS(50),IIPCWS(10),
     .                ILOSUS(50),IQUASS(10),ISETMS(20),ISOLVS(20),
     .                ISTARS(20),ISTIFS(50)
C--------------------------------------------------------------- AUXLIAR
C**** MEMORYSA
      INTEGER*4       IADPRS,LPRINS,IADW1S,LWOR1S,IADSOS,LSOLVS,IRELES,
     .                LBYTSS,IADDBS,LDABAS,IREL1S,LBYTBS,NBLIMS,LSTIFS
C
      COMMON/MEMORYSA/IADPRS,LPRINS,IADW1S,LWOR1S,IADSOS,LSOLVS,IRELES,
     .                LBYTSS,IADDBS,LDABAS,IREL1S,LBYTBS,NBLIMS,LSTIFS
C--------------------------------------------------------------- AUXLIAR
C**** NEWINTSA
      INTEGER*4       NEWBOS,NEWLOS,NEWSTS
C
      COMMON/NEWINTSA/NEWBOS,NEWLOS,NEWSTS
C--------------------------------------------------------------- AUXLIAR
C**** PROCESSA
      INTEGER*4       IELEMS,LMATSS,NDIMLS,NNODLS,NRULES,
     .                NGAULS,NTYPES,NCRITS,NKOSTS,NSTRES,NSTRSS,NNODSS,
     .                NQUTRS
C
      COMMON/PROCESSA/IELEMS,LMATSS,NDIMLS,NNODLS,NRULES,
     .                NGAULS,NTYPES,NCRITS,NKOSTS,NSTRES,NSTRSS,NNODSS,
     .                NQUTRS
C--------------------------------------------------------------- AUXLIAR
C**** RESIDUSA
      REAL*8          AALPHS,GZEROS,GCURNS,AACOES,BBCOES
C
      COMMON/RESIDUSA/AALPHS,GZEROS,GCURNS,AACOES,BBCOES
C--------------------------------------------------------------- AUXLIAR
C**** RSTARTSA
C**** RSTARTSB
      INTEGER*4       INITIS,IRESTS,ISAVES,ISKIPS,KTIMES,KSTEPS,KTSTES,
     .                NWPOSS,KPPCGS,KPPCNS
      REAL*8          TIMSTS,TLIMTS
C
      COMMON/RSTARTSA/INITIS,IRESTS,ISAVES,ISKIPS,KTIMES,KSTEPS,KTSTES,
     .                NWPOSS,KPPCGS,KPPCNS
      COMMON/RSTARTSB/TIMSTS,TLIMTS
C--------------------------------------------------------------- AUXLIAR
C**** RUNTIMSA
      REAL*8          CPUINS,CPUDAS,CPUSTS,CPUSFS,CPUASS,CPUSOS,CPURES,
     .                CPURSS,CPUOUS,CPURNS
C
      COMMON/RUNTIMSA/CPUINS,CPUDAS,CPUSTS,CPUSFS,CPUASS,CPUSOS,CPURES,
     .                CPURSS,CPUOUS,CPURNS
C--------------------------------------------------------------- AUXLIAR
C**** SMIPTIS
      INTEGER*4  MNU4SX,MNU4SMX
      PARAMETER (MNU4SX=400)                  ! change if necessary
      PARAMETER (MNU4SMX=11*MNU4SX+46)        ! estimated; see setdatd.f
C
      INTEGER*4     IPLASS,IPLAOS,IPLANS,IPLAMS,
     .              IPLUAS,IPLUOS,IPLLLS,IPLXXS
      INTEGER*4     NNUINS,NNUNOS
      INTEGER*4     KPLA1S,KPLA2S,KPLA3S,KPLA4S,KPLA5S,
     .              KPLA6S,KPLA7S,KPLA8S,KPLA9S,KPLA10S,
     .              KPLA11S,KPLA12S,KPLA13S,KPLA14S
      INTEGER*4     NNUPCS,NNUPTS
C
      COMMON/SMIPT1S/IPLASS(MNU4SMX),IPLAOS(MNU4SMX),IPLANS(MNU4SMX),
     .               IPLAMS(MNU4SMX),IPLUAS(MNU4SMX),IPLUOS(MNU4SMX),
     .               IPLLLS(MNU4SMX),IPLXXS(MNU4SMX)
      COMMON/SMIPT2S/NNUINS,NNUNOS
      COMMON/SMIPT3S/KPLA1S,KPLA2S,KPLA3S,KPLA4S,KPLA5S,
     .               KPLA6S,KPLA7S,KPLA8S,KPLA9S,KPLA10S,
     .               KPLA11S,KPLA12S,KPLA13S,KPLA14S
      COMMON/SMIPMICS/NNUPCS,NNUPTS
C--------------------------------------------------------------- AUXLIAR
C**** PROPERS1
      INTEGER*4       NDENSS,NCAPAS,NCONDS,NPLATS,NSUBDS,IFRENTS,
     .                IFREKTS
C
      COMMON/PROPERS1/NDENSS,NCAPAS,NCONDS,NPLATS,NSUBDS(3,2),IFRENTS,
     .                IFREKTS
C
C**** PROPERS2
      INTEGER*4  MPLATS
      PARAMETER (MPLATS=5)                    ! change if necessary
C
      REAL*8          VDENSS,VCAPAS,VCONDS,
     .                VPLATS,VPCFUS,
     .                VPCAUS,
     .                VGRO1S,VGRO2S,VGRO3S,
     .                VGRO1ES
C
      COMMON/PROPERS2/VDENSS(20,2),VCAPAS(500,2),VCONDS(500,2,3),
     .                VPLATS(MPLATS,50),VPCFUS(MPLATS,200,3),
     .                VPCAUS(MPLATS,200),
     .                VGRO1S(50,2),VGRO2S(100,2),VGRO3S(100,2),
     .                VGRO1ES(50,2)
C
C**** PROPERS3
      INTEGER*4       NRADH1S,NRADH2S,NRADUS,NRADPS,IR432S
C
      COMMON/PROPERS3/NRADH1S,NRADH2S,NRADUS,NRADPS,IR432S
C
C**** PROPERS4
      REAL*8          VRADH1S,VRADH2S,VRADUS,VRADPS,
     .                RIGINTS
C
      COMMON/PROPERS4/VRADH1S(20,2),VRADH2S(20,2),VRADUS(20,2),
     .                VRADPS(20,2),
     .                RIGINTS
C
C**** PROPERS5
      INTEGER*4       NSOTRS,ISOTRS,NDIMETOS,NFILLS,IFILLS
C
      COMMON/PROPERS5/NSOTRS,ISOTRS,NDIMETOS,NFILLS,IFILLS
C
C**** PROPERS6
      INTEGER*4       NDENSFIS,NCAPAFIS,NCONDFIS,NPLATFIS,NSUBDFIS,
     .                IFRENFIS,IFREKFIS
C
      COMMON/PROPERS6/NDENSFIS,NCAPAFIS,NCONDFIS,NPLATFIS,NSUBDFIS(3,2),
     .                IFRENFIS,IFREKFIS
C
C**** PROPERS7
      REAL*8          VDENSFIS,VCAPAFIS,VCONDFIS,
     .                VPLATFIS,VPCFUFIS,
     .                VPCAUFIS
C
      COMMON/PROPERS7/VDENSFIS(20,2),VCAPAFIS(500,2),VCONDFIS(500,2,3),
     .                VPLATFIS(MPLATS,50),VPCFUFIS(MPLATS,200,3),
     .                VPCAUFIS(MPLATS,200)
C
C**** PROPERS8
      INTEGER*4       NRADH1FIS,NRADH2FIS,NRADUFIS,NRADPFIS
C
      COMMON/PROPERS8/NRADH1FIS,NRADH2FIS,NRADUFIS,NRADPFIS
C
C**** PROPERS9
      REAL*8          VRADH1FIS,VRADH2FIS,VRADUFIS,VRADPFIS
C
      COMMON/PROPERS9/VRADH1FIS(20,2),VRADH2FIS(20,2),VRADUFIS(20,2),
     .                VRADPFIS(20,2)
C
C**** PROPERS10
      INTEGER*4        KPOROS
C
      COMMON/PROPERS10/KPOROS
C
C**** PROPERS11
      INTEGER*4        NBASES,NNUM4S,NNUM4SM,INNUM4S,IWEUS,IMNMS
C
      COMMON/PROPERS11/NBASES,NNUM4S,NNUM4SM,INNUM4S,IWEUS,IMNMS
C--------------------------------------------------------------- AUXLIAR
C**** SMOOTHING
      INTEGER*4        ISMO1S,ISMO2S
      COMMON/SMOOTHBTS/ISMO1S,ISMO2S
C--------------------------------------------------------------- AUXLIAR
C**** COSOLTRUS
      INTEGER*4       NSOL1S,NSOL2S,NSOL3S
      COMMON/COSOLIAS/NSOL1S,NSOL2S,NSOL3S
C
      REAL*8          TSOL1S,TSOL2S,TSOL3S
      COMMON/COSOLIBS/TSOL1S,TSOL2S,TSOL3S
C
      INTEGER*4       ITRUCS,ITRUCVS
      COMMON/TRUCHOAS/ITRUCS,ITRUCVS
C
      REAL*8          TRUCHS
      COMMON/TRUCHOBS/TRUCHS
C
      INTEGER*4      NCETAS
      COMMON/TRUCHIS/NCETAS
C=============================================================== AUXLIAR
