      SUBROUTINE OUTNODT(SMSTST,SMSTNT,SMSTPT,SMSPPT)
C***********************************************************************
C
C**** THIS ROUTINE OUTPUTS NODAL FLUXES AND TEMP. GRAD. TO OUTPUT AND
C     POSTPROCESSOR FILES
C
C       KPRI5=0  DO NOT WRITE NODAL FLUXES
C             1  WRITE NODAL FLUXES
C       KPRI6=0  DO NOT WRITE NODAL MACROSCOPIC f_pc (see outmic.f)
C             1  WRITE NODAL MACROSCOPIC f_pc (see outmic.f)
C       KPRI7=0  DO NOT WRITE NODAL INTERNAL VARIABLES
C             1  WRITE NODAL INTERNAL VARIABLES
C       KPRI8=0 DO NOT WRITE NODAL POROSITY CRITERIA
C            =1 WRITE NODAL POROSITY CRITERIA
C
C       KFEMV=0  DO NOT WRITE TO POSTPROCESSOR FILE
C             1  WRITE TO POSTPROCESSOR FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inpo_omt.f'
C
      COMMON/POROSI1/KPOROA
C
      DIMENSION SMSTST(NSTR1T,NPOINT), SMSTNT(NSTR1T,NPOINT),
     .          SMSTPT(NNUINT,NPOINT), SMSPPT(NPOROT,NPOINT)
      DIMENSION STRSPT(3)
C
C**** OUTPUT NODAL HEAT FLUXES
C
      IF(IPRCOT.GT.0) THEN
       IF(KPRI5T.GT.0.AND.NMEMO4.EQ.1) THEN
        WRITE(LUREST,956)
        IF(NDIMET.EQ.1) THEN
         IF(KPRI5T.EQ.1) WRITE(LUREST,960)
        ELSE IF(NDIMET.EQ.2) THEN
         IF(KPRI5T.EQ.1) WRITE(LUREST,970)
        ELSE IF(NDIMET.EQ.3) THEN
         IF(KPRI5T.EQ.1) WRITE(LUREST,980)
        ENDIF
C
        DO IPOINT=1,NPOINT
         IF(NTYPET.NE.4) THEN
          IF(KPRI2T.EQ.1) WRITE(LUREST,905) IPOINT,
     .                             (SMSTST(ISTR1T,IPOINT),ISTR1T=1,
     .                              NSTR1T)
          IF(KPRI3T.EQ.1.AND.NTYPET.NE.5) 
     .                    WRITE(LUREST,905) IPOINT,(STRSPT(ISTRET),
     .                    ISTRET=1,3)
         ENDIF
C
         IF(NTYPET.EQ.4) THEN
          IF(KPRI5T.EQ.1) WRITE(LUREST,905) IPOINT,
     .                             (SMSTST(ISTR1T,IPOINT),ISTR1T=1,
     .                              NSTR1T)
         ENDIF
        ENDDO     ! ipoint=1,npoint
       ENDIF      ! kpri5t.gt.0.and.nmemo4.eq.1
C
C**** OUTPUT NODAL TEMPERATURE GRADIENTS (SMSTNT, not implemented)
C

C
C**** OUTPUT NODAL INTERNAL VARIABLES
C
       IF(KPRI7T.GT.0.AND.NNUINT.GT.0) THEN
        INUAUT=0
        WRITE(LUREST,2956)
        DO INUNOT=1,NNUNOT
         IPLA1T=IPLANT(INUNOT)
         IPLA2T=IPLAMT(INUNOT)
C
         IF(IPLA2T.GE.IPLA1T) THEN
C
          INUAUT=INUAUT+1
          WRITE(LUREST,2980) INUAUT
C
          DO IPOINT=1,NPOINT
           WRITE(LUREST,2905) IPOINT,(SMSTPT(IPLAUT,IPOINT),
     .                     IPLAUT=INUAUT-1+IPLA1T,INUAUT-1+IPLA2T)
          ENDDO     ! ipoint=1,npoint
         ENDIF      ! ipla2t.ge.ipla1t
        ENDDO       ! inunot=1,nnunot
       ENDIF        ! kpri7t.gt.0.and.nnuint.gt.0
C
C**** OUTPUTS NODAL POROSITY CRITERIA
C
       IF(KPRI8T.GT.0) THEN
        IF(NPOROT.GT.0.AND.ICALPO.EQ.1) THEN
         IF(KPOROA.EQ.0) THEN
          CALL RUNMENT('WARNING: NO POROSITY CRITERIA SELECTED IN
     . MATERIAL DATA')
         ELSE
          WRITE(LUREST,1956)
C
          DO IPOROT=1,NPOROT
           WRITE(LUREST,1960) IPOROT
           DO IPOINT=1,NPOINT
            WRITE(LUREST,905) IPOINT,SMSPPT(IPOROT,IPOINT)
           ENDDO
          ENDDO
         ENDIF     ! kporoa.eq.0
        ENDIF      ! nporot.gt.0
       ENDIF       ! kpri8t.gt.0
      ENDIF        ! iprcot.gt.0
C
C**** WRITE TO POSTPROCESSOR FILE
C
      IF(NMEMO4.EQ.1) THEN
       IF(KFEMVT.EQ.1)
     .  WRITE(LUPOST) ((SNGL(SMSTST(ISTR1T,IPOINT)),ISTR1T=1,NSTR1T),
     .                                              IPOINT=1,NPOINT)
      ENDIF
      IF(NNUINT.GT.0) THEN
       IF(KFEMVT.EQ.1)
     .  WRITE(LUPOST) ((SNGL(SMSTPT(INUINT,IPOINT)),INUINT=1,NNUINT),
     .                                              IPOINT=1,NPOINT)
      ENDIF
      IF(NPOROT.GT.0) THEN        ! ICALPO not considered; see outputt.f
       IF(KFEMVT.EQ.1)
     .  WRITE(LUPOST) ((SNGL(SMSPPT(IPOROT,IPOINT)),IPOROT=1,NPOROT),
     .                                              IPOINT=1,NPOINT)
      ENDIF
C
      RETURN
  905 FORMAT(5X,I5,8E15.6)
  956 FORMAT(1H0,12X,23H FLUXES AT NODAL POINTS)
  960 FORMAT(1H0,5X,5HIPOIN,5X,10H XX-FLUX  )
  970 FORMAT(1H0,5X,5HIPOIN,5X,10H XX-FLUX  ,5X,10H YY-FLUX  ,
     .     5X,10H XY-FLUX  ,5X,10H ZZ-FLUX  )
c  972 FORMAT(1H0,5X,5HIPOIN,5X,10H  MAX F.S.,5X,10H  MIN F.S.,
c     .          10X,5HANGLE)
  980 FORMAT(1H0,5X,5HIPOIN,4X,10H XX-FLUX  ,5X,10H YY-FLUX  ,
     .     5X,10H XY-FLUX  ,5X,10H ZZ-FLUX  ,5X,10H XZ-FLUX  ,
     .     5X,10H YZ-FLUX  )
c  981 FORMAT(1H0,5X,5HIPOIN,3X,10H     P1   ,5X,10H     P2   ,
c     .     5X,10H     P3   )
C
 2905 FORMAT(5X,I5,8E15.6)
 2956 FORMAT(/,5X,35H INTERNAL VARIABLES AT NODAL POINTS)
 2980 FORMAT(5X,5HIPOIN,2X,18H INTERNAL VARIABLE,I5)
C
 1956 FORMAT(/,5X,'POROSITY CRITERIA AT NODAL POINTS')
 1960 FORMAT(5X,5HIPOIN,2X,18H POROSITY CRITERIA,I5)
      END
