      SUBROUTINE ADDELMS
C***********************************************************************
C
C**** THIS ROUTINE CALCULATES THE POINTERS FOR ELEMENTAL ARRAYS
C
C     Notes: VNORI is the normal vector stored at element level. This
C            array is only useful when NMEMO2=0. 
C
C***********************************************************************
C
C**** GENERAL DIMENSIONS
C
      INCLUDE 'para_oms.f'
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_oms.f'
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'         ! thermal-mechanical
      INCLUDE 'nued_om.f'         ! thermal-mechanical
C
C**** MICROSTRUCTURL VARIABLES
C
      INCLUDE 'auxl_oms.f'
      INCLUDE 'prob_oms.f'
C
      ITERME1=1                              ! unidirectional coupled
      ITERME2=1                              ! bidirectional coupled
      IF(ITERME.LT.0) THEN                   ! uncoupled problems
       ITERME1=0                             ! not used
       ITERME2=0
      ENDIF
      IF(ITERME.EQ.0) THEN                   ! unidirectional coupled
       ITERME1=1                             ! not used
       ITERME2=0
      ENDIF
C
C**** GENERAL CHECKS OF VARIABLES DEFINED IN setdatt.f, setdats.f &
C     consett.f
C
      IF(MPROPS.LT.NPROPS)
     . CALL RUNENDS('ERROR: MPROPS LT NPROPS')
C
      IF(MHLODS.LT.NHLODS)
     . CALL RUNENDS('ERROR: MHLODS LT NHLODS')
C
      IF(MSUBFS.LT.NSUBFS)
     . CALL RUNENDS('ERROR: MSUBFS LT NSUBFS')
C
      IF(MPRELS.LT.NPRELS)
     . CALL RUNENDS('ERROR: MPRELS LT NPRELS')
C
      IF(MHISTS.LT.NHISTS)
     . CALL RUNENDS('ERROR: MHISTS LT NHISTS')
C
      IF(MNUINS.LT.NNUINS)
     . CALL RUNENDS('ERROR: MNUINS LT NNUINS')
C
C**** GENERAL CHECKS OF VARIABLES DEFINED IN INPUT DATA
C     (now in setdats.f)
C
      IF(MDISKDS.NE.NDISKDS)
     . CALL RUNENDS('ERROR: MDISKDS =/ NDISKDS')
C
      IF(MFURESS.LT.NFURESS)             ! this control is not necessary
     . CALL RUNENDS('ERROR: MFURESS =/ NFURESS')
C
      IF(MMACHIS.NE.NMACHIS)
     . CALL RUNENDS('ERROR: MMACHIS =/ NMACHIS')
C
      IF(MMEMOS.NE.NMEMOS)
     . CALL RUNENDS('ERROR: MMEMOS =/ NMEMOS')
C
      IF(MMEMO1S.NE.NMEMO1S)
     . CALL RUNENDS('ERROR: MMEMO1S =/ NMEMO1S')
C
      IF(MMEMO2S.NE.NMEMO2S)
     . CALL RUNENDS('ERROR: MMEMO2S =/ NMEMO2S')
C
      IF(MMEMO3S.LT.NMEMO3S)
     . CALL RUNENDS('ERROR: MMEMO3S LT NMEMO3S')
C
      IF(MMEMO4S.LT.NMEMO4S)
     . CALL RUNENDS('ERROR: MMEMO4S =/ NMEMO4S')
C
      IF(MMEMO5S.NE.NMEMO5S)
     . CALL RUNENDS('ERROR: MMEMO5S =/ NMEMO5S')
C
      IF(MMEMO6S.NE.NMEMO6S)
     . CALL RUNENDS('ERROR: MMEMO6S =/ NMEMO6S')
C
      IF(MMEMO7S.NE.NMEMO7S)
     . CALL RUNENDS('ERROR: MMEMO7S =/ NMEMO7S')
C
      IF(MMEMO8S.NE.NMEMO8S)
     . CALL RUNENDS('ERROR: MMEMO8S =/ NMEMO8S')
C
      IF(MMEMO9S.NE.NMEMO9S)
     . CALL RUNENDS('ERROR: MMEMO9S =/ NMEMO9S')
C
      IF(MMEMO10S.LT.NMEMO10S)
     . CALL RUNENDS('ERROR: MMEMO10S LT NMEMO10S')
C
      IF(MMEMO11S.NE.NMEMO11S)
     . CALL RUNENDS('ERROR: MMEMO11S =/ NMEMO11S')
C
C**** INITIAL DATA
C
      IPOONS=0
      IDYONS=0
      ISMOMS=0
C
C**** ELEMENT DATA ARRAY ( ELDATT )
C
      NKOSTS=(NSTR1S+1)*NSTR1S/2
      IF(KSGAUS.NE.0) ISMOMS=1
C
      IF(KPROBS.EQ.2) THEN       ! STRUCTURAL SHELLS AND PLATES
       IDATAS(1)=1                                  ! ELCOD(NDIME,NNODE)
       IDATAS(2)=IDATAS(1)+NDIMES*NNODES          ! DERIV(2,NNODE,NGAUS)
       IDATAS(3)=IDATAS(2)+2*NNODES*NGAUSS          ! DVOLU(NGAUS)
       IDATAS(4)=IDATAS(3)+NGAUSS                   ! GPCOD(NDIME,NGAUS)
       IDATAS(5)=IDATAS(4)+NDIMES*NGAUSS            ! SHAPE(NNODE,NGAUS)
       IDATAS(6)=IDATAS(5)+NNODES*NGAUSS            ! EPMTX(NKOST,NGAUS)
       IDATAS(7)=IDATAS(6)+NKOSTS*NGAUSS            ! TRNOD(NDIME,NNODE)
       IDATAS(8)=IDATAS(7)+NDIMES*NNODES*(NDIMES-2) ! EMASS(NNODE,NNODE)
       NDATAS   =IDATAS(8)+NNODES*NNODES*ISMOMS
      ELSE                        ! OTHERS PROBLEMS
       NMEMA1S=1-NMEMO1S
       NMEMA2S=1-NMEMO2S
       IDATAAS=1
       IF(NMEMA1S.EQ.0.AND.NMEMA2S.EQ.0.AND.NMEMOS.EQ.0.AND.
     .    (NMEMA2S*ISMOMS).EQ.0.AND.NHOURS.EQ.0) IDATAAS=0
       IDATAS(1)=IDATAAS                            ! ELCOD(NDIME,NNODE)
       IDATAS(2)=IDATAS(1)+NDIMES*NNODES*NMEMA1S 
C                                             ! CARTD(NDIME,NNODE,NGAUS)
       IDATAS(3)=IDATAS(2)+NDIMES*NNODES*NGAUSS*NMEMA2S   ! DVOLU(NGAUS)
       IDATAS(4)=IDATAS(3)+NGAUSS*NMEMA2S           ! GPCOD(NDIME,NGAUS)
       IDATAS(5)=IDATAS(4)+NDIMES*NGAUSS*NMEMA2S    ! SHAPE(NNODE,NGAUS)
       IDATAS(6)=IDATAS(5)+NNODES*NGAUSS*NMEMA2S    ! EPMTX(NKOST,NGAUS)
       IDATAS(7)=IDATAS(6)+NKOSTS*NGAUSS*NMEMOS     ! RMAT1(NDIME,NDIME)
       IDATAS(8)=IDATAS(7)+NDIMES*NDIMES*NMEMOS     ! EMASS(NNODE,NNODE)
       IDATAS(9)=IDATAS(8)+NNODES*NNODES*ISMOMS*NMEMA2S
C                                                   ! STIFH(NEVAB,NEVAB)
       IDATAS(10)=IDATAS( 9)+NEVABS*NEVABS*NHOURS   ! VNORI(NDIME,NGAUS)
       NDATAS    =IDATAS(10)+NDIMES*NGAUSS*NMEMA2S*ITERME2
      ENDIF
C
C**** ELEMENT PRESCRIBED VARIABLES ARRAY ( ELPRE )
C
      IPREVS(1)=1*NMEMOS                         ! STRA0(NSTR1,NGAUS)
      IPREVS(2)=IPREVS(1)+NSTR1S*NGAUSS*NMEMOS   ! STRS0(NSTR1,NGAUS)
      IPREVS(3)=IPREVS(2)+NSTR1S*NGAUSS*NMEMOS   ! TEMPC(4)
      NPREVS   =IPREVS(3)+4*NMEMOS
C
C**** ELEMENT STATE VARIABLES ARRAY ( ELVAR )
C
      NMEMA5S=1-NMEMO5S
      ISTATAS=0
      IF(NMEMO3S.EQ.1.OR.NMEMO4S.EQ.1.OR.NMEMO5S.EQ.0)
     . ISTATAS=1
      ISTATS(1)=ISTATAS                          ! ELDIS(NDOFC,NNODE)
      ISTATS(2)=ISTATS(1)+NDOFCS*NNODES*NMEMA5S  ! EHIST(NHIST,NGAUS)
      ISTATS(3)=ISTATS(2)+NHISTS*NGAUSS*NMEMO3S  ! STRAN(NSTR1,NGAUS) 
      ISTATS(4)=ISTATS(3)+NSTR1S*NGAUSS*NMEMO4S  ! STRSG(NSTR1,NGAUS)
      NSTATS   =ISTATS(4)+NSTR1S*NGAUSS*NMEMO4S
C                           
C**** ELEMENT MATRICES ARRAY ( ELMAT )
C
      IF(KDYNAS.EQ.1) IDYONS=1
      IF(KPORES.EQ.2) IPOONS=1
C
      NMEMA6S=1-NMEMO6S
      NMEMA7S=1-NMEMO7S
      IMATXTAS=1
      IF(NMEMA7S.EQ.0.AND.IPOONS.EQ.0) IMATXTAS=0
      IMATXS(1)=IMATXTAS                        ! CSTIF(NEVAC,NEVAC)
      IMATXS(2)=IMATXS(1)+NEVACS*NEVACS*NMEMA7S ! KSTIF(NKOVA)
      IMATXS(3)=IMATXS(2)+NKOVAS*NMEMA6S        ! MSTIF(NKOVA)
      IMATXS(4)=IMATXS(3)+NKOVAS*IDYONS*NMEMA6S ! PSTIF(NKOND)
      IMATXS(5)=IMATXS(4)+NKONDS*IPOONS         ! QSTIF(NKOND)
      IMATXS(6)=IMATXS(5)+NKONDS*IPOONS         ! HSTIF(NEVAB*NNODE)
      NMATXS   =IMATXS(6)+NEVABS*NNODES*IPOONS
C
C**** MEMORY CONTROL
C
      IF(NDATAS.GT.MDATAS)
     . CALL RUNENDS('ERROR IN ADDELMS: NDATAS          ')
      IF(NPREVS.GT.MPREVS)
     . CALL RUNENDS('ERROR IN ADDELMS: NPREVS          ')
      IF(NSTATS.GT.MSTATS)
     . CALL RUNENDS('ERROR IN ADDELMS: NSTATS          ')
      IF(NMATXS.GT.MMATXS)
     . CALL RUNENDS('ERROR IN ADDELMS: NMATXS          ')
C
      RETURN
      END
