C=============================================================== ADDITIO
C**** ADDITI
C
      INTEGER*4     NDISKD,NFURES,NMACHI,NMEMO,ICHALT,IWINDT
      COMMON/ADDITI/NDISKD,NFURES,NMACHI,NMEMO,ICHALT,IWINDT
C
      INTEGER*4      NMEMO1,NMEMO2,NMEMO3,NMEMO4,NMEMO5
      COMMON/ADDITI1/NMEMO1,NMEMO2,NMEMO3,NMEMO4,NMEMO5
C
      INTEGER*4      NMEMO6,NMEMO7,NMEMO8,NMEMO9,NMEMO10
      COMMON/ADDITI2/NMEMO6,NMEMO7,NMEMO8,NMEMO9,NMEMO10
C
      INTEGER*4      NMEMO11,NMEMO12,NMEMO13,NMEMO14,NMEMO15
      COMMON/ADDITI3/NMEMO11,NMEMO12,NMEMO13,NMEMO14,NMEMO15
C
      INTEGER*4      NMEMO16,NMEMO17,NMEMO18,NMEMO19,NMEMO20
      COMMON/ADDITI4/NMEMO16,NMEMO17,NMEMO18,NMEMO19,NMEMO20
C
C=============================================================== ADDITIO
