      SUBROUTINE BISECT(DESMN,DESJ2,DESJ3,EHIST,KGAUS,NCRIT,PREMN,
     .                  PREJ2,PREJ3,PROPS,REDUC,WCOJ3,YCOJ3,ZCOJ2)
C***********************************************************************
C
C****THIS ROUTINE SOLVES THE EQUATION USING THE BISECTION METHOD
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EHIST(*), PROPS(*)
      RCONV=0.01
      RLEFT=0.0
      RIGHT=1.0
      CALL VERIFI(DESMN,DESJ2,DESJ3,DIFLF,EHIST,NCRIT,PREMN,
     .            PREJ2,PREJ3,PROPS,RLEFT,WCOJ3,YCOJ3,ZCOJ2)
      TOLLE=DABS(DIFLF)
      IF(TOLLE.GT.RCONV)GOTO 10
      REDUC=RLEFT
C 
      RETURN
   10 CALL VERIFI(DESMN,DESJ2,DESJ3,DIFRG,EHIST,NCRIT,PREMN,
     .            PREJ2,PREJ3,PROPS,RIGHT,WCOJ3,YCOJ3,ZCOJ2)
      TOLLE=DABS(DIFRG)
      IF(TOLLE.GT.RCONV)GOTO 20
      REDUC=RIGHT
C
      RETURN
C
   20 SIGRT=DIFLF*DIFRG
      IF(SIGRT.LT.0.)GOTO 30
c     WRITE(7,900)KGAUS 
  900 FORMAT(1X,'SUB.BISECT: THE SOLUTIONS OF THE POTENTIAL FUNCTION',/,
     .          'FOR REDUC=0 AND 1 ARE BOTH GREATER OR SMALLER THAN ',/,
     .          'ZERO. IMPOSSIBLE SOLUTION: CHECK GAUSS POINT NO.',I5)
C
      CALL RUNEND('ERROR IN BISECT                    ')
C
C***LOOP OVER BY TRIAL AND ERROR
C
   30 ICOUN=0
   40 ICOUN=ICOUN+1
      IF(ICOUN.LE.30)GOTO 45
c     WRITE(7,950)
  950 FORMAT(3X,'NUMBER OF ITERATION EXCEEDED IN BISECT',/,
     .       3X,'TRY TO CHANGE THE LOAD INCREMENT',/)
C
      CALL RUNEND('ERROR IN BISECT                    ')
C
   45 DIFRL=DABS(RIGHT-RLEFT)
      HALPH=(RIGHT+RLEFT)/2.
      IF(DIFRL.LT.RCONV)GOTO 100
      CALL VERIFI(DESMN,DESJ2,DESJ3,DIFHA,EHIST,NCRIT,PREMN,
     .            PREJ2,PREJ3,PROPS,HALPH,WCOJ3,YCOJ3,ZCOJ2)
      TOLLE=DABS(DIFHA)
      IF(TOLLE.LE.RCONV)GOTO 100
C
      SIGRT=DIFRG*DIFHA
      IF(SIGRT.GE.0.)GOTO 50
      RLEFT=HALPH
      DIFLF=DIFHA
      GOTO 40
   50 RIGHT=HALPH
      DIFRG=DIFHA
      GOTO 40
C
  100 REDUC=HALPH
C
      RETURN
      END
