      SUBROUTINE CART05S(ELCODS,PROPSS,ELDISS,SHAPES,CARTDS,
     .                   POSGPS,WEIGPS,GPCODS,SHAPDS,DERIVS,XJACMS,
     .                   CARDDS,VELCMS,WHAPES,HACHES,WARTDS,
     .                   WERIVS,CENTRS,ADVEMS,TEINIS,FPCHLS,EHISTS)
C***********************************************************************
C
C**** THIS ROUTINE COMPUTES GALERKIN (IGALE=0) OR PETROV-GALERKIN
C     (IGALE=1) TYPE WEIGHT FUNCTIONS & THEIR CARTESIAN DERIVATIVES
C     ( ELEMENT NO. 5 )
C
C     Notes: to compute some perturbation functions(according to IPERTS)
C            or the cartesian derivatives of the perturbation
C            functions, it is necessary to calculate the isoparametric
C            jacobian (SHAPDS & CARDDS are auxiliars variables).
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'   ! thermal-mechanical
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
      COMMON/JACOBSSA/IERORS,KERORS
C
      DIMENSION ELCODS(NDIMES,*),        PROPSS(*),
     .          ELDISS(NDOFCS,*),        SHAPES(NNODLS,*),
     .          CARTDS(NDIMES,NNODLS,*)
      DIMENSION POSGPS(NDIMES,*),        WEIGPS(*),
     .          GPCODS(NDIMES,*),        SHAPDS(NNODLS,*)
      DIMENSION DERIVS(NDIMES,NNODLS,*), XJACMS(NDIMES,*),
     .          CARDDS(NDIMES,NNODLS,*), VELCMS(*),
     .          WHAPES(NNODLS,*),
     .          HACHES(NNODLS),          WARTDS(NDIMES,NNODLS,*),
     .          WERIVS(NDIMES,NNODLS,*)
      DIMENSION CENTRS(NDIMES,*),        ADVEMS(NDIMES,*)
      DIMENSION TEINIS(NDOFCS,*),        FPCHLS(NFPCH,*)
      DIMENSION EHISTS(NHISTS,*)
C
      TWOPIS=6.283185307179586D0
C
      IF(IGALES.EQ.0) THEN
       DO IGAUSS=1,NGAULS
        DO INODLS=1,NNODLS
         WHAPES(INODLS,IGAUSS)=SHAPES(INODLS,IGAUSS)
         DO IDIMES=1,NDIMES
          WARTDS(IDIMES,INODLS,IGAUSS)=CARTDS(IDIMES,INODLS,IGAUSS)
         ENDDO
        ENDDO
       ENDDO
       RETURN
      ENDIF

      call runends('para en cart05s')

C
C**** IDENTIFY SAMPLING POINTS AND WEIGHTS OF THE SHAPE FUNCTION
C
c     CALL RULEPW(NDIMET,NGAULT,NRULET,POSGPT,WEIGPT)
C
C**** LOOP ON INTEGRATION POINTS
C
c     DO 100 IGAUSS=1,NGAULS
C
C**** COMPUTE SHAPE FUNCTIONS AND DERIVATIVES
C
      EXISPS=POSGPS(1,IGAUSS)
      ETASPS=0.0D0
      IF(NDIMES.GE.2) ETASPS=POSGPS(2,IGAUSS)
      EZETAS=0.0
      IF(NDIMES.EQ.3) EZETAS=POSGPS(3,IGAUSS)
      CALL SHAFUN(DERIVS(1,1,IGAUSS),EXISPS,ETASPS,EZETAS,NDIMES,NNODLS,
     .            NQUTRS,     0,SHAPDS(1,IGAUSS))
C
C**** CARTESIAN DERIVATIVES OF THE SHAPE FUNCTIONS
C
c     CALL JACOBST(CARDDT(1,1,IGAUST), DERIVT(1,1,IGAUST), DETJMT,
c    .             ELCODT,             GPCODT(1,IGAUST),   IELEMT,
c    .             NDIMET,NNODLT,      SHAPDT(1,IGAUST),   XJACMT,
c    .             LUREST,LUPRIT)
C
C**** DEFINES THE UPWIND FUNCTION
C
c     NSUPE=1
c     CALL HACHEC(ELCODT,PROPST,ELDIST,VELCMT,HACHET,CENTRO,
c    .            ADVEMT,TEINIT,SHAPET(1,IGAUST),NSUPE,FPCHLT,
c    .            EHISTS(1,IGAUST),CARTDT(1,1,IGAUST))
C
C**** COMPUTES PERTURBATION FUNCTIONS AND DERIVATIVES
C
c     CALL WHAFUN(WERIVT(1,1,IGAUST),EXISPT,ETASPT,EZETAT,NDIMET,NNODLT,
c    .            WHAPEL(1,IGAUST),HACHET,XJACMT,IPERT)
C
C**** CARTESIAN DERIVATIVES OF THE PERTURBATION FUNCTIONS
C
c     CALL WACOBST(WARTDL(1,1,IGAUST),WERIVT(1,1,IGAUST),
c    .             NDIMET,NNODLT,XJACMT)
C
C**** COMPUTES WEIGHT FUNCTION (SHAPE FUNCTION + PERTURBATION FUNCTION)
C     AND ITS CARTESIAN DERIVATIVE
C
c     DO INODLT=1,NNODLT
c      WHAPEL(INODLT,IGAUST)=SHAPET(INODLT,IGAUST)+
c    .                       WHAPEL(INODLT,IGAUST)
c      DO IDIMET=1,NDIMET
c       WARTDL(IDIMET,INODLT,IGAUST)=CARTDT(IDIMET,INODLT,IGAUST)+
c    .                               WARTDL(IDIMET,INODLT,IGAUST)
c      ENDDO
c     ENDDO
C
  100 CONTINUE           ! igauss=1,ngauls
C
      RETURN
      END
