      SUBROUTINE CONCEKT
C***********************************************************************
C
C**** THIS ROUTINE CHECKS THE MAIN CONTROL DATA ESTABLISHED IN
C     "CONTROL_DATA" & "PROBLEM_DATA"
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'                 ! thermal-mechanical
      INCLUDE 'nued_om.f'                 ! thermal-microstructural
      INCLUDE 'nuef_om.f'                 ! thermal-flow
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
C
      DIMENSION NERORT(12)
C
      DO 10 IERORT=1,12
   10 NERORT(IERORT)=0
C
C**** CHECK ON MAXIMUM DIMENSIONS
C
      IF(NPOINT.LE.0)                                     NERORT(1)=1
      IF(NELEMT.LE.0)                                     NERORT(2)=1
      IF(NNODET.LT.2.OR.NNODET.GT.27)                     NERORT(3)=1
      IF(NMATST.LT.1.OR.NMATST.GT.NELEMT)                 NERORT(4)=1
      IF(NFUNCT.LT.1)                                     NERORT(5)=1
C
C**** PROBLEM INCOMPATIBILITY
C
      IF(KPROBT.EQ.0)                                     NERORT(8)=1
      IF(KPORET.EQ.2.AND.LARGET.NE.0)                     NERORT(9)=1
      IF(KPORET.NE.2.AND.KSMUST.NE.0)                     NERORT(10)=1
C
C**** CHECK ON MISCELLANEOUS
C
      IF(KSYMMT.EQ.0) NERORT(11)=0   ! unsymmetric solver is implemented
      IF(IABS(KSMUST).EQ.1.AND.NDIMET.NE.2)               NERORT(12)=1
C
C**** OTHER ERRORS
C
      IF(IMICR.EQ.1.AND.ITERME.GE.0.AND.KSGAUT.EQ.0)
     . CALL RUNENDT('ERROR: SMOOTHING OPTION IS LACKING')
C
      IF(IMICR.EQ.1.AND.ITERMEF.GT.0.AND.KSGAUT.EQ.0)
     . CALL RUNENDT('ERROR: SMOOTHING OPTION IS LACKING')
C
C**** WARNINGS
C
      IF(KSYMMT.EQ.0.AND.ICONVT.EQ.0.AND.IGALET.EQ.0) THEN
       WRITE(LUREST,901)
       WRITE(LUPRIT,901)
  901  FORMAT(//,'WARNING: AN UNSYMMETRIC SOLVER IS USED FOR A',/,
     .           '         NON-ADVECTION-DIFFUSION PROBLEM WITH',/,
     .           '         NO UPWINDING TECHNIQUE',//)
      ENDIF
C
      IF(KSYMMT.EQ.1.AND.ICONVT.EQ.1) THEN
       WRITE(LUREST,902)
       WRITE(LUPRIT,902)
  902  FORMAT(//,'WARNING: A SYMMETRIC SOLVER IS USED FOR AN',/,
     .           '         ADVECTION-DIFFUSION PROBLEM',//)
      ENDIF
C
      IF(KSYMMT.EQ.1.AND.IGALET.EQ.1) THEN
       WRITE(LUREST,903)
       WRITE(LUPRIT,903)
  903  FORMAT(//,'WARNING: A SYMMETRIC SOLVER IS USED WITH AN',/,
     .           '         UPWINDING TECHNIQUE',//)
      ENDIF
C
      IF(ICONVT.EQ.0.AND.IGALET.EQ.1) THEN
       WRITE(LUREST,904)
       WRITE(LUPRIT,904)
  904  FORMAT(//,'WARNING: AN UPWIND TECHNIQUE IS CONSIDERED FOR',/,
     .           '         THIS NON-ADVECTION-DIFFUSION PROBLEM',//)
      ENDIF
C
      IF(ICONVT.EQ.1.AND.IGALET.EQ.0) THEN
       WRITE(LUREST,905)
       WRITE(LUPRIT,905)
  905  FORMAT(//,'WARNING: NO UPWIND TECHNIQUE IS CONSIDERED FOR',/,
     .           '         THIS ADVECTION-DIFFUSION PROBLEM',//)
      ENDIF
C
      IF(KSYMMT.EQ.0.AND.NOCOIT.EQ.0) THEN
       WRITE(LUREST,906)
       WRITE(LUPRIT,906)
  906  FORMAT(//,'WARNING: A NON-SYMMETRIC SOLVER IS USED FOR A',/,
     .           '      PROBLEM WITH NO NON COINCIDENT CONTACT MESH',//)
      ENDIF
      IF(KSYMMT.EQ.1.AND.NOCOIT.GT.0) THEN
       WRITE(LUREST,907)
       WRITE(LUPRIT,907)
  907  FORMAT(//,'WARNING: A SYMMETRIC SOLVER IS USED FOR A NON',/,
     .           '         COINCIDENT CONTACT MESH PROBLEM',//)
      ENDIF
C
      IF(NDIMET.EQ.1.AND.NOCOIT.EQ.1) THEN
       WRITE(LUREST,908)
       WRITE(LUPRIT,908)
  908  FORMAT(//,'WARNING: A 1D PROBLEM HAS ALWAYS A COINCIDENT CON-',/,
     .           '         TACT MESH - THEREFORE, NOCOIT=0 IS SET',//)
       NOCOIT=0
      ENDIF
C
C**** CHECK IF ERRORS HAD OCCURED
C
      KOUNTT=0
      DO 20 IERORT=1,12
      IF (NERORT(IERORT).NE.1) GOTO 20
      KOUNTT=KOUNTT+1
   20 CONTINUE
C
      IF (KOUNTT.EQ.0) RETURN
C
C**** ERRORS DIAGNOSED BY ROUTINE CONCEK
C
      WRITE(LUREST,600)KOUNTT
  600 FORMAT(//,20X,I5,'  INPUT ERRORS DETECTED BY CONTRO',/,
     .          25X,   '  DIAGNOSTIC FOLLOWS: ',//)
C
      IF(NERORT(1).EQ.1)  WRITE(LUREST,700) 
      IF(NERORT(2).EQ.1)  WRITE(LUREST,705) 
      IF(NERORT(3).EQ.1)  WRITE(LUREST,710) NNODET
      IF(NERORT(4).EQ.1)  WRITE(LUREST,715) NMATST,NELEMT
      IF(NERORT(5).EQ.1)  WRITE(LUREST,720)
      IF(NERORT(8).EQ.1)  WRITE(LUREST,735)
      IF(NERORT(9).EQ.1)  WRITE(LUREST,740)
      IF(NERORT(10).EQ.1) WRITE(LUREST,745)
      IF(NERORT(11).EQ.1) WRITE(LUREST,750)
      IF(NERORT(12).EQ.1) WRITE(LUREST,755)
C
      CALL RUNENDT('CONCEKT: ERROR DETECTED            ')
C
  700 FORMAT(' THE SPECIFIED NUMBER OF NODES IS LESS THAN ZERO'//)
C
  705 FORMAT(' THE SPECIFIED NUMBER OF ELEMENTS IS LESS THAN ZERO'//)
C
  710 FORMAT(
     .' THE NUMBER OF NODES PER ELEMENT IS LESS THAN 2 OR GREATER THAN',
     .' 20',/,10X,'NNODE=',I5//)
C
  715 FORMAT(
     .59H THE SPECIFIED TOTAL NUMBER OF DIFFERENT MATERIALS (NMATS) ,/,
     .59H IS LESS THAN OR EQUAL TO ZERO, OR GREATER THAN THE TOTAL  ,/,
     .59H NUMBER OF ELEMENTS (NELEM) IN THE STRUCTURE               ,/,
     .10X,'NMATS=',I5,5X,'NELEM=',I5//)
C
  720 FORMAT(
     .' THE SPECIFIED NUMBER OF FUNCTIONS IS LESS THAN OR EQUAL TO',
     .' ZERO'//)
C
  735 FORMAT(
     .' SEEPAGE PROBLEM IS NOT IMPLEMENTED YET',/ )
C
  740 FORMAT(
     .' COUPLED PROBLEM WITH LARGE DISPLACEMENTS IS NOT IMPLEMENTED',
     .' YET',/ )
C
  745 FORMAT(
     .' UNCOUPLED PROBLEM DOES NOT REQUIRE ANY SMOOTHING',/ )
C
  750 FORMAT(
     .' ALL IMPLEMENTED PROBLEMS YIELD A SYMMETRIX MATRIX AND YOU,',/,
     .' IDIOT, ARE ASKING FOR A NON-SYMMETRIC SOLVER',/)
C
  755 FORMAT(
     .' SPECIFIED TYPE OF SMOOTHING IS INCORRECT OR NOT YET',
     .' IMPLEMENTED',/)
C
      END
