      SUBROUTINE CONJUT(CONJU,DCONJ,TEMPG)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE CONJU FACTOR
C     
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      DCONJ=0.0
      IF(TEMPG.GT.TEMPL) CONJU=0.0D+00
C
      temro=temps
      IF(TEMPG.LE.TEMPL.AND.TEMPG.GT.TEMRO) THEN
       AAMAY=(TEMPL*TEMPL*TEMPL-TEMRO*TEMRO*TEMRO)-3.00*TEMRO*TEMRO*
     .       (TEMPL-TEMRO)-1.50*(TEMPL+TEMRO)*(TEMPL*TEMPL-TEMRO*TEMRO-
     .       2.00*TEMRO*(TEMPL-TEMRO))
       ALP11=-1.00/AAMAY
       ALP22=-1.50*(TEMPL+TEMRO)*ALP11
       ALP33=-3.00*ALP11*TEMRO*TEMRO-2.00*ALP22*TEMRO
       ALP44=-ALP11*TEMPL*TEMPL*TEMPL-ALP22*TEMPL*TEMPL-ALP33*TEMPL
       CONJU=ALP11*TEMPG*TEMPG*TEMPG+ALP22*TEMPG*TEMPG+ALP33*TEMPG+ALP44
       DCONJ=3.0*ALP11*TEMPG*TEMPG+2.0*ALP22*TEMPG+ALP33
      ENDIF
C
      IF(TEMPG.LE.TEMRO) CONJU=1.0D+00
C
      RETURN
      END
