      SUBROUTINE COUPLE0S(LNODSS,MATNOS,PROELS,PROPSS,COORDS,HTLODS,
     .                    IFFIXS,PRESCS,RLOADS,RLOAHS,FICTOS,TFICTS,
     .                    DISITS,DISPRS,DISTOS,HEADSS,REFORS,TLOADS,
     .                    LPNTNS,ELDATS,ELPRES,ELVARS,ELMATS,DISPLS,
     .                    PWORKS,PREASS,TGAPSS,TEMPIS,ADVELS,FPCHAS,
     .                    LACTIS,
     .                    WORK1S,
     .                    LNODST,MATNOT,PROELT,PROPST,COORDT,HTLODT,
     .                    IFFIXT,PRESCT,RLOADT,RLOAHT,FICTOT,TFICTT,
     .                    DISITT,DISPRT,DISTOT,HEADST,REFORT,TLOADT,
     .                    LPNTNT,ELDATT,ELPRET,ELVART,ELMATT,DISPLT,
     .                    PWORKT,PREAST,TGAPST,TEMPIT,ADVELT,FPCHAT,
     .                    LACTIT,
     .                    WORK1T)
C***********************************************************************
C
C**** THIS ROUTINE SOLVES THE THERMO-MICROSTRUCTURAL COUPLED PROBLEM
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8, ALLOCATABLE, INTENT(INOUT) :: WORK1S(:),WORK1T(:)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
      
      INTERFACE
       INCLUDE 'tmstept.inc'
      END INTERFACE
C
C**** MICROSTRUCTURAL VARIABLES
C
      DIMENSION LNODSS(NNODES,NELEMS),  MATNOS(NELEMS),
     .          PROELS(NPRELS,NGRUPS),  PROPSS(NPROPS,NMATSS),
     .          COORDS(NDIMES,NPOINS),  HTLODS(NHLODS,NSUBFS,NFUNCS)
      DIMENSION IFFIXS(NTOTVS,2),       PRESCS(NTOTVS,2),
     .          RLOADS(NTOTVS),         RLOAHS(NTOTVS,NFUNCS),
     .          FICTOS(NFUNCS),         TFICTS(NFUNCS)
      DIMENSION DISITS(NTOTVS,2),
     .          DISPRS(NTOTVS,3),       DISTOS(NTOTVS,3),
     .          HEADSS(NPOINS,4),
     .          REFORS(NTOTVS,2),       TLOADS(NTOTVS,2),
     .          LPNTNS(NPOINS)
      DIMENSION ELDATS(NDATAS),         ELPRES(NPREVS),
     .          ELVARS(NSTATS),         ELMATS(NMATXS)
      DIMENSION DISPLS(NTOTVMS),        PWORKS(NPOINS,3),
     .          PREASS(NPREAS,NPOINS),  TGAPSS(NPOINS),
     .          TEMPIS(NPOINS,2),       ADVELS(NTOTVS*NDIMES),
     .          FPCHAS(NFPCH,NPOINS),   LACTIS(NELEMS)
C
C**** THERMAL VARIABLES
C
      DIMENSION LNODST(NNODET,NELEMT), MATNOT(NELEMT),
     .          PROELT(NPRELT,NGRUPT), PROPST(NPROPT,NMATST),
     .          COORDT(NDIMET,NPOINT), HTLODT(NHLODT,NSUBFT,NFUNCT)
      DIMENSION IFFIXT(NTOTVT,2),      PRESCT(NTOTVT,2),
     .          RLOADT(NTOTVT),        RLOAHT(NTOTVT,NFUNCT),
     .          FICTOT(NFUNCT),        TFICTT(NFUNCT)
      DIMENSION DISITT(NTOTVT,2),
     .          DISPRT(NTOTVT,3),      DISTOT(NTOTVT,3),
     .          HEADST(NPOINT,4),
     .          REFORT(NTOTVT,2),      TLOADT(NTOTVT,2),
     .          LPNTNT(NPOINT)
      DIMENSION ELDATT(NDATAT),        ELPRET(NPREVT),
     .          ELVART(NSTATT),        ELMATT(NMATXT)
      DIMENSION DISPLT(NTOTVM),        PWORKT(NPOINT,3),
     .          PREAST(NPREAT,NPOINT), TGAPST(NPOINT),
     .          TEMPIT(NPOINT,2),      ADVELT(NTOTVT*NDIMET),
     .          FPCHAT(NFPCH,NPOINT),  LACTIT(NELEMT)
C
C**** GLOBAL CONVERGENCE FOR OUTPUT
C
      NCKGLO=0
      IF(ISTAGGS.EQ.1) NCKGLO=1
C
C**** INITIALISES THE INTERCHANGES ITERATION NUMBER
C
      IITERCS=0
C
C**** TRANSFER NODAL MICROSTRUCTURAL VARIABLES TO THERMAL PROBLEM
C
c     CALL TRASMEC(DISTO, PWORK, PREAS, TGAPS,
c    .             DISPLT,PWORKT,PREAST(1,1),TGAPST)
C
C**** TRANSFER GAUSSIAN MICROSTRUCTURAL VARIABLES TO THERMAL PROBLEM
C
c     CALL TRASMEG(ELVAR,ELVART)
C
C**** ADVANCE ON TIME AND PREDICT RESPONSE FOR THE THERMAL PROBLEM
C
      DO ISSTEPT=1,NSSTEPT           !  SUBINCREMENTS
C
       CALL TMSTEPT(DISITT,DISPRT,DISTOT,ELDATT,ELPRET,
     .              ELVART,ELMATT,HEADST,HTLODT,IFFIXT,
     .              PRESCT,LNODST,MATNOT,PROELT,PROPST,
     .              REFORT,RLOADT,RLOAHT,FICTOT,TFICTT,
     .              TLOADT,DISPLT,PWORKT,PREAST,TGAPST,
     .              COORDT,TEMPIT,ADVELT,FPCHAT,LACTIT,
     .              LPNTNT,WORK1T)
C
C**** LOOP ON ITERATIONS FOR THE THERMAL PROBLEM
C
       DO WHILE
     .  ((NCHEKT.NE.0).AND.(IITERT.LE.MITERT))
C
C**** ITERATIVE CORRECTION FOR THE THERMAL PROBLEM
C
        CALL ITERATT(DISITT,DISPRT,DISTOT,ELDATT,ELPRET,
     .               ELVART,ELMATT,HEADST,IFFIXT,PRESCT,
     .               LNODST,MATNOT,PROELT,PROPST,REFORT,
     .               RLOADT,FICTOT,TLOADT,DISPLT,PWORKT,
     .               PREAST,TGAPST,COORDT,TEMPIT,ADVELT,
     .               FPCHAT,LACTIT,HTLODT,WORK1T)
C
       ENDDO
C
       IF(NCHEKT.NE.0)
     .  CALL RUNENDT(' NOT CONVERGED                    ') 
C
C**** CHECK FOR ANALYSIS TERMINATION FOR THE THERMAL PROBLEM
C
       IF(NSSTEPT.GT.1)
     .  CALL FINISHT(DISPRT,DISTOT,ELPRET,ELVART,HEADST,HTLODT,
     .               IFFIXT,REFORT,RLOADT,TLOADT,PWORKT,TEMPIT)
C
      ENDDO             ! LOOP OF SUBINCREMENTS
C
C**** WRITES THE INTERCHANGES ITERATION NUMBER
C
      IITERCS=1
      WRITE(LUPRIS,900) IITERCS
      WRITE(LUPRIT,900) IITERCS
  900 FORMAT('INTERCHANGES ITERATION NUMBER = ',I5)
C
C**** TRANSFER THERMAL VARIABLES TO MICROSTRUCTURAL PROBLEM
C
c     CALL TRASTER(DISTOT,TEMPIT,FPCHAT,PWORKT,TEMPN,DTEMP,FPCHA,PWORK)
C
C**** ADVANCE ON TIME AND PREDICT RESPONSE FOR THE MICROSTRUCTURAL PROB.
C
      DO ISSTEPS=1,NSSTEPS             !  SUBINCREMENTS
C
c      IF(NSSTEPS.GT.1) CALL SUBINCS(TEMPN,DTEMP,FPCHA,ISSTEP)
C
       CALL TMSTEPS(DISITS,DISPRS,DISTOS,ELDATS,ELPRES,
     .              ELVARS,ELMATS,HEADSS,HTLODS,IFFIXS,
     .              PRESCS,LNODSS,MATNOS,PROELS,PROPSS,
     .              REFORS,RLOADS,RLOAHS,FICTOS,TFICTS,
     .              TLOADS,DISPLS,PWORKS,PREASS,TGAPSS,
     .              COORDS,TEMPIS,ADVELS,FPCHAS,
     .              LPNTNS,WORK1S)
C
C**** LOOP ON ITERATIONS FOR THE MICROSTRUCTURAL PROBLEM
C
       DO WHILE
     .  ((NCHEKS.NE.0).AND.(IITERS.LE.MITERS))
C
C**** ITERATIVE CORRECTION FOR THE MICROSTRUCTURAL PROBLEM
C
        CALL ITERATS(DISITS,DISPRS,DISTOS,ELDATS,ELPRES,
     .               ELVARS,ELMATS,HEADSS,IFFIXS,PRESCS,
     .               LNODSS,MATNOS,PROELS,PROPSS,REFORS,
     .               RLOADS,FICTOS,TLOADS,DISPLS,PWORKS,
     .               PREASS,TGAPSS,COORDS,TEMPIS,ADVELS,
     .               FPCHAS,WORK1S)
C
       ENDDO
C
       IF(NCHEKS.NE.0)
     .  CALL RUNENDS(' NOT CONVERGED                    ') 
C
C**** CHECK FOR ANALYSIS TERMINATION FOR THE MICROSTRUCTURAL PROBLEM
C
       IF(NSSTEPS.GT.1)
     .  CALL FINISHS(DISPRS,DISTOS,ELPRES,ELVARS,HEADSS,HTLODS,
     .               IFFIXS,REFORS,RLOADS,TLOADS,PWORKS,TEMPIS)
C
      ENDDO             ! LOOP OF SUBINCREMENTS
C
      RETURN
      END
