      SUBROUTINE COUSTA0S(LNODSS,MATNOS,PROELS,PROPSS,COORDS,HTLODS,
     .                    IFFIXS,PRESCS,RLOADS,RLOAHS,FICTOS,TFICTS,
     .                    DISITS,DISPRS,DISTOS,HEADSS,REFORS,TLOADS,
     .                    LPNTNS,ELDATS,ELPRES,ELVARS,ELMATS,DISPLS,
     .                    PWORKS,PREASS,TGAPSS,TEMPIS,ADVELS,FPCHAS,
     .                    LACTIS,
     .                    WORK1S,
     .                    LNODST,MATNOT,PROELT,PROPST,COORDT,HTLODT,
     .                    IFFIXT,PRESCT,RLOADT,RLOAHT,FICTOT,TFICTT,
     .                    DISITT,DISPRT,DISTOT,HEADST,REFORT,TLOADT,
     .                    LPNTNT,ELDATT,ELPRET,ELVART,ELMATT,DISPLT,
     .                    PWORKT,PREAST,TGAPST,TEMPIT,ADVELT,FPCHAT,
     .                    LACTIT,
     .                    WORK1T)
C***********************************************************************
C
C**** THIS ROUTINE PERFORMS THE STAGGERED SOLUTION
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      DIMENSION LNODSS(NNODES,NELEMS),  MATNOS(NELEMS),
     .          PROELS(NPRELS,NGRUPS),  PROPSS(NPROPS,NMATSS),
     .          COORDS(NDIMES,NPOINS),  HTLODS(NHLODS,NSUBFS,NFUNCS)
      DIMENSION IFFIXS(NTOTVS,2),       PRESCS(NTOTVS,2),
     .          RLOADS(NTOTVS),         RLOAHS(NTOTVS,NFUNCS),
     .          FICTOS(NFUNCS),         TFICTS(NFUNCS)
      DIMENSION DISITS(NTOTVS,2),
     .          DISPRS(NTOTVS,3),       DISTOS(NTOTVS,3),
     .          HEADSS(NPOINS,4),
     .          REFORS(NTOTVS,2),       TLOADS(NTOTVS,2),
     .          LPNTNS(NPOINS)
      DIMENSION ELDATS(NDATAS),         ELPRES(NPREVS),
     .          ELVARS(NSTATS),         ELMATS(NMATXS)
      DIMENSION DISPLS(NTOTVMS),        PWORKS(NPOINS,3),
     .          PREASS(NPREAS,NPOINS),  TGAPSS(NPOINS),
     .          TEMPIS(NPOINS,2),       ADVELS(NTOTVS*NDIMES),
     .          FPCHAS(NFPCH,NPOINS),   LACTIS(NELEMS)
      DIMENSION WORK1S(*)
C
C**** THERMAL VARIABLES
C
      DIMENSION LNODST(NNODET,NELEMT), MATNOT(NELEMT),
     .          PROELT(NPRELT,NGRUPT), PROPST(NPROPT,NMATST),
     .          COORDT(NDIMET,NPOINT), HTLODT(NHLODT,NSUBFT,NFUNCT)
      DIMENSION IFFIXT(NTOTVT,2),      PRESCT(NTOTVT,2),
     .          RLOADT(NTOTVT),        RLOAHT(NTOTVT,NFUNCT),
     .          FICTOT(NFUNCT),        TFICTT(NFUNCT)
      DIMENSION DISITT(NTOTVT,2),
     .          DISPRT(NTOTVT,3),      DISTOT(NTOTVT,3),
     .          HEADST(NPOINT,4),
     .          REFORT(NTOTVT,2),      TLOADT(NTOTVT,2),
     .          LPNTNT(NPOINT)
      DIMENSION ELDATT(NDATAT),        ELPRET(NPREVT),
     .          ELVART(NSTATT),        ELMATT(NMATXT)
      DIMENSION DISPLT(NTOTVM),        PWORKT(NPOINT,3),
     .          PREAST(NPREAT,NPOINT), TGAPST(NPOINT),
     .          TEMPIT(NPOINT,2),      ADVELT(NTOTVT*NDIMET),
     .          FPCHAT(NFPCH,NPOINT),  LACTIT(NELEMT)
      DIMENSION WORK1T(*)
C
  100 CONTINUE
C
C**** TRANSFER NODAL MICROSTRUCTURAL VARIABLES TO THERMAL PROBLEM
C
c     CALL TRASMEC(DISTO, PWORK, PREAS, TGAPS,
c    .             DISPLT,PWORKT,PREAST(1,1),TGAPST)
C
C**** TRANSFER GAUSSIAN MICROSTRUCTURAL VARIABLES TO THERMAL PROBLEM
C
c     CALL TRASMEG(ELVAR,ELVART)
C
C**** INITIALISE ITERATIVE TEMPERATURES
C
      DO ITOTVT=1,NTOTVT
       DISITT(ITOTVT,1)=0.0D0
      END DO
C
C**** CALCULATES THE "THERMAL RESIDUAL FORCES"
C
      CALL RESIDUT(DISITT,DISPRT,DISTOT,ELDATT,ELPRET,ELVART,ELMATT,
     .             HEADST,IFFIXT,LNODST,MATNOT,PROELT,PROPST,REFORT,
     .            TLOADT,DISPLT,PWORKT,PREAST(1,1),TGAPST,COORDT,TEMPIT,
     .             ADVELT,FPCHAT,LACTIT,HTLODT,WORK1T)
C
C**** CHECK CONVERGENCE FOR THE THERMAL PROBLEM
C
      CALL CONVERT(DISITT,DISPRT,DISTOT,REFORT,TLOADT,IFFIXT)
C
      IF(NCHEKT.NE.0) THEN
C
C**** THERMAL PROBLEM OUTPUT (NOT CONVERGED)
C
       IF(IPRCOT.EQ.0)
     .  CALL OUTPUTT(DISTOT,ELDATT,ELPRET,ELVART,ELMATT,HEADST,
     .               IFFIXT,LNODST,MATNOT,PROELT,PROPST,TLOADT,
     .               COORDT,FPCHAT,PREAST(NPRE1T+1,1),DISPLT,LACTIT,
     .               WORK1T)
C
C**** LOOP ON ITERATIONS FOR THE THERMAL PROBLEM
C
       DO WHILE
     .    ((NCHEKT.NE.0).AND.(IITERT.LE.MITERT))
C
C**** ITERATIVE CORRECTION FOR THE THERMAL PROBLEM
C
        CALL ITERATT(DISITT,DISPRT,DISTOT,ELDATT,ELPRET,
     .               ELVART,ELMATT,HEADST,IFFIXT,PRESCT,
     .               LNODST,MATNOT,PROELT,PROPST,REFORT,
     .               RLOADT,FICTOT,TLOADT,DISPLT,PWORKT,
     .               PREAST,TGAPST,COORDT,TEMPIT,ADVELT,
     .               FPCHAT,LACTIT,HTLODT,WORK1T)
C
       ENDDO
C
       IF(NCHEKT.NE.0)
     .  CALL RUNENDT(' NOT CONVERGED                    ') 
C
C**** WRITES THE INTERCHANGES ITERATION NUMBER
C
       IITERCS=IITERCS+1
       WRITE(LUPRIS,900) IITERCS
       WRITE(LUPRIT,900) IITERCS
  900  FORMAT('INTERCHANGES ITERATION NUMBER = ',I5)
C
C**** TRANSFER THERMAL VARIABLES TO MICROSTRUCTURAL PROBLEM
C
c      CALL TRASTER(DISTOT,TEMPIT,FPCHAT,PWORKT,TEMPN,DTEMP,FPCHA,PWORK)
C
C**** INITIALISE ITERATIVE DISPLACEMENTS
C
       DO ITOTVS=1,NTOTVS
        DISITS(ITOTVS,1)=0.0D0
       END DO
C
C**** CALCULATES THE MICROSTRUCTURAL RESIDUAL FORCES
C
       CALL RESIDUS(DISITS,DISPRS,DISTOS,ELDATS,ELPRES,ELVARS,ELMATS,
     .              HEADSS,IFFIXS,LNODSS,MATNOS,PROELS,PROPST,REFORS,
     .              TLOADS,DISPLS,PWORKS,PREASS(1,1),TGAPSS,COORDS,
     .              TEMPIS,
     .              ADVELS,FPCHAS,WORK1S)
C
C**** CHECK CONVERGENCE FOR THE MICROSTRUCTURAL PROBLEM
C
       CALL CONVERS(DISITS,DISPRS,DISTOS,REFORS,TLOADS,IFFIXS)
C
       IF(NCHEKS.NE.0) THEN
C
C**** MICROSTRUCTURAL PROBLEM OUTPUT (NOT CONVERGED)
C
        IF(IPRCOS.EQ.0)
     .   CALL OUTPUTS(DISTOS,ELDATS,ELPRES,ELVARS,ELMATS,HEADSS,
     .                IFFIXS,LNODSS,MATNOS,PROELS,PROPSS,TLOADS,
     .                COORDS,FPCHAS,PREASS(NPRE1S+1,1),DISPLS,WORK1S)
C
C**** LOOP ON ITERATIONS FOR THE MICROSTRUCTURAL PROBLEM
C
        DO WHILE
     .     ((NCHEKS.NE.0).AND.(IITERS.LE.MITERS))
C
C**** ITERATIVE CORRECTION FOR THE MICROSTRUCTURAL PROBLEM
C
         CALL ITERATS(DISITS,DISPRS,DISTOS,ELDATS,ELPRES,
     .                ELVARS,ELMATS,HEADSS,IFFIXS,PRESCS,
     .                LNODSS,MATNOS,PROELS,PROPSS,REFORS,
     .                RLOADS,FICTOS,TLOADS,DISPLS,PWORKS,
     .                PREASS,TGAPSS,COORDS,TEMPIS,ADVELS,
     .                FPCHAS,WORK1S)
C
        ENDDO
C
        IF(NCHEKS.NE.0)
     .   CALL RUNENDS(' NOT CONVERGED                    ')
C
        GO TO 100
       ENDIF  ! microstructural problem is converged => global converg.
      ENDIF   ! thermal problem is converged => global convergence
C
C**** GLOBAL CONVERGENCE FOR OUTPUT
C
      NCKGLO=0
C
C**** THERMAL PROBLEM OUTPUT (GLOBAL CONVERGED)
C
      IF(IPRCOT.EQ.0)
     . CALL OUTPUTT(DISTOT,ELDATT,ELPRET,ELVART,ELMATT,HEADST,
     .              IFFIXT,LNODST,MATNOT,PROELT,PROPST,TLOADT,
     .              COORDT,FPCHAT,PREAST(NPRE1T+1,1),DISPLT,LACTIT,
     .              WORK1T)
C
C**** MICROSTRUCTURAL PROBLEM OUTPUT (GLOBAL CONVERGED)
C
      IF(IPRCOS.EQ.0)
     . CALL OUTPUTS(DISTOS,ELDATS,ELPRES,ELVARS,ELMATS,HEADSS,
     .              IFFIXS,LNODSS,MATNOS,PROELS,PROPSS,TLOADS,
     .              COORDS,FPCHAS,PREASS(NPRE1S+1,1),DISPLS,WORK1S)
C
      RETURN
      END
