
      SUBROUTINE CRKGBL(DMATX,DUMMY,BETAM,TRANS,NDIME,NSTRS)
C***********************************************************************
C
C****THIS ROUTINE TRANSFORMS THE D-MATRIX TO THE GLOBAL SYSTEM
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION DMATX(NSTRS,*), DUMMY(*), BETAM(NDIME,*), TRANS(NSTRS,*)
C
C***BUILD TRANSFORMATION MATRIX
C
      IF(NSTRS.EQ.3) CALL TRANS3(BETAM,TRANS,'STRAIN','G_TO_L')
      IF(NSTRS.EQ.4) CALL TRANS4(BETAM,TRANS,'STRAIN','G_TO_L')
      IF(NSTRS.EQ.6) CALL TRANS6(BETAM,TRANS,'STRAIN','G_TO_L')
C
C***TRANSFORM D-MATRIX TO GLOBAL SYSTEM
C
      DO 20 ISTRE=1,NSTRS
      DO 20 JSTRE=1,NSTRS
      DO 20 KSTRE=1,NSTRS
      DMATX(ISTRE,JSTRE)=DMATX(ISTRE,JSTRE)+
     .     TRANS(KSTRE,ISTRE)*DUMMY(KSTRE)*TRANS(KSTRE,JSTRE)
   20 CONTINUE
C
      RETURN
      END
