      SUBROUTINE DATBASS(ARRAYS,IFLAGS,ITASKS)
C***********************************************************************
C
C**** THIS ROUTINE INTERFACES VULCAN-DATA WITH DATABASE-FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8, ALLOCATABLE :: BUFFERS(:), TEMPS(:)
      INTEGER, SAVE       :: INIT=0,NBUFFERS,NBUFFERSTMP
      INTEGER             :: ERROR

      SAVE BUFFERS
C
C**** GENERAL DIMENSIONS
C
      INCLUDE 'para_oms.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'auxl_oms.f'
      INCLUDE 'prob_oms.f'
C
C
      DIMENSION ARRAYS(*)
C
C**** BEGIN
C
c     NUNITS=LUDTSS                                ! .dts
C
      IF(IDATPS(IFLAGS,5).LT.0) THEN               ! DATA IS OUT-CORE
       NUNITS=LUDTSS                               ! .dts
C
       NRECDS=(IELEMS-1)*NLENPS+IDATPS(IFLAGS,4)+1
       CALL RESTDKS(NUNITS,ITASKS,ARRAYS,IDATPS(IFLAGS,1)*2,LENRCS,
     .              NRECDS)
C
      ELSE                                         ! DATA IS IN-CORE
C
       IF(IFLAGS.EQ.12) THEN ! ACCESS TO DISTO
        NRECDS=1
       ELSE 
        NRECDS=NTOTVS+(IELEMS-1)*NWORPS+IDATPS(IFLAGS,3)+1
       ENDIF

C
C**** INICIALIZA LA VARIABLE BUFFERS
C
       IF(INIT.EQ.0) THEN
        NBUFFERS=(NRECDS+IDATPS(IFLAGS,1))*64
        ERROR=0
        ALLOCATE(BUFFERS(NBUFFERS),STAT=ERROR)
        WRITE(LURESS,*) "INITIAL ALLOCATION FOR BUFFERS"
        IF(ERROR.NE.0)CALL RUNEND("CANT ALLOCATE BUFFERS IN datbass.f")
        INIT=1
       END IF
C
C**** SE COMPRUEBA Y SE REDIMENSIONA SI ES NECESARIO LA VARIABLE BUFFER
C
      NBUFFERSTMP=(NRECDS+IDATPS(IFLAGS,1))
      IF(NBUFFERSTMP.GT.NBUFFERS) THEN
       ERROR=0
       IF (1.5*NBUFFERS.GT.NBUFFERSTMP) NBUFFERSTMP=1.5*NBUFFERS
       WRITE(LURESS,*) "REALLOCATE BUFFERS (FROM, TO, NEED)",
     .            NBUFFERS,NBUFFERSTMP,NRECDS+IDATPS(IFLAGS,1)
       WRITE(LURESS,*) 'REQUIRED DATABASE MEMORY (PERMANENT) ='
     .                 ,NBUFFERSTMP/(1024.0*1024.0)*8.0,'MB'
       ALLOCATE(TEMPS(NBUFFERSTMP),STAT=ERROR)
       IF(ERROR.NE.0)CALL RUNEND("CANT REALLOCATE BUFFERS IN datbass.f")
       TEMPS(1:NBUFFERS)=BUFFERS(:)
       CALL MOVE_ALLOC(FROM=TEMPS, TO=BUFFERS)
       NBUFFERS=NBUFFERSTMP
      END IF

       CALL RESTVM(BUFFERS,ITASKS,ARRAYS,IDATPS(IFLAGS,1),NRECDS)
C
      ENDIF
C
      RETURN
      END
