      SUBROUTINE ELASTI(NSTRS,NTYPE,EPMTX,PROPS,RMAT2,ncrit)
C**********************************************************************
C
C****THIS ROUTINE BUILDS UP THE ELASTIC MATRIX FOR AN
C    ANYSOTROPIC MEDIUM
C
C**********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EPMTX(*),       PROPS(*),       RMAT2(NSTRS,*)
      DIMENSION EPMT1(6*5/2+6)
C
C***THE PRINCIPAL DIRECTION OF THE ELASTIC TENSOR COINCIDE WITH 
C   THE REFERENCE SYSTEM
C
      IF(PROPS(1).EQ.0.) THEN
        CALL DMATRI(EPMTX,NSTRS,NTYPE,PROPS)
      ELSE
C
C***ROTATE THE ELASTIC TENSOR TO BE TRANSFORMED TO THE REFERENCE
C   SYSTEM
C
        if(ncrit.eq.10) then
         CALL DMATRU(EPMT1,NSTRS,NTYPE,PROPS)
        else
         CALL DMATRI(EPMT1,NSTRS,NTYPE,PROPS)
        endif
c
         CALL BDBCO2(RMAT2,EPMT1,EPMTX,NSTRS,NSTRS)
C
      ENDIF
C
      RETURN
      END
