
      SUBROUTINE EQUIVA(EFFST,EHIST,NCRIT,NTYPE,PREDV,PREJ2,PREJ3,
     .                  PREMN,PRESG,PREYS,PROPS,SIGYS,SIGMA)
C***********************************************************************
C
C****THIS ROUTINE CALCULATES THE EQUIVALENT STRESSES
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EHIST(*), PREDV(*), PRESG(*), PROPS(*), SIGDV(6),
     .          SIGMA(*)
      FUNC1(PMEAN,QINVA,FINCL)=QINVA/FINCL+PMEAN
      FUNC2(PMEAN,QINVA,BETAS,RATIO)=DSQRT((PMEAN-BETAS)**2+
     .     (QINVA/RATIO)**2)
C
C***CALCULATE THE EQUIVALENT PRESSURE FOR PREVIOUS & CURRENT STRESS.
C
      CALL INVARS(PRESG,PREDV,NTYPE,PREMN,PREQU,PRETH,PREJ2,
     .            PREJ3)
      CALL INVARS(SIGMA,SIGDV,NTYPE,SIGMN,SIGQU,SIGTH,SIGJ2,
     .            SIGJ3)
C
      PHIAN=PROPS(14)
      IF(NCRIT.EQ.2.AND.PHIAN.EQ.0.)GOTO 10
      IF(NCRIT.EQ.2.AND.PHIAN.GT.0.)GOTO 20
      IF(NCRIT.EQ.4)GOTO 50
C
C***CALCULATE  RATIO ONLY FOR MOHR-COULOMB CASE
C
      CALL VARTHE(CAPTH,PRECI,PREFI,IFLAG,PROPS,PRETH)
      CALL VARTHE(CAPTH,SIGCI,SIGFI,IFLAG,PROPS,SIGTH)
C
      IF(NCRIT.EQ.1.AND.PHIAN.EQ.0.)GOTO 30
      IF(NCRIT.EQ.1.AND.PHIAN.GT.0.)GOTO 40
      IF(NCRIT.EQ.3)GOTO 60
C
C***CALCULATE THE PRE-YIELD AND THE CURRENT YIELD
C
C***LINEAR PLASTIC MODEL
C
   10 PRECI=PROPS(33)
      SIGCI=PROPS(33)
C
C***VON MISES & TRESCA
C
   30 EFFST=PROPS(31)
      PREYS=PREQU/PRECI
      SIGYS=SIGQU/SIGCI
C
      RETURN
C
C***DRUCKER-PRAGER & MOHR-COULOMB
C
   20 PREFI=PROPS(34)
      SIGFI=PROPS(34)
C
   40 EFFST=PROPS(31)
      PREYS=FUNC1(PREMN,PREQU,PREFI)
      SIGYS=FUNC1(SIGMN,SIGQU,SIGFI)  
C
      RETURN
C
C***CAM-CLAY
C
   50 PRERT=PROPS(34)
      SIGRT=PROPS(34)
      GOTO 70
C
   60 PRERT=PROPS(35)*PREFI
      SIGRT=PROPS(35)*SIGFI
C
   70 EFFST=EHIST(3)
      BETAS=EHIST(4)
      PREYS=FUNC2(PREMN,PREQU,BETAS,PRERT)
      SIGYS=FUNC2(SIGMN,SIGQU,BETAS,SIGRT)
C
      RETURN
      END
