      SUBROUTINE FACTOR(DESIG,EHIST,KGAUS,NCRIT,NTYPE,PREDV,PREMN,
     .                  PREJ2,PREJ3,PROPS,REDUC)
C***********************************************************************
C
C****THIS ROUTINE CALCULATES THE REDUCTION FACTOR TO BE APPLIED TO 
C    DSIGMA IN ORDER TO HAVE THE TOTAL STRESS ON THE SURFACE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION DESDV(6), DESIG(*), EHIST(*), PREDV(*), PROPS(*)
C
C***SET UP CONSTANT
C
      CALL FACOEF(DESIG,DESMN,DESJ2,DESJ3,NCRIT,NTYPE,PREDV,
     .            WCOJ3,YCOJ3,ZCOJ2)
C
      IF(NCRIT.EQ.2)GOTO 10
      IF(NCRIT.EQ.4)GOTO 20
C
C***CALCULATES REDUC. FACT. WHEN IT DOES NOT EXIT A CLOSE FORM SOLUTION
C
      CALL BISECT(DESMN,DESJ2,DESJ3,EHIST,KGAUS,NCRIT,PREMN,
     .            PREJ2,PREJ3,PROPS,REDUC,WCOJ3,YCOJ3,ZCOJ2)
C
      RETURN
C
C***CALCULATES REDUCTION FACT. WHEN EXIT A CLOSE FORM SOLUTION
C
C***LINEAR PLASTIC MODEL
C
   10 CALL SOLVE1(DESJ2,DESMN,KGAUS,PREJ2,PREMN,PROPS,REDUC,
     .            ZCOJ2)
C
      RETURN
C
C***CAM CLAY
C
   20 CALL SOLVE2(DESJ2,DESMN,EHIST,KGAUS,PREJ2,PREMN,PROPS,
     .            REDUC,ZCOJ2)
C
      RETURN
      END
