      SUBROUTINE FINISHT(DISPRT,DISTOT,ELPRET,ELVART,HEADST,HTLODT,
     .                   IFFIXT,REFORT,RLOADT,TLOADT,PWORKT,TEMPIT)
C***********************************************************************
C
C**** THIS ROUTINE SAVES THE CONVERGED VALUES AND CHECKS FOR ANALYSIS
C     TERMINATION
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
      DIMENSION  DISPRT(NTOTVT,3),    DISTOT(NTOTVT,3),
     .           ELPRET(NPREVT),      ELVART(NSTATT),          
     .           HEADST(NPOINT,4),    HTLODT(NHLODT,NSUBFT,NFUNCT),    
     .           IFFIXT(NTOTVT,2),    REFORT(NTOTVT),          
     .           RLOADT(NTOTVT),      TLOADT(NTOTVT,2),
     .           PWORKT(NPOINT,3),    TEMPIT(NTOTVT,2)
C
C**** CHECK IF CPU TIME IS RUNNING OUT
C
      ILATET=0
      CALL CPUTIMT(CUCPUT)
      IF(CUCPUT.GE.0.95*TLIMTT) ILATET=1
C
C**** COMPUTE SOME CONVERGED VALUES 
C
      CALL STIPART(DISPRT,IFFIXT,TLOADT,REFORT,PWORKT)
C
C**** SAVE CONVERGED VALUES AND WRITE TO RESTART FILE IF NECESSARY
C
      CALL STOREST(DISPRT,DISTOT,ELPRET,ELVART,HEADST,HTLODT,IFFIXT,
     .             REFORT,RLOADT,TLOADT,TEMPIT,ILATET)
C
C**** CHECK FOR ANALYSIS TERMINATION
C
      IF(CUCPUT.GE.TLIMTT)
     .     CALL RUNENDT(' CPU TIME EXPIRED                  ')
      IF(STIFIT.NE.0.0.AND.STICUT.LT.STIFIT) 
     .     CALL RUNENDT(' FINAL STIFFNESS REACHED           ')
C
      RETURN
      END
