      SUBROUTINE FIXITYS(IFFIXS,LNODSS,PRESCS,PRESHS,ELDATS,MATNOS,
     .                   PROELS,WORK1S)
C***********************************************************************
C
C**** THIS ROUTINE READS AND SETS DATA FOR FIXITY CONDITIONS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'inpo_oms.f'
      INCLUDE 'prob_oms.f'
C
      COMMON/LDFILES/ITAPES
C
      DIMENSION IFFIXS(NTOTVS,*), LNODSS(NNODES,*), PRESCS(NTOTVS,2)
      DIMENSION PRESHS(*)
      DIMENSION ELDATS(*),        MATNOS(*),        PROELS(*),
     .          WORK1S(*)
C
c     IERR1T=1
c     IF(ITAPET.NE.LUDATT.AND.ITAPET.NE.LUFIXT) GOTO 1000
c     IF(ITAPET.EQ.LUFIXT) THEN       ! external .fix file
c      OPEN(UNIT=LUFIXT,FILE=CF1T,STATUS='OLD',ERR=1000)
c      IERR1T=0
C
c1000  IF(IERR1T.NE.0) THEN
c       IF(IERR1T.EQ.1) WRITE(LUREST,901)
c       CALL RUNENDT('ERROR IN OPENING FILE ')
c      ENDIF
c     ENDIF      ! itapet.eq.lufixt
C
C**** INITIALISE FIXITY ARRAY
C
      WRITE(LURESS,900)
C
      DO 10 ITOTVS=1,NTOTVS
   10 IFFIXS(ITOTVS,1)=0
C
      IF(KSMUSS.NE.0) THEN
       DO 12 ITOTVS=1,NTOTVS
   12  IFFIXS(ITOTVS,2)=0
       DO 15 IPOINS=1,NPOINS
       ITOTVS=IPOINS*NDOFCS
   15  IFFIXS(ITOTVS,2)=1
      ENDIF
C
C**** READ THE FIXITY CONDITIONS AND PRESCRIBED VALUES
C
c   20 IF(NDOFNT.LE.4) THEN
c        READ(ITAPET,910) NOFIXT,IFPRET,(PRESCT(IDOFNT),IDOFNT=1,NDOFCT)
c      ELSE
c        READ(ITAPET,915) NOFIXT,IFPRET,(PRESCT(IDOFNT),IDOFNT=1,NDOFCT)
c      ENDIF
c      WRITE(LUREST,920)  NOFIXT,IFPRET,(PRESCT(IDOFNT),IDOFNT=1,NDOFCT)
C
   20 NPRINS=1
      CALL LISTENS('FIXITYS',NPRINS,ITAPES)
      NOFIXS=DINT(PARAMS(1))
      IFPRES=DINT(PARAMS(2))
      IFUNCS=DINT(PARAMS(3))
      IF(NOFIXS.LE.0.OR.NOFIXS.GT.NPOINS)
     . CALL RUNENDS('ERROR: WRONG NUMBER OF PRESCRIBED NODE')
      DO IDOFNS=1,NDOFNS
       PRESHS(IDOFNS)=PARAMS(IDOFNS+3)
      ENDDO
      WRITE(LURESS,920) NOFIXS,IFPRES,IFUNCS,
     .                 (PRESHS(IDOFNS),IDOFNS=1,NDOFCS)
C
      NLOCAS=(NOFIXS-1)*NDOFCS
      IFDOCS=10**(NDOFCS-1)
C
      DO 30 IDOFCS=1,NDOFCS
      ITOTVS=NLOCAS+IDOFCS
      IF(IFPRES.LT.IFDOCS) GOTO 30
      IFFIXS(ITOTVS,1)=1
      IF(KSMUSS.NE.0) IFFIXS(ITOTVS,2)=1
      PRESCS(ITOTVS,1)=PRESHS(IDOFCS)
      PRESCS(ITOTVS,2)=IFUNCS
      IFPRES=IFPRES-IFDOCS
   30 IFDOCS=IFDOCS/10
C
      IF(NOFIXS.LT.NPOINS) GOTO 20
C
      WRITE(LURESS,925)
C
      RETURN
  900 FORMAT(//10X,5H NODE,10X,5H CODE,10X,6H FUNC.,6X,
     .       12HFIXED VALUES)
  901 FORMAT(' ERROR IN OPENING BOUNDARY CONDITIONS INPUT FILE 245',
     . '(55 LINUX)')
c 910 FORMAT(2I5,10F10.6)
c 915 FORMAT(I5,I10,10F10.6)
  920 FORMAT(3(5X,I10),5X,1F10.6)
  925 FORMAT(/)
      END
