      SUBROUTINE FROBAK(DISIT,ELOAD,EQRHS,EQUAT,IDSK2,IDSK3,IFFIX,
     .                  IPASS,KELVA,KRESL,NBUFA,NBUFE,NFRON,NAMEV,
     .                  NPIVO,NREC2,NREC3,NSTIF,VECRV,EQCOL,KSYMM)
C***********************************************************************
C
C**** THIS ROUTINE UNDERTAKES EQUATION SOLUTION BY THE FRONTAL
C     METHOD
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION DISIT(*), ELOAD(*), IFFIX(*)
      DIMENSION EQRHS(NBUFA), EQUAT(NFRON,NBUFA), NAMEV(NBUFA),       
     .          NPIVO(NBUFA), VECRV(NFRON),       EQCOL(NFRON,NBUFA)
C
      NREC2=NREC2-1
C
C**** ENTER BACK-SUBSTITUTION PHASE. LOOP BACKWARDS THROUGH VARIABLES
C
      DO 100 IELVA=1,KELVA
C
C**** READ A NEW BLOCK OF EQUATIONS - IF NEEDED
C
      IF(NBUFE.NE.0)GOTO 10
      IF(KSYMM.EQ.0) THEN
       READ(IDSK2,REC=NREC2) EQUAT,EQCOL,EQRHS,NPIVO,NAMEV
      ELSE
       READ(IDSK2,REC=NREC2) EQUAT,EQRHS,NPIVO,NAMEV
      ENDIF
      NREC2=NREC2-1
      NBUFE=NBUFA
      IF(KRESL.EQ.1)GOTO 10
      READ(IDSK3,REC=NREC3) EQRHS
      NREC3=NREC3-1
   10 CONTINUE
C
C**** PREPARE TO BACK-SUBSTITUTE FROM THE CURRENT EQUATION
C
      IFRON=NPIVO(NBUFE)
      NIKNO=NAMEV(NBUFE)
      PIVOT=EQUAT(IFRON,NBUFE)
      IF(IFFIX(NIKNO).NE.0)VECRV(IFRON)=DISIT(NIKNO)
      IF(IFFIX(NIKNO).EQ.0)EQUAT(IFRON,NBUFE)=0.0
C
C**** BACK-SUBSTITUTE IN THE CURRENT EQUATION
C
      DO 20 JFRON=1,NFRON
   20 EQRHS(NBUFE)=EQRHS(NBUFE)-VECRV(JFRON)*EQUAT(JFRON,NBUFE)
C
C**** PUT THE FINAL VALUES WHERE THEY BELONG
C
      IF(IFFIX(NIKNO).NE.0.AND.IPASS.EQ.2) ELOAD(NIKNO)=-EQRHS(NBUFE)
      IF(IFFIX(NIKNO).EQ.0) VECRV(IFRON)=EQRHS(NBUFE)/PIVOT
      NBUFE=NBUFE-1
      DISIT(NIKNO)=VECRV(IFRON)
  100 CONTINUE
C
      RETURN
      END
