      SUBROUTINE FROTAP(KFRON,LOCEL,NACVA,NDEST,NEVAB,NFRON)
C***********************************************************************
C
C**** THIS ROUTINE READS FROM TAPE THE DESTINATION OF THE CURRENT
C     ELEMENTAL EQUATION INTO FRONT
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      COMMON/LOGUN/LUDTS,LUSOL,LUFRO,LUFRH,LUDAT,LUPRI,LURES,
     .             LUSO2,LUFR2,LUPOS,LURST,LUBFG,LUPIP,LUPAN,LUINF,
     .             LUGEO,LUSET,LUMAT,LUINI,LULOA,LUFIX,LUIN1,
     .             LUTUN,LUCON,LUACT,LUFAN,
     .             LUCU1,LUCU2,LUCU3,LUCU4,LUCU5,LUCU6,LUCU7,
     .             LUCU8,LUCU9,LUC10
C
      DIMENSION LOCEL(NEVAB), NACVA(NFRON), NDEST(NEVAB)
C
      READ(LUFRH) LOCEL,NDEST,KFRON
      READ(LUFRH) (NACVA(IACVA), IACVA=1,KFRON)
C
      DO IACVA=KFRON+1,NFRON
       NACVA(IACVA)=0
      ENDDO
C
      RETURN
      END
