
      SUBROUTINE GRAVEC(AVECT,CONS1,CONS2,CONS3,DEVIA,NSTR1,VARJ2,
     .                  VECA3)
C***********************************************************************
C
C****THIS ROUTINE EVALUATES THE FLOW VECTOR
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION AVECT(*), DEVIA(*), VECA1(6), VECA3(*)
      DATA VECA1/1.,1.,0.,1.,0.,0./
      VARDE=VARJ2/3.
      IF(NSTR1.EQ.6)GOTO 10
C
C***CALCULATE VECTOR A3
C
      VECA3(1)= DEVIA(2)*DEVIA(4)+VARDE
      VECA3(2)= DEVIA(1)*DEVIA(4)+VARDE
      VECA3(3)=-DEVIA(3)*DEVIA(4)
      VECA3(4)= DEVIA(1)*DEVIA(2)-DEVIA(3)*DEVIA(3)+VARDE
C
      GOTO 20
C
C***3-D CASE
C
   10 CONTINUE
      VECA3(1)= DEVIA(2)*DEVIA(4)-DEVIA(6)*DEVIA(6)+VARDE
      VECA3(2)= DEVIA(1)*DEVIA(4)-DEVIA(5)*DEVIA(5)+VARDE
      VECA3(3)=(DEVIA(5)*DEVIA(6)-DEVIA(4)*DEVIA(3))*2.
      VECA3(4)= DEVIA(1)*DEVIA(2)-DEVIA(3)*DEVIA(3)+VARDE
      VECA3(5)=(DEVIA(3)*DEVIA(6)-DEVIA(2)*DEVIA(5))*2.
      VECA3(6)=(DEVIA(3)*DEVIA(5)-DEVIA(1)*DEVIA(2))*2.
C
C***SET UP GRADIENT VECTOR COMPONENTS
C
   20 DO 30 ISTR1=1,NSTR1
      AVECT(ISTR1)=CONS1*VECA1(ISTR1)+CONS2*DEVIA(ISTR1)+
     .             CONS3*VECA3(ISTR1)
   30 CONTINUE
C
      AVECT(3)=2.*AVECT(3)
      AVECT(5)=2.*AVECT(5)
      AVECT(6)=2.*AVECT(6)
C
      RETURN
      END
