      SUBROUTINE IDEPROS2(PROPST,IPLAT,IA1)
C***********************************************************************
C
C**** THIS ROUTINE ORDERS THE MICROSTRUCTURAL PROPERTIES OF MODEL
C     NUMBER 2 (IPCMO=2) OF RATE PHASE-CHANGE FORMULATIONS
C
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C
C**** THERMAL VARIABLES
C
      INCLUDE 'auxl_omt.f'
      INCLUDE 'prob_omt.f'
C
      DIMENSION PROPST(*)
C
      IA2=IA1+2         ! 2=ipcfo,ipcmo
C
      CA=PROPST(IA2+1)
      SI=PROPST(IA2+2)
      PH=PROPST(IA2+3)
      CU=PROPST(IA2+4)
      QM=PROPST(IA2+5)
      QG=PROPST(IA2+6)
      CR=PROPST(IA2+7)
      AN=PROPST(IA2+8)
C
      DENS=PROPST(IA2+9)
      ESPH=PROPST(IA2+10)
      COND=PROPST(IA2+11)
      HENER=PROPST(IA2+12)
C
      IAUSM=INT(PROPST(IA2+13))
      AUSTS=PROPST(IA2+14)
      AUSTL=PROPST(IA2+15)
      AUSLA=PROPST(IA2+16)
C
      ANUCG=PROPST(IA2+17)
      ANUCC=PROPST(IA2+18)
      BGROG=PROPST(IA2+19)
      BGROC=PROPST(IA2+20)
C
      AK1LA=PROPST(IA2+21)
      AK2LA=PROPST(IA2+22)
      MAXNGL=INT(PROPST(IA2+23))
C
      IFPCDT=INT(PROPST(IA2+24))
      IAFLOJ=INT(PROPST(IA2+25))
C
      VPLAT(IPLAT,6)=CA
      VPLAT(IPLAT,7)=SI
      VPLAT(IPLAT,8)=PH
      VPLAT(IPLAT,9)=CU
      VPLAT(IPLAT,10)=QM
      VPLAT(IPLAT,11)=QG
      VPLAT(IPLAT,12)=CR
      VPLAT(IPLAT,13)=AN
C
      VPLAT(IPLAT,14)=DENS
      VPLAT(IPLAT,15)=ESPH
      VPLAT(IPLAT,16)=COND
      VPLAT(IPLAT,17)=HENER
C
      VPLAT(IPLAT,18)=FLOAT(IAUSM)
      VPLAT(IPLAT,19)=AUSTS
      VPLAT(IPLAT,20)=AUSTL
      VPLAT(IPLAT,21)=AUSLA
C
      VPLAT(IPLAT,22)=ANUCG
      VPLAT(IPLAT,23)=ANUCC
      VPLAT(IPLAT,24)=BGROG
      VPLAT(IPLAT,25)=BGROC
C
      VPLAT(IPLAT,26)=AK1LA
      VPLAT(IPLAT,27)=AK2LA
      VPLAT(IPLAT,28)=FLOAT(MAXNGL)
C
      VPLAT(IPLAT,29)=FLOAT(IFPCDT)
      VPLAT(IPLAT,30)=FLOAT(IAFLOJ)
C
      IMODE=25                  ! imode=total number of prop. of model 2
C
      IA1=IA2+IMODE
C
      RETURN
      END
