      SUBROUTINE INCFACS(HTLODS,FICTOS,TFICTS)
C***********************************************************************
C
C**** THIS ROUTINE DETERMINES THE LOAD/DISPLACEMENT FACTOR
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
C
      DIMENSION HTLODS(NHLODS,NSUBFS,*), FICTOS(NFUNCS),
     .          TFICTS(NFUNCS)
C
      DATA FACINS/0.2/
C
      IF(LAUTOS.EQ.0) THEN                         ! LOAD HISTORY
C
       CALL FUNLOD(FICTOS,HTLODS,NSUBFS,NFUNCS,NHLODS,TFICTS,TTIMES)
C
      ELSE                                        ! AUTOMATIC INCREMENT
C
c        IF(ISTEPS.EQ.1) FACTOS=DTIMES
c        IF(ISTEPS.EQ.2) FACTOS=FACINS*FACTOS 
c        IF(ISTEPS.GT.2) FACTOS=FACTOS*DSQRT(DITERS/PITERS)
c        DTIMES=FACTOS
C
      ENDIF
C
C**** PRINT TOTAL AND INCREMENTAL LOAD FACTORS
C
c      TFACTS=TFACTS+FACTOS
c      WRITE(LURESS,900) TFACTS,FACTOS
C
      DO IFUNCS=1,NFUNCS
       TFICTS(IFUNCS)=TFICTS(IFUNCS)+FICTOS(IFUNCS)
       WRITE(LURESS,900) IFUNCS,TFICTS(IFUNCS),FICTOS(IFUNCS)
      ENDDO
C
      RETURN
C
  900 FORMAT(1X,'FUNCT.',I2,5X,'CURRENT TIME FUNCT. FACTOR =',E15.5,/
     .       14X,'INCREM. TIME FUNCT. FACTOR =',E15.5,/)
      END
