      SUBROUTINE INISTR(ELDAT,ELPRE,HEADS,LNODS,MATNO,PROEL,PROPS)
C***********************************************************************
C
C**** THIS ROUTINE COMPUTES THE INITIAL STREESSES DUE TO THE INITIAL
C     PORE WATER PRESSURE DISTRIBUTION
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      DIMENSION MATNO(NELEM),       LNODS(NNODE,NELEM),
     .          PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS),
     .          ELDAT(NDATA),       ELPRE(NPREV)
      DIMENSION HEADS(*)
      DIMENSION DELTA(6)
      DATA DELTA/1.,1.,0.,1.,0.,0./
C
      INDE1=IDATA(5)
      INDE2=IPREV(2)
C
      DO 100 IELEM=1,NELEM
C
      LGRUP=MATNO(IELEM)
      LMATS=INT(PROEL(1,LGRUP))
      NNODL=INT(PROEL(2,LGRUP))
      NGAUL=INT(PROEL(4,LGRUP))
C
C***READ ELDAT ( SHAPE FUNCTIONS ) & ELPRE FROM RESTART-FILE
C
      CALL DATBAS(ELDAT,    1,    2)
      CALL DATBAS(ELPRE,    2,    2)
C
C***COMPUTE PRESSURE AT GAUSS POINTS
C
      DO 200 IGAUS=1,NGAUL
C
      INDX1=INDE1+(IGAUS-1)*NNODE-1
      INDX2=INDE2+(IGAUS-1)*NSTR1-1
C
      PORES=0.0D00
      DO 20 INODE=1,NNODL
      LNODE=LNODS(INODE,IELEM)
 20   PORES=PORES+HEADS(LNODE)*ELDAT(INDX1+INODE) ! HEADS(LNODE)*SHAPE(INODE)
C
      COMPW=PROPS(19,LMATS)     
      IF(COMPW.EQ.0.0) COMPW=1.0D00
      PORES=COMPW*PORES
C
C***CALCULATE THE INITIAL STRESS COMPONENTS
C
      DO 30 ISTR1=1,NSTR1
   30 ELPRE(INDX2+ISTR1)=ELPRE(INDX2+ISTR1)+DELTA(ISTR1)*PORES  ! STRS0
C
  200 CONTINUE
C
C***WRITE ELPRE TO RESTART-FILE
C 
      CALL DATBAS(ELPRE,    2,    1)
C
  100 CONTINUE
C
      RETURN
      END
