      SUBROUTINE INPPROT(ITAPET,PROPST,INDEXT)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MATERIAL PROPERTIES
C
C     Notes:
C           NMATST: number of materials
C           NGRUPT: number of sets
C           In general, NGRUPT ge NMATST
C
C           INDEXT=0 => material properties read at GENERAL_DATA level
C           INDEXT=1 => material properties read at INTERVAL_DATA level
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** THERMAL VARIABLES
C
      INCLUDE 'auxl_omt.f'
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION PROPST(NPROPT,*)
C
      PARAMETER(MCOMDT=5)
      PARAMETER(MCOMET=2)
      CHARACTER*5 COMMDT(MCOMDT)
      CHARACTER*5 COMMET(MCOMET)
C
      DATA COMMDT/'STISO','STORT','STANI','BOUND','AIRGA'/
      DATA COMMET/'     ','FILLI'/
C
      IERR1T=1
      IF(ITAPET.NE.LUDATT.AND.ITAPET.NE.LUMATT) GOTO 1000
      IF(INDEXT.EQ.0) THEN
       IF(ITAPET.EQ.LUMATT)                         ! external .mat file
     .  OPEN(UNIT=LUMATT,FILE=CC1T,STATUS='OLD',ERR=1000)
      ENDIF                                         ! indext.eq.0
      IERR1T=0
C
 1000 IF(IERR1T.NE.0) THEN
       IF(IERR1T.EQ.1) THEN
        WRITE(LUREST,901)
        CALL RUNENDT('ERROR IN OPENING FILES')
       ENDIF
      ENDIF
C
      WRITE(LUREST,900)
C
C**** INITIALIZATION
C
      IF(INDEXT.EQ.0) THEN
       DO IPROPT=1,NPROPT
        DO IMATST=1,NMATST
         PROPST(IPROPT,IMATST)=0.0D+00
        ENDDO
       ENDDO
      ENDIF                                         ! indext.eq.0
C
C**** READ MATERIALS PROPERTIES
C
      DO 10 IMATST=1,NMATST
C
      NPRINT=0
      CALL LISTENT('INPPROT',NPRINT,ITAPET)
C
C**** LOOK FOR 'MATERIAL_DATA' CARD
C
      IF(INDEXT.EQ.0) THEN
       IF(WORDST(1).NE.'MATER')
     .  CALL RUNENDT('INPPROT: WRONG MATERIAL_DATA CARD')
      ELSE
       IF(WORDST(1).NE.'MATER') GO TO 2000
      ENDIF
C
      IF(PARAMT(1).EQ.0.0)
     . CALL RUNENDT('INPPROT: WRONG MATERIAL NUMBER')
C
      NUMATT=INT(PARAMT(1))
C
C**** CONTROLS REPEATED MATERIALS
C
      IF(INDEXT.EQ.0) THEN
       DO IPROPT=1,NPROPT
        IF(PROPST(IPROPT,NUMATT).NE.0.0)
     .   CALL RUNENDT('ERROR IN MATERIAL NUMBER')
       ENDDO
      ENDIF
C
      DO ICOMDT=1,MCOMDT
       IF(WORDST(2).EQ.COMMDT(ICOMDT)) GOTO 100
      ENDDO
      CALL RUNENDT('INPPROT: WRONG MATERIAL CARD')
C
  100 GOTO(1,2,3,4,5), ICOMDT
C
    1 CONTINUE
      DO ICOMET=1,MCOMET
       IF(WORDST(3).EQ.COMMET(ICOMET)) GOTO 110
      ENDDO
      CALL RUNENDT('INPPROT: WRONG MATERIAL CARD')
C
  110 GOTO(111,112), ICOMET
C
  111 CALL PROP05T(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
  112 CALL PROP05F(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
    2 CONTINUE
      DO ICOMET=1,MCOMET
       IF(WORDST(3).EQ.COMMET(ICOMET)) GO TO 210
      ENDDO
      CALL RUNENDT('INPPROT: WRONG MATERIAL CARD')
C
  210 GOTO(211,212), ICOMET
C
  211 CALL PROP05TO(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
  212 CALL PROP05FO(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
    3 CONTINUE
      CALL RUNENDT('ERROR: FULLY ANISOTROPIC MATERIAL NOT IMPLEMENTED')
c     note: change VCOND(500,2,9) in auxl_omt.f & NHIST1 in consett.f
      GOTO 10
C
    4 CONTINUE
      DO ICOMET=1,MCOMET
       IF(WORDST(3).EQ.COMMET(ICOMET)) GOTO 410
      ENDDO
      CALL RUNENDT('INPPROT: WRONG MATERIAL CARD')
C
  410 GOTO(411,412), ICOMET
C
  411 CALL PRO101T(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
  412 CALL PRO101F(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
    5 CONTINUE
      DO ICOMET=1,MCOMET
       IF(WORDST(3).EQ.COMMET(ICOMET)) GOTO 510
      ENDDO
      CALL RUNENDT('INPPROT: WRONG MATERIAL CARD')
C
  510 GOTO(511,512), ICOMET
C
  511 CALL PRO104T(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
  512 CALL PRO104F(ITAPET,PROPST(1,NUMATT))
      GOTO 10
C
   10 CONTINUE
C
C**** LOOK FOR 'END_PROPERTIES' CARD
C
      NPRINT=0
      JTAPET=LUDATT
      CALL LISTENT('INPPROT',NPRINT,JTAPET)
 2000 IF(WORDST(1).NE.'END_P')
     . CALL RUNENDT('INPPROT: END_PROPERTIES CARD NOT FOUND')
C
      RETURN
  900 FORMAT(//,6X,18HELEMENT PROPERTIES,/,6X,18('-'))
  901 FORMAT(' ERROR IN OPENING PROPERTIES INPUT FILE 242 (52 LINUX)')
c  910 FORMAT(10I5)
c  920 FORMAT(//,
c     . 10X,40H MATERIAL NUMBER :                      ,10X,I5,/,
c     . 10X,16H ---------------                               ,/,
c     . 10X,40H MATERIAL MODEL  :                      ,10X,I5,/)
      END
