      SUBROUTINE INPSETS(ITAPES,PROELS)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MATERIAL PROPERTIES
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROELS(NPRELS,*)
C
c     IERR1T=1
c     IF(ITAPET.NE.LUDATT.AND.ITAPET.NE.LUSETT) GOTO 1000
c     IF(ITAPET.EQ.LUSETT) THEN       ! external .set file
c      OPEN(UNIT=LUSETT,FILE=CB1T,STATUS='OLD',ERR=1000)
c      IERR1T=0
C
c1000  IF(IERR1T.NE.0) THEN
c       IF(IERR1T.EQ.1) WRITE(LUREST,901)
c       CALL RUNENDT('ERROR IN OPENING FILE         ')
c      ENDIF
c     ENDIF
C
      WRITE(LURESS,900)
C
      DO 10 IGRUPS=1,NGRUPS
C
C**** READ ELEMENTS CHARACTERISTICS
C
       NPRINS=1
       CALL LISTENS('INPSETS',NPRINS,ITAPES)
       ISETSS=INT(PARAMS(1))
       IMATSS=INT(PARAMS(2))
       ITYPES=INT(PARAMS(3))
       NTYPES=INT(PARAMS(4))
       IRULES=INT(PARAMS(5))
       IGAUSS=INT(PARAMS(6))
       THICKS=    PARAMS(7)
C
       IF(ISETSS.LE.0.OR.ISETSS.GT.NGRUPS)
     .  CALL RUNENDS('WRONG ISETSS VALUE')
       IF(IMATSS.LE.0.OR.IMATSS.GT.NMATSS)
     .  CALL RUNENDS('WRONG IMATSS VALUE')
       IF(ITYPES.NE.5.AND.ITYPES.NE.101.AND.ITYPES.NE.104)
     .  CALL RUNENDS('WRONG ITYPES VALUE')
       IF(NTYPES.LE.0.OR.NTYPES.GT.5)
     .  CALL RUNENDS('WRONG NTYPES VALUE')
       IF(IRULES.LE.0.OR.IRULES.GT.14)
     .  CALL RUNENDS('WRONG IRULES VALUE')
       IF(IRULES.LE.10.AND.IRULES.GT.8)
     .  CALL RUNENDS('WRONG IRULES VALUE')
       IF(IGAUSS.LE.0.OR.IGAUSS.GT.NGAUSS)
     .  CALL RUNENDS('WRONG IGAUSS VALUE')
C
       PROELS(1,ISETSS)=FLOAT(IMATSS)
       PROELS(3,ISETSS)=FLOAT(IRULES)
       PROELS(4,ISETSS)=FLOAT(IGAUSS)
       IF(ITYPES.EQ.0) ITYPES=1
       PROELS(5,ISETSS)=FLOAT(ITYPES)
       PROELS(6,ISETSS)=FLOAT(NTYPES)
C
C**** SOLID ELEMENTS
C
       IF(ITYPES.EQ.5) THEN
        IF(NTYPES.EQ.1.OR.NTYPES.EQ.2) THEN      ! 2D
         IF(THICKS.EQ.0.0)
     .    CALL RUNENDS('ERROR: THICK VALUE EQUAL ZERO')
         PROELS(7,ISETSS)=THICKS
        ENDIF
        IF(NTYPES.EQ.3.OR.NTYPES.EQ.4) THEN      ! axisymm. & 3D
         IF(THICKS.NE.0.0)
     .    CALL RUNMENS('WARNING: THICK VALUE NOT USED')
         PROELS(7,ISETSS)=1.0
        ENDIF
        IF(NTYPES.EQ.5) THEN                     ! 1D
         IF(THICKS.EQ.0.0)
     .    CALL RUNENDS('ERROR: CROSS AREA VALUE EQUAL ZERO')
         PROELS(7,ISETSS)=THICKS
        ENDIF
       ENDIF
C
C**** BOUNDARY & GAP ELEMENTS
C
       IF(ITYPES.EQ.101.OR.ITYPES.EQ.104) THEN
        IF(NTYPES.EQ.1.OR.NTYPES.EQ.2.OR.NTYPES.EQ.3) THEN  ! 2D & axys.
         IF(THICKS.NE.0.0)
     .    CALL RUNMENS('WARNING: THICK VALUE NOT USED')
         PROELS(7,ISETSS)=1.0
        ENDIF
        IF(NTYPES.EQ.4) THEN                     ! impossible
         CALL RUNENDS('ERROR: 3D FOR GAP/BOUNDARY IS NOT POSSIBLE')
        ENDIF
        IF(NTYPES.EQ.5) THEN                     ! 1D
         IF(THICKS.EQ.0.0)
     .    CALL RUNENDS('ERROR: CROSS AREA VALUE EQUAL ZERO')
         PROELS(7,ISETSS)=THICKS
        ENDIF
       ENDIF
C
C**** PRINT ELEMENTS CHARACTERISTICS
C
       IF(ITYPES.EQ.5) THEN                     ! solid
        IF(NTYPES.EQ.5) THEN                    ! 1D
         WRITE(LURESS,910) ISETSS,IMATSS,ITYPES,NTYPES,IRULES,IGAUSS,
     .                     THICKS
        ENDIF
        IF(NTYPES.EQ.1.OR.NTYPES.EQ.2) THEN     ! 2D
         WRITE(LURESS,910) ISETSS,IMATSS,ITYPES,NTYPES,IRULES,IGAUSS,
     .                     THICKS
        ENDIF
        IF(NTYPES.EQ.3.OR.NTYPES.EQ.4) THEN      ! axisymm. & 3D
         WRITE(LURESS,912) ISETSS,IMATSS,ITYPES,NTYPES,IRULES,IGAUSS
        ENDIF
       ENDIF
C
       IF(ITYPES.EQ.101.OR.ITYPES.EQ.104) THEN  ! boundary & gap
        IF(NTYPES.EQ.5) THEN                    ! 1D
         WRITE(LURESS,910) ISETSS,IMATSS,ITYPES,NTYPES,IRULES,IGAUSS,
     .                     THICKS
        ENDIF
        IF(NTYPES.EQ.1.OR.NTYPES.EQ.2) THEN     ! 2D
         IF(ITYPES.EQ.101.OR.ITYPES.EQ.104)
     .    WRITE(LURESS,910) ISETSS,IMATSS,ITYPES,NTYPES,IRULES,IGAUSS
        ENDIF
        IF(NTYPES.EQ.3) THEN                    ! axisymm.
         WRITE(LURESS,912) ISETSS,IMATSS,ITYPES,NTYPES,IRULES,IGAUSS
        ENDIF
       ENDIF
C
   10 CONTINUE
C
C**** LOOK FOR THE 'END_SETS' CARD
C
      NPRINS=0
      JTAPES=LUDATS
      CALL LISTENS('INPSETS',NPRINS,JTAPES)
      IF(WORDSS(1).NE.'END_S')
     . CALL RUNENDS('INPSETS: END_SETS CARD NOT FOUND')
C
      RETURN
  900 FORMAT(//,6X,'ELEMENT CHARACTERISTICS',/,6X,23('-'),
     .        /,5X,'GROUP',3X,'MATERIAL',3X,'TYPE1',3X,'TYPE2',
     .          3X,'INT. RULE',3X,'NO. PTS.',3X,'AREA/THICKNESS',/)
  901 FORMAT(' ERROR IN OPENING SET INPUT FILE 241 (51 LINUX)')
c 905 FORMAT(6I5,F10.3)
  910 FORMAT(5X,I5,6X,I5,3X,I5,3X,I5,7X,I5,6X,I5,7X,F10.3)
  912 FORMAT(5X,I5,6X,I5,3X,I5,3X,I5,7X,I5,6X,I5,7X,'---')
      END
