      SUBROUTINE INTFUN(HTLOD)
C***********************************************************************
C
C**** THIS ROUTINE READ THE INTERVAL FUNCTION DATA
C    
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
      INCLUDE 'inpo_om.f'
C
      COMMON/LDFILE/ITAPE
C
      DIMENSION HTLOD(NHLOD,NSUBF,*)
C
      PARAMETER (MCOMM=2)
      CHARACTER*5 COMMD(MCOMM)
      SAVE
C
      DATA COMMD/'F_NUM','END_F'/
C
      WRITE(LURES,900)
C
C**** INITIALIZATION
C
      DO IHLOD=1,NHLOD
       DO ISUBF=1,NSUBF
        DO IFUNC=1,NFUNC
         HTLOD(IHLOD,ISUBF,IFUNC)=0.0D0
        END DO
       END DO
      END DO
C
C**** READ NEW COMMAND
C
  200 NPRIN=0
      CALL LISTEN('INTFUN',NPRIN,ITAPE)
C
C**** IDENTIFY AND EXEXUTE APROPRIATE COMMAND
C
      DO ICOMM=1,MCOMM
       IF(WORDS(1).EQ.COMMD(ICOMM)) GO TO (1,2), ICOMM
      END DO
      GO TO 1000
C
C**** 'FUNC' READ DATA CONTROLLING LOAD INCREMENTATION IN TIME
C
    1 ITAPE=LUDAT
      IF(PARAM(1).EQ.0.0D0.OR.PARAM(2).EQ.0.0D0)
     . CALL RUNEND('INTFUN: ZERO FUNCTION OR SUBFUNCTION')
      KFUNC=NFUNC
      KFUNC=INT(PARAM(1))
      IF(KFUNC.GT.NFUNC)
     . CALL RUNEND('INTFUN: NUMBER OF FUNCTIONS GT NFUNC')
      KSUBF=INT(PARAM(2))
      IF(KSUBF.GT.NSUBF)
     . CALL RUNEND('INTFUN: NUMBER OF SUBFUNCTIONS GT NSUBF')
      WRITE(LURES,906)
      DO ISUBF=1,KSUBF
       DO INDEX=1,NHLOD
        HTLOD(INDEX,ISUBF,KFUNC)=0.0D0
       END DO
      END DO
      DO ISUBF=1,KSUBF
       CALL LISTEN('INTFUN',    NPRIN,    ITAPE)
       ITYPE=INT(PARAM(1))
       DO IHLOD=2,NHLOD
        HTLOD(IHLOD,ISUBF,KFUNC)=PARAM(IHLOD)
       ENDDO
       WRITE(LURES,908) ISUBF,ITYPE,(HTLOD(IHLOD,ISUBF,KFUNC),
     .                  IHLOD=2,NHLOD)
       HTLOD(1,ISUBF,KFUNC)=FLOAT(ITYPE)
      END DO
      WRITE(LURES,910)
      GO TO 200
C
    2 CONTINUE
      RETURN
C
 1000 CALL RUNEND('INTFUN: ERROR IN FUNCTION DATA BLOCK ')
C
  900 FORMAT(1H1,///,10X,'ECHO OF FUNCTION DATA FOLLOWS :',/
     .               10X,'============================='/)
  906 FORMAT(/,4X,'SUBFUN',6X,'TYPE',35X,'PARAMETERS')
c 907 FORMAT(I5,8E15.6)
  908 FORMAT(5X,I5,5X,I5,12(5X,E15.6))
  910 FORMAT(/)
      END
