      SUBROUTINE INTFUNT(HTLODT)
C***********************************************************************
C
C**** THIS ROUTINE READ THE INTERVAL FUNCTION DATA
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inpo_omt.f'
C
      COMMON/LDFILET/ITAPET
C
      DIMENSION HTLODT(NHLODT,NSUBFT,*)
C
      PARAMETER (MCOMMT=2)
      CHARACTER*5 COMMDT(MCOMMT)
      SAVE
C
      DATA COMMDT/'F_NUM','END_F'/
C
      WRITE(LUREST,900)
C
C**** INITIALIZATION
C
      DO IHLODT=1,NHLODT
       DO ISUBFT=1,NSUBFT
        DO IFUNCT=1,NFUNCT
         HTLODT(IHLODT,ISUBFT,IFUNCT)=0.0D0
        END DO
       END DO
      END DO
C
C**** READ NEW COMMAND
C
  200 NPRINT=0
      CALL LISTENT('INTFUNT',NPRINT,ITAPET)
C
C**** IDENTIFY AND EXEXUTE APROPRIATE COMMAND
C
      DO ICOMMT=1,MCOMMT
       IF(WORDST(1).EQ.COMMDT(ICOMMT)) GO TO (1,2), ICOMMT
      END DO
      GO TO 1000
C
C**** 'FUNC' READ DATA CONTROLLING LOAD INCREMENTATION IN TIME
C
    1 ITAPET=LUDATT
      IF(PARAMT(1).EQ.0.0D0.OR.PARAMT(2).EQ.0.0D0)
     . CALL RUNENDT('INTFUNT: ZERO FUNCTION OF SUBFUNCTION')
      KFUNCT=INT(PARAMT(1))
      IF(KFUNCT.GT.NFUNCT)
     . CALL RUNENDT('INTFUNT: NUMBER OF FUNCTIONS GT NFUNCT')
      KSUBFT=INT(PARAMT(2))
      IF(KSUBFT.GT.NSUBFT)
     . CALL RUNENDT('INTFUNT: NUMBER OF SUBFUNCTIONS GT NSUBFT')
      WRITE(LUREST,906)
      DO ISUBFT=1,KSUBFT
       CALL LISTENT('INTFUNT',1,LUDATT)
       ITYPET=INT(PARAMT(1))
       IF(ITYPET.GE.1.AND.ITYPET.LE.9) ILDV1T=1           ! see funlod.f
       IF((ITYPET.GE.101.AND.ITYPET.LE.104).OR.
     .    (ITYPET.GE.121.AND.ITYPET.LE.124)) ILDV2T=1     ! see funlod.f
       DO IHLODT=1,NHLODT
        HTLODT(IHLODT,ISUBFT,KFUNCT)=PARAMT(IHLODT)
       ENDDO
       WRITE(LUREST,908) ISUBFT,ITYPET,(HTLODT(IHLODT,ISUBFT,KFUNCT),
     .                   IHLODT=2,NHLODT)
      END DO
      WRITE(LUREST,910)
      GO TO 200
C
    2 CONTINUE
      RETURN
C
 1000 CALL RUNENDT('FUNCTION: ERROR IN FUNCT.DATA BLOCK   ')
C
  900 FORMAT(1H1,///,10X,'ECHO OF FUNCTION DATA FOLLOWS :',/
     .               10X,'============================='/)
  906 FORMAT(/,4X,'SUBFUN',6X,'TYPE',35X,'PARAMETERS')
  908 FORMAT(5X,I5,5X,I5,12(5X,E15.6))
  910 FORMAT(/)
      END
