      SUBROUTINE INTFUNS(HTLODS)
C***********************************************************************
C
C**** THIS ROUTINE READ THE INTERVAL FUNCTION DATA
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      COMMON/LDFILES/ITAPES
C
      DIMENSION HTLODS(NHLODS,NSUBFS,*)
C
      PARAMETER (MCOMMS=2)
      CHARACTER*5 COMMDS(MCOMMS)
      SAVE
C
      DATA COMMDS/'F_NUM','END_F'/
C
      WRITE(LURESS,900)
C
C**** INITIALIZATION
C
      DO IHLODS=1,NHLODS
       DO ISUBFS=1,NSUBFS
        DO IFUNCS=1,NFUNCS
         HTLODS(IHLODS,ISUBFS,IFUNCS)=0.0D0
        END DO
       END DO
      END DO
C
C**** READ NEW COMMAND
C
  200 NPRINS=0
      CALL LISTENS('INTFUNS',NPRINS,ITAPES)
C
C**** IDENTIFY AND EXEXUTE APROPRIATE COMMAND
C
      DO ICOMMS=1,MCOMMS
       IF(WORDSS(1).EQ.COMMDS(ICOMMS)) GO TO (1,2), ICOMMS
      END DO
      GO TO 1000
C
C**** 'FUNC' READ DATA CONTROLLING LOAD INCREMENTATION IN TIME
C
    1 ITAPES=LUDATS
      IF(PARAMS(1).EQ.0.0D0.OR.PARAMS(2).EQ.0.0D0)
     .CALL RUNENDS('INTFUNS')
      KFUNCS=NFUNCS
      KFUNCS=INT(PARAMS(1)) 
      IF(KFUNCS.GT.NFUNCS)
     . CALL RUNENDS('INTFUNS :')
      KSUBFS=INT(PARAMS(2)) 
      IF(KSUBFS.GT.NSUBFS)
     . CALL RUNENDS('INTFUNS : ')
      WRITE(LURESS,906)
      DO ISUBFS=1,KSUBFS
       DO INDEXS=1,NHLODS
        HTLODS(INDEXS,ISUBFS,KFUNCS)=0.0
       END DO
      END DO
      DO ISUBFS=1,KSUBFS
       CALL LISTENS('INTFUNS',1,LUDATS)
       ITYPES=INT(PARAMS(1))
       DO IHLODS=2,NHLODS
        HTLODS(IHLODS,ISUBFS,KFUNCS)=PARAMS(IHLODS)
       ENDDO
       WRITE(LURESS,908) ISUBFS,ITYPES,(HTLODS(IHLODS,ISUBFS,KFUNCS),
     .                   IHLODS=2,NHLODS)
       HTLODS(1,ISUBFS,KFUNCS)=FLOAT(ITYPES)
      END DO
      WRITE(LURESS,910)
      GO TO 200
C
    2 CONTINUE
      RETURN
C
 1000 CALL RUNENDS('FUNCTION: ERROR IN FUNCT.DATA BLOCK   ')
C
  900 FORMAT(1H1,///,10X,'ECHO OF FUNCTION DATA FOLLOWS :',/
     .               10X,'============================='/)
  906 FORMAT(/,4X,'SUBFUN',6X,'TYPE',35X,'PARAMETERS')
c 907 FORMAT(I5,8E15.6)
  908 FORMAT(5X,I5,5X,I5,12(5X,E15.6))
  910 FORMAT(/)
      END
