      SUBROUTINE INTREDS(TFICTS)
C***********************************************************************
C
C**** THIS ROUTINE SETS UP THE TYPE OF ALGORITHM AND REFERENCE LOAD
C     TO BE USED IN THE CURRENT TIME INTERVAL
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
      DIMENSION TFICTS(NFUNCS)
C
      CHARACTER XCOMMS*9,YCOMMS*123
C
C**** NEW RUN: LOOK FOR 'INTE'RVAL CARD OR FOR END OF ANALYSIS ('STOP')
C
      IF(IRESTS.EQ.0) THEN
       CALL INTRD0S(DTIMES,KSTEPS,NSTEPS,NSSTEPS)
       GO TO 1000
      ENDIF
C
C**** RESTART RUN:
C
      IF(IRESTS.EQ.1) THEN
C
C**** FIRST OF ALL READ ALL DATA UP TO THE END OF THE GENERAL DATA
C     AND COUNT THE NUMBER OF "INTERVAL DATA BLOCKS" UNTIL
C     THE ONE TO RESTART IS FOUND
C
       KOUNTS=0
  200  CONTINUE
       READ(LUDATS,900) XCOMMS,YCOMMS
       IF(XCOMMS.NE.'INTERVAL_') GOTO 200
       KOUNTS=KOUNTS+1
       IF(KOUNTS.LT.ITIMES) GOTO 200
C
C**** NOW LOOK FOR THE LAST "END_INTERVAL" CARD
C
  210  CONTINUE
       READ(LUDATS,900) XCOMMS,YCOMMS
       IF(XCOMMS.NE.'END_INTER') GOTO 210
C
C**** IF THE LAST INTERVAL HAS BEEN FINISHED ( NSTEP < KSTEP )
C     IN A "RESTART CONTINUE" THE NEXT CARDS ARE SUPPOSED TO BE 
C     THE DATA FOR A NEW INTERVAL
C
       IF(ISKIPS.EQ.0) THEN
        KSTEPS=ISTEPS+1
        IF(KSTEPS.LE.NSTEPS) GO TO 1000
C
        IRESTS=2
C
        CALL INTRD0S(DTIMES,KSTEPS,NSTEPS,NSSTEPS)
        GO TO 1000
C
       ENDIF
C
C**** IN A "RESTART SKIP" THE NEXT CARDS ARE SUPPOSED TO BE 
C     THE NEW STRATEGY FOR THE NEXT INTERVAL 
C
       IF(ISKIPS.EQ.1)THEN
C
        CALL INTRD0S(DTIMES,KSTEPS,NSTEPS,NSSTEPS)
        GO TO 1000
C
       ENDIF
C
       GOTO 1000
C
      ENDIF
C
C**** END OF SEARCH
C
 1000 CONTINUE
C
C**** IF A NEW INTERVAL IS STARTING UPDATE SOME VALUES
C
      IF(KSTEPS.EQ.1) THEN
       ITIMES=ITIMES+1
       DO IFUNCS=1,NFUNCS
        TFICTS(IFUNCS)=0.0
       ENDDO 
       KUNLDS=0
      ENDIF
C
      RETURN
  900 FORMAT(A9,A123)
      END
