      SUBROUTINE ITERATS(DISITS,DISPRS,DISTOS,ELDATS,ELPRES,ELVARS,
     .                   ELMATS,HEADSS,IFFIXS,PRESCS,LNODSS,MATNOS,
     .                   PROELS,PROPSS,REFORS,RLOADS,FICTOS,TLOADS,
     .                   DISPLS,PWORKS,PREASS,TGAPSS,COORDS,TEMPIS,
     .                   ADVELS,FPCHAS,WORK1S)
C***********************************************************************
C
C**** THIS ROUTINE PERFORMS THE ITERATIVE CORRECTION ON THE RESPONSE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_oms.f'
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION DISITS(NTOTVS,2),       DISPRS(NTOTVS,3),
     .          DISTOS(NTOTVS,3),       ELDATS(NDATAS),
     .          ELPRES(NPREVS),         ELVARS(NSTATS),
     .          ELMATS(NMATXS),         HEADSS(NPOINS,4),
     .          IFFIXS(NTOTVS,2),       LNODSS(NNODES,NELEMS),
     .          MATNOS(NELEMS),         PROELS(NPRELS,NGRUPS),
     .          PROPSS(NPROPS,NMATSS),  REFORS(NTOTVS,2),
     .          RLOADS(NTOTVS),         TLOADS(NTOTVS,2),
     .          WORK1S(*),              DISPLS(NTOTVMS),
     .          PWORKS(NPOINS,3),       COORDS(NDIMES,NPOINS)
      DIMENSION PREASS(NPREAS,NPOINS),  TGAPSS(NPOINS)
      DIMENSION PRESCS(NTOTVS,2),       FICTOS(NFUNCS)
      DIMENSION TEMPIS(NPOINS,2),       ADVELS(NTOTVS*NDIMES),
     .          FPCHAS(NFPCH,NPOINS)
C
C**** UPDATE ITERATION COUNTER
C
      IITERS=IITERS+1
C
C**** ASSEMBLE GLOBAL COUPLED STIFFNESS MATRIX, IF NECESSARY
C
      CALL ALGORSS     ! select solution flags KSTIF, KRESL
C
      IF(NMEMO7S.EQ.0) THEN
       IF(KSTIFS.EQ.1)                 ! evaluate a new stiffness matrix
     .   CALL STIFMXS(ELDATS,ELPRES,ELVARS,ELMATS,LNODSS,MATNOS,PROELS,
     .                PROPSS,WORK1S,DISTOS(1,2),DISITS(1,1),COORDS,
     .                ADVELS,TEMPIS(1,1),PREASS(1,1),TGAPSS,DISTOS(1,1),
     .                TEMPIS(1,2),DISPLS,FPCHAS)
      ENDIF
C
      IF(NMEMO6S.EQ.0) THEN
       IF(KRESLS.EQ.1)        ! assemble global coupled stiffness matrix
     .  CALL ASELMTS(MATNOS,PROELS,PROPSS,
     .               ELMATS(IMATXS(1)),ELMATS(IMATXS(2)),
     .               ELMATS(IMATXS(3)),ELMATS(IMATXS(4)),
     .               ELMATS(IMATXS(5)),ELMATS(IMATXS(6)))
      ENDIF
C
C**** INITIALISE THE ITERA.TEMPER. TAKING INTO ACCOUNT FIXITY CONDITIONS
C
      CALL INIDISS(DISITS,IFFIXS,PRESCS,FICTOS,RLOADS)
C
C**** SOLVE EQUATIONS FOR ITERATIVE TEMPERATURES
C
      CALL ESEPASS(DISITS,DISPRS,IFFIXS,LNODSS,REFORS,RLOADS,TLOADS,
     .             WORK1S,
     .             MATNOS,PROELS,PROPSS,ELDATS,ELPRES,
     .             ELVARS,ELMATS,
     .             DISTOS,COORDS,
     .             ADVELS,TEMPIS,PREASS(1,1),TGAPSS,DISPLS,FPCHAS)
C
C**** CALCULATES THERMAL RESIDUAL VECTOR
C
      CALL RESIDUS(DISITS,DISPRS,DISTOS,ELDATS,ELPRES,ELVARS,ELMATS,
     .             HEADSS,IFFIXS,LNODSS,MATNOS,PROELS,PROPSS,REFORS,
     .            TLOADS,DISPLS,PWORKS,PREASS(1,1),TGAPSS,COORDS,TEMPIS,
     .             ADVELS,FPCHAS,WORK1S)
C
C**** CHECK FOR CONVERGENCE
C
      CALL CONVERS(DISITS,DISPRS,DISTOS,REFORS,TLOADS,IFFIXS)
C
C**** OUTPUT RESULTS
C
      CALL OUTPUTS(DISTOS,ELDATS,ELPRES,ELVARS,ELMATS,HEADSS,
     .             IFFIXS,LNODSS,MATNOS,PROELS,PROPSS,TLOADS,
     .             COORDS,FPCHAS,PREASS(NPRE1S+1,1),DISPLS,WORK1S)
C
      RETURN
      END
