      SUBROUTINE LISTENT(SUBNAT,NPRINT,ITAPET)
C***********************************************************************
C
C**** READS A STRING AND INTERPRETS IT AS WORDS AND PARAMETERS.
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'inpo_omt.f'
C
      CHARACTER SUBNAT*7
C
      GO TO (1,2,3,2,5,1,1,8), NMACHI
C
    1 CALL LISTENT1(SUBNAT,NPRINT,ITAPET)
      RETURN
C
    2 CALL LISTENT2(SUBNAT,NPRINT,ITAPET)
      RETURN
C
    3 CALL LISTENT3(SUBNAT,NPRINT,ITAPET)
      RETURN
C
    5 CALL LISTENT5(SUBNAT,NPRINT,ITAPET)
      RETURN
C
    8 CALL LISTENT8(SUBNAT,NPRINT,ITAPET)
      RETURN
C
      END
