      SUBROUTINE LOAPOIT(NDIMET,NDOFCT,NDOFNT,NPOINT,KPROBT,NTOTVT,
     .                   NFUNCT,RLOADT,RLOAHT,NLOPOT,LUREST)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE EQUIVALENT NODAL FLUXES DUE TO
C     POINT FLUXES (ACTING ON THE ELEMENT NODES)
C
C     Notes: DINT is used to avoid problems in challenge machines
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'inpo_omt.f'
C
      COMMON/LDFILET/ITAPET
C
      DIMENSION POINTT(6), RLOADT(NTOTVT), RLOAHT(NTOTVT,NFUNCT)
C
      WRITE(LUREST,900)
      IF(KPROBT.EQ.1) THEN
        IF(NDIMET.EQ.2) WRITE(LUREST,905)
        IF(NDIMET.EQ.3) WRITE(LUREST,910)
      ELSE IF(KPROBT.EQ.2) THEN
        IF(NDIMET.EQ.2) WRITE(LUREST,915)
        IF(NDIMET.EQ.3) WRITE(LUREST,916)
      ENDIF
C
      DO ILOPOT=1,NLOPOT
       NPRINT=1
       CALL LISTENT('LOAPOIT',NPRINT,ITAPET)
       LODPTT=DINT(PARAMT(1))
       IFUNCT=DINT(PARAMT(2))
       DO IDOFNT=1,NDOFNT
        POINTT(IDOFNT)=PARAMT(IDOFNT+2)
       ENDDO
C
       WRITE(LUREST,925) LODPTT,IFUNCT,
     .               (POINTT(IDOFNT),IDOFNT=1,NDOFNT)
       IF(IFUNCT.GT.NFUNCT)
     .  CALL RUNENDT('LOAPOIT: ERROR IN FUNCTION NUMBER')
C
C**** ASSEMBLE IN GLOBAL ARRAY
C
       ITOTVT=(LODPTT-1)*NDOFCT
       DO IDOFNT=1,NDOFNT
        ITOTVT=ITOTVT+1
        RLOAHT(ITOTVT,IFUNCT)=RLOAHT(ITOTVT,IFUNCT)+
     .                        POINTT(IDOFNT)
        RLOADT(ITOTVT)=RLOADT(ITOTVT)+POINTT(IDOFNT)
       ENDDO
      ENDDO           ! ilopot=1,nlopot
C
      WRITE(LUREST,930)
C
      RETURN
  900 FORMAT(//,10X,5H NODE,10X,6H FUNC.,6X,11H HEAT VALUE)
  905 FORMAT(5H NODE,4X,9H X-FORCES,4X,9H Y-FORCES)
  910 FORMAT(5H NODE,4X,9H X-FORCES,4X,9H Y-FORCES,4X,9H Z-FORCES)
  915 FORMAT(5H NODE,4X,9H Z-FORCES,4X,9H X-COUPLE,4X,9H Y-COUPLE)
  916 FORMAT(5H NODE,4X,9H X-FORCES,4X,9H Y-FORCES,4X,9H Z-FORCES,
     .               4X,9H X-COUPLE,4X,9H Y-COUPLE,4X,9H Z-COUPLE)
c  920 FORMAT(I5,6F10.3)
  925 FORMAT(2(5X,I10),6X,F10.6)
  930 FORMAT(/)
      END
