      SUBROUTINE LOASUR(ELDAT,ELPRE,ELVAR,ELMAT,LNODS,MATNO,PROEL,
     .                  PROPS,RLOAD,RLOAH,COORD,LACTI,NOPRF,PREHF,
     .                  NEDGE,WORK1)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE EQUIVALENT NODAL FORCES DUE TO 
C     THE TRACTION FORCES ACTING ON THE ELEMENT SURFACE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_om.f'
C
C**** MECHANICAL VARIABLES
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
      INCLUDE 'inpo_om.f'
C
      COMMON/LDFILE/ITAPE
      COMMON/LDFILE1/IAXES
C
      DIMENSION MATNO(NELEM),       LNODS(NNODE,NELEM),
     .          PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS),
     .          ELDAT(NDATA),       ELPRE(NPREV),
     .          ELVAR(NSTAT),       ELMAT(NMATX),
     .          WORK1(*)
      DIMENSION RLOAD(NTOTV),       RLOAH(NTOTV,NFUNC)
      DIMENSION COORD(NDIME,NPOIN), LACTI(NELEM)
      DIMENSION NOPRF(NNODE,NELEM), PREHF(NNODE,NDIME,NELEM,NFUNC)
C
      IF(NDIME.EQ.3) GOTO 1000
C
C**** DISTRIBUTED EDGE LOADS SECTION (2D CASE)
C
      WRITE(LURES,805) NEDGE
      WRITE(LURES,810)
C
C**** LOOP OVER EACH LOADED EDGE
C
      DO 10 IEDGE=1,NEDGE
C
      NPRIN=1
      CALL LISTEN('LOASUR',NPRIN,ITAPE)
      IELEM=INT(PARAM(1))
      IF(IELEM.LE.0.OR.IELEM.GT.NELEM)
     . CALL RUNEND('LOASUR: WRONG ELEMENT NUMBER')
      IFUNC=INT(PARAM(2))
      IF(IFUNC.GT.NFUNC)
     . CALL RUNEND('LOASUR: ERROR IN FUNCTION NUMBER')
C
      IF(NACTI.EQ.1) THEN
       IF(LACTI(IELEM).EQ.0) GO TO 10         ! skip non active elements
      ENDIF
C
      LGRUP=MATNO(IELEM)
      LMATS=INT(PROEL(1,LGRUP))
      NNODL=INT(PROEL(2,LGRUP))
C
C**** READ ELDAT FROM DATA-BASE
C
      IF(NMEMO1M.EQ.0)                   ! independent of NMEMO2M
     . CALL DATBAS(ELDAT,    1,    2)
C
      IF(NMEMO1M.EQ.1) THEN              ! coordinates in a global array
       CALL GATHER(COORD,NDIME,NPOIN,WORK1(ILOSU(16)),NDIME,
     .             NNODL,LNODS(1,IELEM))
      ENDIF
C
C**** CALL ELEMENT PROCESSOR TO PERFORM THE REQUIRED OPERATIONS
C
      CALL ELMLIB(LNODS(1,IELEM),PROEL(1,LGRUP),PROPS(1,LMATS),
     .            WORK1,WORK1,NOPRF(1,IELEM),PREHF(1,1,IELEM,IFUNC),
     .            WORK1,
     .            ELDAT,ELPRE,ELVAR,ELMAT,WORK1,    8)
C
C**** SCALAR SCATTER OPERATION ( RLOAD )
C
      CALL SCATER(WORK1,NDOFN,NNODL,RLOAD,NDOFC,NPOIN,
     .            LNODS(1,IELEM))
C
C**** SCALAR SCATTER OPERATION ( RLOAH )
C
      CALL SCATER(WORK1,NDOFN,NNODL,RLOAH(1,IFUNC),NDOFC,NPOIN,
     .            LNODS(1,IELEM))
C
   10 CONTINUE
C
      RETURN
C
C**** 3-D CASE
C
 1000 CONTINUE
C
      NFACE=NEDGE
      WRITE(LURES,905) NFACE
      WRITE(LURES,910)
C
C**** LOOP OVER EACH LOADED FACE
C
      DO 110 IFACE=1,NFACE
C
      NPRIN=1
      CALL LISTEN('LOASUR',NPRIN,ITAPE)
      IELEM=INT(PARAM(1))
      IF(IELEM.LE.0.OR.IELEM.GT.NELEM)
     . CALL RUNEND('LOASUR: WRONG ELEMENT NUMBER')
      IFUNC=INT(PARAM(2))
      IF(IFUNC.GT.NFUNC)
     . CALL RUNEND('LOASUR: ERROR IN FUNCTION NUMBER')
C
      IF(NACTI.EQ.1) THEN
       IF(LACTI(IELEM).EQ.0) GO TO 110        ! skip non active elements
      ENDIF
C
      LGRUP=MATNO(IELEM)
      LMATS=INT(PROEL(1,LGRUP))
      NNODL=INT(PROEL(2,LGRUP))
C
C**** READ ELDAT FROM DATA-BASE
C
      IF(NMEMO1M.EQ.0)                   ! independent of NMEMO2M
     . CALL DATBAS(ELDAT,    1,    2)
C
      IF(NMEMO1M.EQ.1) THEN              ! coordinates in a global array
       CALL GATHER(COORD,NDIME,NPOIN,WORK1(ILOSU(16)),NDIME,
     .             NNODL,LNODS(1,IELEM))
      ENDIF
C
C**** CALL ELEMENT PROCESSOR TO PERFORM THE REQUIRED OPERATIONS
C
      CALL ELMLIB(LNODS(1,IELEM),PROEL(1,LGRUP),PROPS(1,LMATS),
     .            WORK1,WORK1,NOPRF(1,IELEM),PREHF(1,1,IELEM,IFUNC),
     .            WORK1,
     .            ELDAT,ELPRE,ELVAR,ELMAT,WORK1,    8)
C
C**** SCALAR SCATTER OPERATION ( RLOAD )
C
      CALL SCATER(WORK1,NDOFN,NNODL,RLOAD,NDOFC,NPOIN,
     .            LNODS(1,IELEM))
C
C**** SCALAR SCATTER OPERATION ( RLOAH )
C
      CALL SCATER(WORK1,NDOFN,NNODL,RLOAH(1,IFUNC),NDOFC,NPOIN,
     .            LNODS(1,IELEM))
C
  110 CONTINUE
C
      RETURN
c 800 FORMAT(10I5)
  805 FORMAT(1H0,5X,21HNO. OF LOADED EDGES =,I7)
  810 FORMAT(1H0,5X,38HLIST OF LOADED EDGES AND APPLIED LOADS)
c 900 FORMAT(10I5)
  905 FORMAT(1H0,5X,21HNO. OF LOADED FACES =,I7)
  910 FORMAT(1H0,5X,38HLIST OF LOADED FACES AND APPLIED LOADS)
      END
