      SUBROUTINE MAMF05T(DVOLUT,PROPST,SHAPET,WSTIFT,EHISTT,SHAPDT,
     .                   DVOLDT,POSGPT,ELDIST,ELCODT,WEIGPT,DERIDT,
     .                   XJACMT,CARDDT,GPCDDT,VELCMT,WSTI1T,WSTI2T,
     .                   LNODST,DISIMT,HACHET,WHADEL,CENTRO,ADVEMT,
     .                   TEINIT,FPCHLT,DVOLIT)
C***********************************************************************
C
C**** THIS ROUTINE COMPUTES THE LATENT HEAT CONTRIBUTION IN THE
C     JACOBIAN MATRIX FOR MULTIPHASE ELEMENTS
C     ( ELEMENT NO. 5 )
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'   ! thermal-mechanical
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
      DIMENSION DVOLUT(*),        PROPST(*),
     .          SHAPET(NNODLT,*)
      DIMENSION DVOLDT(*),        POSGPT(NDIMET,*),
     .          SHAPDT(NNODLT,*)
      DIMENSION WSTIFT(*),        EHISTT(NHISTT,*),
     .          ELDIST(NDOFCT,*), ELCODT(NDIMET,*)
C
      DIMENSION WEIGPT(*),        DERIDT(NDIMET,NNODLT,*),
     .          XJACMT(NDIMET,*), CARDDT(NDIMET,NNODLT,*),
     .          GPCDDT(NDIMET,*)
      DIMENSION LNODST(*),        VELCMT(*),
     .          DISIMT(*)
      DIMENSION WSTI1T(*),        WSTI2T(*)
      DIMENSION HACHET(NNODLT),   WHADEL(NNODLT,*),
     .          CENTRO(NDIMET,*), ADVEMT(NDIMET,*),
     .          TEINIT(NDOFCT,*), FPCHLT(NFPCH,*),
     .          DVOLIT(*)
C
      GOTO(1,2,3), NDIMET
C
    1 CALL MAMF1DT(DVOLUT,PROPST,SHAPET,WSTIFT,EHISTT,SHAPDT,DVOLDT,
     .             POSGPT,ELDIST,ELCODT,WEIGPT,DERIDT,XJACMT,CARDDT,
     .             GPCDDT,LNODST,VELCMT,WSTI1T,WSTI2T,DISIMT,HACHET,
     .             WHADEL,CENTRO,ADVEMT,TEINIT,FPCHLT,DVOLIT)
      RETURN
C
    2 CALL MAMF2DT(DVOLUT,PROPST,SHAPET,WSTIFT,EHISTT,SHAPDT,DVOLDT,
     .             POSGPT,ELDIST,ELCODT,WEIGPT,DERIDT,XJACMT,CARDDT,
     .             GPCDDT,LNODST,VELCMT,WSTI1T,WSTI2T,DISIMT,HACHET,
     .             WHADEL,CENTRO,ADVEMT,TEINIT,FPCHLT,DVOLIT)
      RETURN
C
    3 CALL MAMF3DT(DVOLUT,PROPST,SHAPET,WSTIFT,EHISTT,SHAPDT,DVOLDT,
     .             POSGPT,ELDIST,ELCODT,WEIGPT,DERIDT,XJACMT,CARDDT,
     .             GPCDDT,LNODST,VELCMT,WSTI1T,WSTI2T,DISIMT,HACHET,
     .             WHADEL,CENTRO,ADVEMT,TEINIT,FPCHLT,DVOLIT)
      RETURN
C
      END
