      SUBROUTINE MEMODTS
C***********************************************************************
C
C**** THIS ROUTINE CALCULATES THE MEMORY REQUIREMENTS & ADDRESS FOR 
C     DATABASE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** GENERAL DIMENSIONS
C
      INCLUDE 'para_oms.f'
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_oms.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
C**** TRY TO ALLOCATE DATA BASE IN VIRTUAL MEMORY
C
      ISTOPS=NDISKDS     ! ndiskd=0 out-of-core; ndiskd=1 virtual memory
C
      NBLOCS=11
      DO 10 IBLOCS=NBLIMS,1,-1
C
C**** CHECK POSSIBILITY TO ALLOCATE IBLOC ARRAYS IN VIRTUAL MEMORY
C
       IF((IBLOCS.EQ.6).AND.(KDYNAS.EQ.0).AND.(KPORES.NE.2)) GO TO 10
C
       NWORPS=IDATPS(IBLOCS+1,3)
C
C**** MEMORY CONTROL
C
       IF(NWORPS.GT.MWORPS)
     .  CALL RUNENDS('ERROR IN MEMODTS: NWORPS         ')
C
       LDABAS=NWORPS*NELEMS+IDATPS(12,3)
       LBYTBS=LDABAS*8
C
C**** SET APPROPRIATE FLAGS AND POINTERS FOR DATABASE
C                                 ISTOP=1 >> MEMORY HAS BEEN ALLOCATED
       IF(ISTOPS.EQ.1) THEN
        DO ILOOPS=1,IBLOCS
         IDATPS(ILOOPS,5)=1
        ENDDO
        NSKIPS=IDATPS(IBLOCS+1,4)
        NLENPS=NLENPS-NSKIPS
        NRECPS=NLENPS*NELEMS
        DO ILOOPS=NBLOCS+1,IBLOCS+1,-1
         IDATPS(ILOOPS,4)=IDATPS(ILOOPS,4)-NSKIPS
        ENDDO
        GO TO 100
       ENDIF
   10 CONTINUE
C
C**** ALLOCATE VM FOR DISTO
C
      IBLOCS=0
      LDABAS=IDATPS(12,3)
      LBYTBS=LDABAS*8
C
  100 CONTINUE
C
C**** TRANSFER DISTO TO DATABASE
C
      IDATPS(12,5)=1
C
      RETURN
      END
