      SUBROUTINE MODULS2  (RA1, RA2, RA3, RA4, RA5, RA6,
     .                     RA7, RA8, RA9, RA10,RA11,RA12,
     .                     RA13,RA14,RA15,RA16,RA17,RA18,
     .                     RA19,RA20,RA21,RA22,RA23,RA24,
     .                     RA25,RA26,RA27,RA28,RA29,RA30,
     .                     RA31,RA32,RA33,RA34,RA35,RA36,
     .                     RA37,
     .                     WORK1,
     .                     RB1, RB2, RB3, RB4, RB5, RB6,
     .                     RB7, RB8, RB9, RB10,RB11,RB12,
     .                     RB13,RB14,RB15,RB16,RB17,RB18,
     .                     RB19,RB20,RB21,RB22,RB23,RB24,
     .                     RB25,RB26,RB27,RB28,RB29,RB30,
     .                     RB31,
     .                     WORK1T,
     .                     RC1, RC2, RC3, RC4, RC5, RC6,
     .                     RC7, RC8, RC9, RC10,RC11,RC12,
     .                     RC13,RC14,RC15,RC16,RC17,RC18,
     .                     RC19,RC20,RC21,RC22,RC23,RC24,
     .                     RC25,RC26,RC27,RC28,RC29,RC30,
     .                     RC31,
     .                     WORK1S)

C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8, ALLOCATABLE, INTENT(INOUT) :: WORK1(:),WORK1T(:),WORK1S(:)
      END SUBROUTINE
