      SUBROUTINE MODULTS(WORKST,IPRINT,MPRINT,
     .                   WS,    IS,    MPRINS,
     .                   W1)
C====================================================================
      IMPLICIT REAL*8(A-H,O-Z)
      REAL*8, ALLOCATABLE, INTENT(INOUT) :: W1(:)
      INCLUDE 'modults0.inc'
C
C**** THERMAL VARIABLES (PERMANENT)
C
      DIMENSION WORKST(MPRINT), IPRINT(50)
C
C**** MICROSTRUCTURAL VARIABLES (PERMANENT)
C
      DIMENSION WS(MPRINS),     IS(50)
C
C**** THERMAL & MICROSTRUCTURAL VARIABLES (TEMPORARY)
C
      CALL MODULTS0(
     .     WORKST(IPRINT( 1)),WORKST(IPRINT( 2)),WORKST(IPRINT( 3)),
     .     WORKST(IPRINT( 4)),WORKST(IPRINT( 5)),WORKST(IPRINT( 6)),
     .     WORKST(IPRINT( 7)),WORKST(IPRINT( 8)),WORKST(IPRINT( 9)),
     .     WORKST(IPRINT(10)),WORKST(IPRINT(11)),WORKST(IPRINT(12)),
     .     WORKST(IPRINT(13)),WORKST(IPRINT(14)),WORKST(IPRINT(15)),
     .     WORKST(IPRINT(16)),WORKST(IPRINT(17)),WORKST(IPRINT(18)),
     .     WORKST(IPRINT(19)),WORKST(IPRINT(20)),WORKST(IPRINT(21)),
     .     WORKST(IPRINT(22)),WORKST(IPRINT(23)),WORKST(IPRINT(24)),
     .     WORKST(IPRINT(25)),WORKST(IPRINT(26)),WORKST(IPRINT(27)),
     .     WORKST(IPRINT(28)),WORKST(IPRINT(29)),WORKST(IPRINT(30)),
     .     WORKST(IPRINT(31)),
     .     W1,
     .     WS(IS( 1)),WS(IS( 2)),WS(IS( 3)),WS(IS( 4)),WS(IS( 5)),
     .     WS(IS( 6)),WS(IS( 7)),WS(IS( 8)),WS(IS( 9)),WS(IS(10)),
     .     WS(IS(11)),WS(IS(12)),WS(IS(13)),WS(IS(14)),WS(IS(15)),
     .     WS(IS(16)),WS(IS(17)),WS(IS(18)),WS(IS(19)),WS(IS(20)),
     .     WS(IS(21)),WS(IS(22)),WS(IS(23)),WS(IS(24)),WS(IS(25)),
     .     WS(IS(26)),WS(IS(27)),WS(IS(28)),WS(IS(29)),WS(IS(30)),
     .     WS(IS(31)),
     .     W1)
C
      RETURN
      END
