      SUBROUTINE OUTG05T(EHISTT,STRANT,STRSGT)
C***********************************************************************
C
C**** THIS ROUTINE PRINT THE GAUSSIAN VARIABLES
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION EHISTT(NHISTT,*), STRANT(NSTR1T,*),
     .          STRSGT(NSTR1T,*)
      DIMENSION STRSPT(3)
C
      KELGST=0
C
      WRITE(LUREST,900) IELEMT
C
      IF(NTYPET.EQ.1.OR.NTYPET.EQ.2) THEN
       IF(KPRI2T.EQ.1) WRITE(LUREST,960)
       IF(KPRI3T.EQ.1) WRITE(LUREST,962)
      ELSE IF(NTYPET.EQ.3) THEN
       IF(KPRI2T.EQ.1) WRITE(LUREST,965)
       IF(KPRI3T.EQ.1) WRITE(LUREST,966)
      ELSE IF(NTYPET.EQ.4) THEN
       IF(KPRI2T.EQ.1) WRITE(LUREST,970)
       IF(KPRI3T.EQ.1) WRITE(LUREST,971)
      ELSE IF(NTYPET.EQ.5) THEN
       IF(KPRI2T.EQ.1) WRITE(LUREST,972)
      ENDIF
C
C**** LOOP OVER GAUSS POINTS
C
      DO 30 IGAUST=1,NGAULT
      KELGST=KELGST+1
C
C**** CALCULATE THE PRINCIPAL STRESSES
C
      IF(KPRI3T.EQ.1) THEN
       IF(NTYPET.LE.3) CALL PRIDIRT(NTYPET,STRSGT(1,IGAUST),STRSPT)
       IF(NTYPET.EQ.4) CALL PRINSIT(STRSGT(1,IGAUST),STRSPT)
      ENDIF
C
      IF(NTYPET.NE.5) THEN
       EPSIVT=STRANT(1,IGAUST)+STRANT(2,IGAUST)+STRANT(4,IGAUST)
      ELSE
       EPSIVT=STRANT(1,IGAUST)
      ENDIF
C
C**** PRINT STRESSES
C
      IF(NTYPET.NE.4) THEN
       IF(KPRI2T.EQ.1) WRITE(LUREST,905) KELGST,
     .  (STRSGT(ISTR1T,IGAUST),ISTR1T=1,NSTR1T)
       IF(KPRI3T.EQ.1.AND.NTYPET.NE.5) 
     .  WRITE(LUREST,905) KELGST,(STRSPT(ISTRET),ISTRET=1,3)
      ENDIF
C
      IF(NTYPET.EQ.4) THEN
       IF(KPRI2T.EQ.1)
     .  WRITE(LUREST,905) KELGST,(STRSGT(ISTR1T,IGAUST),ISTR1T=1,NSTR1T)
       IF(KPRI3T.EQ.1)
     .  WRITE(LUREST,905) KELGST,(STRSPT(ISTR1T),ISTR1T=1,3)
      ENDIF
   30 CONTINUE
C
C**** PRINT STATE VARIABLES
C
      IF(KPRI4T.EQ.1) THEN
       IF(NCRITT.EQ.3.OR.NCRITT.EQ.4) THEN      !CRITICAL STATE MODEL
        WRITE(LUREST,980)
        DO 40 IGAUST=1,NGAULT
         WRITE(LUREST,981) IGAUST,(EHISTT(INDEXT,IGAUST),INDEXT=1,6)
   40    CONTINUE
       ENDIF
C
       IF(NCRITT.EQ.5) THEN
        DO 50 IGAUST=1,NGAULT
         IF(NTYPET.NE.4)
     .    WRITE(LUREST,991) IGAUST,(EHISTT(INDE1T,IGAUST),INDE1T=16,17),
     .                             (EHISTT(INDE2T,IGAUST),INDE2T=13,14),
     .                             (EHISTT(INDE3T,IGAUST),INDE3T= 1, 4)
         IF(NTYPET.EQ.4)
     .    WRITE(LUREST,992) IGAUST,(EHISTT(INDE1T,IGAUST),INDE1T=16,18),
     .                             (EHISTT(INDE2T,IGAUST),INDE2T=13,15),
     .                             (EHISTT(INDE3T,IGAUST),INDE3T= 1, 9)
   50    CONTINUE
       ENDIF
C
       IF(NCRITT.EQ.21.OR.NCRITT.EQ.22.OR.NCRITT.EQ.23) THEN
        DO 60 IGAUST=1,NGAULT
         WRITE(LUREST,993) IGAUST,(EHISTT(INDE1T,IGAUST),INDE1T=10,12),
     .                             EHISTT(13,IGAUST),
     .                             EHISTT(17,IGAUST),
     .                             EHISTT(19,IGAUST)
   60   CONTINUE
       ENDIF
      ENDIF
C
      RETURN
C
  900 FORMAT(/,5X,13HELEMENT NO. =,I5)
  905 FORMAT(5X,I5,3(3X,E15.6))
  960 FORMAT(5X,5H G.P.,4X,13H XX-HEAT FLUX,5X,13H YY-HEAT FLUX)
  962 FORMAT(1H0,5X,5H G.P.,5X,10H  MAX P.S.,5X,10H  MIN P.S.,
     .          10X,5HANGLE)
  965 FORMAT(5X,5H G.P.,5X,13H RR-HEAT FLUX,5X,13H ZZ-HEAT FLUX)
  966 FORMAT(1H0,5X,5H G.P.,5X,10H  MAX P.S.,5X,10H  MIN P.S.,
     .          10X,5HANGLE)
  970 FORMAT(5X,5H G.P.,4X,13H XX-HEAT FLUX,5X,13H YY-HEAT FLUX,
     .      5X,13H ZZ-HEAT FLUX)
  971 FORMAT(1H0,5X,5H G.P.,3X,10H     P1   ,5X,10H     P2   ,
     .     5X,10H     P3   ,4X,12H DVOL.STRAIN)
  972 FORMAT(5X,5H G.P.,4X,13H XX-HEAT FLUX)
  980 FORMAT(5X,5H G.P.,4X,11H Q-CO. CEN., 4X,11H P-CO. CEN.,
     .                  4X,11H MJ. S-AXIS, 4X,11H EQ.ME.PR.,
     .                  4X,11H  SPEC.VOL., 2X,13H PLA.VOL.STR.)
  981 FORMAT(5X,I5,6E15.6)
  991 FORMAT(I5,2E15.6,5X,2E15.6,//,2(40X,2E15.6,/))
  992 FORMAT(I5,3E15.6,5X,3E15.6,//,3(55X,3E15.6,/))
  993 FORMAT(I5,6E15.6)
      END
