      SUBROUTINE OUTG01(EHIST,STRAN,STRSG)
C***********************************************************************
C
C**** THIS ROUTINE PRINT THE GAUSSIAN VARIABLES
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
      INCLUDE 'inpo_om.f'
C
      DIMENSION EHIST(NHIST,*), STRAN(NSTR1,*), STRSG(NSTR1,*)
      DIMENSION STRSP(3)
C
      KELGS=0
C
      WRITE(LURES,900) IELEM
C
      IF(NTYPE.EQ.1.OR.NTYPE.EQ.2) THEN
       IF(KPRI2.EQ.1) WRITE(LURES,960)
       IF(KPRI3.EQ.1) WRITE(LURES,962)
       IF(KPRI4.EQ.1) WRITE(LURES,994)
      ELSE IF(NTYPE.EQ.3) THEN
       IF(KPRI2.EQ.1) WRITE(LURES,965)
       IF(KPRI3.EQ.1) WRITE(LURES,966)
       IF(KPRI4.EQ.1) WRITE(LURES,994)
      ELSE IF(NTYPE.EQ.4) THEN
       IF(KPRI2.EQ.1) WRITE(LURES,970)
       IF(KPRI3.EQ.1) WRITE(LURES,971)
       IF(KPRI4.EQ.1) WRITE(LURES,994)
      ELSE IF(NTYPE.EQ.5) THEN
       IF(KPRI2.EQ.1) WRITE(LURES,972)
      ENDIF
C
C**** LOOP OVER GAUSS POINTS
C
      DO 30 IGAUS=1,NGAUL
      KELGS=KELGS+1
C
C**** CALCULATE THE PRINCIPAL STRESSES
C
      IF(KPRI3.EQ.1) THEN
        IF(NTYPE.LE.3) CALL PRIDIR(NTYPE,STRSG(1,IGAUS),STRSP)
        IF(NTYPE.EQ.4) CALL PRINSI(STRSG(1,IGAUS),STRSP)
      ENDIF
C
      IF(NTYPE.NE.5) THEN
        EPSIV=STRAN(1,IGAUS)+STRAN(2,IGAUS)+STRAN(4,IGAUS)
      ELSE
        EPSIV=STRAN(1,IGAUS)
      ENDIF
C
C**** PRINT STRESSES
C
      IF(NTYPE.NE.4) THEN
        IF(KPRI2.EQ.1) WRITE(LURES,905) KELGS,
     .    (STRSG(ISTR1,IGAUS),ISTR1=1,NSTR1),EPSIV
        IF(KPRI3.EQ.1.AND.NTYPE.NE.5) 
     .    WRITE(LURES,905) KELGS,(STRSP(ISTRE),ISTRE=1,3)
      ENDIF
C
      IF(NTYPE.EQ.4) THEN
       IF(KPRI2.EQ.1)
     .   WRITE(LURES,905) KELGS,(STRSG(ISTR1,IGAUS),ISTR1=1,NSTR1),
     .                    EPSIV
       IF(KPRI3.EQ.1)
     .   WRITE(LURES,905) KELGS,(STRSP(ISTR1),ISTR1=1,3),
     .                    EPSIV
      ENDIF
   30 CONTINUE
C
C**** PRINT STATE VARIABLES
C
      IF(KPRI4.EQ.1) THEN
       DO 40 IGAUS=1,NGAUL
       WRITE(LURES,981) IGAUS,(EHIST(INDEX,IGAUS),INDEX=1,NSTR1)
       INDEX=NSTR1+NKOST+1               ! effective plastic deformation
       WRITE(LURES,981) IGAUS,EHIST(INDEX,IGAUS)
   40  CONTINUE
      ENDIF
C
      IF(NCRIT.EQ.5) THEN
       DO 50 IGAUS=1,NGAUL
       IF(NTYPE.NE.4)
     .  WRITE(LURES,991) IGAUS, (EHIST(INDE1,IGAUS),INDE1=16,17),
     .                          (EHIST(INDE2,IGAUS),INDE2=13,14),
     .                          (EHIST(INDE3,IGAUS),INDE3= 1, 4)
       IF(NTYPE.EQ.4)
     .  WRITE(LURES,992) IGAUS, (EHIST(INDE1,IGAUS),INDE1=16,18),
     .                          (EHIST(INDE2,IGAUS),INDE2=13,15),
     .                          (EHIST(INDE3,IGAUS),INDE3= 1, 9)
   50  CONTINUE
      ENDIF
C
      IF(NCRIT.EQ.21.OR.NCRIT.EQ.22.OR.NCRIT.EQ.23) THEN
       DO 60 IGAUS=1,NGAUL
       WRITE(LURES,993) IGAUS, (EHIST(INDE1,IGAUS),INDE1=10,12),
     .                          EHIST(13,IGAUS),
     .                          EHIST(17,IGAUS),
     .                          EHIST(19,IGAUS)
   60  CONTINUE
      ENDIF
C
      RETURN
C
  900 FORMAT(5X,13HELEMENT NO. =,I5)
  905 FORMAT(5X,I5,8E15.6)
  960 FORMAT(5X,5H G.P.,4X,10H XX-STRESS,5X,10H YY-STRESS,
     .       5X,10H XY-STRESS,5X,10H ZZ-STRESS,3X,12H DVOL.STRAIN)
  962 FORMAT(5X,5H G.P.,5X,10H  MAX P.S.,5X,10H  MIN P.S.,
     .       10X,5HANGLE)
  965 FORMAT(5X,5H G.P.,5X,10H RR-STRESS,5X,10H ZZ-STRESS,
     .       5X,10H RZ-STRESS,5X,10H TT-STRESS,3X,12H DVOL.STRAIN)
  966 FORMAT(5X,5H G.P.,5X,10H  MAX P.S.,5X,10H  MIN P.S.,
     .       10X,5HANGLE)
  970 FORMAT(5X,5H G.P.,4X,10H XX-STRESS,5X,10H YY-STRESS,
     .       5X,10H XY-STRESS,5X,10H ZZ-STRESS,5X,10H XZ-STRESS,
     .       5X,10H YZ-STRESS,3X,12H DVOL.STRAIN)
  971 FORMAT(5X,5H G.P.,3X,10H     P1   ,5X,10H     P2   ,
     .       5X,10H     P3   ,4X,12H DVOL.STRAIN)
  972 FORMAT(5X,5H G.P.,4X,10H XX-STRESS,3X,12H DVOL.STRAIN)
  980 FORMAT(5X,5H G.P.,4X,11H Q-CO. CEN., 4X,11H P-CO. CEN.,
     .                  4X,11H MJ. S-AXIS, 4X,11H EQ.ME.PR. ,
     .                  4X,11H  SPEC.VOL., 2X,13H PLA.VOL.STR.)
  981 FORMAT(5X,I5,6E15.6)
  991 FORMAT(I5,2E15.6,5X,2E15.6,//,2(40X,2E15.6,/))
  992 FORMAT(I5,3E15.6,5X,3E15.6,//,3(55X,3E15.6,/))
  993 FORMAT(I5,6E15.6)
  994 FORMAT(5X,' G.P.    TOTAL PLASTIC DEFORMATION TENSOR')
      END
