      SUBROUTINE OUTNOD(SMSTS,SMSTN,SMSTP)
C***********************************************************************
C
C**** THIS ROUTINE OUTPUTS NODAL STRESSES AND 'STRAINS' TO OUTPUT AND
C     POSTPROCESSOR FILES
C
C       KPRI5 =0  DO NOT WRITE NODAL STRESSES
C              1  WRITE NODAL STRESSES
C       KPRI6 =0  DO NOT WRITE NODAL PRINCIPAL STRESSES
C              1  WRITE NODAL PRINCIPAL STRESSES
C       KPRI7 =0  DO NOT WRITE NODAL INTERNAL VARIABLES
C              1  WRITE NODAL INTERNAL VARIABLES
C       KPRI9 =0  DO NOT WRITE NODAL STRAINS
C              1  WRITE NODAL STRAINS
C       KPRI10=0  DO NOT WRITE NODAL PRINCIPAL STRAINS
C              1  WRITE NODAL PRINCIPAL STRAINS
C       KFEMV =0  DO NOT WRITE TO POSTPROCESSOR FILE
C              1  WRITE TO POSTPROCESSOR FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
      INCLUDE 'inpo_om.f'
C
      COMMON/HOMOGENIZATION/HVOLU,HSTRE(6)
C
      DIMENSION SMSTS(NSTR1,NPOIN), SMSTN(NSTR1,NPOIN),
     .          SMSTP(NNUIN,NPOIN)
      DIMENSION STRSP(3),           STRNP(3)
C
C**** COMPUTES NUMBER OF POINTS WITHOUT CONTACT (AL METHOD)
C
      NPOI1=NPOIN-NPOIC
C
C**** OUTPUT NODAL STRESSES
C
      IF(IPRCO.GT.0) THEN
       IF((KPRI5+KPRI6).GT.0) THEN
        WRITE(LURES,956)
        IF(NTYPE.EQ.1.OR.NTYPE.EQ.2) THEN
         IF(KPRI5.EQ.1) WRITE(LURES,970)
         IF(KPRI6.EQ.1) WRITE(LURES,971)
        ELSE IF(NTYPE.EQ.3) THEN
         IF(KPRI5.EQ.1) WRITE(LURES,972)
         IF(KPRI6.EQ.1) WRITE(LURES,971)
        ELSE IF(NTYPE.EQ.4) THEN
         IF(KPRI5.EQ.1) WRITE(LURES,980)
         IF(KPRI6.EQ.1) WRITE(LURES,981)
        ELSE IF(NTYPE.EQ.5) THEN
         IF(KPRI5.EQ.1) WRITE(LURES,960)
        ENDIF
C
C**** CALCULATE THE PRINCIPAL STRESSES
C
        DO IPOIN=1,NPOI1
         IF(KPRI6.EQ.1) THEN
          IF(NTYPE.LE.3) CALL PRIDIR(NTYPE,SMSTS(1,IPOIN),STRSP)
          IF(NTYPE.EQ.4) CALL PRINSI(SMSTS(1,IPOIN),STRSP)
         ENDIF
C
         IF(NTYPE.NE.4) THEN
          IF(KPRI5.EQ.1) WRITE(LURES,905) IPOIN,
     .                   (SMSTS(ISTR1,IPOIN),ISTR1=1,NSTR1)
          IF(KPRI6.EQ.1.AND.NTYPE.NE.5) 
     .     WRITE(LURES,905) IPOIN,(STRSP(ISTRE),ISTRE=1,3)
         ENDIF
C
         IF(NTYPE.EQ.4) THEN
          IF(KPRI5.EQ.1) WRITE(LURES,905) IPOIN,
     .                   (SMSTS(ISTR1,IPOIN),ISTR1=1,NSTR1)
          IF(KPRI6.EQ.1) WRITE(LURES,905) IPOIN,(STRSP(ISTRE),ISTRE=1,3)
         ENDIF
        ENDDO       ! ipoin=1,npoi1
       ENDIF
C
C**** OUTPUT NODAL STRAINS
C
       IF((KPRI9+KPRI10).GT.0) THEN
        WRITE(LURES,1956)
        IF(NTYPE.EQ.1.OR.NTYPE.EQ.2) THEN
         IF(KPRI9.EQ.1)  WRITE(LURES,1970)
         IF(KPRI10.EQ.1) WRITE(LURES,1971)
        ELSE IF(NTYPE.EQ.3) THEN
         IF(KPRI9.EQ.1)  WRITE(LURES,1972)
         IF(KPRI10.EQ.1) WRITE(LURES,1971)
        ELSE IF(NTYPE.EQ.4) THEN
         IF(KPRI9.EQ.1)  WRITE(LURES,1980)
         IF(KPRI10.EQ.1) WRITE(LURES,1981)
        ELSE IF(NTYPE.EQ.5) THEN
         IF(KPRI9.EQ.1)  WRITE(LURES,1960)
        ENDIF
C
C**** CALCULATE THE PRINCIPAL STRAINS
C
        DO IPOIN=1,NPOI1
         IF(KPRI10.EQ.1) THEN
          IF(NTYPE.LE.3) CALL PRIDIR(NTYPE,SMSTN(1,IPOIN),STRNP)
          IF(NTYPE.EQ.4) CALL PRINSI(SMSTN(1,IPOIN),STRNP)
         ENDIF
C
         IF(NTYPE.NE.4) THEN
          IF(KPRI9.EQ.1) WRITE(LURES,1905) IPOIN,
     .                   (SMSTN(ISTR1,IPOIN),ISTR1=1,NSTR1)
          IF(KPRI10.EQ.1.AND.NTYPE.NE.5) 
     .     WRITE(LURES,1905) IPOIN,(STRNP(ISTRE),ISTRE=1,3)
         ENDIF
C
         IF(NTYPE.EQ.4) THEN
          IF(KPRI9.EQ.1) WRITE(LURES,1905) IPOIN,
     .                    (SMSTN(ISTR1,IPOIN),ISTR1=1,NSTR1)
          IF(KPRI10.EQ.1) WRITE(LURES,1905) IPOIN,
     .                                     (STRNP(ISTRE),ISTRE=1,3)
         ENDIF
        ENDDO        ! ipoin=1,npoi1
       ENDIF
C
C**** OUTPUT NODAL INTERNAL VARIABLES
C
       IF(KPRI7.GT.0) THEN
        WRITE(LURES,2956)
        DO INUNO=1,NNUNO
         IPLA1=IPLAN(INUNO)
         IPLA2=IPLAM(INUNO)
C
         WRITE(LURES,2980) INUNO
C
C**** CHECKS POSITIVENESS OF NODAL EFFECTIVE PLASTIC DEFORMATION
C
         IF(INUNO.EQ.1) THEN
          DO IPOIN=1,NPOI1
           IF(SMSTP(IPLA1,IPOIN).LT.0.0) SMSTP(INUNO,IPOIN)=0.0D0
          ENDDO     ! ipoin=1,npoi1
         ENDIF
C
C**** CHECKS POSITIVENESS OF NODAL POROSITY    ! to be generalized
C
c        IF(INUNO.EQ.4) THEN
c         DO IPOIN=1,NPOI1
c          IF(SMSTP(IPLA1,IPOIN).LT.0.0) SMSTP(INUNO,IPOIN)=0.0D0
c         ENDDO     ! ipoin=1,npoi1
c        ENDIF
C
         DO IPOIN=1,NPOI1
          WRITE(LURES,2905) IPOIN,(SMSTP(IPLAU,IPOIN),IPLAU=IPLA1,IPLA2)
         ENDDO      ! ipoin=1,npoi1
        ENDDO       ! inuno=1,nnuno
       ENDIF        ! kpri7.gt.0
      ENDIF         ! iprco.gt.0
C
C**** OUTPUT HOMOGENIZED STRESS
C
      IF(KPRI12.EQ.1) 
     . WRITE(LURES,2981) HVOLU,(HSTRE(ISTRE),ISTRE=1,NSTR1)
C
C**** WRITE TO POSTPROCESSOR FILE
C
      IF(KFEMV.EQ.1)
     . WRITE(LUPOS)
     .         ((SNGL(SMSTS(ISTR1,IPOIN)),ISTR1=1,NSTR1),IPOIN=1,NPOI1),
     .         ((SNGL(SMSTN(ISTR1,IPOIN)),ISTR1=1,NSTR1),IPOIN=1,NPOI1),
     .         ((SNGL(SMSTP(INUIN,IPOIN)),INUIN=1,NNUIN),IPOIN=1,NPOI1)
C
      RETURN
  905 FORMAT(5X,I5,8E15.6)
  956 FORMAT(/,5X,23H STRESS AT NODAL POINTS)
  960 FORMAT(5X,5HIPOIN,5X,10H XX-STRESS)
  970 FORMAT(5X,5HIPOIN,5X,10H XX-STRESS,5X,10H YY-STRESS,
     .       5X,10H XY-STRESS,5X,10H ZZ-STRESS)
  971 FORMAT(5X,5HIPOIN,5X,10H  MAX P.S.,5X,10H  MIN P.S.,
     .      10X,5HANGLE)
  972 FORMAT(5X,5HIPOIN,5X,10H RR-STRESS,5X,10H ZZ-STRESS,
     .       5X,10H RZ-STRESS,5X,10H TT-STRESS)
  980 FORMAT(5X,5HIPOIN,4X,10H XX-STRESS,5X,10H YY-STRESS,
     .       5X,10H XY-STRESS,5X,10H ZZ-STRESS,5X,10H XZ-STRESS,
     .       5X,10H YZ-STRESS)
  981 FORMAT(5X,5HIPOIN,3X,10H     P1   ,5X,10H     P2   ,
     .       5X,10H     P3   )
C
 1905 FORMAT(5X,I5,8E15.6)
 1956 FORMAT(/,5X,24H STRAINS AT NODAL POINTS)
 1960 FORMAT(5X,5HIPOIN,5X,10H XX-STRAIN)
 1970 FORMAT(5X,5HIPOIN,5X,10H XX-STRAIN,5X,10H YY-STRAIN,
     .       5X,10H XY-STRAIN,5X,10H ZZ-STRAIN)
 1971 FORMAT(5X,5HIPOIN,5X,10H  MAX P.S.,5X,10H  MIN P.S.,
     .      10X,5HANGLE)
 1972 FORMAT(5X,5HIPOIN,5X,10H RR-STRAIN,5X,10H ZZ-STRAIN,
     .       5X,10H RZ-STRAIN,5X,10H TT-STRAIN)
 1980 FORMAT(5X,5HIPOIN,4X,10H XX-STRAIN,5X,10H YY-STRAIN,
     .       5X,10H XY-STRAIN,5X,10H ZZ-STRAIN,5X,10H XZ-STRAIN,
     .       5X,10H YZ-STRAIN)
 1981 FORMAT(5X,5HIPOIN,3X,10H     P1   ,5X,10H     P2   ,
     .       5X,10H     P3   )
C
 2905 FORMAT(5X,I5,8E15.6)
 2956 FORMAT(/,5X,35H INTERNAL VARIABLES AT NODAL POINTS)
c2980 FORMAT(5X,5HIPOIN,5X,25H EFFECTIVE PLASTIC STRAIN)
 2980 FORMAT(5X,5HIPOIN,2X,18H INTERNAL VARIABLE,I5)
 2981 FORMAT(/,5X,14H TOTAL VOLUME=,E15.6,/,
     .         5X,27H HOMOGENIZED STRESS TENSOR=,6E15.6)
      END
