      SUBROUTINE OUTPRIT(DISTOT,ELDATT,ELPRET,ELVART,ELMATT,HEADST,
     .                   LNODST,MATNOT,PROELT,PROPST,
     .                   SMSTST,SMSTNT,SMSTPT,SMSPPT,
     .                   COORDT,FPCHAT,DISPLT,
     .                   WORK1T)
C***********************************************************************
C
C**** THIS ROUTINE OUTPUTS TEMPERATURES & HEAT FLUXES
C
C       KPRI0=0  DO NOT WRITE TO OUTPUT FILE
C             1  WRITE TO OUTPUT FILES
C       KPRI1=0  DO NOT WRITE TEMPERATURES TO OUTPUT FILE
C             1  WRITE TEMPERATURES TO OUTPUT FILES
C       KPRI2=0  DO NOT WRITE GAUSSIAN HEAT FLUXES TO OUTPUT FILE
C             1  WRITE GAUSSIAN HEAT FLUXES TO OUTPUT FILES
C       KPRI3=0  ---
C             1  ---
C       KPRI4=0  DO NOT WRITE GAUSS INTERNAL VARIABLES TO OUTPUT FILE
C             1  WRITE GAUSS INTERNAL VARIABLES TO OUTPUT FILES
C       KPRI5=0  DO NOT WRITE NODAL HEAT FLUXES
C             1  WRITE NODAL HEAT FLUXES
C       KPRI6=0  ---
C             1  ---
C       KPRI7=0  DO NOT WRITE NODAL INTERNAL VARIABLES TO OUTPUT FILE
C             1  WRITE NODAL INTERNAL VARIABLES TO OUTPUT FILES
C       KPRI8=0 DO NOT WRITE NODAL POROSITY CRITERIA
C            =1 WRITE NODAL POROSITY CRITERIA
C
C       KPRIN=1  WRITE TO OUTPUT FILES TEMPERATURES & HEAT FLUXES
C
C       KFEMV=0  DO NOT WRITE FOR POSTPROCESOR
C             1  WRITE FOR POSTPROCESOR
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION MATNOT(NELEMT),        LNODST(NNODET,NELEMT),
     .          PROELT(NPRELT,NGRUPT), PROPST(NPROPT,NMATST),
     .          ELDATT(NDATAT),        ELPRET(NPREVT),
     .          ELVART(NSTATT),        ELMATT(NMATXT)
      DIMENSION DISTOT(*),             HEADST(NPOINT,*),
     .          SMSTST(NSTR1T,NPOINT), SMSTNT(NSTR1T,NPOINT)
      DIMENSION SMSTPT(NNUINT,NPOINT), SMSPPT(NPOROT,NPOINT)
      DIMENSION STRSPT(3)
      DIMENSION COORDT(NDIMET,NPOINT), FPCHAT(NFPCH,NPOINT),
     .          DISPLT(NTOTVM)
      DIMENSION WORK1T(*)
C
      IF(KFEMVT.NE.0)
     . OPEN(UNIT=LUPOST,FILE=CJT,STATUS='OLD',FORM='UNFORMATTED',
     .      ACCESS='APPEND')
C
C**** OUTPUT TEMPERATURES
C
      CALL OUTDIST(DISTOT,HEADST,DISPLT)
C
C**** OUTPUT GAUSSIAN VARIABLES
C
      IF((KPRI2T+KPRI4T).NE.0)
     . CALL OUTGAUT(ELDATT,ELPRET,ELVART,ELMATT,
     .              LNODST,MATNOT,PROELT,PROPST,COORDT,DISPLT,
     .              WORK1T)
C
C**** OUTPUTS MACROSCOPICAL PHASE-CHANGES
C
      CALL OUTMIC(FPCHAT)
C
C**** OUTPUT NODAL HEAT FLUXES & INTERNAL VARIABLES
C
      IF(((KPRI5T+KPRI7T+KPRI8T+KFEMVT).GT.0).AND.(KSGAUT.NE.0))
     . CALL OUTNODT(SMSTST,SMSTNT,SMSTPT,SMSPPT)
C
C**** CLOSE POSTPROCESS FILE
C
C     Warning: in CONVEX C-120, comment "close(lupost)" (february 1993)
C
      IF(KFEMVT.NE.0) CLOSE(LUPOST)
C
      RETURN
      END
