C***********************************************************************
C
C**** MICROSCOPICAL PARAMETERS
C
C     !m mechanical variable (NTOTV=NTOTVT*NDIMET in solids) ???
C
C***********************************************************************
C
      INCLUDE 'gend_oms.f'
C
      PARAMETER(
c    . MNODGS=max(MNODES,MGAUSS) )                ! sg
     . MNODGS=(MNODES+MGAUSS) )                   ! PC & linux
C
C**** ADDELMS
C
      PARAMETER(
c    . MDATA1AS=
c    .         max(MMEMA1S,MMEMA2S,MMEMOS,(MSMOMS*MMEMA2S),MHOURS) ) !sg
     . MDATA1AS=0 )                                    ! PC & linux
C
      PARAMETER(
     . MDATA1S=MDATA1AS,                            ! ELCOD(NDIME,NNODE)
     . MDATA2S=MDATA1S+MDIMES*MNODES*MMEMA1S, ! CARTD(NDIME,NNODE,NGAUS)
     . MDATA3S=MDATA2S+MDIMES*MNODES*MGAUSS*MMEMA2S,      ! DVOLU(NGAUS)
     . MDATA4S=MDATA3S+MGAUSS*MMEMA2S,              ! GPCOD(NDIME,NGAUS)
     . MDATA5S=MDATA4S+MDIMES*MGAUSS*MMEMA2S,       ! SHAPE(NNODE,NGAUS)
     . MDATA6S=MDATA5S+MNODES*MGAUSS*MMEMA2S,       ! EPMTX(NKOST,NGAUS)
     . MDATA7S=MDATA6S+MKOSTS*MGAUSS*MMEMOS,   ! RMAT1(NDIME,NDIME)
     . MDATA8S=MDATA7S+MDIMES*MDIMES*MMEMOS,   ! EMASS(NNODE,NNODE)
     . MDATA9S=MDATA8S+MNODES*MNODES*MSMOMS*MMEMA2S, !STIFH(NEVAB,NEVAB)
     . MDATA10S=MDATA9S+MEVABS*MEVABS*MHOURS,        !VNORI(NDIME,NGAUS)
     . MDATAS  =MDATA10S+MDIMES*MGAUSS*MMEMA2S )
C
      PARAMETER(
     .  MPREV1S=1*MMEMOS,                      ! STRA0(NSTR1,NGAUS)
     .  MPREV2S=MPREV1S+MSTR1S*MGAUSS*MMEMOS,  ! STRS0(NSTR1,NGAUS)
     .  MPREV3S=MPREV2S+MSTR1S*MGAUSS*MMEMOS,  ! TEMPC(4)
     .  MPREVS =MPREV3S+4*MMEMOS )
C
      PARAMETER(
c    . MSTAT1AS=max(MMEMO3S,MMEMO4S,MMEMA5S) )   ! sg
     . MSTAT1AS=1 )                              ! PC & linux
C
      PARAMETER(
     . MSTAT1S=MSTAT1AS,                       ! ELDIS(NDOFC,NNODE)
     . MSTAT2S=MSTAT1S+MDOFCS*MNODES,          ! EHIST(NHIST,NGAUS)
     . MSTAT3S=MSTAT2S+MHISTS*MGAUSS,          ! STRAN(NSTR1,NGAUS) 
     . MSTAT4S=MSTAT3S+MSTR1S*MGAUSS*MMEMO4S,  ! STRSG(NSTR1,NGAUS)
     . MSTATS =MSTAT4S+MSTR1S*MGAUSS*MMEMO4S )
C
      PARAMETER(
c    . MPORETAS=max(MPORES-1,0) )              ! sg
     . MPORETAS=0 )                            ! PC & linux
C
      PARAMETER(
c    . MMATXTAS=max(MMEMA7S,MPORETAS) )        ! sg
     . MMATXTAS=1 )                            ! PC & linux
C
      PARAMETER(
     .  MMATX1S=MMATXTAS,                      ! CSTIF(NEVAC,NEVAC)
     .  MMATX2S=MMATX1S+MEVACS*MEVACS,         ! KSTIF(NKOVA)
     .  MMATX3S=MMATX2S+MKOVAS*MMEMA6S,        ! MSTIF(NKOVA)
     .  MMATX4S=MMATX3S+MKOVAS*MDYNAS*MMEMA6S, ! PSTIF(NKOND)
     .  MMATX5S=MMATX4S+MKONDS*MPORES,         ! QSTIF(NKOND)
     .  MMATX6S=MMATX5S+MKONDS*MPORES,         ! HSTIF(NEVAB*NNODE)
     .  MMATXS =MMATX6S+MEVABS*MNODES*MPORES )
C
C**** ADDPRIS
C
      PARAMETER(
c    .   MTER12S=max((MTERMES+1),0) )         ! sg
     .   MTER12S=2 )                          ! PC & linux
      PARAMETER(
c    .   MTER2S=max(MTERMES,0) )              ! sg
     .   MTER2S=1 )                           ! PC & linux
      PARAMETER(
     .   MTER1S=MTER12S/(1+MTER2S) )
C
      PARAMETER(              ! simplification
     . MTER3S=MTER2S,
c    . MTER113S=max(MTER3S,MMEMO11S) )        ! sg
     . MTER113S=1 )                           ! PC & linux
C
      PARAMETER(
     . MPREASS=MTER2S*MMEMA11S,
     . MPREATS=MPREASS+MPOROS )
C
      PARAMETER(                             ! simplified
c    . MITERCTS=max(MTERMES,0) )             ! sg
     . MITERCTS=1 )                          ! PC & linux
C
      PARAMETER(
c    . MPORETBS=max(MPORES,1) )              ! sg
     . MPORETBS=1 )                          ! PC & linux
      PARAMETER(
     . MPORETCS=MPORES/MPORETBS )
C
      PARAMETER(
     . mprin1s=1,                             ! LNODS(NNODE,NELEM)
     . mprin2s =mprin1s +(MNODES*MELEMS*MCHALS+4)/8, ! MATNO(NELEM)
     . mprin3s =mprin2s +(MELEMS*MCHALS+4)/8, ! PROEL(NPREL,NGRUP)
     . mprin4s =mprin3s +MPRELS*MGRUPS,       ! PROPS(NPROP,NMATS)
     . mprin5s =mprin4s +MPROPS*MMATSS,       ! COORD(NDIME,NPOIN)#
     . mprin6s =mprin5s +MDIMES*MPOINS*MMEMO1S,!HTLOD(NHLOD,NSUBF,NFUNC)
     . mprin7s =mprin6s +MHLODS*MSUBFS*MFUNCS,! IFFIX(NTOTV,2)
     . mprin8s =mprin7s +(MTOTVS*MCHALS+4)/8*
     .                      (1+MPORETBS/2)*(1+MACTIS),  ! PRESC(NTOTV,2)
     . mprin9s =mprin8s +MTOTVS*2,            ! RLOAD(NTOTV)
     . mprin10s=mprin9s +MTOTVS,              ! RLOAH(NTOTV,NFUNC)
     . mprin11s=mprin10s+MTOTVS*MFUNCS,       ! FICTO(NFUNC)
     . mprin12s=mprin11s+MFUNCS )             ! TFICT(NFUNC)
      PARAMETER(
     . mprin13s=mprin12s+MFUNCS,              ! DISIT(NTOTV,2)
     . mprin14s=mprin13s+MTOTVS*2,            ! DISPR(NTOTV,3)
     . mprin15s=mprin14s+MTOTVS*3,            ! DISTO(NTOTV,3)
     . mprin16s=mprin15s+MTOTVS*3,            ! HEADS(NPOIN,4)
     . mprin17s=mprin16s+MPOINS*4,            ! REFOR(NTOTV,2)
     . mprin18s=mprin17s+MTOTVS*2,            ! TLOAD(NTOTV,2)
     . mprin19s=mprin18s+MTOTVS*2,            ! LPNTN(NPOIN)
     . mprin20s=mprin19s+(MPOINS*MCHALS+4)/8, ! ELDAT(NDATA)
     . mprin21s=mprin20s+MDATAS,              ! ELPRE(NPREV)
     . mprin22s=mprin21s+MPREVS,              ! ELVAR(NSTAT)
     . mprin23s=mprin22s+MSTATS,              ! ELMAT(NMATX)
     . mprin24s=mprin23s+MMATXS )             ! DISPL(NTOTV) !m
      PARAMETER(
     . mprin25s=mprin24s+MTOTVS*MDIMES*MTER2S,  ! PWORK(NPOIN,3)
     . mprin26s=mprin25s+MPOINS*(2+MITERCTS)*MTER2S,  ! PREAS(NPOIN)
     . mprin27s=mprin26s+MPOINS*MTER2S,         ! TGAPS(NPOIN)
     . mprin28s=mprin27s+MPOINS*MTER2S,         ! TEMPI(NPOIN)
     . mprin29s=mprin28s+MPOINS*MTER1S,         ! ADVEL(NTOTV) !m
     . mprin30s=mprin29s+MTOTVS*MDIMES*MCONVS,  ! FPCHA(NFPCH,NPOIN)
     . mprin31s=mprin30s+MFPCHS*MPOINS*MTER1S,  ! LACTI(NELEM)
     . MPRINS  =mprin31s+MACTIS*MELEMS )
C
C**** RSSETPT
C
      PARAMETER(
     .       i11s =MDATAS,                    ! ELDAT
     .       i21s =MPREVS,                    ! ELPRE
     .       i31s =MSTATS,                    ! ELVAR
     .       i41s =MPREVS,                    ! ELPRE
     .       i51s =MSTATS,                    ! ELVAR
     .       i61s =MEVACS*MEVACS,             ! CSTIF
     .       i71s =MKOVAS*MMEMA6S,            ! ESTIF
     .       i81s =MKOVAS*MDYNAS*MMEMA6S,     ! WSTIF
     .       i91s =MKONDS*MPORES,             ! PSTIF
     .       i101s=MKONDS*MPORES,             ! QSTIF
     .       i111s=MEVABS*MNODES*MPORES,      ! HSTIF
     .       i121s=MTOTVS)                    ! DISTO
C
      PARAMETER(
     .       i23s =MDATAS,
     .       i33s =(i23s+MPREVS),
     .       i43s =(i33s+MSTATS),
     .       i53s =(i43s+MPREVS),
     .       i63s =(i53s+MSTATS),
     .       i73s =(i63s+MEVACS*MEVACS),
     .       i83s =(i73s+MDYNAS*i71s),
     .       i93s =(i83s+i81s),
     .       i103s=(i93s+i91s),
     .       i113s=(i103s+i101s),
     .       i123s=(i113s+i111s) )
C
C**** DATBASS (BUFFERS)
C
C     DISTOS is always IN-CORE for MBUFFERS
C
      PARAMETER(
c    . MWORPS =max(i23s,i33s,i43s,i53s,i63s,i73s,           ! sg
c    .             i83s,i93s,i103s,i113s,i123s),
     . MWORPS =i123s,                                       ! PC & linux
c    . index1s=max(MDATAS,MPREVS,MSTATS,(MEVACS*MEVACS),    ! sg
c    .             MKOVAS*MMEMA6S,MKONDS*MPORES,(MEVABS*MNODES),MTOTVS),
     . index1s=(MDATAS+MPREVS+MSTATS+(MEVACS*MEVACS)+       ! PC & linux
     .             MKOVAS*MMEMA6S+MKONDS*MPORES+(MEVABS*MNODES)+MTOTVS),
     . index2s=   (MDATAS+MPREVS+MSTATS+MEVACS*MEVACS+
     .             MKOVAS*MMEMA6S+MKONDS*MPORES+MEVABS*MNODES+MTOTVS),
     . MBUFFERS=MTOTVS+(MELEMS*MWORPS+INDEX2S+1+INDEX1S)*MDISKDS )
C
C**** ADDWORS
C
      PARAMETER(
     . ISTA1S =1,                                  ! COORD(NDIME,NPOIN)
     . ISTA2S =ISTA1S +MDIMES*MPOINS*MMEMA1S,      ! GPCOD(NDIME,NGAUS)
     . ISTA3S =ISTA2S +MDIMES*MGAUSS,        ! CARTD(NDIME,NNODE,NGAUS)
     . ISTA4S =ISTA3S +MDIMES*MNODES*MGAUSS*MMEMO2S, ! DVOLU(NGAUS)
     . ISTA5S =ISTA4S +MGAUSS*MMEMO2S,             ! GPCOD(NDIME,NGAUS)
     . ISTA6S =ISTA5S +MDIMES*MGAUSS*MMEMO2S,      ! SHAPE(NNODE,NGAUS)
     . ISTA7S =ISTA6S +MNODES*MGAUSS*MMEMO2S, !DERIV(NDIME,NNODE,NGAUS)
     . ISTA8S =ISTA7S +MDIMES*MNODES*MGAUSS*MMEMO2S, !POSGP(NDIME,NGAUS)
     . ISTA9S =ISTA8S +MDIMES*MGAUSS*MMEMO2S,       ! WEIGP(NGAUS)
     . ISTA10S=ISTA9S +MGAUSS*MMEMO2S,              !XJACM(NDIME,NDIME)
     . ISTA11S=ISTA10S+MDIMES*MDIMES*MMEMO2S,       !ELCO1(NDIME,NNODE)
     . ISTA12S=ISTA11S+MDIMES*MNODES*MMEMO2S,       !EMASS(NNODE,NNODE)
     . ISTA13S=ISTA12S+MNODES*MNODES*MMEMO2S,       !ELDI1(NDOFN,NNODE)
     . ISTA14S=ISTA13S+MDOFCS*MNODES*MMEMO2S,       ! VNORL(NDIME,NGAUS)
     . ISTA15S=ISTA14S+MDIMES*MGAUSS*MTER2S*MMEMO11S, ! DVOLI(NGAUS)
     . ISTA16S=ISTA15S+MGAUSS*MTER3S,               ! ELCOI(NDIME,NNODE)
     . ISTA17S=ISTA16S+MDIMES*MNODES*MTER3S,     ! DISPT(NDOFC,NNODE) !m
     . LINDS  =ISTA17S+MDOFCMS*MNODES*MTER3S )
C
      PARAMETER(
     . LRENS=MRENUS*MPOINS*(10*MNODES+3)/2 )
C
      PARAMETER(
     . IQUA1S=1,                              ! VVECT(NTOTV)
     . IQUA2S=IQUA1S+MTOTVS,                  ! WVECT(NTOTV)
     . LQUAS =IQUA2S+MTOTVS )
C
      PARAMETER(
     . IFIX1S=1,                              ! LEQNS(NEVAC)
     . IFIX2S=IFIX1S+(MEVACS*MCHALS+4)/8,     ! LNUEQ(NTOTV)
     . IFIX3S=IFIX2S+(MTOTVS*MCHALS+4)/8,     ! LOCEL(NEVAC)
     . IFIX4S=IFIX3S+(MEVACS*MCHALS+4)/8,     ! LPONT(NTOTV)
     . IFIX5S=IFIX4S+(MTOTVS*MCHALS+4)/8,     ! NACVA(NTOTV)
     . IFIX6S=IFIX5S+(MTOTVS*MCHALS+4)/8,     ! NDEST(NEVAC)
     . IFIX7S=IFIX6S+(MEVACS*MCHALS+4)/8,     ! NDFRO(NELEM)
     . IFIX8S=IFIX7S+(MELEMS*MCHALS+4)/8,     ! PRESC(NDOFC)
     . LFIXS =IFIX8S+MDOFCS )
C
      PARAMETER(
     . IFOT1S=1,                              ! BMSIG(NEVAB)
     . IFOT2S=IFOT1S+MEVABS,                  ! BMATX(NSTR1,NEVAB)
     . IFOT3S=IFOT2S+MSTR1S*MEVABS,           ! DESIG(NSTR1) 
     . IFOT4S=IFOT3S+MSTR1S,                  ! DMATX(NSTR1,NSTR1)
     . IFOT5S=IFOT4S+MSTR1S*MSTR1S,           ! DSTRA(NSTR1)
     . IFOT6S=IFOT5S+MSTR1S,                  ! PRESG(NSTR1)
     . IFOT7S=IFOT6S+MSTR1S,                  ! SGTOT(NSTR1)
     . IFOT8S=IFOT7S+MSTR1S,                  ! SIGMA(NSTR1)
     . IFOT9S=IFOT8S+MSTR1S,                  ! TSTRA(NSTR1)
     . IFOT10S=IFOT9S+MSTR1S,                 ! XJACM(NDIME,NDIME)
     . IFOT11S=IFOT10S+MDIMES*MDIMES,         ! ELELT(NEVAB)
     . IFOT12S=IFOT11S+MEVABS,                ! VELCM(NEVAB)
     . IFOT13S=IFOT12S+MEVABS,                ! DISPTT(NDOFC,NNODET)
     . IFOT14S=IFOT13S+MDOFCS*MNODES,         ! PREASL(NNODET)
     . IFOT15S=IFOT14S+MNODES,                ! TGAPSL(NNODET)
     . IFOT16S=IFOT15S+MNODES )               ! ELCO1(NDIME,NNODE)
      PARAMETER(
c    . MAUX1S=max(MCONVS,MGALES) )            ! sg
     . MAUX1S=1 )                             ! PC & linux
      PARAMETER(
     . IFOT17S=IFOT16S+MDIMES*MNODES,         ! SHAPD(NNODE,NGAUS)
     . IFOT18S=IFOT17S+MNODES*MGAUSS*MAUX1S,  ! DVOLD(NGAUS)
     . IFOT19S=IFOT18S+MGAUSS*MCONVS,         ! POSGP(NDIME,NGAUS)
     . IFOT20S=IFOT19S+MDIMES*MGAUSS*MAUX1S,  ! WEIGP(NGAUS)
     . IFOT21S=IFOT20S+MGAUSS*MAUX1S,        ! DERID(NDIME,NNODE,NGAUS)
     . IFOT22S=IFOT21S+MDIMES*MNODES*MGAUSS*MAUX1S, !XJACM(NDIME,NDIME)
     . IFOT23S=IFOT22S+MDIMES*MDIMES*MAUX1S,  !CARDD(NDIME,NNODE,NGAUS)
     . IFOT24S=IFOT23S+MDIMES*MNODES*MGAUSS*MAUX1S, !GPCDD(NDIME,NGAUS)
     . IFOT25S=IFOT24S+MDIMES*MGAUSS*MAUX1S,  ! ELEL1(NEVAB)
     . IFOT26S=IFOT25S+MEVABS*MCONVS,         ! ELEL2(NEVAB)
     . IFOT27S=IFOT26S+MEVABS*MCONVS,         ! WHAPE(NNODE,NGAUS)
     . IFOT28S=IFOT27S+MNODES*MGAUSS,         ! HACHE(NNODE)
     . IFOT29S=IFOT28S+MNODES*MGALES,        ! WARTD(NDIME,NNODE,NGAUS)
     . IFOT30S=IFOT29S+MDIMES*MNODES*MGAUSS, ! WERIV(NDIME,NNODE,NGAUS)
     . IFOT31S=IFOT30S+MDIMES*MNODES*MGAUSS*MGALES, !WHADE(NNODE,NGAUS)
     . IFOT32S=IFOT31S+MNODES*MGAUSS*MCONVS ) ! CENTR(NDIME,NNODE)
      PARAMETER(
     . IFOT33S=IFOT32S+MDIMES*MNODES*MGALES,  ! VEL1M(NEVAB)
     . IFOT34S=IFOT33S+MEVABS*MMICRS*(1-MMICOS), ! ADVEM(NDIME*NNODE)
     . IFOT35S=IFOT34S+MDIMES*MNODES*MCONVS, ! CARTD(NDIME,NNODE,NGAUS)
     . IFOT36S=IFOT35S+MDIMES*MNODES*MGAUSS,  ! DVOLU(NGAUS)
     . IFOT37S=IFOT36S+MGAUSS,                ! GPCOD(NDIME,NGAUS)
     . IFOT38S=IFOT37S+MDIMES*MGAUSS,         ! SHAPE(NNODE,NGAUS)
     . IFOT39S=IFOT38S+MNODES*MGAUSS,        ! DERIV(NDIME,NNODE,NGAUS)
     . IFOT40S=IFOT39S+MDIMES*MNODES*MGAUSS,  ! POSGP(NDIME,NGAUS)
     . IFOT41S=IFOT40S+MDIMES*MGAUSS,         ! WEIGP(NGAUS)
     . IFOT42S=IFOT41S+MGAUSS,                ! XJACM(NDIME,NDIME)
     . IFOT43S=IFOT42S+MDIMES*MDIMES,         ! EMASS(NNODE,NNODE)
     . IFOT44S=IFOT43S+MNODES*MNODES,         ! ELDI1(NDOFN,NNODE)
     . IFOT45S=IFOT44S+MDOFCS*MNODES,         ! TEINI(NDOFN,NNODE)

     . IFOT46S=IFOT45S+MDOFCS*MNODES,         ! BOUCH(NDOFN,NNODE)
     . IFOT47S=IFOT46S+MDOFCS*MNODES*MMEMO10S,      ! VNORL(NDIME,NGAUS)
     . IFOT48S=IFOT47S+MDIMES*MGAUSS*MTER2S*MMEMO11S )
C                                                    !FPCHL(NFPCH,NNODE)
      PARAMETER(
     . IFOT49S=IFOT48S+MFPCHS*MNODES,               ! DVOLI(NGAUS)
     . IFOT50S=IFOT49S+MGAUSS*MTER3S,               ! ELCOI(NDIME,NNODE)
     . LFOTS  =IFOT50S+MDIMES*MNODES*MTER3S )
C
      PARAMETER(
     . IFOR1S=1,                              ! ELELM(NEVAB)
     . IFOR2S=IFOR1S+MEVABS,                  ! VELCM(NEVAB)
     . IFOR3S=IFOR2S+MEVABS,                  ! DISIM(NEVAB)
     . IFOR4S=IFOR3S+MEVABS,                  ! ESTIF(NKOVA)
     . IFOR5S=IFOR4S+MKOVAS,                  ! DSTIF(NKOVA)
     . IFOR6S=IFOR5S+MKOVAS,                  ! ELELT(NEVAB)
     . IFOR7S=IFOR6S+MEVABS,                  ! SHAPD(NNODE,NGAUS)
     . IFOR8S=IFOR7S+MNODES*MGAUSS,           ! DVOLD(NGAUS)
     . IFOR9S=IFOR8S+MGAUSS,                  ! POSGP(NDIME,NGAUS)
     . IFOR10S=IFOR9S+MDIMES*MGAUSS,          ! WEIGP(NGAUS)
     . IFOR11S=IFOR10S+MGAUSS,               ! DERID(NDIME,NNODE,NGAUS)
     . IFOR12S=IFOR11S+MDIMES*MNODES*MGAUSS,  ! XJACM(NDIME,NDIME)
     . IFOR13S=IFOR12S+MDIMES*MDIMES,        ! CARDD(NDIME,NNODE,NGAUS)
     . IFOR14S=IFOR13S+MDIMES*MNODES*MGAUSS,  ! GPCDD(NDIME,NGAUS)
     . IFOR15S=IFOR14S+MDIMES*MGAUSS,         ! ELEL1(NEVAB)
     . IFOR16S=IFOR15S+MEVABS )               ! ELEL2(NEVAB)
      PARAMETER(
     . IFOR17S=IFOR16S+MEVABS,                ! ELCO1(NDIME,NNODE)
     . IFOR18S=IFOR17S+MDIMES*MNODES,         ! WHAPE(NNODE,NGAUS)
     . IFOR19S=IFOR18S+MNODES*MGAUSS,         ! HACHE(NNODE)
     . IFOR20S=IFOR19S+MNODES*MGALES,         ! WHADE(NNODE,NGAUS)
     . IFOR21S=IFOR20S+MNODES*MGAUSS,         ! CENTR(NDIME,NNODE)
     . IFOR22S=IFOR21S+MDIMES*MNODES*MGALES,  ! ADVEM(NDIME,NNODE)
     . IFOR23S=IFOR22S+MDIMES*MNODES*MCONVS, ! CARTD(NDIME,NNODE,NGAUS)
     . IFOR24S=IFOR23S+MDIMES*MNODES*MGAUSS,  ! DVOLU(NGAUS)
     . IFOR25S=IFOR24S+MGAUSS,                ! GPCOD(NDIME,NGAUS)
     . IFOR26S=IFOR25S+MDIMES*MGAUSS,         ! SHAPE(NNODE,NGAUS)
     . IFOR27S=IFOR26S+MNODES*MGAUSS,        ! DERIV(NDIME,NNODE,NGAUS)
     . IFOR28S=IFOR27S+MDIMES*MNODES*MGAUSS,  ! POSGP(NDIME,NGAUS)
     . IFOR29S=IFOR28S+MDIMES*MGAUSS,         ! WEIGP(NGAUS)
     . IFOR30S=IFOR29S+MGAUSS,                ! XJACM(NDIME,NDIME)
     . IFOR31S=IFOR30S+MDIMES*MDIMES,         ! EMASS(NNODE,NNODE)
     . IFOR32S=IFOR31S+MNODES*MNODES )        ! ELDI1(NDOFN,NNODE)
      PARAMETER(
     . IFOR33S=IFOR32S+MDOFCS*MNODES,         ! TEINI(NDOFN,NNODE)
     . IFOR34S=IFOR33S+MDOFCS*MNODES,         ! FPCHL(NFPCH,NNODE)
     . IFOR35S=IFOR34S+MFPCHS*MNODES,               ! DVOLI(NGAUS)
     . IFOR36S=IFOR35S+MGAUSS*MTER3S,               ! ELCOI(NDIME,NNODE)
     . IFOR37S=IFOR36S+MDIMES*MNODES*MTER3S,     ! DISPT(NDOFC,NNODE) !m
     . LFORS  =(IFOR37S+MDOFCMS*MNODES*MTER3S)*MDYNAS )
C
      PARAMETER(
     . ILOS1S=1,                              ! ALOAD(NEVAB)
     . ILOS2S=ILOS1S+MEVABS,                  ! DERIV(NDIME,NNODE)
     . ILOS3S=ILOS2S+MDIMES*MNODES,           ! ELEDG(NDIME,NNODE)
     . ILOS4S=ILOS3S+MDIMES*MNODES,           ! GPCOD(NDIME)
     . ILOS5S=ILOS4S+MDIMES,                  ! GVECT(NDIME)
     . ILOS6S=ILOS5S+MDIMES,                  ! NOPRS(NNODE)
     . ILOS7S=ILOS6S+MNODES,                  ! POSGP(NDIME,NGAUS)
     . ILOS8S=ILOS7S+MDIMES*MGAUSS,           ! PRESS(NNODE,NDIME)
     . ILOS9S=ILOS8S+MNODES*MDIMES,           ! PVECT(NDIME)
     . ILOS10S=ILOS9S+MDIMES,                 ! SHAPE(NNODE)
     . ILOS11S=ILOS10S+MNODES,                ! VAREA(NDIME)
     . ILOS12S=ILOS11S+MDIMES,                ! WEIGP(NGAUS)
     . ILOS13S=ILOS12S+MGAUSS,                ! XJACM(NDIME*NDIME)
     . ILOS14S=ILOS13S+MDIMES*MDIMES,         ! CARTD(NDIME,NNODE)
     . ILOS15S=ILOS14S+MDIMES*MDIMES,         ! PRESC(NTOTV)
     . ILOS16S=ILOS15S+MTOTVS )               ! VELCM(NEVAB)
      PARAMETER(
     . ILOS17S=ILOS16S+MEVABS,                ! ELCO1(NDIME,NNODE)
     . ILOS18S=ILOS17S+MDIMES*MNODES,         ! WHAPE(NNODE,NGAUS)
     . ILOS19S=ILOS18S+MNODES*MGAUSS,         ! HACHE(NNODE)
     . ILOS20S=ILOS19S+MNODES*MGALES,         ! CENTR(NDIME,NNODE)
     . ILOS21S=ILOS20S+MDIMES*MNODES*MGALES,  ! CARTD(NDIME,NNODE,NGAUS)
     . ILOS22S=ILOS21S+MDIMES*MNODES*MGAUSS,  ! DVOLU(NGAUS)
     . ILOS23S=ILOS22S+MGAUSS,                ! GPCOD(NDIME,NGAUS)
     . ILOS24S=ILOS23S+MDIMES*MGAUSS,         ! SHAPE(NNODE,NGAUS)
     . ILOS25S=ILOS24S+MNODES*MGAUSS,        ! DERIV(NDIME,NNODE,NGAUS)
     . ILOS26S=ILOS25S+MDIMES*MNODES*MGAUSS,  ! POSGP(NDIME,NGAUS)
     . ILOS27S=ILOS26S+MDIMES*MGAUSS,         ! WEIGP(NGAUS)
     . ILOS28S=ILOS27S+MGAUSS,                ! XJACM(NDIME,NDIME)
     . ILOS29S=ILOS28S+MDIMES*MDIMES,         ! EMASS(NNODE,NNODE)
     . ILOS30S=ILOS29S+MNODES*MNODES,         ! ELDI1(NDOFN,NNODE)
     . ILOS31S=ILOS30S+MDOFCS*MNODES,         ! TEINI(NDOFN,NNODE)
     . ILOS32S=ILOS31S+MDOFCS*MNODES )        ! ADVEM(NDIME,NNODE)
      PARAMETER(
     . ILOS33S=ILOS32S+MDIMES*MNODES*MCONVS,   ! BOUCH(NDOFN,NNODE)
     . ILOS34S=ILOS33S+MDOFCS*MNODES*MMEMO10S, ! FPCHL(NFPCH,NNODE)
     . ILOS35S=ILOS34S+MFPCHS*MNODES,          ! DVOLI(NGAUS)
     . ILOS36S=ILOS35S+MGAUSS*MTER3S,          ! ELCOI(NDIME,NNODE)
     . ILOS37S=ILOS36S+MDIMES*MNODES*MTER3S,   ! DISPT(NDOFC,NNODE) !m
     . LLOSS  =ILOS37S+MDOFCMS*MNODES*MTER3S )
C
      PARAMETER(
     . IGSM1S=1,                                   ! SMSTS(NSTR1,NPOIN)
     . IGSM2S=IGSM1S+MSTR1S*MPOINS*MSMOMS*MMEMO4S, ! SMSTN(NDIME,NPOIN)
     . IGSM3S=IGSM2S+MDIMES*MPOINS*MSMOMS*MMEMO4S, ! ACCPN(NPOIN)
     . IGSM4S=IGSM3S+MPOINS*MSMOMS*MMEMO4S,        ! STREB(NSTR1,NNODE)
     . IGSM5S=IGSM4S+MSTR1S*MNODES*MSMOMS*MMEMO4S, ! STREA(NNODE,NSTR1)
     . IGSM6S=IGSM5S+MNODES*MSTR1S*MSMOMS*MMEMO4S, ! SFISB(NDIME,NNODE)
     . IGSM7S=IGSM6S+MDIMES*MNODES*MSMOMS*MMEMO4S, ! SFISA(NNODE,NDIME)
     . IGSM8S=IGSM7S+MNODES*MSTR1S*MSMOMS*MMEMO4S, ! SMSTP(NNUIN,NPOIN)
     . IGSM9S=IGSM8S+MNUINS*MPOINS*MSMOMS,         ! SFIPA(NNUIN,NNODE)
     . IGSM10S=IGSM9S+MNUINS*MNODES*MSMOMS,        ! SFIPB(NNODE,NNUIN)
     . IGSM11S=IGSM10S+MNODES*MNUINS*MSMOMS,  ! CARTD(NDIME,NNODE,NGAUS)
     . IGSM12S=IGSM11S+MDIMES*MNODES*MGAUSS,  ! DVOLU(NGAUS)
     . IGSM13S=IGSM12S+MGAUSS,                ! GPCOD(NDIME,NGAUS)
     . IGSM14S=IGSM13S+MDIMES*MGAUSS,         ! SHAPE(NNODE,NGAUS)
     . IGSM15S=IGSM14S+MNODES*MGAUSS,         ! DERIV(NDIME,NNODE,NGAUS)
     . IGSM16S=IGSM15S+MDIMES*MNODES*MGAUSS ) ! POSGP(NDIME,NGAUS)
      PARAMETER(
     . IGSM17S=IGSM16S+MDIMES*MGAUSS,         ! WEIGP(NGAUS)
     . IGSM18S=IGSM17S+MGAUSS,                ! XJACM(NDIME,NDIME)
     . IGSM19S=IGSM18S+MDIMES*MDIMES,         ! ELCO1(NDIME,NNODE)
     . IGSM20S=IGSM19S+MDIMES*MNODES,         ! EMASS(NNODE,NNODE)
     . IGSM21S=IGSM20S+MNODES*MNODES,         ! ELDI1(NDOFN,NNODE)
     . IGSM22S=IGSM21S+MDOFCS*MNODES,         ! SMSPP(NPORO,NPOIN)
     . IGSM23S=IGSM22S+MPOROS*MPOINS,         ! SPIPA(NNODE,NPORO)
     . IGSM24S=IGSM23S+MNODES*MPOROS,         ! SPIPB(NPORO,NPORO)
     . IGSM25S=IGSM24S+MPOROS*MNODES,         ! SPIPC(NPORO,NNODG)
     . IGSM26S=IGSM25S+MPOROS*MNODGS,         ! FPCHL(NFPCH,NNODE)
     . IGSM27S=IGSM26S+MFPCHS*MNODES,         ! VELCM(NDOFN,NNODE)
     . IGSM28S=IGSM27S+MDOFCS*MNODES,         ! DVOLI(NGAUS)
     . IGSM29S=IGSM28S+MGAUSS*MTER3S,         ! ELCOI(NDIME,NNODE)
     . IGSM30S=IGSM29S+MDIMES*MNODES*MTER3S,  ! DISPT(NDOFC,NNODE) !m
     . LGSMS  =IGSM30S+MDOFCMS*MNODES*MTER3S )
C
      PARAMETER(
     . ISET1S=1,                              ! DERIV(NDIME,NNODE,NGAUS)
     . ISET2S=ISET1S+MDIMES*MNODES*MGAUSS,    ! POSGP(NDIME,NGAUS)
     . ISET3S=ISET2S+MGAUSS*MDIMES,           ! WEIGP(NGAUS)
     . ISET4S=ISET3S+MGAUSS,                  ! XJACM(NDIME,NDIME)
     . ISET5S=ISET4S+MDIMES*MDIMES,           ! RMAT2(NSTR1,NSTR1)
     . ISET6S=ISET5S+MSTR1S*MSTR1S,           ! ELCO1(NDIME,NNODE)
     . ISET7S=ISET6S+MDIMES*MNODES,          ! CARTD(NDIME,NNODE,NGAUS)
     . ISET8S=ISET7S+MDIMES*MNODES*MGAUSS,    ! DVOLU(NGAUS)
     . ISET9S=ISET8S+MGAUSS,                  ! GPCOD(NDIME,NGAUS)
     . ISET10S=ISET9S+MDIMES*MGAUSS,          ! SHAPE(NNODE,NGAUS)
     . ISET11S=ISET10S+MNODES*MGAUSS,         ! EMASS(NNODE,NNODE)
     . ISET12S=ISET11S+MNODES*MNODES,         ! ELDI1(NDOFN,NNODE)
     . ISET13S=ISET12S+MDOFCS*MNODES,         ! TEINI(NDOFN,NNODE)
     . ISET14S=ISET13S+MDOFCS*MNODES,         ! FPCHL(NFPCH,NNODE)
     . ISET15S=ISET14S+MFPCHS*MNODES,         ! VNORL(NDIME,NGAUS)
     . ISET16S=ISET15S+MDIMES*MGAUSS*MTER2S*MMEMO11S )    ! DVOLI(NGAUS)
      PARAMETER(
     . ISET17S=ISET16S+MGAUSS*MTER3S,         ! ELCOI(NDIME,NNODE)
     . ISET18S=ISET17S+MDIMES*MNODES*MTER3S,  ! DISPT(NDOFC,NNODE) !m
     . LSETS  =ISET18S+MDOFCMS*MNODES*MTER3S )
C
      PARAMETER(
     . ISTI1S=1,                              ! BMATX(NSTR1,NEVAB)
     . ISTI2S=ISTI1S+MSTR1S*MEVABS,           ! DMATX(NSTR1,NSTR1)
     . ISTI3S=ISTI2S+MSTR1S*MSTR1S,           ! SIGMA(NSTR1)
     . ISTI4S=ISTI3S+MSTR1S,                  ! XJACM(NDIME,NDIME)
     . ISTI5S=ISTI4S+MDIMES*MDIMES,           ! SHAPD(NNODE,NGAUS)
     . ISTI6S=ISTI5S+MNODES*MGAUSS,           ! DVOLD(NGAUS)
     . ISTI7S=ISTI6S+MGAUSS,                  ! POSGP(NDIME,NGAUS)
     . ISTI8S=ISTI7S+MDIMES*MGAUSS,           ! WEIGP(NGAUS)
     . ISTI9S=ISTI8S+MGAUSS,                 ! DERID(NDIME,NNODE,NGAUS)
     . ISTI10S=ISTI9S+MDIMES*MNODES*MGAUSS,   ! XJACM(NDIME,NDIME)
     . ISTI11S=ISTI10S+MDIMES*MDIMES,        ! CARDD(NDIME,NNODE,NGAUS)
     . ISTI12S=ISTI11S+MDIMES*MNODES*MGAUSS,  ! GPCDD(NDIME,NGAUS)
     . ISTI13S=ISTI12S+MDIMES*MGAUSS,         ! VELCM(NEVAB)
     . ISTI14S=ISTI13S+MEVABS,                ! WSTI1(NKOVA)
     . ISTI15S=ISTI14S+MKOVAS,                ! WSTI2(NKOVA)
     . ISTI16S=ISTI15S+MKOVAS )               ! VELAN(NEVAB)
      PARAMETER(
     . ISTI17S=ISTI16S+MEVABS,                ! DISIT(NEVAB)
     . ISTI18S=ISTI17S+MEVABS,                ! ELCO1(NDIME,NNODE)
     . ISTI19S=ISTI18S+MDIMES*MNODES,         ! WHAPE(NNODE,NGAUS)
     . ISTI20S=ISTI19S+MNODES*MGAUSS,         ! HACHE(NNODE)
     . ISTI21S=ISTI20S+MNODES*MGALES,         ! WARTD(NDIME,NNODE,NGAUS)
     . ISTI22S=ISTI21S+MDIMES*MNODES*MGAUSS, ! WERIV(NDIME,NNODE,NGAUS)
     . ISTI23S=ISTI22S+MDIMES*MNODES*MGAUSS*MGALES, ! WHADE(NNODE,NGAUS)
     . ISTI24S=ISTI23S+MNODES*MGAUSS,               ! CENTR(NDIME,NNODE)
     . ISTI25S=ISTI24S+MDIMES*MNODES*MGALES,        ! ADVEM(NDIME,NNODE)
     . ISTI26S=ISTI25S+MDIMES*MNODES*MCONVS, ! CARTD(NDIME,NNODE,NGAUS)
     . ISTI27S=ISTI26S+MDIMES*MNODES*MGAUSS,  ! DVOLU(NGAUS)
     . ISTI28S=ISTI27S+MGAUSS,                ! GPCOD(NDIME,NGAUS)
     . ISTI29S=ISTI28S+MDIMES*MGAUSS,         ! SHAPE(NNODE,NGAUS)
     . ISTI30S=ISTI29S+MNODES*MGAUSS,        ! DERIV(NDIME,NNODE,NGAUS)
     . ISTI31S=ISTI30S+MDIMES*MNODES*MGAUSS,  ! POSGP(NDIME,NGAUS)
     . ISTI32S=ISTI31S+MDIMES*MGAUSS )        ! WEIGP(NGAUS)
      PARAMETER(
     . ISTI33S=ISTI32S+MGAUSS,                ! XJACM(NDIME,NDIME)
     . ISTI34S=ISTI33S+MDIMES*MDIMES,         ! EMASS(NNODE,NNODE)
     . ISTI35S=ISTI34S+MNODES*MNODES,         ! PREASL(NNODE)
     . ISTI36S=ISTI35S+MNODES,                ! TGAPSL(NNODE)
     . ISTI37S=ISTI36S+MNODES,                ! ESTII(NKOVA)
     . ISTI38S=ISTI37S+MKOVAS,                ! WSTII(NKOVA)
     . ISTI39S=ISTI38S+MKOVAS*MDYNAS,         ! ELDI1(NDOFN,NNODE)
     . ISTI40S=ISTI38S+MDOFCS*MNODES,         ! ELDI1(NDOFN,NNODE)
     . ISTI41S=ISTI40S+MDOFCS*MNODES,         ! CSTI1(NEVAB,NEVAB)
     . ISTI42S=ISTI41S+MEVABS*MEVABS*MMEMO7S, ! BOUCH(NDOFN,NNODE)
     . ISTI43S=ISTI42S+MDOFCS*MNODES*MMEMO10S, ! VNORL(NDIME,NGAUS)
     . ISTI44S=ISTI43S+MDIMES*MGAUSS*MTER2S*MMEMO11S,
C                                             ! DISPT(NDOFC,NNODE) !m
     . ISTI45S=ISTI44S+MDOFCMS*MNODES*MTER113S, ! FPCHL(NFPCH,NNODE)
     . ISTI46S=ISTI45S+MFPCHS*MNODES,         ! DVOLI(NGAUS)
     . ISTI47S=ISTI46S+MGAUSS*MTER3S,         ! ELCOI(NDIME,NNODE)
     . ISTI48S=ISTI47S+MDIMES*MNODES*MTER3S,  ! EMATX(NEVAB,NEVAB)
     . ISTI49S=ISTI48S+MEVABS*MEVABS,         ! FMATX(NEVAB,NEVAB)
     . LSTIS  =ISTI49S+MEVABS*MEVABS )
C
C**** ADDSOLS
C
C**** 1) SKYLINE SOLVER
C
      PARAMETER(
     . ISOL1TSS=1,                               ! GSTDI(NEQNS)
     . ISOL2TSS=ISOL1TSS+MEQNSS,                 ! GSTLO(NLAST*IUNSY)
     . ISOL3TSS=ISOL2TSS+MLASTS*MUNSY2S,          ! GSTUP(NLAST)
     . ISOL4TSS=ISOL3TSS+MLASTS,                 ! CSTIF(NEVAC,NEVAC)
     . ISOL5TSS=ISOL4TSS+MEVACS*MEVACS,          ! ELOAD(NEQNS)
     . ISOL6TSS=ISOL5TSS+MEQNSS,                 ! LNUEQ(NTOTV)
     . ISOL7TSS=ISOL6TSS+(MTOTVS*MCHALS+4)/8,    ! LPONT(NTOTV)
     . ISOL8TSS=ISOL7TSS+(MTOTVS*MCHALS+4)/8,    ! DISIM(NEVAC)
     . ISOL9TSS=ISOL8TSS+MEVACS,                 ! FOREL(NEVAC)
     . ISOL10TSS=ISOL9TSS+MEVACS,                ! ALOAD(NEQNS*IFITE)
     . ISOL11TSS=ISOL10TSS+MEQNSS*MFITES,        ! DELTA(NEQNS*IFITE)
     . ISOL12TSS=ISOL11TSS+MEQNSS*MFITES,        ! DISIC(NEQNS*IFITE)
     . ISOL13TSS=ISOL12TSS+MEQNSS*MFITES,        ! LOCAL(NEVAC*IFITE)
     . LSOLTSS  =ISOL13TSS+(MEVACS*MFITES*MCHALS+4)/8 )
C
      PARAMETER(
     . LSOLT1S=MSOLV1S*LSOLTSS )
C
C**** 2) FRONTAL SOLVER
C
      PARAMETER(
     . ISOL1TFS=1,                               ! EQRHS(NBUFA)
     . ISOL2TFS=ISOL1TFS+MBUFAS,                 ! EQUAT(NFRON,NBUFA)
     . ISOL3TFS=ISOL2TFS+MFRONS*MBUFAS,          ! GLOAD(NFRON)
     . ISOL4TFS=ISOL3TFS+MFRONS,                 ! GSTIF(NSTIF)
     . ISOL5TFS=ISOL4TFS+MSTIFS,                 ! LOCEL(NEVAC)
     . ISOL6TFS=ISOL5TFS+(MEVACS*MCHALS+4)/8,    ! NACVA(NFRON)
     . ISOL7TFS=ISOL6TFS+(MFRONS*MCHALS+4)/8,    ! NAMEV(NBUFA)
     . ISOL8TFS=ISOL7TFS+(MBUFAS*MCHALS+4)/8,    ! NDEST(NEVAC)
     . ISOL9TFS=ISOL8TFS+(MEVACS*MCHALS+4)/8,    ! NPIVO(NBUFA)
     . ISOL10TFS=ISOL9TFS+(MBUFAS*MCHALS+4)/8,   ! VECRV(NFRON)
     . ISOL11TFS=ISOL10TFS+MFRONS,               ! CSTIF(NEVAC,NEVAC)
     . ISOL12TFS=ISOL11TFS+MEVACS*MEVACS,     ! EQCOL(IUNSY*NFRON*NBUFA)
     . LSOLTFS  =ISOL12TFS+MUNSY2S*MFRONS*MBUFAS  )
C
      PARAMETER(
     . LSOLT2S=MSOLV2S*LSOLTFS )
C
C**** 3) PCG SOLVER
C
      PARAMETER(
     . ISOL1TPS=1,                               ! GSTDI(NPOIN*NSIZE)
     . ISOL2TPS=ISOL1TPS+MPOINS*MSIZES,          ! CSTIF(NEVAC,NEVAC)
     . ISOL3TPS=ISOL2TPS+MEVACS*MEVACS,          ! DISIM(NEVAC)
     . ISOL4TPS=ISOL3TPS+MEVACS,                 ! FOREL(NEVAC)
     . ISOL5TPS=ISOL4TPS+MEVACS,                 ! ALOAD(NTOTV)
     . ISOL6TPS=ISOL5TPS+MTOTVS,                 ! DELTA(NTOTV)
     . LSOLTPS =ISOL6TPS+MTOTVS )
C
      PARAMETER(
     . LSOLT3S=MSOLV3S*LSOLTPS )
C
C**** 4) GMRES SOLVER (not implemented)
C
      PARAMETER(
     . LSOLTGS =0 )
C
      PARAMETER(
     . LSOLT4S=MSOLV4S*LSOLTGS )
C
C**** 5) EXPLICIT SOLVER
C
      PARAMETER(
     . ISOL1TES=1+LSTIS*MMEMO7S,                 ! CSTIF(NEVAC,NEVAC)
     . ISOL2TES=ISOL1TES+MEVACS*MEVACS,          ! DISIM(NEVAC)
     . ISOL3TES=ISOL2TES+MEVACS,                 ! FOREL(NEVAC)
     . ISOL4TES=ISOL3TES+MEVACS,                 ! CSTII(NEVAC)
     . ISOL5TES=ISOL4TES+MEVACS,                 ! CSTIT(NTOTV)
     . LSOLTES =ISOL5TES+MTOTVS )
C
      PARAMETER(
     . LSOLT5S=MSOLV5S*LSOLTES )
C
      PARAMETER(
c    . LSOLSS=max(LSOLT1,LSOLT2,LSOLT3,LSOLT4,LSOLT5) )     ! sg
     . LSOLSS=(LSOLT1S+LSOLT2S+LSOLT3S+LSOLT4S+LSOLT5S) )   ! PC & linux
C
C**** SCRATCH VECTOR (WORK1S)
C
      PARAMETER(
c    . MWORK1S=max(LINDS,LRENS,LQUAS,LFIXS,LFOTS,LFORS,     ! sg
c    .             LLOSS,LGSMS,LSETS,LSTIS,LSOLSS) )        ! sg
     . MWORK1S=(LINDS+LRENS+LQUAS+LFIXS+LFOTS+LFORS+        ! PC & linux
     .          LLOSS+LGSMS+LSETS+LSTIS+LSOLSS) )           ! PC & linux
C
