      SUBROUTINE PETR05S(ELCODS,PROPSS,ELDISS,SHAPES,CARTDS,
     .                   POSGPS,WEIGPS,GPCODS,SHAPDS,DERIVS,XJACMS,
     .                   CARDDS,VELCMS,WHAPES,HACHES,
     .                   WERIVS,CENTRS,ADVEMS,TEINIS,FPCHLS,
     .                   EHISTS)
C***********************************************************************
C
C**** THIS ROUTINE COMPUTES GALERKIN (IGALES=0) OR PETROV-GALERKIN
C     (IGALES=1) TYPE WEIGHT FUNCTIONS
C
C     NOTES: WERIVT (DERIDT) IS NOT REALLY USED IN THE CALCULATION OF
C            THE WEIGHT FUNCTION WHAPEL
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'   ! thermal-mechanical
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
      COMMON/JACOBSSA/IERORS,KERORS
C
      DIMENSION ELCODS(NDIMES,*),        PROPSS(*),
     .          ELDISS(NDOFCS,*),        SHAPES(NNODLS,*),
     .          CARTDS(NDIMES,NNODLS,*)
      DIMENSION POSGPS(NDIMES,*),        WEIGPS(*),
     .          GPCODS(NDIMES,*),        SHAPDS(NNODLS,*)
      DIMENSION DERIVS(NDIMES,NNODLS,*), XJACMS(NDIMES,*),
     .          CARDDS(NDIMES,NNODLS,*), VELCMS(*),
     .          WHAPES(NNODLS,*),
     .          HACHES(NNODLS),
     .          WERIVS(NDIMES,NNODLS,*)
      DIMENSION CENTRS(NDIMES,*),        ADVEMS(NDIMES,*)
      DIMENSION TEINIS(NDOFCS,*),        FPCHLS(NFPCH,*)
      DIMENSION EHISTS(NHISTS,*)
C
      TWOPIT=6.283185307179586D0
C
      IF(IGALES.EQ.0) THEN
       DO IGAUSS=1,NGAULS
        DO INODLS=1,NNODLS
         WHAPES(INODLS,IGAUSS)=SHAPES(INODLS,IGAUSS)
        ENDDO
       ENDDO
       RETURN
      ENDIF
C
C**** IDENTIFY SAMPLING POINTS AND WEIGHTS OF THE SHAPE FUNCTION
C
c     CALL RULEPW(NDIMET,NGAULT,NRULET,POSGPT,WEIGPT)
C
C**** LOOP ON INTEGRATION POINTS
C
      DO 100 IGAUSS=1,NGAULS
C
C**** COMPUTE SHAPE FUNCTIONS AND DERIVATIVES
C
c     EXISPT=POSGPT(1,IGAUST)
c     ETASPT=0.0D0
c     IF(NDIMET.GE.2) ETASPT=POSGPT(2,IGAUST)
c     EZETAT=0.0
c     IF(NDIMET.EQ.3) EZETAT=POSGPT(3,IGAUST)
c     CALL SHAFUN(DERIVT(1,1,IGAUST),EXISPT,ETASPT,EZETAT,NDIMET,NNODLT,
c    .            NQUTRS,     0,SHAPDT(1,IGAUST))
C
C**** CARTESIAN DERIVATIVES OF THE SHAPE FUNCTIONS
C
c     CALL JACOBST(CARDDT(1,1,IGAUST), DERIVT(1,1,IGAUST), DETJMT,
c    .             ELCODT,             GPCODT(1,IGAUST),   IELEMT,
c    .             NDIMET,NNODLT,      SHAPDT(1,IGAUST),   XJACMT,
c    .             LUREST,LUPRIT)
C
C**** DEFINES THE UPWIND FUNCTION
C
c     NSUPE=1
c     CALL HACHEC(ELCODT,PROPST,ELDIST,VELCMT,HACHET,CENTRO,
c    .            ADVEMT,TEINIT,SHAPET(1,IGAUST),NSUPE,FPCHLT,
c    .            EHISTS(1,IGAUST),CARTDT(1,1,IGAUST))
C
C**** COMPUTE PERTURBATION FUNCTIONS AND DERIVATIVES
C
c     CALL WHAFUN(WERIVT(1,1,IGAUST),EXISPT,ETASPT,EZETAT,NDIMET,NNODLT,
c    .            WHAPEL(1,IGAUST),HACHET,XJACMT,IPERT)
C
C**** COMPUTES WEIGHT FUNCTION (SHAPE FUNCTION + PERTURBATION FUNCTION)
C
c     DO INODLT=1,NNODLT
c      WHAPEL(INODLT,IGAUST)=SHAPET(INODLT,IGAUST)+
c    .                       WHAPEL(INODLT,IGAUST)
c     ENDDO
C
  100 CONTINUE           ! igauss=1,ngauss
C
      RETURN
      END
