      SUBROUTINE POSTSOT(DISITT,DSOLDT,REFORT,RFOLDT,VVECTT,WVECTT)
C***********************************************************************
C
C**** THIS ROUTINE MODIFIES THE ITERATIVE DISPLACEMENTS IF A 
C     SECANT-NEWTON OR QUASI-NEWTON METHOD IS USED
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
      DIMENSION DISITT(*), DSOLDT(*), REFORT(*), RFOLDT(*)
      DIMENSION VVECTT(*), WVECTT(*)
C
C**** MODIFY ITERATIVE DISPLACEMENTS FOR SECANT-NEWTON METHOD
C
      CALL SECANTT(DISITT,DSOLDT,REFORT,RFOLDT)
C
C**** MODIFY ITERATIVE DISPLACEMENTS FOR QUASI-NEWTON METHOD ( BFGS )
C
      IF((LACCET.EQ.3).AND.IITERT.GT.1.AND.KARCLT.EQ.0)
     .  CALL BFGSUPT(DISITT,REFORT,VVECTT,WVECTT)
C
      IF(LACCET.LE.1) RETURN
C
C**** STORE DISIT & REFOR IN ALLOCATED SPACE
C
      DO ITOTVT=1,NTOTVT
        DSOLDT(ITOTVT)=DISITT(ITOTVT)
        RFOLDT(ITOTVT)=REFORT(ITOTVT)
      ENDDO
C
      RETURN
      END
