      SUBROUTINE POTEN1(DEFPI,DEFQU,DEFTH,DEFPP,DEFQQ,DEFTT,DEFPQ,
     .                  DEFPT,DEFQT,EHIST,HARDS,IFLAG,ITEST,NCRIT,
     .                  PROPS,QINVA,THETA)
C***********************************************************************
C
C****THIS ROUTINE CALCULATES THE ASSOCIATED ELLIPSE PARAMETERS
C
C    ITEST=1  CALCULATE 1ST ORDER PARTIAL DERIVATIVE AND PLASTIC
C             MODULUS;
C    ITEST=2  CALCULATE AS IN ITEST=1 AND THE SECOND ORDER PARTIAL 
C             DERIVATIVE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EHIST(*), PROPS(*)
C
      FINCL=PROPS(34)
      IFLAG=0
      IF(NCRIT.EQ.1) 
     . CALL VARTHE(CAPTH,CINTE,FINCL,IFLAG,PROPS,THETA)
C
C***AND THE FIRST ORDER PARTIAL DERIVATIVE
C
      DEFPI=FINCL
      DEFQU=1.
      DEFTH=0.
      IF(IFLAG.EQ.1)DEFTH=-QINVA*CAPTH
      IF(ITEST.EQ.2)GOTO 15
C
C***CALCULATE THE PLASTIC MODULUS
C
      HARDS=0.0
C
      RETURN
C
C***CALCULATE THE SECOND ORDER PARTIAL DERIVATIVE
C
   15 DEFPP=0.
      DEFQQ=0.
      DEFPQ=0.
      IF(IFLAG.EQ.0)GOTO 20
      DEFTT=-(1.+2.*CAPTH*CAPTH)*QINVA
      DEFPT=0.
      DEFQT=0.
C
      RETURN
C
   20 CONTINUE
      DEFTT=0.
      DEFPT=0.
      DEFQT=0.
C
      RETURN
      END
