      SUBROUTINE POTEN2(DEFPI,DEFQU,DEFTH,DEFPP,DEFQQ,DEFTT,DEFPQ,
     .                  DEFPT,DEFQT,EHIST,HARDS,IFLAG,ITEST,NCRIT,
     .                  PMEAN,PROPS,QINVA,THETA,VSTOT)
C***********************************************************************
C
C****THIS ROUTINE CALCULATES THE ASSOCIATED ELLIPSE PARAMETERS
C
C    ITEST=1  CALCULATE 1ST ORDER PARTIAL DERIVATIVE AND PLASTIC
C             MODULUS;
C    ITEST=2  CALCULATE AS IN ITEST=1 AND THE SECOND ORDER PARTIAL 
C             DERIVATIVE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EHIST(*), PROPS(*)
C
      HPARA=EHIST(3)
      BETAS=EHIST(4)
      EQUMN=EHIST(5)
      RATIO=PROPS(34)
      FACTO=PROPS(35)
      IFLAG=0
      IF(NCRIT.EQ.2.OR.NCRIT.EQ.4)GOTO 10
      CALL VARTHE(CAPTH,CINTE,FINCL,IFLAG,PROPS,THETA)
      RATIO=FACTO*FINCL
C
C***AND THE FIRST ORDER PARTIAL DERIVATIVE
C
   10 CONTINUE
      RATI2=RATIO*RATIO
      DEFPI=2.*(PMEAN-BETAS)
      DEFQU=2.*QINVA/RATI2
      DEFTH=0.
      IF(IFLAG.EQ.1)DEFTH=-DEFQU*QINVA*CAPTH
      IF(ITEST.EQ.2)GOTO 15
C
C***CALCULATE THE PLASTIC MODULUS
C
      HLAMD=PROPS(32)
      CHAIS=PROPS(33)
      DEFPE=-(DEFPI*FACTO-2*HPARA)/(FACTO+1)
      HARDS=DEFPE*DEFPI*VSTOT*EQUMN/(HLAMD-CHAIS)
C
      RETURN
C
C***CALCULATE THE SECOND ORDER PARTIAL DERIVATIVE
C
   15 DEFPP=2.
      DEFQQ=2.*RATI2
      DEFPQ=0.
      IF(IFLAG.EQ.0)GOTO 20
      TITAL=QINVA*(1-CAPTH)/RATIO
      DEFTT=-2.*TITAL*TITAL
      DEFPT=0.
      DEFQT=-4.*QINVA*CAPTH/RATI2 
C
      RETURN
C
   20 CONTINUE
      DEFTT=0.
      DEFPT=0.
      DEFQT=0.
C
      RETURN
      END
