      SUBROUTINE PREDIST(DISTOT,NCOMPX)
C***********************************************************************
C
C**** THIS ROUTINE READS THE INITIAL VALUES FOR DISTO
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'inpo_omt.f'
C
      COMMON/PRFILET/JTAPET,IFLAGT
C
      DIMENSION DISTOT(NDOFCT,*)
      DIMENSION SUBTAT(12)
C
      IOLDE=1                       ! new reading
C
      IERR1T=1
      IF(JTAPET.NE.LUDATT.AND.JTAPET.NE.LUINIT) GO TO 1000
      IF(JTAPET.EQ.LUINIT) THEN       ! external .ini file
       IF(IOINIT.EQ.0) OPEN(UNIT=LUINIT,FILE=CD1T,STATUS='OLD',ERR=1000)
       IOINIT=1
       IERR1T=0
C
 1000  IF(IERR1T.NE.0) THEN
        IF(IERR1T.EQ.1) WRITE(LUREST,901)
        CALL RUNENDT('PREDIST: ERROR IN OPENING FILES')
       ENDIF
      ENDIF
C
C**** READ FOR NUMBER OF NODES WITH INITIAL CONDITIONS
C
      IF(IOLDE.EQ.0) THEN
C
C**** OLD READING (IOLDE=0)
C
       READ(JTAPET,900) NPOI1T
       WRITE(LUREST,905) NPOI1T
       IF(NPOINT.LT.NPOI1T) THEN
        WRITE(LUREST,910)
        CALL RUNENDT('PREDIST:ERROR WHEN READING         ')
       ENDIF
C
      ELSE
C
C**** NEW READING (IOLDE=1)
C
       NPRINT=1
       CALL LISTENT('PREDIST',NPRINT,JTAPET)
       IF(PARAMT(2).NE.0.0)
     .  CALL RUNENDT('PREDIST: ERROR WHEN READING THE NUMBER OF POINTS
     .                         WITH INITIAL TEMPERATURE')
       NPOI1T=DINT(PARAMT(1))
       WRITE(LUREST,905) NPOI1T
       IF(NPOINT.LT.NPOI1T) THEN
        WRITE(LUREST,910)
        CALL RUNENDT('PREDIST: ERROR WHEN READING THE NUMBER OF POINTS
     .                         WITH INITIAL TEMPERATURE')
       ENDIF
C
      ENDIF                   ! iolde.eq.0
C
C**** READ TITLE (ONLY WITH IOLDE=0)
C
      IF(IOLDE.EQ.0) THEN
       READ(JTAPET,915) SUBTAT
       WRITE(LUREST,916) SUBTAT
      ENDIF
C
C**** READ NODAL VARIABLES
C
      DO IPOINT=1,NPOI1T
       IF(IOLDE.EQ.0) THEN
        READ(JTAPET,920) JPOINT, (DISTOT(IDOFNT,JPOINT),IDOFNT=1,NDOFNT)
       ELSE
        CALL LISTENT('PREDIST',NPRINT,JTAPET)
        JPOINT=INT(PARAMT(1))
        DO IDOFNT=1,NDOFNT
         DISTOT(IDOFNT,JPOINT)=PARAMT(1+IDOFNT)
        ENDDO
       ENDIF
      ENDDO
C
C**** ECHO NODAL VALUES FOR THE WHOLE MESH
C
      IF(NCOMPX.EQ.1) WRITE(LUREST,921)
      IF(NCOMPX.EQ.2) WRITE(LUREST,922)
      IF(NCOMPX.EQ.3) WRITE(LUREST,923)
      DO IPOINT=1,NPOINT
        WRITE(LUREST,930)  IPOINT,(DISTOT(IDOFNT,IPOINT),
     .                             IDOFNT=1,NDOFNT)
      ENDDO
C
      WRITE(LUREST,940)
C
      RETURN
C
  900 FORMAT(I5)
  901 FORMAT(' ERROR IN OPENING INITIAL TEMPERATURE INPUT FILE 243',
     . '(53 LINUX)')
  905 FORMAT(/,5X,'NUMBER OF NODES WITH INITIAL DATA',I5,/)
  910 FORMAT(//,
     .    'ERROR: NUMBER OF INPUT POINTS GT TOTAL NO. POINTS')
  915 FORMAT(12A6)
  916 FORMAT(5X,12A6)
  920 FORMAT(I5,3E15.6)
  921 FORMAT(1X,'NODE',4X,'INITIAL TEMPERATURE',/)
  922 FORMAT(1X,'NODE',8X,'INITIAL VELOCITY',/)
  923 FORMAT(1X,'NODE',4X,'INITIAL ACCELERATION',/)
  930 FORMAT(I5,10X,3(E15.6,5X))
  940 FORMAT(/)
      END
