      SUBROUTINE PREPWP(DISTO,HEADS)
C***********************************************************************
C
C****THIS ROUTINE READS THE INITIAL PORE WATER PRESSURES
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
C
      COMMON/PRFILE/JTAPE,IFLAG
C
      DIMENSION DISTO(*), HEADS(NPOIN,*)
      DIMENSION SUBTA(12)
C
C***READ FOR NUMBER OF SATURATED NODES
C
      READ(JTAPE,900) NPOI1
      WRITE(LURES,905)    NPOI1
      IF(NPOIN.LT.NPOI1) THEN
        WRITE(LURES,910)
        CALL RUNEND('ERROR IN PREPWP                    ')
      ENDIF
C
C***READ PORE WATER PRESSURE 
C
      READ(JTAPE,915) SUBTA
      WRITE(LURES,916) SUBTA
C
      DO 30 IPOIN=1,NPOI1
      READ(JTAPE,920)             JPOIN,PWPRE,HEADS(JPOIN,2)
C????      PWPRE=PWPRE*GRAVY
      HEADS(JPOIN,1)=PWPRE
      IF(KPORE.EQ.2)THEN
        ITOTV=JPOIN*NDOFC
        DISTO(ITOTV)=PWPRE
      ENDIF
C????      HEADS(JPOIN,2)=HEADS(JPOIN,2)*GRAVY
   30 CONTINUE
C
C***ECHO PORE WATER PRESSURE VALUES FOR THE WHOLE MESH
C
      WRITE(LURES,925)
      WRITE(LURES,930) (IPOIN,(HEADS(IPOIN,INDEX),INDEX=1,2),
     .                                            IPOIN=1,NPOIN)
C
      RETURN
  900 FORMAT(2I5)
  905 FORMAT(/,5X,'NUMBER OF SATURATED POINTS',I5,/)
  910 FORMAT(//,
     .    '***ERROR SATURATED POINTS GREATER THAN TOTAL NO. POINTS')
  915 FORMAT(12A6)
  916 FORMAT(5X,12A6)
  920 FORMAT(I5,2E15.6)
  925 FORMAT(3(1X,'NODE',5X,'PORE PRES.',5X,'TOTAL HEAD',7X),/)
  930 FORMAT(3(I5,2(5X,F10.3),7X))
      END
