      SUBROUTINE PREVOSS(DISTOS,ELDATS,ELPRES,ELVARS,ELMATS,HEADSS,
     .                   LNODSS,MATNOS,PROELS,PROPSS,TEMPIS,WORK1S)
C***********************************************************************
C
C**** THIS ROUTINE READS THE INITIAL STATE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_oms.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      COMMON/PRFILES/JTAPES,IFLAGS
C
      DIMENSION MATNOS(NELEMS),        LNODSS(NNODES,NELEMS),
     .          PROELS(NPRELS,NGRUPS), PROPSS(NPROPS,NMATSS),
     .          ELDATS(NDATAS),        ELPRES(NPREVS),
     .          ELVARS(NSTATS),        ELMATS(NMATXS)
      DIMENSION DISTOS(NTOTVS,*),      HEADSS(NPOINS,*),
     .          TEMPIS(NPOINS)
      DIMENSION WORK1S(*)
C
      PARAMETER   (MCOMMS=7)
      CHARACTER*5 COMMDS(MCOMMS)
C
      SAVE IFLA1S,IFLA2S,ISTOPS
      DATA IFLA1S,IFLA2S,ISTOPS/0,0,0/
C
      DATA COMMDS/'GAUSS','WATER','TEMPI','TEMPE','VELOC','ACCEL',
     .            'END_I'/
C
      CALL CPUTIMS(TIME1S)
      WRITE(LURESS,900)
C
C**** READ INITIAL_DATA CARD
C
      NPRINS=0
      ITAPES=LUDATS
      CALL LISTENS('PREVOSS',NPRINS,ITAPES)
      IF(WORDSS(1).NE.'INITI') GO TO 1000
C
C**** READ NEW COMMAND
C
  100 CALL LISTENS('PREVOSS',NPRINS,ITAPES)
C
C**** IDENTIFY COMMAND
C
      DO ICOMMS=1,MCOMMS
        IF(WORDSS(1).EQ.COMMDS(ICOMMS)) GO TO 20
      END DO
      GO TO 1000 
C
C**** EXECUTE APPROPRIATE COMMAND
C
   20 JTAPES=LUDATS
      IF(PARAMS(1).NE.0.0) JTAPES=INT(PARAMS(1))
C
      GO TO (1,2,3,4,4,4,5), ICOMMS
C
C**** READ THE INITIAL STATE VARIABLES AT THE GAUSSIAN POINTS
C
    1 call runends('prevoss - not implemented 1')
c   1 IFLAGT=0
c     IF(NMEMO.EQ.0)
c    . CALL RUNENDT('ERROR (PREVOST): MEMORY IS NOT DIMENSIONED FOR 
c    .               INITIAL GAUSSIAN VARIABLES')
c     IF(WORDST(2).EQ.'STRAI') IFLAGT=1
c     IF(WORDST(2).EQ.'STRES') IFLAGT=2
c     IF(WORDST(2).EQ.'PLAST') IFLAGT=3
c     IF(IFLAGT.NE.0)
c    .  CALL PREGAUT(ELDATT,ELPRET,ELVART,ELMATT,LNODST,MATNOT,PROELT,
c    .               PROPST)
      GO TO 100
C
C**** READ THE INITIAL PORE PRESSURE AT NODES
C
    2 call runends('prevoss - not implemented 2')
c   2 CONTINUE
c     IF(KPORET.NE.2) KPORET=1
      GO TO 100
C
C**** READ THE TEMPERATURE DATA AT NODES
C
    3 call runends('prevoss - not implemented 3')
c   3 CONTINUE
c     KTEMPT=1
c     GO TO 100
C
C**** READ THE INITIAL TEMPERATURE AT NODES
C     (VELOCITIES OR ACCELERATIONS AT NODES)
C
    4 IF(WORDSS(1).EQ.'TEMPE') NCOMPS=1
      IF(WORDSS(1).EQ.'VELOC') NCOMPS=2
      IF(WORDSS(1).EQ.'ACCEL') NCOMPS=3
      CALL PREDISS(DISTOS(1,NCOMPS),NCOMPS)
      DO ITOTVS=1,NTOTVS
       TEMPIS(ITOTVS)=DISTOS(ITOTVS,1)
      ENDDO
      GO TO 100
C
C**** RETURN
C
    5 CALL CPUTIMS(TIME2S)
      CPUDAS=CPUDAS+(TIME2S-TIME1S)
      RETURN
C
 1000 CALL RUNENDS('PREVOST:ERROR IN INITIAL DATA BLOCK')
  900 FORMAT(1H1,///,10X,'ECHO OF INITIAL STATE DATA FOLLOWS :',/
     .               10X,'=================================='/)
      END
