      SUBROUTINE PRGA01(PROPS,EHIST,STRA0,STRS0,STRSG)
C***********************************************************************
C
C*** THIS ROUTINE READS THE INITIAL STATE VARIABLES AT GAUSS POINTS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'inte_om.f'
      INCLUDE 'auxl_om.f'
C
      COMMON/PRFILE/JTAPE,IFLAG
C
      DIMENSION EHIST(NHIST,NGAUS),   STRA0(NSTR1,NGAUS),
     .          STRS0(NSTR1,NGAUS),   STRSG(NSTR1,NGAUS), 
     .          PROPS(NPROP)
C
      WRITE(LURES,900) IELEM
C
C***IFLAG=1 >>>> READ INITIAL STRAINS
C
      IF(IFLAG.EQ.1) THEN
        IF(NTYPE.LE.2) WRITE(LURES,920)
        IF(NTYPE.EQ.3) WRITE(LURES,921)
        IF(NTYPE.EQ.4) WRITE(LURES,922)
        IF(NTYPE.EQ.5) WRITE(LURES,923)
        DO  JGAUS=1,NGAUL
          READ(JTAPE,905)  IGAUS,(STRA0(ISTR1,IGAUS),ISTR1=1,NSTR1)
          WRITE(LURES,910) IGAUS,(STRA0(ISTR1,IGAUS),ISTR1=1,NSTR1)
        ENDDO
        RETURN
      ENDIF
C
C***IFLAG=2 >>>> READ INITIAL STRESSES
C
      IF(IFLAG.EQ.2) THEN
        IF(NTYPE.LE.2) WRITE(LURES,930)
        IF(NTYPE.EQ.3) WRITE(LURES,931)
        IF(NTYPE.EQ.4) WRITE(LURES,932)
        IF(NTYPE.EQ.5) WRITE(LURES,933)
        DO  JGAUS=1,NGAUL
          READ(JTAPE,905)  IGAUS,(STRS0(ISTR1,IGAUS),ISTR1=1,NSTR1)
          WRITE(LURES,910) IGAUS,(STRS0(ISTR1,IGAUS),ISTR1=1,NSTR1)
        ENDDO
C
C.....STORE INITIAL STRESSES INTO STRESS ARRAY
C
        DO 30 INDEX=1,NGAUL*NSTR1
   30   STRSG(INDEX,1)=STRS0(INDEX,1)
C
        RETURN
      ENDIF
C
C***IFLAG=3 >>>> READ INITIAL PLASTIC PARAMETERS
C
      IF(IFLAG.EQ.3) THEN
        IF(NCRIT.EQ.3.OR.NCRIT.EQ.4) THEN
          DCOEF=PROPS(31)
          FACTO=PROPS(35)
C
          WRITE(LURES,940)
          DO JGAUL=1,NGAUL
          READ(JTAPE,905) IGAUS,VSTOT,EQUMN
C
          HPARA=(DCOEF-EQUMN)/(FACTO+1.)      
          BETAS=DCOEF-FACTO*HPARA
C
          EHIST(2,IGAUS)=VSTOT
          EHIST(3,IGAUS)=HPARA
          EHIST(4,IGAUS)=BETAS
          EHIST(5,IGAUS)=EQUMN
C
          WRITE(LURES,910) IGAUS,(EHIST(INDEX,IGAUS),INDEX=2,5)
          ENDDO
C
        ENDIF
        RETURN
      ENDIF
C
      RETURN
  900 FORMAT(/,1X,'ELEMENT NO. ',I5)
  905 FORMAT(I5,6E15.6)
  910 FORMAT(5X,I5,6E15.6)
  920 FORMAT(4X,6HPOINTS,6X,9HXX-STRAIN,6X,9HYY-STRAIN,6X,9HXY-STRAIN,
     .                   6X,9HZZ-STRAIN)
  921 FORMAT(4X,6HPOINTS,6X,9HRR-STRAIN,6X,9HZZ-STRAIN,6X,9HRZ-STRAIN,
     .                   6X,9HTT-STRESS)
  922 FORMAT(4X,6HPOINTS,6X,9HXX-STRAIN,6X,9HYY-STRAIN,6X,9HXY-STRAIN,
     .                   6X,9HZZ-STRAIN,6X,9HXZ-STRAIN,6X,9HYZ-STRAIN)
  923 FORMAT(4X,6HPOINTS,6X,9HXX-STRAIN)
  930 FORMAT(4X,6HPOINTS,6X,9HXX-STRESS,6X,9HYY-STRESS,6X,9HXY-STRESS,
     .                   6X,9HZZ-STRESS)
  931 FORMAT(4X,6HPOINTS,6X,9HRR-STRESS,6X,9HZZ-STRESS,6X,9HRZ-STRESS,
     .                   6X,9HTT-STRESS)
  932 FORMAT(4X,6HPOINTS,6X,9HXX-STRESS,6X,9HYY-STRESS,6X,9HXY-STRESS,
     .                   6X,9HZZ-STRESS,6X,9HXZ-STRESS,6X,9HYZ-STRESS)
  933 FORMAT(4X,6HPOINTS,6X,9HXX-STRESS)
  940 FORMAT(6X,4HG.P.,6X,9HSPEC.VOL.5X,10HMJ. S-AXIS,
     .       5X,10HP-CO. CEN.,6X,9HEQ.ME.PR.)
      END
