      SUBROUTINE PRO104F(ITAPET,PROPST)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MATERIAL PROPERTIES FOR THE GAP INTERFACE
C     MODEL (ELEMENT=104) FOR FILLING MATERIAL
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLE
C
      INCLUDE 'nuec_om.f'      ! thermal-mechanical
C
C**** THERMAL VARIABLE
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION PROPST(*)
C
C**** ESTABLISH SOME PARAMETERS
C
      PROPST(1)=1.0             ! ifill=1 => filling material
      NFILL=1                   ! at least one filling material
C
C**** READ & WRITE MATERIAL PROPERTIES
C
      NPRINT=0
C
C**** LOOK FOR 'CONDUCTANCE COEFFICIENT CURVE' CARD
C
      ICONT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
      IF(WORDST(1).NE.'CONDU')
     . CALL RUNENDT('ERROR: CONDUCTANCE COEFF.-TEMP. CARD NOT FOUND')
C
C**** LOOK FOR 'METAL CONDUCTANCE-TEMP1 CURVE' CARD
C
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
      IF(WORDST(1).NE.'TEMP1') THEN
       NPOI1T=2                 ! IFILL=PROPST(1)
       NPOI2T=6
       PROPST(2)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 1
      ELSE
       IF(WORDST(2).NE.'METAL')
     .  CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'METAL CONDUCTANCE-TEMPERATURE 1 CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=2                 ! IFILL=PROPST(1)
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,802)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
      ENDIF
C
C**** LOOK FOR 'AIR CONDUCTANCE-TEMP1 CURVE' CARD
C
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    1 IF(WORDST(1).NE.'TEMP1') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(2)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 2
      ELSE
       IF(WORDST(2).NE.'AIR')
     .  CALL RUNENDT('ERROR: AIR CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'AIR CONDUCTANCE-TEMPERATURE 1 CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,803)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
      ENDIF
C
C**** LOOK FOR 'METAL CONDUCTANCE-TEMP2 CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    2 IF(WORDST(1).NE.'TEMP2') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 3
      ELSE
       IF(WORDST(2).NE.'METAL')
     .  CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'METAL CONDUCTANCE-TEMPERATURE 2 CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,802)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
      ENDIF
C
C**** LOOK FOR 'AIR CONDUCTANCE-TEMP2 CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    3 IF(WORDST(1).NE.'TEMP2') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 4
      ELSE
       IF(WORDST(2).NE.'AIR')
     .  CALL RUNENDT('ERROR: AIR CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'AIR CONDUCTANCE-TEMPERATURE 2 CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,803)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
      ENDIF
C
C**** LOOK FOR 'METAL CONDUCTANCE-GAP_N CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    4 IF(ITERME.LE.0.AND.ICONT.EQ.0)     ! thermal or unidirect. coupled
     . CALL RUNENDT('ERROR: NO VALUES OF CONDUCTANCE ARE FOUND')
      IF(WORDST(1).NE.'GAP_N') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 5
      ELSE
       IF(WORDST(2).NE.'METAL')
     .  CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'METAL CONDUCTANCE-GAP_N (NORMAL GAP) CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,902)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
      ENDIF
C
C**** LOOK FOR 'AIR CONDUCTANCE-GAP_N CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    5 IF(ITERME.LE.0.AND.ICONT.EQ.0)     ! thermal or unidirect. coupled
     . CALL RUNENDT('ERROR: NO VALUES OF CONDUCTANCE ARE FOUND')
      IF(WORDST(1).NE.'GAP_N') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 6
      ELSE
       IF(WORDST(2).NE.'AIR')
     .  CALL RUNENDT('ERROR: AIR CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'AIR CONDUCTANCE-GAP_N (NORMAL GAP) CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,903)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
      ENDIF
C
C**** LOOK FOR 'METAL CONDUCTANCE-PRESS (NORMAL PRESSURE) CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    6 IF(WORDST(1).NE.'PRESS') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 7
      ELSE

       call runendt('ERROR: NO pressure dependent gap with filling')

       IF(WORDST(2).NE.'METAL')
     .  CALL RUNENDT('ERROR: METAL CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'METAL CONDUCTANCE-PRESSURE (NORMAL) CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,912)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
C
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0  ! normal stiffness to be assigned in checkp.f
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0  ! index IR432 to be assigned in checkp.f
      ENDIF
C
C**** LOOK FOR 'AIR CONDUCTANCE-PRESS (NORMAL PRESSURE) CURVE' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    7 IF(WORDST(1).NE.'PRESS') THEN
       NPOI1T=NPOI2T+1
       NPOI2T=4+NPOI1T
       PROPST(NPOI1T)=2.0
       DO IPROPT=NPOI1T+1,NPOI2T
        PROPST(IPROPT)=1.0
       ENDDO
       GOTO 8
      ELSE

       call runendt('ERROR: NO pressure dependent gap with filling')

       IF(WORDST(2).NE.'AIR')
     .  CALL RUNENDT('ERROR: AIR CARD NOT FOUND')
       IF(PARAMT(1).EQ.0.0)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
C
C**** READ 'AIR CONDUCTANCE-PRESSURE (NORMAL) CURVE' BY LISTEN
C
       ICONT=ICONT+1
       NPOI1T=NPOI2T+1
       NPOI2T=NPOI1T
       PROPST(NPOI1T)=PARAMT(1)
       NLINET=INT(PARAMT(1))
       IF(NLINET.GT.20)
     .  CALL RUNENDT('ERROR: WRONG NUMBER OF POINTS IN CONDUC.')
       NPRINT=1
       DO LINEAT=1,NLINET
        CALL LISTENT('PRO104F',NPRINT,ITAPET)
        DO I=1,2
         NPOI2T=NPOI2T+1
         PROPST(NPOI2T)=PARAMT(I)
        ENDDO
       ENDDO
       WRITE(LUREST,913)
       DO IPROPT=NPOI1T+1,NPOI2T,2
        WRITE(LUREST,805) PROPST(IPROPT),PROPST(IPROPT+1)
       ENDDO
       WRITE(LUREST,806)
C
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0  ! normal stiffness to be assigned in checkp.f
       NPOI2T=NPOI2T+1
       PROPST(NPOI2T)=0.0  ! index IR432 to be assigned in checkp.f
      ENDIF
C
C**** LOOK FOR 'END_MATERIAL' CARD
C
      NPRINT=0
      CALL LISTENT('PRO104F',NPRINT,ITAPET)
    8 IF(WORDST(1).NE.'END_M')
     . CALL RUNENDT('ERROR: END_MATERIAL CARD NOT FOUND   ')
      IF(ICONT.EQ.0)
     . CALL RUNENDT('ERROR: NO VALUES OF CONDUCTANCE ARE FOUND')
      WRITE(LUREST,806)
C
C**** CONTROLS DIMENSION OF PROPST
C
      IF(NPOI2T.GT.NPROPT) THEN
       WRITE(LUREST,900) NPROPT,NPOI2T
       CALL RUNENDT('PROP05T: TOO MANY PROPERTIES TO READ')
      ENDIF
C
      RETURN
  802 FORMAT(/,'METAL CONDUCT. COEF. Vs.     TEMPERATURE',/)
  803 FORMAT(/,'AIR CONDUCT. COEF.   Vs.     TEMPERATURE',/)
  902 FORMAT(/,'METAL CONDUCT. COEF. Vs.     NORMAL GAP ',/)
  903 FORMAT(/,'AIR CONDUCT. COEF.   Vs.     NORMAL GAP ',/)
  912 FORMAT(/,'METAL CONDUCT. COEF. Vs.     PRESSURE   ',/)
  913 FORMAT(/,'AIR CONDUCT. COEF.   Vs.     PRESSURE   ',/)
  805 FORMAT(E15.6,10X,E15.6)
  806 FORMAT(/)
  900 FORMAT(//,'TOO MANY MATERIAL PROPERTIES TO READ:',/,
     .      20X,'NPROP =',I5,5X,'NUMBE =',I5,/)
      END
