      SUBROUTINE PROPMIC4(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 4
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** COMPOSITION (INITIAL)
C
      NPRINT=0
      CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'COMPO') THEN
       WRITE(LURESS,810)
       WRITE(LURESS,809)
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'CARBO') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO CARBON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG CARBON COMPOSITION')
       WRITE(LURESS,811) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SILIC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO SILICON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG SILICON COMPOSITION')
       WRITE(LURESS,812) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'PHOSP') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO PHOSPHORUS CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG PHOSPORUS COMPOSITION')
       WRITE(LURESS,813) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'COPPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO COPPER CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG COPPER COMPOSITION')
       WRITE(LURESS,814) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MANGA') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO MANGANESE CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG MANGANESE COMPOSITION')
       WRITE(LURESS,815) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MAGNE') THEN      ! spheroidizer in SG cast iron
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO MAGNESIUM CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG MAGNESIUM COMPOSITION')
       WRITE(LURESS,816) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'CHROM') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .   CALL RUNENDS('PROPMIC4: WRONG CHROMIUM COMPOSITION')
        WRITE(LURESS,817) PROPSS(NPOI2T)
        WRITE(LURESS,809)
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        GO TO 12
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC4: NO COMPOSITION CARD')
      ENDIF
C
C**** EQUILIBRIUM DIAGRAM PARAMETERS
C
      CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
   12 IF(WORDSS(1).EQ.'EQUIL') THEN
       WRITE(LURESS,820)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SILIC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC4: NO SILICON PARTITION COEFFICIENT CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0)
     .  CALL RUNENDS('PROPMIC4: WRONG SILICON PARTITION COEFFICIENT')
       WRITE(LURESS,821) PARAMS(1)
       WRITE(LURESS,809)
C
       IMNMS=0
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'MANGA') THEN
        IMNMS=1
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IF(PARAMS(1).LT.0.0D0)
     .   CALL RUNENDS('PROPMIC4: WRONG MANGANESE PARTITION COEFFICIENT')
        WRITE(LURESS,822) PARAMS(1)
        WRITE(LURESS,809)
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        GO TO 13
       ENDIF
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
   13  IF(WORDSS(1).EQ.'CORRE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1.0D0                              ! Heine
        IF(WORDSS(2).EQ.'LACAZ') PROPSS(NPOI2T)=2.0D0     ! Lacaze
        IF(WORDSS(2).EQ.'ESCOB') PROPSS(NPOI2T)=3.0D0     ! Escobar
        IF(WORDSS(2).EQ.'THERM') THEN                     ! Thermocalc
         PROPSS(NPOI2T)=4.0D0
         IF(PARAMS(1).NE.0.0D0) THEN
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(1)                        ! Stable
         ELSE
          CALL RUNENDS('PROPMIC4: NO STABLE TEMPERATURE')
         ENDIF
         IF(PARAMS(2).NE.0.0D0) THEN
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(2)                        ! Metastable
         ELSE
          CALL RUNENDS('PROPMIC4: NO METASTABLE TEMPERATURE')
         ENDIF
        ENDIF
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1.0D0      ! default: Heine
        GO TO 11
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC4: NO EQUIL. DIAGRAM PARAM. CARD')
      ENDIF
C
C**** PRIMARY AUSTENITE SOLIDIFICATION (not implemented yet!)
C

C
C**** EUTECTIC SOLIDIFICATION
C
      CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
   11 IF(WORDSS(1).EQ.'EUTEC') THEN
       WRITE(LURESS,840)
       WRITE(LURESS,809)
C
C**** NUCLEATION PROPERTIES
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'NUCLE'.AND.WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)     ! nucleation model index
        INUCMX=INT(PARAMS(1))
        IF(INUCMX.EQ.1.OR.INUCMX.EQ.2) THEN     ! Su & Boeri nuc. models
         CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! coefficient b
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)    ! coefficient c
         WRITE(LURESS,841) PROPSS(NPOI2T-1),PROPSS(NPOI2T)
        ELSE
         CALL RUNENDS('PROPMIC4: INCORRECT NUCLEATION MODEL NUMBER')
        ENDIF
C
        CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'ARRES') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! nucleation arrest criterion index
         INUCAX=INT(PARAMS(1))
         IF(INUCAX.NE.1.AND.INUCAX.NE.2)         ! Trecal & Tmin
     .    CALL RUNENDS('PROPMIC4: INCORRECT ARREST CRITERION NUMBER')
        ELSE
         CALL RUNENDS('PROPMIC4: NO ARREST CRITERION CARD')
        ENDIF
C
        CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'CONTR') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=1.0D0        ! control minimum N index
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)    ! minimum N
        ELSE
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=0.0D0
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=0.0D0
         GO TO 1
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC4: NO NUCLEATION OR MODEL CARD')
       ENDIF
       WRITE(LURESS,809)
C
C**** GROWTH PROPERTIES
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
    1  IF(WORDSS(1).EQ.'GROWT'.AND.WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)     ! growth model index
        IGROMX=INT(PARAMS(1))
        IF(IGROMX.LE.2) THEN
         INNUM4S=0
         IF(IGROMX.EQ.1) THEN        ! Boeri growth model
          CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(1)   ! diffusion coef. of C in liquid
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(2)   ! diffusion coef. of C in austenite
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(3)   ! r of nodule enveloped by auste.
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(4)   ! initial r of graphite nodule
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(5)   ! auste. shell r/graphite r ratio
          WRITE(LURESS,842) PROPSS(NPOI2T-4),PROPSS(NPOI2T-3),
     .                      PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                      PROPSS(NPOI2T)
         ENDIF
         IF(IGROMX.EQ.2) THEN        ! Sandra growth model
          CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(1)   ! diffusion coef. of C in liquid
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(2)   ! diffusion coef. of C in austenite
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(3)   ! initial r of graphite nodule
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(4)   ! auste. shell r/graphite r ratio
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(5)   ! lower liquid fraction bound
          NPOI2T=NPOI2T+1
          PROPSS(NPOI2T)=PARAMS(6)   ! upper liquid fraction bound
          INNUM4S=1                  ! nodularity index
          WRITE(LURESS,843) PROPSS(NPOI2T-5),PROPSS(NPOI2T-4),
     .                      PROPSS(NPOI2T-3),PROPSS(NPOI2T-2),
     .                      PROPSS(NPOI2T-1),PROPSS(NPOI2T)
         ENDIF
        ELSE
         CALL RUNENDS('PROPMIC4: INCORRECT GROWTH MODEL NUMBER')
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC4: NO GROWTH OR MODEL CARD')
       ENDIF
       WRITE(LURESS,809)
C
C**** WHITE NUCLEATION & GROWTH
C
       IWEUS=0
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'WHITE') THEN
        IWEUS=1                      ! white fraction computation
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)     ! Ac (nucleation parameter)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2)     ! Bc (growth parameter)
        WRITE(LURESS,844) PROPSS(NPOI2T-1),PROPSS(NPOI2T)
       ELSE
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0.0D0
        GO TO 2
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC4: NO EUTECTIC SOLIDIFICATION CARD')
      ENDIF
C
C**** MICROSTRUCTURE-DEPENDENT THERMAL PROPERTIES
C
      CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
    2 IF(WORDSS(1).EQ.'CONDU'.AND.WORDSS(2).EQ.'MODEL') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1) ! micro-dependent conductivity index
       IKMICX=INT(PARAMS(1))
       IF(IKMICX.EQ.1.OR.IKMICX.EQ.2.OR.IKMICX.EQ.3) THEN
        CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1) ! solid conductivity
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(2) ! mushy conductivity
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(3) ! liquid conductivity
        WRITE(LURESS,851) PROPSS(NPOI2T-3),PROPSS(NPOI2T-2),
     .                    PROPSS(NPOI2T-1),PROPSS(NPOI2T)
       ELSE
        CALL RUNENDS('PROPMIC4: INCORRECT CONDUCTIVITY MODEL NUMBER')
       ENDIF
       WRITE(LURESS,809)
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0     ! conductivity does not depend on micro.
       GO TO 3
      ENDIF
C
C**** NUMERICAL STRATEGY PARAMETERS
C
      CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
    3 IF(WORDSS(1).EQ.'NUMER') THEN
       WRITE(LURESS,860)
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TEMPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IFPCDT=INT(PARAMS(1))
        IF(IFPCDT.LT.1.OR.IFPCDT.GT.5)
     .   CALL RUNENDS('PROPMIC4: WRONG IFPCDT VALUE')
        WRITE(LURESS,861) IFPCDT
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC4: NO TEMPERATURE DERIVATIVE FORM OF FL')
       ENDIF
C
       CALL LISTENS('PROPMIC4',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'FRACT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IAFLOJ=INT(PARAMS(1))
        WRITE(LURESS,862) IAFLOJ
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC4: NO FRACTION CORRECTION CARD')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC4: NO NUMERICAL STRATEGY CARD')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA4S=1
      IPLLLS(INUPM)=4
C
      RETURN
  809 FORMAT(/)
  810 FORMAT(3X,'COMPOSITION (INITIAL):')
  811 FORMAT(3X,' CARBON CONTENT     =',E15.6)
  812 FORMAT(3X,' SILICON CONTENT    =',E15.6)
  813 FORMAT(3X,' PHOSPHORUS CONTENT =',E15.6)
  814 FORMAT(3X,' COPPER CONTENT     =',E15.6)
  815 FORMAT(3X,' MANGANESE CONTENT  =',E15.6)
  816 FORMAT(3X,' MAGNESIUM CONTENT  =',E15.6)
  817 FORMAT(3X,' CHROMIUM CONTENT   =',E15.6)
C
  820 FORMAT(3X,'EQUILIBRIUM DIAGRAM PARAMETERS:')
  821 FORMAT(3X,' SILICON PARTITION COEFFICIENT  =',E15.6)
  822 FORMAT(3X,' MANGANESE PARTITION COEFFICIENT=',E15.6)
C

C
  840 FORMAT(3X,'EUTECTIC SOLIDIFICATION PARAMETERS:')
  841 FORMAT(3X,' NUCLEATION PARAMETERS:',/,
     .       3X,'  COEFFICIENT b            =',E15.6,/,
     .       3X,'  COEFFICIENT c            =',E15.6)
  842 FORMAT(3X,' GROWTH PARAMETERS (MODEL=1):',/,
     .       3X,'  DIFFUSION COEF. OF C IN THE LIQUID=',E15.6,/,
     .       3X,'  DIFFUSION COEF. OF C IN AUSTENITE=',E15.6,/,
     .       3X,'  RADIUS AT WHICH NOD. IS ENVELOPED BY AUST.=',E15.6,/,
     .       3X,'  INITIAL RADIUS OF NODULES=',E15.6,/,
     .       3X,'  AUSTENITE SHELL RADIUS/GRAPHITE RADIUS=',E15.6)
  843 FORMAT(3X,' GROWTH PARAMETERS (MODEL=2):',/,
     .       3X,'  DIFFUSION COEF. OF C IN THE LIQUID=',E15.6,/,
     .       3X,'  DIFFUSION COEF. OF C IN AUSTENITE=',E15.6,/,
     .       3X,'  INITIAL RADIUS OF NODULES=',E15.6,/,
     .       3X,'  AUSTENITE SHELL RADIUS/GRAPHITE RADIUS=',E15.6,/,
     .       3X,'  LOWER LIQUID FRACTION BOUND=',E15.6,/,
     .       3X,'  UPPER LIQUID FRACTION BOUND=',E15.6)
  844 FORMAT(3X,' WHITE NUCLEATION & GROWTH PARAMETERS=',2E15.6)
C
  851 FORMAT(3X,'MICROSTRUCTURE-DEPENDENT CONDUCTIVITY:',/,
     .       3X,' SOLID CONDUCTIVITY =',E15.6,/,
     .       3X,' MUSHY CONDUCTIVITY =',E15.6,/,
     .       3X,' LIQUID CONDUCTIVITY=',E15.6)
C
  860 FORMAT(3X,'NUMERICAL STRATEGY PARAMETERS')
  861 FORMAT(3X,'TEMPERATURE DERIVATIVE FORM OF FL=',I5)
  862 FORMAT(3X,'FRACTION CORRECTION FORM         =',I5)
      END
