      SUBROUTINE PROPMIC7(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 7 (CONCRETE HYDRATATION)
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** LOOK FOR 'VERSION' CARD
C
      NPRINT=0
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'VERSI') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)
       WRITE(LURESS,829) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: VERSION CARD NOT FOUND')
      ENDIF
C
      IVERSI=INT(PROPSS(NPOI2T))
      IF(IVERSI.EQ.1) THEN
C
C**** LOOK FOR 'CHEMICAL_POTENTIAL' CARD
C
      NPRINT=0
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CHEMI') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! Amo
       WRITE(LURESS,830) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: CHEMICAL_POTENTIAL CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'CONSTANT_K' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! K
       WRITE(LURESS,831) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT K CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'VISCOSITY' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'VISCO') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! eta
       WRITE(LURESS,832) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: VISCOSITY CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'UNIVERSAL_GAS_CONSTANT' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'UNIVE') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! R
       WRITE(LURESS,833) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: UNIV. GAS CONST. CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'HYDRATION_ENERGY' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'HYDRA') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! Ea
       WRITE(LURESS,834) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: HYDRATION ENERGY CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'LATENT HEAT' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'LATEN') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! fx
       WRITE(LURESS,835) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: LATENT HEAT CARD NOT FOUND')
      ENDIF
C
C**** HYDRATION AMPLITUDE AT INFINITY
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'HYDRA') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! chi_inf
       WRITE(LURESS,836) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: HYDRATION AMPLITUDE AT INF. NOT FOUND')
      ENDIF
C
C**** CONSTANT A FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! constant A
       WRITE(LURESS,837) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT A NOT FOUND')
      ENDIF
C
C**** CONSTANT B FOR COMPRESSION STRENGTH
C 
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
      IF(WORDSS(1).EQ.'CONST') THEN 
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! constant B
       WRITE(LURESS,838) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE 
       CALL RUNENDS('PROPMIC7: CONSTANT B NOT FOUND')
      ENDIF 
C
C**** MECHANICAL-MICROSTRUCTURAL COUPLING INDEX
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'MECHA') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! IMECHMIC
       WRITE(LURESS,839) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: MECH.-MICROST. COUPLING INDEX NOT FOUND')
      ENDIF
      ENDIF              ! iversi.eq.1
C
      IF(IVERSI.EQ.2) THEN
C
C**** CONSTANT K BAR (OR K FOR LINEAR VISCOSITY)
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'K_BAR') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! k-bar
       WRITE(LURESS,840) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: K BAR CONSTANT NOT FOUND')
      ENDIF
C
C**** CONSTANT ETA_0
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'ETA_0') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! eta_0
       WRITE(LURESS,845) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: ETA_0 CONSTANT NOT FOUND')
      ENDIF
C
C**** CONSTANT ETA BAR
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'ETA_B') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! eta-bar
       WRITE(LURESS,846) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: ETA BAR CONSTANT NOT FOUND')
      ENDIF
C 
C**** HYDRATION DEGREE AT INFINITY
C 
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
      IF(WORDSS(1).EQ.'INFIN') THEN 
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
       NPOI2T=NPOI2T+1 
       PROPSS(NPOI2T)=PARAMS(1)            ! gh-inf
       WRITE(LURESS,841) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE 
       CALL RUNENDS('PROPMIC7: HYDRATION DEGREE AT INF. NOT FOUND')
      ENDIF 
C 
C**** CONSTANT ALPHA BAR
C 
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
      IF(WORDSS(1).EQ.'ALPHA') THEN 
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
       NPOI2T=NPOI2T+1 
       PROPSS(NPOI2T)=PARAMS(1)            ! alpha-bar
       WRITE(LURESS,842) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE 
       CALL RUNENDS('PROPMIC7: ALPHA BAR CONSTANT NOT FOUND')
      ENDIF 
C 
C**** CONSTANT A BAR
C 
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
      IF(WORDSS(1).EQ.'A_BAR') THEN 
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
       NPOI2T=NPOI2T+1 
       PROPSS(NPOI2T)=PARAMS(1)            ! A-bar
       WRITE(LURESS,843) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE 
       CALL RUNENDS('PROPMIC7: K BAR CONSTANT NOT FOUND')
      ENDIF 
C
C**** LOOKS FOR 'UNIVERSAL_GAS_CONSTANT' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'UNIVE') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! R
       WRITE(LURESS,833) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: UNIV. GAS CONST. CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'HYDRATION_ENERGY' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'HYDRA') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! Ea
       WRITE(LURESS,834) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: HYDRATION ENERGY CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'LATENT HEAT' CARD
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'LATEN') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! fx
       WRITE(LURESS,835) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: LATENT HEAT CARD NOT FOUND')
      ENDIF
C
C**** CONSTANT A_f  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! constant A_f
       WRITE(LURESS,837) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT A NOT FOUND')
      ENDIF
C
C**** CONSTANT B_f  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! constant B_f
       WRITE(LURESS,838) PROPSS(NPOI2T)
       WRITE(LURESS,899) 
      ELSE 
       CALL RUNENDS('PROPMIC7: CONSTANT B NOT FOUND')
      ENDIF 
C
C**** CONSTANT n_T  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! constant n_T
       WRITE(LURESS,847) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT N_T NOT FOUND')
      ENDIF
C
C**** CONSTANT FC_INFINITY  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! constant fc_infinity-
       WRITE(LURESS,848) PROPSS(NPOI2T)
       WRITE(LURESS,899)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(2)            ! constant fc_infinity+
       WRITE(LURESS,849) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT FC_INFINITY NOT FOUND')
      ENDIF
C
C**** CONSTAN GH_SETTING  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! gh_setting
       WRITE(LURESS,850) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT GH_SETTING  NOT FOUND')
      ENDIF
C
C**** CONSTANT T_MAXIMA  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! T_maxima 
       WRITE(LURESS,851) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: T_MAXIMA  NOT FOUND')
      ENDIF
C
C**** CONSTANT T_REFER  FOR COMPRESSION STRENGTH
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'CONST') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! T_refer 
       WRITE(LURESS,852) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7:  T_REFER  NOT FOUND')
      ENDIF
C 
C**** CONSTANT A_E FOR YOUNG MODULUS 
C 
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
      IF(WORDSS(1).EQ.'CONST') THEN 
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET) 
       NPOI2T=NPOI2T+1 
       PROPSS(NPOI2T)=PARAMS(1)            ! constant E_oo
       WRITE(LURESS,844) PROPSS(NPOI2T) 
       WRITE(LURESS,899)  
      ELSE
       CALL RUNENDS('PROPMIC7: CONSTANT A_E NOT FOUND')
      ENDIF
C
C**** MECHANICAL-MICROSTRUCTURAL COUPLING INDEX
C
      CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'MECHA') THEN
       CALL LISTENS('PROPMIC7',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! IMECHMIC
       WRITE(LURESS,839) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC7: MECH.-MICROST. COUPLING INDEX NOT FOUND')
      ENDIF
      ENDIF              ! iversi.eq.2
C
C**** CONTROLS DIMENSION OF PROPSS
C
      IF(NPOI2T.GT.NPROPS) THEN
       WRITE(LURESS,900) NPROPS,NPOI2T
       CALL RUNENDS('PROPMIC6: TOO MANY PROPERTIES TO READ')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA7S=1
      IPLLLS(INUPM)=7
C
      RETURN
C
  829 FORMAT(/,'  HYDRATION MODEL - VERSION           =',E15.6)
  830 FORMAT(/,'  CHEMICAL POTENTIAL                  =',E15.6)
  831 FORMAT(/,'  CONSTANT K                          =',E15.6)
  832 FORMAT(/,'  VISCOSITY                           =',E15.6)
  833 FORMAT(/,'  UNIVERSAL GAS CONSTANT              =',E15.6)
  834 FORMAT(/,'  HYDRATION ENERGY                    =',E15.6)
  835 FORMAT(/,'  LATENT HEAT VALUE                   =',E15.6)
  836 FORMAT(/,'  HYDRATION AMPLITUDE AT INFINITY     =',E15.6)
  837 FORMAT(/,'  CONSTANT A                          =',E15.6)
  838 FORMAT(/,'  CONSTANT B                          =',E15.6)
  839 FORMAT(/,'  MECH.-MICROST. COUPLING INDEX       =',E15.6)
  840 FORMAT(/,'  CONSTANT K BAR                      =',E15.6)
  841 FORMAT(/,'  HYDRATION DEGREE AT INFINITY        =',E15.6)
  842 FORMAT(/,'  CONSTANT ALPHA BAR                  =',E15.6)
  843 FORMAT(/,'  CONSTANT A BAR                      =',E15.6)
  844 FORMAT(/,'  CONSTANT E_oo                       =',E15.6)
  845 FORMAT(/,'  CONSTANT ETA_0                      =',E15.6)
  846 FORMAT(/,'  CONSTANT ETA_BAR                    =',E15.6)
  847 FORMAT(/,'  CONSTANT N_T                        =',E15.6)
  848 FORMAT(/,'  CONSTANT FC_INFINITY (COMPRESSION)  =',E15.6)
  849 FORMAT(/,'  CONSTANT FC_INFINITY (TENSION)      =',E15.6)
  850 FORMAT(/,'  CONSTANT GH_SETTING                 =',E15.6)
  851 FORMAT(/,'  CONSTANT T_MAXIMA                   =',E15.6)
  852 FORMAT(/,'  CONSTANT T_REFER                    =',E15.6)
  899 FORMAT(/)
  900 FORMAT(//,'TOO MANY MATERIAL PROPERTIES TO READ:',/,
     .      20X,'NPROP =',I5,5X,'NUMBE =',I5,/)
      END
