      SUBROUTINE PROPMIC11(ITAPET,PROPSS,NPOI2T,INUPM,NLINET)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 11
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nued_om.f'       ! thermal-microestructural
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** INITIAL CONDITION FROM OTHER PHASE-CHANGES
C
C     Note:
C     In principle, the phase-changes that provide the initial condition
C     (ic) for the present model (eutectoid transformation) should be
C     saved in PROPSS and transferred to IPLAC in idepros.f.
C     However, this information is directly stored in IPLAC in the
C     present routine (propmic11.f) to avoid re-initialization of IPLAC
C     and, besides, to simplify the identification of the ALPHAM
C     pointers to be included in IPLAC (this last task in performed in
C     propmic.f).
C
      NPRINT=0
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'INITI') THEN
       NCOPC=0
       DO I=1,NLINET
        IF(INT(PARAMS(I)).NE.0) NCOPC=NCOPC+1
       ENDDO
       IPLAC(INUPM,1,1)=NCOPC    ! total number of ph-ch for ic
       IF(NCOPC.GT.1)
     .  CALL RUNMENS('WARNING: NCOPC > 1 - not implemented yet')
       WRITE(LURESS,800) (INT(PARAMS(ICOPC)), ICOPC=1,NCOPC)
       WRITE(LURESS,809)
       DO ICOPC=1,NCOPC
        IPLAC(INUPM,ICOPC+1,1)=INT(PARAMS(ICOPC))   ! ph-ch numb. for ic
        IF(IPLAC(INUPM,ICOPC+1,1).EQ.INUPM)
     .   CALL RUNENDS('ERROR: SELF-COUPLING IS NOT POSSIBLE')
       ENDDO
      ELSE
       WRITE(LURESS,801)
       WRITE(LURESS,809)
       IPLAC(INUPM,1,1)=0        ! no initial condition from other ph-ch
      ENDIF
C
C**** COMPOSITION (ONLY WHEN INITIAL CONDITION IS NOT FROM OTHER
C     PHASE-CHANGES)
C
      NCOPC=IPLAC(INUPM,1,1)
      IF(NCOPC.EQ.0) THEN
       CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'COMPO') THEN
        WRITE(LURESS,810)
        WRITE(LURESS,809)
        CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'CARBO') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC11: NO CARBON CARD')
        ENDIF
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .   CALL RUNENDS('PROPMIC11: WRONG CARBON COMPOSITION')
        WRITE(LURESS,811) PROPSS(NPOI2T)
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'SILIC') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC11: NO SILICON CARD')
        ENDIF
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .   CALL RUNENDS('PROPMIC11: WRONG SILICON COMPOSITION')
        WRITE(LURESS,812) PROPSS(NPOI2T)
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'COPPE') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC11: NO COPPER CARD')
        ENDIF
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .   CALL RUNENDS('PROPMIC11: WRONG COPPER COMPOSITION')
        WRITE(LURESS,814) PROPSS(NPOI2T)
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'MANGA') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
        ELSE
         CALL RUNENDS('PROPMIC11: NO MANGANESE CARD')
        ENDIF
        IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.6.0D0)
     .   CALL RUNENDS('PROPMIC11: WRONG MANGANESE COMPOSITION')
        WRITE(LURESS,815) PROPSS(NPOI2T)
        WRITE(LURESS,809)
C
        CALL LISTENS('PROPMIC11',NPRINT,ITAPET)    ! optional
        IF(WORDSS(1).EQ.'CHROM') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.1.0D0)
     .   CALL RUNENDS('PROPMIC11: WRONG CHROMIUM COMPOSITION')
         WRITE(LURESS,817) PROPSS(NPOI2T)
         WRITE(LURESS,809)
        ELSE
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=0.0D0
         GO TO 1
        ENDIF
C
        CALL LISTENS('PROPMIC11',NPRINT,ITAPET)    ! optional
    1   IF(WORDSS(1).EQ.'NICKE') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)
         IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.1.0D0)
     .    CALL RUNENDS('PROPMIC11: WRONG NICKEL COMPOSITION')
         WRITE(LURESS,818) PROPSS(NPOI2T)
         WRITE(LURESS,809)
        ELSE
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=0.0D0
         GO TO 2
        ENDIF
       ELSE
        CALL RUNENDS('ERROR: COMPOSITION CARD NOT FOUND')
       ENDIF
      ENDIF
C
C**** FERRITE TRANSFORMATION
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
    2 IF(WORDSS(1).EQ.'FERRI') THEN
       WRITE(LURESS,820)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC11: FERRITE_TRANSFORMATION CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'REFER') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)    ! reference temperature
       WRITE(LURESS,821) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC11: FERRITE LATENT HEAT CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'LATEN') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)    ! latent heat
       WRITE(LURESS,822) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC11: FERRITE LATENT HEAT CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'NUCLE') THEN
       IF(WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)   ! nucleation model
        IFENU=INT(PARAMS(1))
        IF(IFENU.EQ.1) THEN
         CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)  ! omega_a
         WRITE(LURESS,823) PROPSS(NPOI2T)
         WRITE(LURESS,809)
        ELSE
         CALL RUNENDS('PROPMIC11: ERROR IN FERRITE NUCLEAT. MODEL')
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC11: FERRITE NUCLEAT. MODEL CARD NOT FOUND')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC11: FERRITE NUCLEATION CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'GROWT') THEN
       IF(WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)   ! growth model
        IFEGR=INT(PARAMS(1))
        IF(IFEGR.EQ.1) THEN
         CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)  ! initial ferrite radius
         WRITE(LURESS,825) PROPSS(NPOI2T)
         WRITE(LURESS,809)
        ELSE
         CALL RUNENDS('PROPMIC11: ERROR IN FERRITE GROWTH MODEL')
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC11: FERRITE GROWTH MODEL CARD NOT FOUND')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC11: FERRITE GROWTH CARD NOT FOUND')
      ENDIF
C
C**** PEARLITE TRANSFORMATION
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'PEARL') THEN
       WRITE(LURESS,830)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC11: PEARLITE_TRANSFORMATION CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'REFER') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)    ! reference temperature
       WRITE(LURESS,831) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC11: FERRITE LATENT HEAT CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'LATEN') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)    ! latent heat
       WRITE(LURESS,832) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC11: PEARLITE LATENT HEAT CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'NUCLE') THEN
       IF(WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)   ! nucleation model
        IPENU=INT(PARAMS(1))
        IF(IPENU.EQ.1) THEN
         CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)  ! omega_p
         WRITE(LURESS,833) PROPSS(NPOI2T)
         WRITE(LURESS,809)
        ELSE
         CALL RUNENDS('PROPMIC11: ERROR IN PEARLITE NUCLEAT. MODEL')
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC11: PEARLITE NUCLEA. MODEL CARD NOT FOUND')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC11: PEARLITE NUCLEATION CARD NOT FOUND')
      ENDIF
C
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'GROWT') THEN
       IF(WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)   ! growth model
        IPEGR=INT(PARAMS(1))
        IF(IFEGR.EQ.1) THEN
         CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)  ! interface thickness
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)  ! C diffusion at the pearlite bound.
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)  ! ferrite/cementite interfacial ener.
         WRITE(LURESS,835) PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                     PROPSS(NPOI2T)
         WRITE(LURESS,809)
        ELSE
         CALL RUNENDS('PROPMIC11: ERROR IN PEARLITE GROWTH MODEL')
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC11: PEARLITE GROWTH MODEL CARD NOT FOUND')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC11: PEARLITE GROWTH CARD NOT FOUND')
      ENDIF
C
C**** NUMERICAL STRATEGY PARAMETERS
C     
      CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'NUMER') THEN
       WRITE(LURESS,860)
       CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TEMPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IFPCDT=INT(PARAMS(1))
        IF(IFPCDT.LT.1.OR.IFPCDT.GT.5)
     .   CALL RUNENDS('PROPMIC11: WRONG IFPCDT VALUE')
        WRITE(LURESS,861) IFPCDT
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC11: NO TEMPERATURE DERIVATIVE FORM OF FL')
       ENDIF
C
       CALL LISTENS('PROPMIC11',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'FRACT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IAFLOJ=INT(PARAMS(1))
        WRITE(LURESS,862) IAFLOJ
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC11: NO FRACTION CORRECTION CARD')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC11: NO NUMERICAL STRATEGY CARD')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA11S=1
      IPLLLS(INUPM)=11
C
      RETURN
  800 FORMAT(3X,'INITIAL CONDITION FROM PHASE-CHANGE NUMBER=',5I5)
  801 FORMAT(3X,'NO INITIAL CONDITION FROM OTHER PHASE-CHANGE')
  809 FORMAT(/)
C
  810 FORMAT(3X,'COMPOSITION:')
  811 FORMAT(3X,'   CARBON CONTENT     =',E15.6)
  812 FORMAT(3X,'   SILICON CONTENT    =',E15.6)
  814 FORMAT(3X,'   COPPER CONTENT     =',E15.6)
  815 FORMAT(3X,'   MANGANESE CONTENT  =',E15.6)
  817 FORMAT(3X,'   CHORMIUM CONTENT   =',E15.6)
  818 FORMAT(3X,'   NICKEL CONTENT     =',E15.6)
C
  820 FORMAT(3X,'FERRITE TRANSFORMATION')
  821 FORMAT(3X,'   REFERENCE TEMPERATURE=',E15.6)
  822 FORMAT(3X,'   LATENT HEAT=',E15.6)
  823 FORMAT(3X,'   NUCLEATION MODEL 1',/,
     .          '      PARAMETER OMEGA_A=',E15.6)
  825 FORMAT(3X,'   GROWTH MODEL 1',/,
     .          '      INITIAL FERRITE RADIUS=',E15.6)
C
  830 FORMAT(3X,'PEARLITE TRANSFORMATION')
  831 FORMAT(3X,'   REFERENCE TEMPERATURE=',E15.6)
  832 FORMAT(3X,'   LATENT HEAT=',E15.6)
  833 FORMAT(3X,'   NUCLEATION MODEL 1',/,
     .          '      PARAMETER OMEGA_P=',E15.6)
  835 FORMAT(3X,'   GROWTH MODEL 1',/,
     .          '      INTERFACE THICKNESS=',E15.6,/,
     .          '      CARBON DIFFUSION AT PEARLITE BOUNDARY=',E15.6,/,
     .          '      FERRITE/CEMENTITE INTERFACIAL ENERGY=',E15.6)
C
  860 FORMAT(3X,'NUMERICAL STRATEGY PARAMETERS')
  861 FORMAT(3X,' TEMPERATURE DERIVATIVE FORM OF FL=',I5)
  862 FORMAT(3X,' FRACTION CORRECTION FORM         =',I5)
      END
