      SUBROUTINE PROPMIC10(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 12
C
C     Notes:
C     The oxygen partition coefficient is only useful to determine the
C     solid fraction evolution by using the lever or Scheil expressions
C     without any nucleation and growth models.
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C
C**** DEGREES CELSIUS TO KELVIN TEMPERATURE CONVERSION TERM
C
      NPRINT=1
      CALL LISTENS('PROPMIC10',NPRINT,ITAPET)     ! C to K conversion
      IF(WORDSS(1).EQ.'C_TO_') THEN
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=273.15D0                    ! input data in C
      ELSE
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=0.0D0                       ! input data in K
       GO TO 1
      ENDIF
      WRITE(LURESS,809)
C
C**** COMPOSITION (INITIAL)
C
      NPRINT=1
      CALL LISTENS('PROPMIC10',NPRINT,ITAPET)     ! oxygen concentration
    1 IF(WORDSS(1).EQ.'COMPO') THEN
       WRITE(LURESS,810)
       WRITE(LURESS,809)
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'OXYGE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO OXYGEN CARD')
       ENDIF
       IF(PARAMS(1).LE.0.0000D0.OR.PARAMS(1).GT.1.00D0)   ! %O anodic Cu
     .  CALL RUNENDS('PROPMIC10: WRONG OXYGEN COMPOSITION')
       WRITE(LURESS,811) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)      ! as cuprophosphorus
       IF(WORDSS(1).EQ.'PHOSP') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO PHOSPHOROUS CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.2.0D0)
     .  CALL RUNENDS('PROPMIC10: WRONG PHOSPHORUS COMPOSITION')
       WRITE(LURESS,812) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'ARSEN') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO ARSENICAL CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG ARSENICAL COMPOSITION')  
       WRITE(LURESS,813) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'ANTIM') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO ANTIMONY CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG ANTIMONY COMPOSITION')
       WRITE(LURESS,814) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'IRON_') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO IRON CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG IRON COMPOSITION')
       WRITE(LURESS,815) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SELEN') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO SELENIUM CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG SELENIUM COMPOSITION')
       WRITE(LURESS,816) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TELUR') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO TELURIUM CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG TELURIUM COMPOSITION')
       WRITE(LURESS,817) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'SULPH') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO SULPHUR CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG SULPHUR COMPOSITION')
       WRITE(LURESS,818) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'ZINC_') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO ZINC CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.0.1D0)
     .  CALL RUNENDS('PROPMIC10: WRONG ZINC COMPOSITION')
       WRITE(LURESS,819) PROPSS(NPOI2T)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'LEAD_') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO LEAD CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.5.0D0)
     .  CALL RUNENDS('PROPMIC10: WRONG LEAD COMPOSITION')
       WRITE(LURESS,820) PROPSS(NPOI2T)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC10: NO COMPOSITION CARD')
      ENDIF
C
C**** EQUILIBRIUM DIAGRAM PARAMETERS FOR ANODIC COPPER
C
      CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'EQUIL') THEN
       WRITE(LURESS,821)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'LIQUI') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO LIQUIDUS TEMP. CARD')
       ENDIF
       IF(PARAMS(1).LT.1000.0D0.OR.PARAMS(1).GT.1500.0D0)
     .  CALL RUNENDS('PROPMIC10: WRONG LIQUIDUS TEMPERATURE')
       WRITE(LURESS,822) PARAMS(1)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'EUTEC') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO EUTECTIC TEMP. CARD')
       ENDIF
       IF(PARAMS(1).LT.1000.0D0.OR.PARAMS(1).GT.1500.0D0)
     .  CALL RUNENDS('PROPMIC10: WRONG EUTECTIC TEMPERATURE')
       WRITE(LURESS,823) PARAMS(1)
       WRITE(LURESS,809)
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'OXYGE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
       ELSE
        CALL RUNENDS('PROPMIC10: NO OXYGEN PARTITION COEFF. CARD')
       ENDIF
       IF(PARAMS(1).LT.0.0D0.OR.PARAMS(1).GT.1.0D0)
     .  CALL RUNENDS('PROPMIC10: WRONG OXYGEN PARTITION COEFFICIENT')
       WRITE(LURESS,824) PARAMS(1)
       WRITE(LURESS,809)
      ELSE
       CALL RUNENDS('PROPMIC10: NO EQUIL. DIAGRAM PARAM. CARD')
      ENDIF
C
C**** PRIMARY COPPER SOLIDIFICATION
C
      CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'PRIMA') THEN
C
C**** NUCLEATION PARAMETERS FOR PRIMARY SOLIDIFICATION
C
C     THREE MODELS OF NUCLEATION:
C     1) TURNBULL & FISCHER
C     2) HOLLOMAN & TURNBULL
C     3) INSTANTANEOUS NUCLEATION GIVEN BY OLDFIELD
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'NUCLE'.AND.WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)    ! nucleation model index
        INUCMX=INT(PARAMS(1))
        IF(INUCMX.LT.1.OR.INUCMX.GT.3)
     .   CALL RUNENDS('PROPMIC10: INCORRECT NUCLEATION MODEL NUMBER')
        WRITE(LURESS,840)
        IF(INUCMX.EQ.1) THEN        ! Turnbull & Fisher
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! atoms per cubic meter 
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! atoms in liquid surrounding the
         NPOI2T=NPOI2T+1            ! surface of solid
         PROPSS(NPOI2T)=PARAMS(3)   ! vibration frecuency
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(4)   ! s-l interfacial energy
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(5)   ! enthalpy of fusion
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(6)   ! Boltzman constant
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(7)   ! f(theta) parameter
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LE.0.0D0.OR.
     .      PARAMS(3).LE.0.0D0.OR.PARAMS(4).LE.0.0D0.OR.
     .      PARAMS(5).LE.0.0D0.OR.PARAMS(6).LE.0.0D0.OR.
     .      PARAMS(7).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUES OF PARAMETERS')
         WRITE(LURESS,841) PROPSS(NPOI2T-6),PROPSS(NPOI2T-5),
     .                     PROPSS(NPOI2T-4),PROPSS(NPOI2T-3),
     .                     PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                     PROPSS(NPOI2T)
        END IF
        IF(INUCMX.EQ.2) THEN        ! Holloman & Turnbull
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! B1 coefficient
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! s-l interfacial energy
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)   ! enthalpy of fusion
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(4)   ! Boltzman constant
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(5)   ! f(theta) parameter
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LE.0.0D0.OR.
     .      PARAMS(3).LE.0.0D0.OR.PARAMS(4).LE.0.0D0.OR.
     .      PARAMS(5).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUES OF PARAMETERS')
         WRITE(LURESS,842) PROPSS(NPOI2T-4),PROPSS(NPOI2T-3),
     .                     PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                     PROPSS(NPOI2T)
        END IF
        IF(INUCMX.EQ.3) THEN        ! instantaneous nucleation
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1                     
         PROPSS(NPOI2T)=PARAMS(1)   ! A parameter
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! n exponent 
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LT.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUES OF PARAMETERS')
         WRITE(LURESS,843) PROPSS(NPOI2T-1),PROPSS(NPOI2T)
        END IF
       ELSE
        CALL RUNENDS('PROPMIC10: NO NUCLEATION PARAMETERS CARD')    
       END IF
       WRITE(LURESS,809)
C
C**** GROWTH PARAMETERS FOR PRIMARY SOLIDIFICATION
C
C     FOUR DENDRITE GROWTH MODELS:
C     1) RAPPAZ & THEVOZ 1
C     2) DEL PERO-SANZ'S CONTINUOUS
C     3) TURNBULL 1 (RADIUS 2 ORDERS OF MAGNITUDE GREATER)
C     4) TURNBULL 2 (RADIUS 2 ORDERS OF MAGNITUDE GREATER)
C     5) RAPPAZ & THEVOZ 2
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'GROWT'.AND.WORDSS(2).EQ.'MODEL') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)    ! growth model index
        IGROMX=INT(PARAMS(1))
        IF(IGROMX.LT.1.OR.IGROMX.GT.5)
     .   CALL RUNENDS('PROPMIC10: INCORRECT GROWTH MODEL NUMBER')
        WRITE(LURESS,850)
        IF(IGROMX.EQ.1) THEN        ! Rappaz & Thevoz model 1
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! diffusion coef. of Cu in liquid
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! Gibbs-Thomson parameter for copper
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)   ! liquidus curve slope 
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUES OF PARAMETERS')
         IF(PARAMS(3).GE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUES OF PARAMETERS')
         WRITE(LURESS,851) PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                     PROPSS(NPOI2T)
        ENDIF
        IF(IGROMX.EQ.2) THEN        ! Pero - Sanz model
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! Z coefficient
         IF(PARAMS(1).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUE OF PARAMETER')
         WRITE(LURESS,852) PROPSS(NPOI2T)
        ENDIF
        IF(IGROMX.EQ.3) THEN        ! Turnbull model 1
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! enthalpy of fusion
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! gases constant
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)   ! factor
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(4)   ! Sound speed
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LE.0.0D0.OR.
     .      PARAMS(4).EQ.0.0D0.OR.PARAMS(4).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUE OF PARAMETER')
         WRITE(LURESS,853) PROPSS(NPOI2T-3),PROPSS(NPOI2T-2),
     .                     PROPSS(NPOI2T-1),PROPSS(NPOI2T)
        ENDIF
        IF(IGROMX.EQ.4) THEN        ! Turnbull model 2
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! enthalpy of fusion
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! gases constant 
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)   ! Boltzman's constant
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(4)   ! atomic mass
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LE.0.0D0.OR.
     .      PARAMS(4).EQ.0.0D0.OR.PARAMS(4).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUE OF PARAMETER')
         WRITE(LURESS,854) PROPSS(NPOI2T-3),PROPSS(NPOI2T-2),
     .                     PROPSS(NPOI2T-1),PROPSS(NPOI2T)
        ENDIF
        IF(IGROMX.EQ.5) THEN        ! Rappaz & Thevoz model 2
         CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)   ! diffusion coef. of Cu in liquid
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)   ! Gibbs-Thomson parameter for copper
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)   ! liquidus curve slope
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(4)   ! solute partition coefficient
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(5)   ! initial composition (oxygen)
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(6)   ! diffusion coef. of O in liquid
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(7)   ! maximum observed grain radius
         IF(PARAMS(1).LE.0.0D0.OR.PARAMS(2).LE.0.0D0.OR.
     .      PARAMS(3).EQ.0.0D0.OR.PARAMS(4).EQ.0.0D0.OR.
     .      PARAMS(5).LE.0.0D0.OR.PARAMS(6).LE.0.0D0.OR.
     .      PARAMS(7).LE.0.0D0)
     .    CALL RUNENDS('PROPMIC10: INCORRECT VALUES OF PARAMETERS')
         WRITE(LURESS,855) PROPSS(NPOI2T-6),PROPSS(NPOI2T-5),
     .                     PROPSS(NPOI2T-4),PROPSS(NPOI2T-3),
     .                     PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                     PROPSS(NPOI2T)
        ENDIF
       ELSE
        CALL RUNENDS('PROPMIC10: NO GROWTH MODEL CARD')
       END IF
       WRITE (LURESS, 809)
      ELSE
       CALL RUNENDS('PROPMIC10: NO PRIMARY SOLIDIFICATION MODEL CARD')
      END IF
C
C**** EUTECTIC COPPER SOLIDIFICATION (to be revised!)
C

C
C**** NUMERICAL STRATEGY PARAMETERS
C
      CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'NUMER') THEN
       WRITE(LURESS,860)
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'TEMPE') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IFPCDT=INT(PARAMS(1))
        IF(IFPCDT.LT.1.OR.IFPCDT.GT.5)
     .   CALL RUNENDS('PROPMIC10: WRONG IFPCDT VALUE')
        WRITE(LURESS,861) IFPCDT
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC10: NO TEMPERATURE DERIVATIVE FORM OF FL')
       ENDIF
C
       CALL LISTENS('PROPMIC10',NPRINT,ITAPET)
       IF(WORDSS(1).EQ.'FRACT') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)
        IAFLOJ=INT(PARAMS(1))
        WRITE(LURESS,862) IAFLOJ
        WRITE(LURESS,809)
       ELSE
        CALL RUNENDS('PROPMIC10: NO FRACTION CORRECTION CARD')
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC10: NO NUMERICAL STRATEGY CARD')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
      KPLA12S=1
      IPLLLS(INUPM)=12
C
      RETURN
  809 FORMAT(/)
  810 FORMAT(3X,'PROPERTIES OF PHASE DIAGRAM:')
  811 FORMAT(3X,'OXYGEN CONTENT %100 =',E15.6)
  812 FORMAT(3X,'PHOSPHORUS CONTENT %100 =',E15.6)
  813 FORMAT(3X,'ARSENICAL CONTENT %100 =',E15.6)
  814 FORMAT(3X,'ANTIMONY CONTENT %100 =',E15.6)
  815 FORMAT(3X,'IRON CONTENT %100 =',E15.6)
  816 FORMAT(3X,'SELENIUM CONTENT %100 =',E15.6)
  817 FORMAT(3X,'TELURIUM CONTENT %100 =',E15.6)
  818 FORMAT(3X,'SULPHUR CONTENT %100 =',E15.6)
  819 FORMAT(3X,'ZINC CONTENT %100 =',E15.6)
  820 FORMAT(3X,'LEAD CONTENT %100 =',E15.6)
  821 FORMAT(3X,'EQUILIBRIUM DIAGRAM PARAMETERS:')
  822 FORMAT(3X,'LIQUIDUS TEMPERATURE K =',E15.6)
  823 FORMAT(3X,'EUTECTIC TEMPERATURE K =',E15.6)
  824 FORMAT(3X,'OXYGEN PARTITION COEFFICIENT =',E15.6)
  825 FORMAT(3X,'DIFF. COEFF.OF OXYGEN IN Cu LIQUID (m^2/s) =',E15.6)
  826 FORMAT(3X,'MAXIMUN OBSERVED GRAIN RADIUS (m) = ',E15.6)
C
  840 FORMAT(3X,'NUCLEATION MODEL')
  841 FORMAT(3X,'NUCLEATION PARAMETERS OF TURNBULL & FISHER MODEL:',/,
     .       3X,'ATOMS PER CUBIC METER (atoms/m^3) =',E15.6,/,
     .       3X,'ATOMS SURROUNDING SOLID SURFACE (adimensional/dT^2) =',
     .                                                          E15.6,/,
     .       3X,'VIBRATION FRECUENCY (1/s) =',E15.6,/,
     .       3X,'S-L INTERFACIAL ENERGY (J/m^2) =',E15.6,/,
     .       3X,'ENTAHLPY OF FUSION (J/m^3) =',E15.6,/,
     .       3X,'BOLTZMAN CONSTANT (J/°K) =',E15.6,/,
     .       3X,'f(theta) PARAMETER (adimensional) =',E15.6)
  842 FORMAT(3X,'NUCLEATION PARAMETERS OF HOLLOMAN & TURNBULL MODEL:',/,
     .       3X,'COEFFICIENT B (nucleii/m^3*s) =',E15.6,/,
     .       3X,'S-L INTERFACIAL ENERGY (J/m^2) =',E15.6,/,
     .       3X,'ENTAHLPY OF FUSION (J/m^3) =',E15.6,/,
     .       3X,'BOLTZMAN CONSTANT (J/°K) =',E15.6,/,
     .       3X,'f(theta) PARAMETER (adimensional) =',E15.6)
  843 FORMAT(3X,'NUCLEATION PARAMETERS OF OLDFIELD MODEL:',/,
     .       3X,'A PARAMETER (nucleii/m^3*s*°K) =',E15.6,/,
     .       3X,'n EXPONENT (adimensional) =',E15.6)
C
  850 FORMAT(3X,'GROWTH MODEL')
  851 FORMAT(3X,'GROWTH PARAMETERS OF RAPPAZ & THEVOZ MODEL 1:',/,
     .       3X,'DIFFUSION COEF. OF Cu IN THE LIQUID (m^2/s) =',E15.6,/,
     .       3X,'GIBBS-THOMSON PARAMETER (°K*m) =',E15.6,/,
     .       3X,'LIQUIDUS CURVE SLOPE (%1) =',E15.6,/,
     .       3X,'OXYGEN PARTITION COEFFICIENT (adimensional) =',E15.6,/,
     .       3X,'INITIAL COMPOSITION (%1) =',E15.6)
  852 FORMAT(3X,'GROWTH PARAMETERS OF PERO - SANZ MODEL:',/,
     .       3X,'Z COEFFICIENT (m/s) =',E15.6)
  853 FORMAT(3X,'GROWTH PARAMETERS OF TURNBULL MODEL 1:',/,
     .       3X,'ENTAHLPY OF FUSION (J/kg) =',E15.6,/,
     .       3X,'GASES CONSTANT (J/kg°K) =',E15.6,/,
     .       3X,'FACTOR ORDER 1 (adimensional) =',E15.6,/,
     .       3X,'SOUND SPEED (m/s) =',E15.6)
  854 FORMAT(3X,'GROWTH PARAMETERS OF TURNBULL MODEL 2:',/,
     .       3X,'ENTAHLPY OF FUSION (J/kg) =',E15.6,/,
     .       3X,'GASES CONSTANT (J/kg°K) =',E15.6,/,
     .       3X,'BOLTZMAN CONSTANT (J/atom°K) =',E15.6,/,
     .       3X,'ATOMIC MASS (Kg/atom) =',E15.6)
  855 FORMAT(3X,'GROWTH PARAMETERS OF RAPPAZ & THEVOZ MODEL 2:',/,
     .       3X,'DIFFUSION COEF. OF Cu IN THE LIQUID (m^2/s) =',E15.6,/,
     .       3X,'GIBBS-THOMSON PARAMETER (°K*m) =',E15.6,/,
     .       3X,'LIQUIDUS CURVE SLOPE (%1) =',E15.6,/,
     .       3X,'OXYGEN PARTITION COEFFICIENT (adimensional) =',E15.6,/,
     .       3X,'INITIAL COMPOSITION (%1) =',E15.6,/,
     .       3X,'DIFFUSION COEF. OF O IN THE Cu LIQUID (m^2/s) =',E15.6,/,
     .       3X,'MAXIMUM OBSERVED GRAIN RADIUS =',E15.6)
C
  860 FORMAT(3X,'NUMERICAL STRATEGY PARAMETERS')
  861 FORMAT(3X,'TEMPERATURE DERIVATIVE FORM OF FL=',I5)
  862 FORMAT(3X,'FRACTION CORRECTION FORM         =',I5)
      END
