      SUBROUTINE RADCOFU(BASHH ,PROPST,TGAUS1,TGAUS2,GAPTET,PRESUT,
     .                   PSEUDO1,PSEUDO2, INDEP)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE CONVECTION-RADIATION COEFFICIENT
C
C***********************************************************************
C
C     BASHH= Convection-radiation coefficient
C
C     INDEP=1    >>    elm104
C
C***********************************************************************
      IMPLICIT REAL*8 (A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
C
      DIMENSION PROPST(*)
C
C**** CONVECTION RADIATION COEFFICIENT: TEMPERATURE OF 
C     BODY 1-DEPENDENT PART (GAP ELEMENT 104)
C
      IF(TGAUS1.LE.VRADH1(1,2)) BASHT1=VRADH1(1,1)
      DO IRADH1=2,NRADH1
       I1=IRADH1-1
       I2=IRADH1
       IF(TGAUS1.GT.VRADH1(I1,2).AND.TGAUS1.LE.VRADH1(I2,2)) 
     .  BASHT1=(VRADH1(I2,1)-VRADH1(I1,1))/(VRADH1(I2,2)-VRADH1(I1,2))*
     .         (TGAUS1-VRADH1(I1,2))+VRADH1(I1,1)
      ENDDO
      IF(TGAUS1.GT.VRADH1(NRADH1,2)) BASHT1=VRADH1(NRADH1,1)
C
C**** CONVECTION RADIATION COEFFICIENT: TEMPERATURE OF 
C     BODY 2-DEPENDENT PART (GAP ELEMENT 104)
C
      IF(TGAUS2.LE.VRADH2(1,2)) BASHT2=VRADH2(1,1)
      DO IRADH2=2,NRADH2
       I1=IRADH2-1
       I2=IRADH2
       IF(TGAUS2.GT.VRADH2(I1,2).AND.TGAUS2.LE.VRADH2(I2,2)) 
     .  BASHT2=(VRADH2(I2,1)-VRADH2(I1,1))/(VRADH2(I2,2)-VRADH2(I1,2))*
     .         (TGAUS2-VRADH2(I1,2))+VRADH2(I1,1)
      ENDDO
      IF(TGAUS2.GT.VRADH2(NRADH2,2)) BASHT2=VRADH2(NRADH2,1)
C
C**** CONVECTION RADIATION COEFFICIENT: GAP-DEPENDENT PART
C     (GAP ELEMENT 104)
C
      IF(GAPTET.LE.VRADU(1,2)) BASHU=VRADU(1,1)
      DO IRADU=2,NRADU
       I1=IRADU-1
       I2=IRADU
       IF(GAPTET.GT.VRADU(I1,2).AND.GAPTET.LE.VRADU(I2,2)) 
     .    BASHU=(VRADU(I2,1)-VRADU(I1,1))/(VRADU(I2,2)-VRADU(I1,2))*
     .          (GAPTET-VRADU(I1,2))+VRADU(I1,1)
      ENDDO
      IF(GAPTET.GT.VRADU(NRADU,2)) BASHU=VRADU(NRADU,1)
C
C**** CONVECTION RADIATION COEFFICIENT: PRESSURE-DEPENDENT PART
C     (GAP ELEMENT 104)
C
      IF(PRESUT.LE.VRADP(1,2)) BASHP=VRADP(1,1)
      DO IRADP=2,NRADP
       I1=IRADP-1
       I2=IRADP
       IF(PRESUT.GT.VRADP(I1,2).AND.PRESUT.LE.VRADP(I2,2)) 
     .    BASHP=(VRADP(I2,1)-VRADP(I1,1))/(VRADP(I2,2)-VRADP(I1,2))*
     .          (PRESUT-VRADP(I1,2))+VRADP(I1,1)
      ENDDO
      IF(PRESUT.GT.VRADP(NRADP,2)) BASHP=VRADP(NRADP,1)
C
C**** CONVECTION-RADIATION COEFFICIENT
C
      IF(ITERMG.EQ.0) THEN
       BASHU=1.0D0
       BASHP=1.0D0
      ENDIF
      BASHH=BASHT1*BASHT2*BASHU*BASHP
C
C**** DEALS WITH FILLING MATERIAL
C
      IF(IFILL.EQ.0) RETURN
C
      PSEUDO=PSEUDO1                                    ! simplification
C
C**** CONVECTION RADIATION COEFFICIENT: TEMPERATURE OF 
C     BODY 1-DEPENDENT PART (GAP ELEMENT 104)
C
      IF(TGAUS1.LE.VRADH1FI(1,2)) BASHT1=VRADH1FI(1,1)
      DO IRADH1=2,NRADH1FI
       I1=IRADH1-1
       I2=IRADH1
       IF(TGAUS1.GT.VRADH1FI(I1,2).AND.TGAUS1.LE.VRADH1FI(I2,2)) 
     .  BASHT1=(VRADH1FI(I2,1)-VRADH1FI(I1,1))/
     .         (VRADH1FI(I2,2)-VRADH1FI(I1,2))*
     .         (TGAUS1-VRADH1FI(I1,2))+VRADH1FI(I1,1)
      ENDDO
      IF(TGAUS1.GT.VRADH1FI(NRADH1FI,2)) BASHT1=VRADH1FI(NRADH1FI,1)
C
C**** CONVECTION RADIATION COEFFICIENT: TEMPERATURE OF
C     BODY 2-DEPENDENT PART (GAP ELEMENT 104)
C
      IF(TGAUS2.LE.VRADH2FI(1,2)) BASHT2=VRADH2FI(1,1)
      DO IRADH2=2,NRADH2FI
       I1=IRADH2-1
       I2=IRADH2
       IF(TGAUS2.GT.VRADH2FI(I1,2).AND.TGAUS2.LE.VRADH2FI(I2,2)) 
     .  BASHT2=(VRADH2FI(I2,1)-VRADH2FI(I1,1))/
     .         (VRADH2FI(I2,2)-VRADH2FI(I1,2))*
     .         (TGAUS2-VRADH2FI(I1,2))+VRADH2FI(I1,1)
      ENDDO
      IF(TGAUS2.GT.VRADH2FI(NRADH2FI,2)) BASHT2=VRADH2FI(NRADH2FI,1)
C
C**** CONVECTION RADIATION COEFFICIENT: GAP-DEPENDENT PART
C     (GAP ELEMENT 104)
C
      IF(GAPTET.LE.VRADUFI(1,2)) BASHU=VRADUFI(1,1)
      DO IRADU=2,NRADUFI
       I1=IRADU-1
       I2=IRADU
       IF(GAPTET.GT.VRADUFI(I1,2).AND.GAPTET.LE.VRADUFI(I2,2)) 
     .    BASHU=(VRADUFI(I2,1)-VRADUFI(I1,1))/
     .          (VRADUFI(I2,2)-VRADUFI(I1,2))*
     .          (GAPTET-VRADUFI(I1,2))+VRADUFI(I1,1)
      ENDDO
      IF(GAPTET.GT.VRADUFI(NRADUFI,2)) BASHU=VRADUFI(NRADUFI,1)
C
C**** CONVECTION RADIATION COEFFICIENT: PRESSURE-DEPENDENT PART
C     (GAP ELEMENT 104)
C
      IF(PRESUT.LE.VRADPFI(1,2)) BASHP=VRADPFI(1,1)
      DO IRADP=2,NRADPFI
       I1=IRADP-1
       I2=IRADP
       IF(PRESUT.GT.VRADPFI(I1,2).AND.PRESUT.LE.VRADPFI(I2,2)) 
     .    BASHP=(VRADPFI(I2,1)-VRADPFI(I1,1))/
     .          (VRADPFI(I2,2)-VRADPFI(I1,2))*
     .          (PRESUT-VRADPFI(I1,2))+VRADPFI(I1,1)
      ENDDO
      IF(PRESUT.GT.VRADPFI(NRADPFI,2)) BASHP=VRADPFI(NRADPFI,1)
C
C**** CONVECTION-RADIATION COEFFICIENT
C
      IF(ITERMG.EQ.0) THEN
       BASHU=1.0D0
       BASHP=1.0D0
      ENDIF
      BASHHFI=BASHT1*BASHT2*BASHU*BASHP
C
C**** COMPUTES THE WEIGHTED CONVECTION-RADIATION COEFFICIENT
C
      BASHH=PSEUDO*BASHH+(1.0D0-PSEUDO)*BASHHFI
C
      RETURN
      END
