      SUBROUTINE RSOPENT
C***********************************************************************
C
C**** THIS ROUTINE OPENS THE FOLLOWING FILES:
C
C     - FILE 201 (21 LINUX)  PROCESS DATA BASE FILE
C     - FILE 211 (31 LINUX)  RESTART DATA BASE FILE
C     - FILE 207 (27 LINUX)  OUTPUT FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      LOGICAL OPENFILE
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_omt.f'
C
C**** THERMAL VARIABLES
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
C
      CALL CPUTIMT(TIME1T)
C
      GO TO (101,102,102,101,101,101,101,101), NMACHI
C
  101 CONTINUE
      LENRCT=512
      GO TO 1001
C
  102 CONTINUE
      LENRCT=512/4
      GO TO 1001
C
 1001 CONTINUE
C
      OPEN(UNIT=LUPRIT,FILE=CFT)
      INQUIRE(UNIT=LUINFT, OPENED=OPENFILE)
      IF(.NOT.OPENFILE) THEN
        OPEN(UNIT=LUINFT,FILE=CTT,STATUS='UNKNOWN',IOSTAT=IERR)
      END IF
C
      IF(IRESTT.NE.0)  GOTO 100
C***********************************************************************
C
C**** N E W   R U N  *** OPEN NEW RESTART AND OUTPUT FILES . . . . . 
C
C***********************************************************************
      IERORT=1
      IF(NMACHI.NE.8) THEN
       OPEN(UNIT=LUREST,FILE=CGT,STATUS='OLD',ERR=1000)
      ENDIF
      IERORT=2
      IF(NDISKD.EQ.0)
     . OPEN(UNIT=LUDTST,FILE=CAT,STATUS='UNKNOWN',ACCESS='DIRECT',
     .      FORM='UNFORMATTED',RECL=LENRCT,ERR=1000)
      IERORT=3
      IF(NFURES.EQ.1) THEN
       OPEN(UNIT=LUFANT,FILE=COT,STATUS='UNKNOWN',FORM='UNFORMATTED')
       CLOSE(LUFANT)
      ENDIF
      IF(NFURES.EQ.2)
     . OPEN(UNIT=LURSTT,FILE=CKT,STATUS='UNKNOWN',ACCESS='DIRECT',
     .      FORM='UNFORMATTED',RECL=LENRCT,ERR=1000)
      IERORT=0
      GOTO 1000
C***********************************************************************
C
C**** R E S T A R T  R U N *** OPEN OLD RESTART AND OUTPUT FILES . . . .
C
C***********************************************************************
 100  CONTINUE
      IERORT=1
      OPEN(UNIT=LUREST,FILE=CGT,STATUS='UNKNOWN',ACCESS='APPEND',
     .     ERR=1000)
      IERORT=2
      IF(NDISKD.EQ.0)
     . OPEN(UNIT=LUDTST,FILE=CAT,STATUS='UNKNOWN',ACCESS='DIRECT',
     .      FORM='UNFORMATTED',RECL=LENRCT,ERR=1000)
      IERORT=3
      OPEN(UNIT=LURSTT,FILE=CKT,STATUS='OLD',ACCESS='DIRECT',
     .     FORM='UNFORMATTED',RECL=LENRCT,ERR=1000)
      IERORT=0
C
 1000 IF(IERORT.NE.0)THEN
       IF(IERORT.EQ.1) WRITE(LUPRIT,901)
       IF(IERORT.EQ.2) WRITE(LUREST,902)
       IF(IERORT.EQ.3) WRITE(LUREST,903)
       CALL RUNENDT('  ERROR IN OPENING FILES           ')
      ENDIF
C
      CALL CPUTIMT(TIME2T)
      CPURST=CPURST+(TIME2T-TIME1T)
      RETURN
C
  901 FORMAT(' ERROR IN OPENING OUTPUT  FILE 207 (27 LINUX)')     
  902 FORMAT(' ERROR IN OPENING PROCESS FILE 201 (21 LINUX)')     
  903 FORMAT(' ERROR IN OPENING RESTART FILE 211 (31 LINUX)')     
C
      END
