      SUBROUTINE RSSETPS
C***********************************************************************
C
C**** THIS ROUTINE CALCULATES  THE RECORD ADDRES FOR DIFFERENT ARRAYS
C     STORED IN THE PROCESSING AREA
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** ADDITIONAL PARAMETERS
C
      INCLUDE 'addi_oms.f'
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
C
C**** SET IDATP POINTERS
C
      DO INDEXS=1,12
       IDATPS(INDEXS,1)=0
       IDATPS(INDEXS,2)=0
      ENDDO
C
C**** EVALUATE LENGTH OF EACH ARRAY IN DOUBLE PRECISION WORDS
C
      NMEMA6S=1-NMEMO6S
      NMEMA7S=1-NMEMO7S
C
      IDATPS( 1,1)=NDATAS                                   ! ELDAT
      IDATPS( 2,1)=NPREVS                                   ! ELPRE
      IDATPS( 3,1)=NSTATS                                   ! ELVAR
      IDATPS( 4,1)=NPREVS                                   ! ELPRE
      IDATPS( 5,1)=NSTATS                                   ! ELVAR
      IDATPS( 6,1)=NEVACS*NEVACS*NMEMA7S                    ! CSTIF
      IDATPS( 7,1)=NKOVAS*NMEMA6S                           ! ESTIF
      IF(KDYNAS.NE.0) IDATPS( 8,1)=NKOVAS*NMEMA6S           ! WSTIF
      IF(KPORES.EQ.2) THEN
       IDATPS( 9,1)=NKONDS                                  ! PSTIF
       IDATPS(10,1)=NKONDS                                  ! QSTIF
       IDATPS(11,1)=NEVABS*NNODES                           ! HSTIF
      ENDIF
      IDATPS(12,1)=NTOTVS                                   ! DISTO
C
      GO TO (101,102,102,101,101,101,101,101), NMACHIS
C
  101 CONTINUE
      LENWDS=LENRCS/4
      GO TO 1000
C
  102 CONTINUE
      LENWDS=LENRCS
      GO TO 1000
C
 1000 CONTINUE
C
C**** EVALUATE LENGTH OF EACH ARRAY IN RECORDS
C
      DO INDEXS=1,12
       IF(IDATPS(INDEXS,1).NE.0)
     .  IDATPS(INDEXS,2)=(2*IDATPS(INDEXS,1)-1)/LENWDS+1
      ENDDO
C
C**** INITIALIZE POINTERS FOR POSITION IN DOUBLE PRECISION WORDS
C
      IDATPS( 1,3)=0
      DO INDEXS=2,7
       IDATPS(INDEXS,3)=IDATPS(INDEXS-1,3)+IDATPS(INDEXS-1,1)
      ENDDO
C
      IF((KPROBS.EQ.1).AND.(KPORES.NE.2.AND.KDYNAS.NE.1)) THEN
       IDATPS(8,3)=IDATPS(7,3)
       IDATPS(7,3)=IDATPS(6,3)
      ELSE
       IDATPS(8,3)=IDATPS(7,3)+IDATPS(7,1)
      ENDIF
C
      IDATPS(9,3)=IDATPS(8,3)+IDATPS(8,1)
C
      IDATPS(10,3)=IDATPS( 9,3)+IDATPS( 9,1)
      IDATPS(11,3)=IDATPS(10,3)+IDATPS(10,1)
      IDATPS(12,3)=IDATPS(11,3)+IDATPS(11,1)
C
C**** INITIALIZE POINTERS FOR POSITION IN RECORDS
C
      IDATPS( 1,4)=0
      DO INDEXS=2,7
       IDATPS(INDEXS,4)=IDATPS(INDEXS-1,4)+IDATPS(INDEXS-1,2)
      ENDDO
C
      IF((KPROBS.EQ.1).AND.(KPORES.NE.2.AND.KDYNAS.NE.1)) THEN
       IDATPS(8,4)=IDATPS(7,4)
       IDATPS(7,4)=IDATPS(6,4)
      ELSE
       IDATPS(8,4)=IDATPS(7,4)+IDATPS(7,2)
      ENDIF
C
      IDATPS(9,4)=IDATPS(8,4)+IDATPS(8,2)
C
      IDATPS(10,4)=IDATPS( 9,4)+IDATPS( 9,2)
      IDATPS(11,4)=IDATPS(10,4)+IDATPS(10,2)
      IDATPS(12,4)=IDATPS(11,4)+IDATPS(11,2)
C
C**** LAST RECORD OF THE BLOCK
C
      NLENPS=IDATPS(12,4)
C
C**** LAST RECORD OF THE FILE
C
      NRECPS=NLENPS*NELEMS
C
C**** INITIALIZE FLAGS FOR ARRAYS ALLOCATION
C
      DO INDEXS=1,11
       IDATPS(INDEXS,5)=-1
      ENDDO
      IDATPS(12,5)=0
C
      RETURN
      END
