      SUBROUTINE RSTAR2(LPNTN,LNODS,MATNO,PROEL,PROPS,IFLAG)
C***********************************************************************
C
C**** THIS ROUTINE READS OR WRITES SOME GENERAL DATA ARRAYS
C
C   - IFLAG = 1 - NEW RUN    : WRITE INTO RESTART FILE 
C   - IFLAG = 2 - RESTART RUN: READ  FROM RESTART FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_om.f'
      INCLUDE 'auxl_om.f'
C
      DIMENSION LPNTN(*), LNODS(NNODE,NELEM), MATNO(NELEM),
     .                    PROEL(NPREL,NGRUP), PROPS(NPROP,NMATS)
C
      CALL CPUTIM(TIME1)
C
      NRCUR=4
      NUNIT=LURST
C
C**** WRITE OR READ ALL MATRICES
C
      LENGH=NPOIN
      CALL RESTDK(NUNIT,IFLAG,LPNTN,LENGH,LENRC,NRCUR)
C
      LENGH=NNODE*NELEM
      CALL RESTDK(NUNIT,IFLAG,LNODS,LENGH,LENRC,NRCUR)
C
      LENGH=NELEM
      CALL RESTDK(NUNIT,IFLAG,MATNO,LENGH,LENRC,NRCUR)
C
      LENGH=NPREL*NGRUP*2
      CALL RESTDK(NUNIT,IFLAG,PROEL,LENGH,LENRC,NRCUR)
C
      LENGH=NPROP*NMATS*2
      CALL RESTDK(NUNIT,IFLAG,PROPS,LENGH,LENRC,NRCUR)
C
      CALL CPUTIM(TIME2)
      CPURS=CPURS+(TIME2-TIME1)
C
      RETURN
      END
