      SUBROUTINE SOLVE1(DESJ2,DESMN,KGAUS,PREJ2,PREMN,PROPS,REDUC,
     .                  ZCOJ2)
C***********************************************************************
C
C**** THIS ROUTINE FINDS REDUC WHENEVER IS AVAILABLE A CLOSED 
C     FORM SOLUTION
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION PROPS(*)
C
      CINTE=PROPS(33)
      FINCL=PROPS(34)
      FINC2=FINCL*FINCL
      TERMS=FINCL*PREMN-CINTE
C
      AITAL=3.*DESJ2-FINC2*DESMN*DESMN
      BITAL=3.*ZCOJ2-FINCL*DESMN*TERMS
      CITAL=3.*PREJ2-TERMS*TERMS
C
      DISCR=BITAL*BITAL-AITAL*CITAL
      IF(DISCR.GE.0.0)GOTO 10
c     WRITE(7,900) KGAUS
  900 FORMAT(1X,'SUB.SOLVER: DISCRIMINANT SMALLER THAN ZERO. 
     .       IMMAGINARY',/,'SOLUTION. CHECK GAUSS POINT NO',I5)
C
      CALL RUNEND('ERROR IN SOLVE1                    ')
C
   10 CONTINUE
      REDUC=(-BITAL+DSQRT(DISCR))/AITAL
      ABRED=DABS(REDUC)
      IF(ABRED.LT.0.00001) REDUC=0.0
C
      IF(REDUC.GE.0.OR.REDUC.LE.1.)RETURN
C
c     WRITE(7,910)KGAUS,REDUC
  910 FORMAT(1X,'SUB.SOLVER: REDUCTION FACTOR OUT OF RANGE 0 - 1',/, 
     .       1X,'AT KGAUS NO.',I5,'  N.B. REDUC=',E15.6)
C
      CALL RUNEND('ERROR IN SOLVE1                    ')
C
      END
