      SUBROUTINE SOLVE2(DESJ2,DESMN,EHIST,KGAUS,PREJ2,PREMN,PROPS,
     .                  REDUC,ZCOJ2)
C***********************************************************************
C
C**** THIS ROUTINE FINDS REDUC WHENEVER IS AVAILABLE A CLOSED 
C     FORM SOLUTION
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION EHIST(*), PROPS(*)
C
      HPARA=EHIST(3)
      BETAS=EHIST(4)
C
C**** BURLAND IN THE HPS: DRUCKER-PRAGER & ALPHA=0.0
C
      RATIO=PROPS(34)
      RATI2=RATIO*RATIO
      PREB2=(PREMN-BETAS)*(PREMN-BETAS)
      ACOEF=DESMN*DESMN+3.*DESJ2/RATI2
      BCOEF=DESMN*(PREMN-BETAS)+3.0*ZCOJ2/RATI2
      CCOEF=PREB2-HPARA*HPARA+3.0*PREJ2/RATI2
C
      DISCR=BCOEF*BCOEF-ACOEF*CCOEF
      IF(DISCR.GE.0.0)GOTO 10
c     WRITE(7,900) KGAUS
  900 FORMAT(1X,'SUB.SOLVER: DISCRIMINANT SMALLER THAN ZERO. 
     .       IMMAGINARY',/,'SOLUTION. CHECK GAUSS POINT NO',I5)
C
      CALL RUNEND('ERROR IN SOLVE2                    ')
C
   10 CONTINUE
      REDUC=(-BCOEF+DSQRT(DISCR))/ACOEF
      ABRED=DABS(REDUC)
      IF(ABRED.LT.0.00001) REDUC=0.0
C
      IF(REDUC.GE.0.OR.REDUC.LE.1.)RETURN
C
c     WRITE(7,910)KGAUS,REDUC
  910 FORMAT(1X,'SUB.SOLVER: REDUCTION FACTOR OUT OF RANGE 0 - 1',/, 
     .       1X,'AT KGAUS NO.',I5,'  N.B. REDUC=',E15.6)
C
      CALL RUNEND('ERROR IN SOLVE2                    ')
      END
