      SUBROUTINE STROUTT
C***********************************************************************
C
C**** THIS ROUTINE PRINTS OUT THE SOLUTION STRATEGY FOR THE CURRENT 
C     INTERVAL
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
C
      CHARACTER WACCET*31,WACTIT*14,WALGOT*24,WARCLT*31,WCONVT*35,
     .          WSMUST*14
      DIMENSION WACCET(4),WACTIT(2),WALGOT(4),WARCLT(5),WCONVT(4),
     .          WSMUST(5)
      DATA WACCET/' NOT ACTIVATED ',
     .            ' SN 1 PARAMET. ',
     .            ' SN 2 PARAMET. ',
     .            '          BFGS '/
      DATA WACTIT/' NOT ACTIVATED',
     .            '     ACTIVATED '/
      DATA WALGOT/' INITIAL STIFF.',
     .            ' NEWTON-RAPHSON',
     .            ' MODIF. N_R    ',
     .            ' MODIF. N_R    '/
      DATA WARCLT/' NOT ACTIVATED ',
     .            '   NORMAL PLANE',
     .            ' UPD. NM. PLANE',
     .            ' SPHERICAL PATH',
     .            ' DISPL. CONTROL'/
      DATA WCONVT/' RESID / TOTAL FORCES',
     .            ' RESID / INCR. FORCES',
     .            ' ITERT / INCR. DISPL. ',
     .            ' ITERT / TOTAL ENERGY '/
      DATA WSMUST/' NOT ACTIVATED',
     .            '         LOCAL',
     .            '   GLOBAL A.F.',
     .            '   GLOBAL H.O.',
     .            '      DISCRETE'/
C
C**** HEADING
C
      WRITE(LUREST,900)
  900 FORMAT(
     .10X//,' * * * SOLUTION STRATEGY OF THE CURRENT INTERVAL * * *',//)
C
C**** NUMBER OF STEPS AND TIME STEP INTERVAL
C
      WRITE(LUREST,899) NSTEPT,DTIMET
  899 FORMAT(
     .10X,'TOTAL N0. OF STEPS IN THE INTERVAL: ',8X,I5,/,
     .10X,'INITIAL TIME STEP INCREMENT       : ',1X,E12.6)
C
C**** TIME MARCHING SCHEME
C
      IF(KINTET.EQ.0) WRITE(LUREST,810)
  810 FORMAT(
     .10X,'TIME MARCHING SCHEME              : NOT ACTIVATED')
C
      IF(KINTET.EQ.1) THEN
         WRITE(LUREST,811) TALFAT
         IF(KOPTIT.EQ.0) WRITE(LUREST,812)
         IF(KOPTIT.EQ.1) WRITE(LUREST,813)
         IF(KOPTIT.EQ.2) WRITE(LUREST,814)
         IF(KOPTIT.EQ.3) WRITE(LUREST,815)
      ENDIF
  811 FORMAT(
     .10X,'TIME MARCHING SCHEME              : EULER ',/,
     .10X,'INITIAL THETA PARAMETER           =',3X,F10.5,/)
  812 FORMAT(10X,'TIME INCREMENT AND THETA PARAMETER CONSTANT',/)
  813 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LOG. SCALE AND CONSTANT',/,
     .10X,'THETA PARAMETER. ',/)
  814 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LOG. SCALE AND THETA   ',/,
     .10X,'THETA PARAMETER CALCULATED ACCORDING TO SANDHU . ',/)
  815 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LINEAR SCALE AND THETA ',/,
     .10X,'THETA PARAMETER CALCULATED ACCORDING TO SANDHU . ',/)
C
      IF(KINTET.EQ.2) THEN
         CNEW2T=1./TALFAT
         CNEW1T=TBETAT*CNEW2T
         WRITE(LUREST,816) CNEW1T,CNEW2T
         IF(KOPTIT.EQ.0) WRITE(LUREST,817)
         IF(KOPTIT.EQ.1.OR.KOPTIT.EQ.2) WRITE(LUREST,818)
         IF(KOPTIT.EQ.3) WRITE(LUREST,819)
      ENDIF
  816 FORMAT(
     .10X,'TIME MARCHING SCHEME              : NEWMARK',/,
     .10X,'FIRST PARAMETER                   =',3X,F10.5 ,/,
     .10X,'SECOND PARAMETER                  =',3X,F10.5,/)
  817 FORMAT(10X,'TIME INCREMENT CONSTANT',/)
  818 FORMAT(10X,'TIME INCREMENT CONSTANT IN LOG. SCALE ',/)
  819 FORMAT(10X,'TIME INCREMENT CONSTANT IN LINEAR SCALE',/)
C
      IF(KINTET.EQ.3) THEN
         WRITE(LUREST,1811) TALFAT
         IF(KOPTIT.EQ.0) WRITE(LUREST,1812)
         IF(KOPTIT.EQ.1) WRITE(LUREST,1813)
         IF(KOPTIT.EQ.2) WRITE(LUREST,1814)
         IF(KOPTIT.EQ.3) WRITE(LUREST,1815)
      ENDIF
 1811 FORMAT(
     .10X,'TIME MARCHING SCHEME              : HUGHES-V_FORM',/,
     .10X,'INITIAL ALPHA PARAMETER           =',3X,F10.5,/)
 1812 FORMAT(10X,'TIME INCREMENT AND ALPHA PARAMETER CONSTANT',/)
 1813 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LOG. SCALE AND CONSTANT',/,
     .10X,'THETA PARAMETER. ',/)
 1814 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LOG. SCALE AND THETA   ',/,
     .10X,'THETA PARAMETER CALCULATED ACCORDING TO SANDHU . ',/)
 1815 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LINEAR SCALE AND THETA ',/,
     .10X,'THETA PARAMETER CALCULATED ACCORDING TO SANDHU . ',/)
C
      IF(KINTET.EQ.4) THEN
         WRITE(LUREST,2811) TALFAT
         IF(KOPTIT.EQ.0) WRITE(LUREST,2812)
         IF(KOPTIT.EQ.1) WRITE(LUREST,2813)
         IF(KOPTIT.EQ.2) WRITE(LUREST,2814)
         IF(KOPTIT.EQ.3) WRITE(LUREST,2815)
      ENDIF
 2811 FORMAT(
     .10X,'TIME MARCHING SCHEME              : HUGHES-D_FORM',/,
     .10X,'INITIAL ALPHA PARAMETER           =',3X,F10.5,/)
 2812 FORMAT(10X,'TIME INCREMENT AND ALPHA PARAMETER CONSTANT',/)
 2813 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LOG. SCALE AND CONSTANT',/,
     .10X,'THETA PARAMETER. ',/)
 2814 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LOG. SCALE AND THETA   ',/,
     .10X,'THETA PARAMETER CALCULATED ACCORDING TO SANDHU . ',/)
 2815 FORMAT(
     .10X,'TIME INCREMENT CONSTANT IN LINEAR SCALE AND THETA ',/,
     .10X,'THETA PARAMETER CALCULATED ACCORDING TO SANDHU . ',/)
C
C***TYPE OF OVERALL ALGORITHM
C
      WRITE(LUREST,901) WALGOT(NALGOT)
  901 FORMAT(10X,'TYPE OF ALGORITHM                 :',A)
C
C***LINE SEARCH
C
      WRITE(LUREST,920) WACTIT(LINEST+1)
  920 FORMAT(10X,'LINE SEARCH                       :',A)
C
C***ARC-LENGTH
C
      WRITE(LUREST,930) WARCLT(KARCLT+1)
  930 FORMAT(10X,'ARC-LENGHT                        :',A)
C
C***ACCELERATION METHOD
C
      WRITE(LUREST,940) WACCET(LACCET+1)
  940 FORMAT(10X,'ACCELERATION METHOD               :',A,/)
C
C***CONVERGENCE CRITERIA
C
      WRITE(LUREST,951) WCONVT(KCONVT),TOLERT,MITERT
C
  951 FORMAT(10X,'CONVERGENCE CRITERIA              : ',A,/,
     .       10X,'  WITH A TOLLERANCE               = ',1X,E12.6,/,
     .       10X,'  MAX. NO. ITERATIONS             = ',8X,I5,/)
C
C***AUTOMATIC LOAD INCREMENT
C
      IF(LAUTOT.EQ.0) WRITE(LUREST,960)
      IF(LAUTOT.EQ.1) WRITE(LUREST,961) INT(DITERT)
      IF(LAUTOT.EQ.2) WRITE(LUREST,962) DITERT
      IF(LAUTOT.EQ.3) WRITE(LUREST,963) DITERT
  960 FORMAT(10X,'AUTOMATIC LOAD/DISPL. INCREM.     : NOT ACTIVATED')
  961 FORMAT(
     .10X,'AUTOMATIC LOAD/DISPL. INCREM.     : BASED ON NO. 
     .ITERATIONS',/,
     .10X,'          DESIRED NO. ITERATIONS  = ',8X,I5)
  962 FORMAT(
     .10X,'AUTOMATIC LOAD/DISPL. INCREM.     : BASED ON STIFFNESS 
     .CHANGE',/,
     .10X,'                                   REFERED TO THE 
     .INITIAL ONE',/,
     .10X,'    DESIRED STIFFNESS CHANGE      = ',1X,E12.6)
  963 FORMAT(
     .10X,'AUTOMATIC LOAD/DISPL. INCREM.     : BASED ON STIFFNESS
     .CHANGE',/,
     .10X,'                                   REFERED TO THE 
     .PREVIOUS ONE',/,
     .10X,'    DESIRED STIFFNESS CHANGE      = ',1X,E12.6)
C
C***AUTOMATIC END OF ANALYSIS
C
      IF(STIFIT.EQ.0.) WRITE(LUREST,970)
      IF(STIFIT.NE.0.) WRITE(LUREST,971) STIFIT
  970 FORMAT(10X,'AUTOMATIC END OF ANALYSIS         : NOT ACTIVATED',/)
  971 FORMAT(
     .10X,'AUTOMATIC END OF ANALYSIS         : THE ANALYSIS IS 
     .STOPPED IF  ',/,
     .10X,'                                   THE STIFFNESS 
     .PARAMETER IS  ',/,
     .10X,'                                   LOWER THAN A 
     .SPECIFIED VALUE',/,
     .10X,'FINAL STIFFNESS PARAMETER  =',1X,E12.6,/)
C
C***FOR COUPLED PROLEM: PORE PRESSURE SMOOTHING & LUMPING OPTIONS
C
      IF(KPORET.EQ.2) THEN
         ISMUST=IABS(KSMUST)
         WRITE(LUREST,980) WSMUST(ISMUST+1)
         IF(WLUMPT.EQ.1) WRITE(LUREST,990)
         IF(WLUMPT.NE.1) WRITE(LUREST,991) WLUMPT
      ENDIF
  980 FORMAT(10X,'PORE PRESSURE SMOOTHING OPTION    : ',A)
  990 FORMAT(10X,'PORE PRESSURE LUMPING OPTION      : NOT ACTIVATED',/)
  991 FORMAT(10X,'PORE PRESSURE LUMPING MULTIPLIER  =',1X,E12.6,/)
      RETURN
      END
