      SUBROUTINE TESTM2(CARTD,DERIV,SHAPE,KGAUS,NDIME,NNODE)
C***********************************************************************
C
C**** THIS ROUTINE MAKES A CONTROL ON THE CORRECTNESS OF THE SHAPE 
C     FUNCTION AND THEIR DERIV.:
C     FOR STANDARD FINITE ELEMENT SHAPE FUNCTIONS:
C     THE SUM OF ALL NODAL VALUES OF SHAPE MUST BE EQUAL TO 1
C     THE SUM OF ALL NODAL VALUES OF DERIV MUST BE EQUAL TO 0
C     THE SUM OF ALL NODAL VALUES OF CARTD MUST BE EQUAL TO 0
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION CARTD(NDIME,*), DERIV(NDIME,*), SHAPE(*),
     .          DUMM1(3),       DUMM2(3)
C
      TSHAP=0.
      DO 11 IDIME=1,NDIME
      DUMM1(IDIME)=0.
   11 DUMM2(IDIME)=0.

      DO 12 INODE=1,NNODE
      TSHAP=TSHAP+SHAPE(INODE)
      DO 12 IDIME=1,NDIME
      DUMM1(IDIME)=DUMM1(IDIME)+DERIV(IDIME,INODE)
   12 DUMM2(IDIME)=DUMM2(IDIME)+CARTD(IDIME,INODE)
c     PRINT *,KGAUS,TSHAP,(DUMM1(IDIME),IDIME=1,NDIME),
c    .                    (DUMM2(IDIME),IDIME=1,NDIME)
C
      RETURN
      END
