
      SUBROUTINE VERIF2(DESMN,DESJ2,DESJ3,DIFFE,EHIST,NCRIT,PREMN,
     .                  PREJ2,PREJ3,PROPS,REDUC,WCOJ3,YCOJ3,ZCOJ2)
C***********************************************************************
C
C****THIS ROUTINE CHECKS IF THE TRIAL REDUCTION SATISFIES THE
C    BOUNDARY  SURFACE.
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION EHIST(*), PROPS(*)
C
      HPARA=EHIST(3)
      BETAS=EHIST(4)
C
C***CALCULATES THETA AND RATIO
C
      CALL CALTHE(BARMN,BARQU,BARTH,DESMN,DESJ2,DESJ3,PREMN,
     .            PREJ2,PREJ3,REDUC,WCOJ3,YCOJ3,ZCOJ2)
      CALL VARTHE(CAPTH,BARCI,BARFI,IFLAG,PROPS,BARTH)
      RATIO=PROPS(35)*BARFI
C
C***CHECK IF THE REDUCED STRESS LIES ON THE SURFACE
C
      FIRTE=BARMN-BETAS
      SECTE=BARQU/RATIO
C
      DIFFE=FIRTE*FIRTE+SECTE*SECTE-HPARA*HPARA
C
      RETURN
      END
