      SUBROUTINE WBOUNDT(DVOLU,NDOFN,NEVAB,NNODE,PROPS,SHAPE,WSTIF,
     .                   BASHH,ELDIS,NDOFC,KSYMM,EMATX,ICIEN)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE CONSISTENT BOUNDARY ELEMENT MATRIX
C     (FOR BOUNDARY AND CONTACT ELEMENTS; IN THIS LATTER CASE FOR
C     COINCIDENT MESHES)
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION PROPS(*), SHAPE(*), WSTIF(*), ELDIS(NDOFC,*)
      DIMENSION EMATX(NEVAB,*)
C
      IF(ICIEN.NE.101.AND.ICIEN.NE.104)
     . CALL RUNENDT('WBOUNDT: ERROR IN ICIEN')
C
      COEFH=BASHH
      CONST=COEFH
C
C**** INITIALISES E
C
      DO INODE=1,NNODE
       DO JNODE=1,NNODE
        EMATX(INODE,JNODE)=0.0D0
       ENDDO
      ENDDO
C
      DO INODE=1,NNODE
       INDEX=INODE               ! SYMMETRIC CASE
       IF(KSYMM.EQ.0) INDEX=1    ! UNSYMMETRIC CASE
       DO JNODE=INDEX,NNODE
        EMATX(INODE,JNODE)=EMATX(INODE,JNODE)+SHAPE(INODE)*
     .                     CONST*SHAPE(JNODE)
       ENDDO
      ENDDO
C
C**** ADD THE CONTRIBUTION TO THE CAPACITY MATRIX
C
      IF(ICIEN.EQ.101)
     . CALL SQTOTA(WSTIF,EMATX,DVOLU,NEVAB,KSYMM)
C
      RETURN
      END
