      SUBROUTINE WHAFUN(DERIV,EXISP,ETASP,EZETA,NDIME,NNODE,SHAPE,HACHE,
     .                  XJACM,IPERT)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES SHAPE FUNCTIONS AND THEIR DERIVATIVES
C     FOR LINEAR AND QUADRATIC ISOPARAMETRIC ELEMENTS
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION DERIV(NDIME,*), SHAPE(*), HACHE(*), XJACM(NDIME,*)
C
      DIMENSION XJACI(3,3), CARTT(3,27), SHAPT(3,27)
C
      GOTO(1,2,3), NDIME
    1 CALL WHAPE1(DERIV,EXISP,NDIME,NNODE,SHAPE,HACHE,
     .            XJACM,IPERT,XJACI,CARTT,SHAPT)
      RETURN
    2 CALL WHAPE2(DERIV,EXISP,ETASP,NDIME,NNODE,SHAPE,HACHE,
     .            XJACM,IPERT,xjaci,cartt,shapt)
      RETURN
    3 CALL WHAPE3(DERIV,EXISP,ETASP,EZETA,NDIME,NNODE,SHAPE,HACHE,
     .            XJACM,IPERT,XJACI,CARTT,SHAPT)
      RETURN
      END
