      SUBROUTINE WINTERT(DVOLU,NEVAB,NNODE,WSTIF,KSYMM,EMATX,FMATX)
C***********************************************************************
C
C**** THIS ROUTINE EVALUATES THE CONSISTENT INTERFACE ELEMENT MATRIX
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION WSTIF(*)
      DIMENSION EMATX(NNODE,*), FMATX(NEVAB,*)
C
      DO INODE=1,NNODE
       INDEX=INODE                   ! SYMMETRIC CASE
       IF(KSYMM.EQ.0) INDEX=1        ! UNSYMMETRIC CASE
       DO JNODE=INDEX,NNODE
        FMATX(INODE,JNODE)=EMATX(INODE,JNODE)
        FMATX(INODE,JNODE+NNODE)=-EMATX(INODE,JNODE)
        IF(KSYMM.EQ.0) THEN          ! UNSYMMETRIC CASE
         FMATX(INODE+NNODE,JNODE)=-EMATX(INODE,JNODE)
        ELSE                         ! SYMMETRIC CASE
         FMATX(JNODE,INODE+NNODE)=-EMATX(INODE,JNODE)
        ENDIF
        FMATX(INODE+NNODE,JNODE+NNODE)=EMATX(INODE,JNODE)
       ENDDO
      ENDDO
C
C**** ADD THE CONTRIBUTION TO THE INTERFACE MATRIX
C
      CALL SQTOTA(WSTIF,FMATX,DVOLU,NEVAB,KSYMM)
C
      RETURN
      END
