      SUBROUTINE CONCEKS
C***********************************************************************
C
C**** THIS ROUTINE CHECKS THE MAIN CONTROL DATA ESTABLISHED IN
C     "CONTROL_DATA" & "PROBLEM_DATA"
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** COUPLING VARIABLES
C
      INCLUDE 'nuec_om.f'
      INCLUDE 'nued_om.f'
      INCLUDE 'nuef_om.f'                 ! thermal-flow
C
C**** MICROSTRUCTURAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
C
      DIMENSION NERORS(12)
C
      DO 10 IERORS=1,12
   10 NERORS(IERORS)=0
C
C**** CHECK ON MAXIMUM DIMENSIONS
C
      IF(NPOINS.LE.0)                                     NERORS(1)=1
      IF(NELEMS.LE.0)                                     NERORS(2)=1
      IF(NNODES.LT.2.OR.NNODES.GT.27)                     NERORS(3)=1
      IF(NMATSS.LT.1.OR.NMATSS.GT.NELEMS)                 NERORS(4)=1
      IF(NFUNCS.LT.1)                                     NERORS(5)=1
C
C**** PROBLEM INCOMPATIBILITY
C
      IF(KPROBS.EQ.0)                                     NERORS(8)=1
      IF(KPORES.EQ.2.AND.LARGES.NE.0)                     NERORS(9)=1
      IF(KPORES.NE.2.AND.KSMUSS.NE.0)                     NERORS(10)=1
C
C**** CHECK ON MISCELLANEOUS
C
      IF(KSYMMS.EQ.0) NERORS(11)=0   ! unsymmetric solver is implemented
      IF(IABS(KSMUSS).EQ.1.AND.NDIMES.NE.2)               NERORS(12)=1
C
C**** OTHER ERRORS
C
c     IF(IMICR.EQ.1.AND.ITERME.GE.0.AND.KSGAUS.EQ.0)
c    . CALL RUNENDS('ERROR: SMOOTHING OPTION IS LACKING')
C
c     IF(IMICR.EQ.1.AND.ITERMEF.GT.0.AND.KSGAUS.EQ.0)
c    . CALL RUNENDS('ERROR: SMOOTHING OPTION IS LACKING')
C
C**** WARNINGS
C
      IF(KSYMMS.EQ.0.AND.ICONVS.EQ.0.AND.IGALES.EQ.0) THEN
       WRITE(LURESS,901)
       WRITE(LUPRIS,901)
  901  FORMAT(//,'WARNING: AN UNSYMMETRIC SOLVER IS USED FOR A',/,
     .           '         NON-ADVECTION-DIFFUSION PROBLEM WITH',/,
     .           '         NO UPWINDING TECHNIQUE',//)
      ENDIF
C
      IF(KSYMMS.EQ.1.AND.ICONVS.EQ.1) THEN
       WRITE(LURESS,902)
       WRITE(LUPRIS,902)
  902  FORMAT(//,'WARNING: A SYMMETRIC SOLVER IS USED FOR AN',/,
     .           '         ADVECTION-DIFFUSION PROBLEM',//)
      ENDIF
C
      IF(KSYMMS.EQ.1.AND.IGALES.EQ.1) THEN
       WRITE(LURESS,903)
       WRITE(LUPRIS,903)
  903  FORMAT(//,'WARNING: A SYMMETRIC SOLVER IS USED WITH AN',/,
     .           '         UPWINDING TECHNIQUE',//)
      ENDIF
C
      IF(ICONVS.EQ.0.AND.IGALES.EQ.1) THEN
       WRITE(LURESS,904)
       WRITE(LUPRIS,904)
  904  FORMAT(//,'WARNING: AN UPWIND TECHNIQUE IS CONSIDERED FOR',/,
     .           '         THIS NON-ADVECTION-DIFFUSION PROBLEM',//)
      ENDIF
C
      IF(ICONVS.EQ.1.AND.IGALES.EQ.0) THEN
       WRITE(LURESS,905)
       WRITE(LUPRIS,905)
  905  FORMAT(//,'WARNING: NO UPWIND TECHNIQUE IS CONSIDERED FOR',/,
     .           '         THIS ADVECTION-DIFFUSION PROBLEM',//)
      ENDIF
C
C**** CHECK IF ERRORS HAD OCCURED
C
      KOUNTS=0
      DO 20 IERORS=1,12
      IF (NERORS(IERORS).NE.1) GOTO 20
      KOUNTS=KOUNTS+1
   20 CONTINUE
C
      IF(KOUNTS.EQ.0) RETURN
C
C**** ERRORS DIAGNOSED BY ROUTINE CONCEK
C
      WRITE(LURESS,600) KOUNTS
  600 FORMAT(//,20X,I5,'  INPUT ERRORS DETECTED BY CONTRO',/,
     .          25X,   '  DIAGNOSTIC FOLLOWS: ',//)
C
      IF(NERORS(1).EQ.1)  WRITE(LURESS,700) 
      IF(NERORS(2).EQ.1)  WRITE(LURESS,705) 
      IF(NERORS(3).EQ.1)  WRITE(LURESS,710) NNODES
      IF(NERORS(4).EQ.1)  WRITE(LURESS,715) NMATSS,NELEMS
      IF(NERORS(5).EQ.1)  WRITE(LURESS,720)
      IF(NERORS(8).EQ.1)  WRITE(LURESS,735)
      IF(NERORS(9).EQ.1)  WRITE(LURESS,740)
      IF(NERORS(10).EQ.1) WRITE(LURESS,745)
      IF(NERORS(11).EQ.1) WRITE(LURESS,750)
      IF(NERORS(12).EQ.1) WRITE(LURESS,755)
C
      CALL RUNENDS('CONCEKT: ERROR DETECTED            ')
C
  700 FORMAT(' THE SPECIFIED NUMBER OF NODES IS LESS THAN ZERO'//)
C
  705 FORMAT(' THE SPECIFIED NUMBER OF ELEMENTS IS LESS THAN ZERO'//)
C
  710 FORMAT(
     .' THE NUMBER OF NODES PER ELEMENT IS LESS THAN 2 OR GREATER THAN',
     .' 20',/,10X,'NNODE=',I5//)
C
  715 FORMAT(
     .59H THE SPECIFIED TOTAL NUMBER OF DIFFERENT MATERIALS (NMATS) ,/,
     .59H IS LESS THAN OR EQUAL TO ZERO, OR GREATER THAN THE TOTAL  ,/,
     .59H NUMBER OF ELEMENTS (NELEM) IN THE STRUCTURE               ,/,
     .10X,'NMATS=',I5,5X,'NELEM=',I5//)
C
  720 FORMAT(
     .' THE SPECIFIED NUMBER OF FUNCTIONS IS LESS THAN OR EQUAL TO',
     .' ZERO'//)
C
  735 FORMAT(
     .' SEEPAGE PROBLEM IS NOT IMPLEMENTED YET',/ )
C
  740 FORMAT(
     .' COUPLED PROBLEM WITH LARGE DISPLACEMENTS IS NOT IMPLEMENTED',
     .' YET',/ )
C
  745 FORMAT(
     .' UNCOUPLED PROBLEM DOES NOT REQUIRE ANY SMOOTHING',/ )
C
  750 FORMAT(
     .' ALL IMPLEMENTED PROBLEMS YIELD A SYMMETRIX MATRIX AND YOU,',/,
     .' IDIOT, ARE ASKING FOR A NON-SYMMETRIC SOLVER',/)
C
  755 FORMAT(
     .' SPECIFIED TYPE OF SMOOTHING IS INCORRECT OR NOT YET',
     .' IMPLEMENTED',/)
C
      END
