      SUBROUTINE PROPMIC8(ITAPET,PROPSS,NPOI2T,INUPM)
C***********************************************************************
C
C**** THIS ROUTINE READS THE MICROSTRUCTURAL MATERIAL PROPERTIES FOR
C     MODEL 8 (ALUMINIUM NITRIDE PRECIPITATION & RECRYSTALIZATION)
C                                                      
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
C**** MICROSCOPICAL VARIABLES
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
      INCLUDE 'inpo_oms.f'
C
      DIMENSION PROPSS(*)
C                                                    ! AlN precipitation
C**** LOOKS FOR 'PREEXPONENTIAL_FACTOR' CARD
C
      NPRINT=0
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'PREEX') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! A
       WRITE(LURESS,830) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: PREEXPONENTIAL_FACTOR CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'ACTIVATION_ENERGY' CARD
C
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'ACTIV') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! Q
       WRITE(LURESS,831) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: ACTIVATION_ENERGY CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'EXPONENT' CARD
C
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'EXPON') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! k
       WRITE(LURESS,832) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: EXPONENT CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'UNIVERSAL_GAS_CONSTANT' CARD
C
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'UNIVE') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! R
       WRITE(LURESS,833) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: UNIV. GAS CONST. CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'KELVIN_CONSTANT' CARD
C
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'KELVI') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! P
       WRITE(LURESS,833) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: KELVIN CONSTANT CARD NOT FOUND')
      ENDIF
C                                                    ! recrystalization
C**** LOOKS FOR 'PREEXPONENTIAL_FACTOR' CARD
C
      NPRINT=0
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'PREEX') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! A
       WRITE(LURESS,840) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: PREEXPONENTIAL_FACTOR CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'ACTIVATION_ENERGY' CARD
C
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'ACTIV') THEN
       IF(WORDSS(2).EQ.'     ') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=0                    ! index for Q
        CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=PARAMS(1)            ! Q
        WRITE(LURESS,841) PROPSS(NPOI2T)
        WRITE(LURESS,899)
       ENDIF
       IF(WORDSS(2).EQ.'VARIA') THEN
        NPOI2T=NPOI2T+1
        PROPSS(NPOI2T)=1                    ! index for Q
        CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'TOTAL') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)           ! total nitrogen content
         WRITE(LURESS,843) PROPSS(NPOI2T)
         WRITE(LURESS,899)
        ELSE
         CALL RUNENDS('PROPMIC8: TOTAL_NITROGEN_CONTENT CARD NOT FOUND')
        ENDIF
        CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
        IF(WORDSS(1).EQ.'PARAM') THEN
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(1)           ! activation parameter a
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(2)           ! activation parameter b
         NPOI2T=NPOI2T+1
         PROPSS(NPOI2T)=PARAMS(3)           ! activation parameter c
         WRITE(LURESS,844) PROPSS(NPOI2T-2),PROPSS(NPOI2T-1),
     .                     PROPSS(NPOI2T)
         WRITE(LURESS,899)
        ELSE
         CALL RUNENDS('PROPMIC8: ACTIVATION_PARAMETERS CARD NOT FOUND')
        ENDIF
       ENDIF
      ELSE
       CALL RUNENDS('PROPMIC8: ACTIVATION_ENERGY CARD NOT FOUND')
      ENDIF
C
C**** LOOKS FOR 'EXPONENT' CARD
C
      CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
      IF(WORDSS(1).EQ.'EXPON') THEN
       CALL LISTENS('PROPMIC8',NPRINT,ITAPET)
       NPOI2T=NPOI2T+1
       PROPSS(NPOI2T)=PARAMS(1)            ! k
       WRITE(LURESS,842) PROPSS(NPOI2T)
       WRITE(LURESS,899)
      ELSE
       CALL RUNENDS('PROPMIC8: EXPONENT CARD NOT FOUND')
      ENDIF
C
C**** CONTROLS DIMENSION OF PROPSS
C
      IF(NPOI2T.GT.NPROPS) THEN
       WRITE(LURESS,900) NPROPS,NPOI2T
       CALL RUNENDS('PROPMIC6: TOO MANY PROPERTIES TO READ')
      ENDIF
C
C**** OUTPUT (see pointes.f)
C
C     Model 8 is not a real phase-change model => IPLLLT is not assigned
C
      KPLA8S=1
C
      RETURN
C
  830 FORMAT(/,'  PREEXPONENTIAL FACTOR (AlN PRECIP.) =',E15.6)
  831 FORMAT(/,'  ACTIVATION ENERGY (AlN PRECIP.)     =',E15.6)
  832 FORMAT(/,'  EXPONENT (AlN PRECIP.)              =',E15.6)
  833 FORMAT(/,'  UNIVERSAL GAS CONSTANT              =',E15.6)
  840 FORMAT(/,'  PREEXPONENTIAL FACTOR (RECRYSTAL.)  =',E15.6)
  841 FORMAT(/,'  ACTIVATION ENERGY (RECRYSTAL.)      =',E15.6)
  842 FORMAT(/,'  EXPONENT (RECRYSTAL.)               =',E15.6)
  843 FORMAT(/,'  TOTAL NITROGEN CONTENT              =',E15.6)
  844 FORMAT(/,'  ACTIVATION PARAMETERS (RECRYSTAL.)  =',E15.6,2X,E15.6,
     .                                                         2X,E15.6)
  899 FORMAT(/)
  900 FORMAT(//,'TOO MANY MATERIAL PROPERTIES TO READ:',/,
     .      20X,'NPROP =',I5,5X,'NUMBE =',I5,/)
      END
