      SUBROUTINE RSTAR2T(LPNTNT,LNODST,MATNOT,PROELT,PROPST,IFLAGT)
C***********************************************************************
C
C**** THIS ROUTINE READS OR WRITES SOME GENERAL DATA ARRAYS
C
C   - IFLAG = 1 - NEW RUN    : WRITE INTO RESTART FILE 
C   - IFLAG = 2 - RESTART RUN: READ  FROM RESTART FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'auxl_omt.f'
C
      DIMENSION LPNTNT(*), LNODST(NNODET,NELEMT), MATNOT(NELEMT),
     .                     PROELT(NPRELT,NGRUPT), PROPST(NPROPT,NMATST)
C
      CALL CPUTIMT(TIME1T)
C
      NRCURT=4
      NUNITT=LURSTT
C
C**** WRITE OR READ ALL MATRICES
C
      LENGHT=NPOINT
      CALL RESTDKT(NUNITT,IFLAGT,LPNTNT,LENGHT,LENRCT,NRCURT)
C
      LENGHT=NNODET*NELEMT
      CALL RESTDKT(NUNITT,IFLAGT,LNODST,LENGHT,LENRCT,NRCURT)
C
      LENGHT=NELEMT
      CALL RESTDKT(NUNITT,IFLAGT,MATNOT,LENGHT,LENRCT,NRCURT)
C
      LENGHT=NPRELT*NGRUPT*2
      CALL RESTDKT(NUNITT,IFLAGT,PROELT,LENGHT,LENRCT,NRCURT)
C
      LENGHT=NPROPT*NMATST*2
      CALL RESTDKT(NUNITT,IFLAGT,PROPST,LENGHT,LENRCT,NRCURT)
C
      CALL CPUTIMT(TIME2T)
      CPURST=CPURST+(TIME2T-TIME1T)
C
      RETURN
      END
