      SUBROUTINE INCFACT(HTLODT,FICTOT,TFICTT)
C***********************************************************************
C
C**** THIS ROUTINE DETERMINES THE LOAD/DISPLACEMENT FACTOR
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
C
      DIMENSION HTLODT(NHLODT,NSUBFT,*), FICTOT(NFUNCT),
     .          TFICTT(NFUNCT)
C
      DATA FACINT/0.2/
C
      IF(LAUTOT.EQ.0) THEN                         ! LOAD HISTORY
C
       CALL FUNLOD(FICTOT,HTLODT,NSUBFT,NFUNCT,NHLODT,TFICTT,TTIMET)
C
      ELSE                                        ! AUTOMATIC INCREMENT
C
c        IF(ISTEPT.EQ.1) FACTOT=DTIMET
c        IF(ISTEPT.EQ.2) FACTOT=FACINT*FACTOT 
c        IF(ISTEPT.GT.2) FACTOT=FACTOT*DSQRT(DITERT/PITERT)
c        DTIMET=FACTOT
C
      ENDIF
C
C**** PRINT TOTAL AND INCREMENTAL LOAD FACTORS
C
c      TFACTT=TFACTT+FACTOT
c      WRITE(LUREST,900) TFACTT,FACTOT
C
      DO IFUNCT=1,NFUNCT
       TFICTT(IFUNCT)=TFICTT(IFUNCT)+FICTOT(IFUNCT)
       WRITE(LUREST,900) IFUNCT,TFICTT(IFUNCT),FICTOT(IFUNCT)
      ENDDO
C
      RETURN
C
  900 FORMAT(1X,'FUNCT.',I2,5X,'CURRENT TIME FUNCT. FACTOR =',E15.5,/
     .       14X,'INCREM. TIME FUNCT. FACTOR =',E15.5,/)
      END
