      SUBROUTINE OUTDIST(DISTOT,HEADST,DISPLT)
C***********************************************************************
C
C**** THIS ROUTINE WRITES TEMPERATURES TO OUTPUT AND POSTPROCESSOR
C     FILES
C
C       KPRI1=0  DO NOT WRITE TEMPERATURES TO OUTPUT FILE
C             1  WRITE TEMPERATURES TO OUTPUT FILES
C       KFEMV=0  DO NOT WRITE TEMPERATURES TO POSTPROCESSOR FILE
C             1  WRITE TEMPERATURES TO POSTPROCESSOR FILE
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_omt.f'
      INCLUDE 'inte_omt.f'
      INCLUDE 'auxl_omt.f'
      INCLUDE 'inpo_omt.f'
C
      DIMENSION DISTOT(NTOTVT,*), HEADST(NPOINT,*), DISPLT(NTOTVM)
C
C**** OUTPUT TEMPERATURES
C
      IF(IPRCOT.GT.0) THEN
       IF(KPRI1T.EQ.1) THEN
        WRITE(LUREST,915)
        IF(KPROBT.EQ.1) THEN
         IF(NDIMET.EQ.2.AND.KPORET.EQ.0) WRITE(LUREST,920)
         IF(NDIMET.EQ.2.AND.KPORET.NE.0) WRITE(LUREST,925)
         IF(NDIMET.EQ.3.AND.KPORET.EQ.0) WRITE(LUREST,930)
         IF(NDIMET.EQ.3.AND.KPORET.NE.0) WRITE(LUREST,935)
        ENDIF
        IF(KPROBT.EQ.4) WRITE(LUREST,950)
C
        GAMAWT=9999999.*GRAVYT         !???????????????????
        IF(GAMAWT.EQ.0.0) GAMAWT=1.0
        DO IPOINT=1,NPOINT
C
         ITOT0T=(IPOINT-1)*NDOFCT+1
         ITOT1T=(IPOINT-1)*NDOFCT+NDOFNT
         ITOTFT=IPOINT*NDOFCT
C
         IF(KPORET.EQ.0) TOPWPT=0.
         IF(KPORET.EQ.1) TOPWPT=HEADST(IPOINT,1)
         IF(KPORET.EQ.2) TOPWPT=DISTOT(ITOTFT,1)
C
         IF(KPORET.NE.0) THEN
          EXPWPT=TOPWPT-HEADST(IPOINT,1)
          THEADT=HEADST(IPOINT,2)+EXPWPT/GAMAWT
         ENDIF
C
         IF(KPORET.EQ.0)
     .    WRITE(LUREST,905) IPOINT,(DISTOT(ITOTVT,1),
     .                      ITOTVT=ITOT0T,ITOT1T)
         IF(KPORET.NE.0)
     .    WRITE(LUREST,905) IPOINT,(DISTOT(ITOTVT,1),
     .                      ITOTVT=ITOT0T,ITOT1T),
     .                      EXPWPT,TOPWPT,THEADT
        ENDDO
C
C**** OUTPUT TEMPERATURE RATES
C
        IF(KDYNAT.EQ.1) THEN
         WRITE(LUREST,1915)
         IF(KPROBT.EQ.1) THEN
          IF(NDIMET.EQ.2.AND.KPORET.EQ.0) WRITE(LUREST,1920)
          IF(NDIMET.EQ.2.AND.KPORET.NE.0) WRITE(LUREST,1925)
          IF(NDIMET.EQ.3.AND.KPORET.EQ.0) WRITE(LUREST,1930)
          IF(NDIMET.EQ.3.AND.KPORET.NE.0) WRITE(LUREST,1935)
         ENDIF
         IF(KPROBT.EQ.4) WRITE(LUREST,1950)
C
         GAMAWT=9999999.*GRAVYT         !???????????????????
         IF(GAMAWT.EQ.0.0) GAMAWT=1.0
         DO IPOINT=1,NPOINT
          ITOT0T=(IPOINT-1)*NDOFCT+1
          ITOT1T=(IPOINT-1)*NDOFCT+NDOFNT
          ITOTFT=IPOINT*NDOFCT
C
          IF(KPORET.EQ.0) TOPWPT=0.
          IF(KPORET.EQ.1) TOPWPT=HEADST(IPOINT,1)
          IF(KPORET.EQ.2) TOPWPT=DISTOT(ITOTFT,1)
C
          IF(KPORET.NE.0) THEN
           EXPWPT=TOPWPT-HEADST(IPOINT,1)
           THEADT=HEADST(IPOINT,2)+EXPWPT/GAMAWT
          ENDIF
C
          IF(KPORET.EQ.0)
     .     WRITE(LUREST,1905) IPOINT,(DISTOT(ITOTVT,2),
     .                        ITOTVT=ITOT0T,ITOT1T)
          IF(KPORET.NE.0)
     .     WRITE(LUREST,1905) IPOINT,(DISTOT(ITOTVT,2),
     .                        ITOTVT=ITOT0T,ITOT1T),
     .                        EXPWPT,TOPWPT,THEADT
         ENDDO
        ENDIF              ! kdynat.eq.1
       ENDIF               ! kpri1t.eq.1
      ENDIF                ! iprcot.gt.0
C
      IF(KFEMVT.NE.0)
     . WRITE(LUPOST) TITLET,SUBTIT,ITIMET,ISTEPT,IITERT,SNGL(TTIMET),
     .              (SNGL(DISTOT(ITOTVT,1)),ITOTVT=1,NTOTVT)
C
      IF(KDYNAT.EQ.1) THEN
       IF(KFEMVT.NE.0)
     .  WRITE(LUPOST) (SNGL(DISTOT(ITOTVT,2)),ITOTVT=1,NTOTVT)
      ENDIF
C
      IF(LARGET.GT.0) THEN
       IF(KFEMVT.NE.0)
     .  WRITE(LUPOST) (SNGL(DISPLT(ITOTVM)),ITOTVM=1,NTOTVM)
      ENDIF
C
      RETURN
  905 FORMAT(5X,I5,8E15.6)
  915 FORMAT(/,5X,19H NODAL TEMPERATURES)
  920 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.)
  925 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H EXP.PWP,
     .                      7X,8H TOT.PWP,6X,9H TOT.HEAD)
  930 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H Z-DISP.)
  935 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H Z-DISP.,
     .                      7X,8H EXP.PWP,7X,8H TOT.PWP,6X,9H TOT.HEAD)
  950 FORMAT(5X,5H NODE,3X,12H TEMPERATURE)
C
 1905 FORMAT(5X,I5,8E15.6)
 1915 FORMAT(/,5X,25H NODAL TEMPERATURES RATES)
 1920 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.)
 1925 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H EXP.PWP,
     .                      7X,8H TOT.PWP,6X,9H TOT.HEAD)
 1930 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H Z-DISP.)
 1935 FORMAT(1H0,4X,5H NODE,7X,8H X-DISP.,7X,8H Y-DISP.,7X,8H Z-DISP.,
     .                      7X,8H EXP.PWP,7X,8H TOT.PWP,6X,9H TOT.HEAD)
 1950 FORMAT(5X,5H NODE,3X,17H TEMPERATURE RATE)
C
      END
