      SUBROUTINE ANTESOS(REFORS,RFOLDS,DSOLDS,VVECTS,WVECTS)
C***********************************************************************
C
C**** THIS ROUTINE MODIFIES THE R. H. S. IF A QUASI-NEWTON METHOD IS 
C     USED ( BFGS )
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'prob_oms.f'
      INCLUDE 'inte_oms.f'
      INCLUDE 'auxl_oms.f'
C
      COMMON/ANTESOSA/NBFGSS,NVECTS
C
      DIMENSION REFORS(NTOTVS), RFOLDS(NTOTVS), DSOLDS(NTOTVS), 
     .          VVECTS(NTOTVS), WVECTS(NTOTVS)
C
      DATA CONMXS,MVECTS/1.0D+10,15/
C
      IF(LACCES.NE.3.OR.IITERS.LE.1.OR.KARCLS.NE.0) RETURN
C

      call runends('stop in antesos.f')

c     IBFGST=1
c     IF(IITERT.EQ.2) THEN
c       NVECTT=0
c       NBFGST=LUBFGT
c       REWIND NBFGST
c     ENDIF
C
C**** SEE IF BFGS UPDATE IS POSSIBLE
C
c     GAMMAT= GZEROT-GCURNT
c     IF(GAMMAT.LE.0.0.OR.GZEROT.LE.0.0) THEN
c       WRITE(LUREST,900)
c       WRITE(LUPRIT,900)
c       IBFGST=0
c       GO TO 100
c     ENDIF
C
C**** COMPUTE UPDATING VECTORS FOR THIS ITERATION
C
c     FACT1T=1.0D+00 + DSQRT((AALPHT*GAMMAT)/GZEROT)
c     FACT2T=1.0D+00/GAMMAT
c     DO 10 ITOTVT=1,NTOTVT
c       VVECTT(ITOTVT)=-FACT1T*RFOLDT(ITOTVT)+REFORT(ITOTVT)
c       WVECTT(ITOTVT)= FACT2T*DSOLDT(ITOTVT)
c 10  CONTINUE
C
C**** CHECK ON CONDITION NUMBER
C
c     VV=0.0D+00
c     WW=0.0D+00
c     DO 20 ITOTVT=1,NTOTVT
c       V=VVECTT(ITOTVT)
c       W=WVECTT(ITOTVT)
c       VV=VV+V*V
c       WW=WW+W*W
c 20  CONTINUE
C
C**** CHECK IF COND. NUMBER IS POSITIVE
C
c     WV4=4.0D+00*(1.0D+00 + FACT2T*(-FACT1T*GZEROT+GCURNT) )
c     IF(ABS(WV4).LT.1.0D-15) THEN
c       WRITE(LUREST,902)
c       WRITE(LUPRIT,902)
c       IBFGST=0
c       GO TO 100
c     ENDIF
C
C**** CHECK IF COND. NUMBER IS TOO LARGE
C
c     VALUET=DSQRT(VV*WW)+DSQRT(ABS(VV*WW+WV4))
c     ESTCNT=VALUET*VALUET/ABS(WV4)
c     IF(ESTCNT.GT.CONMXT) THEN
c       WRITE(LUREST,901)
c       WRITE(LUPRIT,901)
c       IBFGST=0
c       GO TO 100
c     ENDIF
C
c100  CONTINUE
C
C**** ADD NEW PAIR OF UPDATING VECTORS
C
c     IF(IBFGST.EQ.1) THEN
c       NVECTT=NVECTT+1
c       IF(NVECTT.GT.MVECTT) THEN
c         NVECTT=1
c         REWIND NBFGST
c       ENDIF
c       WRITE(NBFGST) VVECTT,WVECTT
c     ENDIF
C
C**** END FILE WITH 'REAL' RESIDUAL FORCES ARRAY
C
c     WRITE(NBFGST) REFORT
c     BACKSPACE NBFGST
C
C**** UPDATE R.H.S. ( RESIDUAL FORCES )
C
c     IF(NVECTT.EQ.0) RETURN
C
c     DO 200 IVECTT=1,NVECTT
c       BACKSPACE NBFGST
c       READ(NBFGST) VVECTT,WVECTT
c       BACKSPACE NBFGST
c       CONSTT=0.0D+00
c       DO 210 ITOTVT=1,NTOTVT
c 210   CONSTT=CONSTT+WVECTT(ITOTVT)*REFORT(ITOTVT)
c       DO 220 ITOTVT=1,NTOTVT
c 220   REFORT(ITOTVT)=REFORT(ITOTVT)+CONSTT*VVECTT(ITOTVT)
c 200 CONTINUE     
C
      RETURN
  900 FORMAT(/,5X,3('*'),' BFGS UPDATE ABANDONED DUE TO NEGATIVE ',
     .                     'SQRT ',3('*'),/)
  901 FORMAT(/,5X,3('*'),' BFGS UPDATE ABANDONED DUE TO LARGE ',
     .                     'EST. COND. NUMBER ',3('*'),/)
  902 FORMAT(/,5X,3('*'),' BFGS UPDATE ABANDONED DUE TO NEGATIVE ',
     .                     'EST. COND. NUMBER ',3('*'),/)
      END
