      SUBROUTINE SOLVERT(DISITT,REFORT,IFFIXT,IMPOST,KPORET,KRESLT,
     .                   LNODST,NDOFNT,NELEMT,NEVABT,NNODET,NPOINT,
     .                   NTOTVT,IPASST,IITERT,WORK1T,mitert,
     .                   NPRELT,NGRUPT,NPROPT,NMATST,
     .                  NDATAT,NPREVT,NSTATT,NMATXT,NDIMET,NTOTVM,NFPCH,
     .                   MATNOT,PROELT,PROPST,ELDATT,ELPRET,
     .                   ELVART,ELMATT,
     .                   DISTOT,COORDT,
     .                   ADVELT,TEMPIT,PREAST,TGAPST,DISPLT,FPCHAT,
     .                   NACTIT,LACTIT)
C***********************************************************************
C
C**** THIS ROUTINE SOLVES THE SYSTEM OF EQUATIONS SELECTING THE
C     THE APPROPRIATE SOLVER
C
C     KRESLT=1  ASSEMBLE & FACTORISE THE MATRIX (see algors.f)
C     IPASST=1  (with no arc-length or displ. control; see esepas.f)
C     KPASST=0  (see below)
C
C***********************************************************************
      IMPLICIT REAL*8(A-H,O-Z)
C
      INCLUDE 'auxl_omt.f'
C
      COMMON/SOLVERTA/KRENUT,KSOLVT,KSYMMT,NWIDTT,MITCGT,NBUFAT,NPRIRT,
     .                MITGMT,MKRYLT,IPGMRT
      COMMON/SOLVERTB/TOLCGT,TOLC1T,TOLGMT
C
      COMMON/LOGUNT/LUDTST,LUSOLT,LUFROT,LUFRHT,LUDATT,LUPRIT,LUREST,
     .              LUSO2T,LUFR2T,LUPOST,LURSTT,LUBFGT,LUPIPT,LUPANT,
     .              LUGEOT,LUSETT,LUMATT,LUINIT,LULOAT,LUFIXT,LUADVT,
     .              LUACTT,LUFANT,LUSTRT,
     .              LUCU1T,LUCU2T,LUCU3T,LUCU4T,LUCU5T,LUCU6T,LUCU7T,
     .              LUCU8T,LUCU9T,LUC10T
C
      DIMENSION DISITT(*),        IFFIXT(*), 
     .          LNODST(NNODET,*), REFORT(*),
     .          WORK1T(*)
C
      DIMENSION MATNOT(NELEMT),
     .          PROELT(NPRELT,NGRUPT), PROPST(NPROPT,NMATST),
     .          ELDATT(NDATAT),        ELPRET(NPREVT),
     .          ELVART(NSTATT),        ELMATT(NMATXT)
      DIMENSION DISTOT(NTOTVT,3),      COORDT(NDIMET,NPOINT)
      DIMENSION ADVELT(NTOTVT*NDIMET), TEMPIT(NPOINT,2)
      DIMENSION PREAST(NPOINT),        TGAPST(NPOINT)
      DIMENSION DISPLT(NTOTVM),        FPCHAT(NFPCH,NPOINT),
     .          LACTIT(NELEMT)
C
      CALL CPUTIMT(TIME1T)
C
      INRHST=0
      IF(IITERT.EQ.1) INRHST=IMPOST
ctm   IF(NEWBOT.EQ.1) KPASST=0
      KPASST=0
ctm
      IDSK2T=LUSOLT
      IF(IPASST.EQ.2) THEN
       INRHST=1
       IDSK2T=LUSO2T
      ENDIF
C
C**** CALL THE PROFILE SOLVER
C
      IF(KSOLVT.EQ.0)
     . CALL SKYGRAT(DISITT,REFORT,LNODST,
     .              NDOFNT,NELEMT,NEVABT,NNODET,NPOINT,NTOTVT,
     .              IDSK2T,INRHST,IPASST,KPASST,KPORET,KRESLT,NEQNST,
     .              NLASTT,IFFIXT,
     .              WORK1T(ISOLVT( 1)),WORK1T(ISOLVT( 2)),
     .              WORK1T(ISOLVT( 3)),
     .              WORK1T(ISOLVT( 4)),WORK1T(ISOLVT( 5)),
     .              WORK1T(ISOLVT( 6)),
     .              WORK1T(ISOLVT( 7)),WORK1T(ISOLVT( 8)),
     .              WORK1T(ISOLVT( 9)),
     .              WORK1T(ISOLVT(10)),WORK1T(ISOLVT(11)),
     .              WORK1T(ISOLVT(12)),
     .              WORK1T(ISOLVT(13)),iitert,mitert,
     .              NPRELT,NGRUPT,NPROPT,NMATST,
     .              NDATAT,NPREVT,NSTATT,NMATXT,NDIMET,NTOTVM,NFPCH,
     .              MATNOT,PROELT,PROPST,ELDATT,ELPRET,
     .              ELVART,ELMATT,WORK1T,DISTOT,COORDT,
     .              ADVELT,TEMPIT,PREAST,TGAPST,DISPLT,FPCHAT,
     .              NACTIT,LACTIT)
C
C**** CALL THE FRONTAL SOLVER
C
      IF(KSOLVT.EQ.1) THEN
       IDSK3T=LUFROT
       IF(IPASST.EQ.2) IDSK3T=LUFR2T
       CALL FRONTST(DISITT,IDSK2T,IDSK3T,IFFIXT,IPASST,LNODST,KRESLT,
     .              NDOFNT,NELEMT,NEVABT,NNODET,NPOINT,KPORET,REFORT,
     .         WORK1T(ISOLVT(1)), WORK1T(ISOLVT(2)), WORK1T(ISOLVT(3)),
     .         WORK1T(ISOLVT(4)), WORK1T(ISOLVT(5)), WORK1T(ISOLVT(6)),
     .         WORK1T(ISOLVT(7)), WORK1T(ISOLVT(8)), WORK1T(ISOLVT(9)),
     .         WORK1T(ISOLVT(10)),WORK1T(ISOLVT(11)),WORK1T(ISOLVT(12)),
     .              KSYMMT,
     .              NPRELT,NGRUPT,NPROPT,NMATST,
     .           NDATAT,NPREVT,NSTATT,NMATXT,NTOTVT,NDIMET,NTOTVM,NFPCH,
     .              MATNOT,PROELT,PROPST,ELDATT,ELPRET,
     .              ELVART,ELMATT,WORK1T,DISTOT,COORDT,
     .              ADVELT,TEMPIT,PREAST,TGAPST,DISPLT,FPCHAT,
     .              NACTIT,LACTIT)
      ENDIF
C
C**** CALL THE PCG SOLVER
C
      IF(KSOLVT.EQ.2)
     . CALL PCGSOLT(DISITT,IFFIXT,REFORT,LNODST,
     .              NDOFNT,NELEMT,NEVABT,NNODET,NPOINT,NTOTVT,
     .              INRHST,IPASST,KRESLT,
     .            WORK1T(ISOLVT(1)),WORK1T(ISOLVT(2)),WORK1T(ISOLVT(3)),
     .            WORK1T(ISOLVT(4)),WORK1T(ISOLVT(5)),WORK1T(ISOLVT(6)),
     .              NPRELT,NGRUPT,NPROPT,NMATST,
     .              NDATAT,NPREVT,NSTATT,NMATXT,NDIMET,NTOTVM,NFPCH,
     .              MATNOT,PROELT,PROPST,ELDATT,ELPRET,
     .              ELVART,ELMATT,WORK1T,DISTOT,COORDT,
     .              ADVELT,TEMPIT,PREAST,TGAPST,DISPLT,FPCHAT,
     .              NACTIT,LACTIT)
C
C**** CALL THE GMRES SOLVER
C
      IF(KSOLVT.EQ.3)
     . CALL GMRESST(WORK1T(ISOLVT( 4)),NEQNST,WORK1T(ISOLVT(15)),
     .              WORK1T(ISOLVT(16)),WORK1T(ISOLVT(17)),
     .              DISITT,REFORT,
     .              WORK1T(ISOLVT( 1)),WORK1T(ISOLVT( 6)),
     .              LNODST,NDOFNT,NELEMT,NEVABT,NNODET,IPASST,NTOTVT,
     .              NPOINT,
     .              NLASTT,IDSK2T,WORK1T(ISOLVT( 7)),  ! added variables
     .              MITGMT,MKRYLT,IPGMRT,TOLGMT,
     .              LUREST)
C
C**** CALL THE EXPLICIT SOLVER
C
      IF(KSOLVT.EQ.4)
     . CALL EXPLICT(DISITT,IFFIXT,REFORT,LNODST,
     .              NDOFNT,NELEMT,NEVABT,NNODET,NPOINT,NTOTVT,
     .              INRHST,IPASST,KRESLT,
     .            WORK1T(ISOLVT(1)),WORK1T(ISOLVT(2)),WORK1T(ISOLVT(3)),
     .            WORK1T(ISOLVT(4)),WORK1T(ISOLVT(5)),
     .              NPRELT,NGRUPT,NPROPT,NMATST,
     .              NDATAT,NPREVT,NSTATT,NMATXT,NDIMET,NTOTVM,NFPCH,
     .              MATNOT,PROELT,PROPST,ELDATT,ELPRET,
     .              ELVART,ELMATT,WORK1T,DISTOT,COORDT,
     .              ADVELT,TEMPIT,PREAST,TGAPST,DISPLT,FPCHAT,
     .              NACTIT,LACTIT)
C
      CALL CPUTIMT(TIME2T)
      CPUSOT=CPUSOT+(TIME2T-TIME1T)
C
      RETURN
      END
